#!/usr/bin/env python3
"""Machine certificate for ``coker K^sharp ~= (ker K)^*``."""

from __future__ import annotations

import argparse
import hashlib
import json
from pathlib import Path
import sys

import sympy as sp

ROOT = Path(__file__).resolve().parents[2]
if str(ROOT) not in sys.path:
    sys.path.insert(0, str(ROOT))

from field_bv_identification.zero_modes import DualEndpointCokernel


CERTIFICATE_PATH = ROOT / "field_bv_identification" / "zero_modes" / "certificates" / "dual_zero_modes.json"
LATEX_PATH = ROOT / "field_bv_identification" / "generated_latex" / "dual_zero_modes.tex"


def check(label: str, condition: object) -> None:
    if not bool(condition):
        raise AssertionError(label)
    print("[OK ] " + label)


def _digest(matrix: sp.MatrixBase) -> str:
    payload = "\n".join(
        f"{row},{column}:{value}"
        for (row, column), value in sorted(matrix.todok().items())
    ).encode("utf-8")
    return hashlib.sha256(payload).hexdigest()


def certificate_data() -> dict[str, object]:
    endpoint = DualEndpointCokernel.build()
    check(
        "FTBV-ZD1: the gauge kernel and endpoint cokernel both have dimension fifteen",
        endpoint.zero_dimension == 15
        and endpoint.endpoint_dimension - endpoint.exact_endpoint_dimension == 15,
    )
    check(
        "FTBV-ZD2: Theta([u])(z)=<z,u> annihilates im K^sharp",
        endpoint.quotient_map * endpoint.adjoint_map == sp.zeros(15, 50),
    )
    check(
        "FTBV-ZD3: Theta has an explicit exact quotient inverse",
        endpoint.quotient_map * endpoint.quotient_section == sp.eye(15),
    )
    check(
        "FTBV-ZD4: ker Theta equals im K^sharp",
        endpoint.exact_endpoint_projector.rank() == endpoint.adjoint_map.rank() == 50
        and endpoint.quotient_map * endpoint.exact_endpoint_projector
        == sp.zeros(15, 65)
        and sp.Matrix.hstack(endpoint.adjoint_map, endpoint.quotient_section).rank()
        == 65,
    )
    check(
        "FTBV-ZD5: the endpoint carries the dual 4+7+4 compact grading",
        endpoint.generator_compact_degrees == (-1,) * 4 + (0,) * 7 + (1,) * 4
        and endpoint.dual_compact_degrees == (1,) * 4 + (0,) * 7 + (-1,) * 4,
    )
    return {
        "schema": "pure-weyl-dual-endpoint-cokernel-v1",
        "category": "finite algebraic conformal-Killing zero-mode block",
        "theorem": "I/im(K^sharp) is canonically isomorphic to (ker K)^*",
        "dim_kernel_K": endpoint.zero_dimension,
        "dim_endpoint_I": endpoint.endpoint_dimension,
        "rank_K_sharp": endpoint.exact_endpoint_dimension,
        "dim_coker_K_sharp": endpoint.obstruction_dimension,
        "rank_duality_map": endpoint.quotient_map.rank(),
        "duality_map_times_K_sharp": "zero",
        "quotient_inverse_identity": "Theta S = I_15",
        "compact_types": {
            "ghost": "4_-1 + 7_0 + 4_+1",
            "dual": "4_+1 + 7_0 + 4_-1",
        },
        "labels": list(endpoint.labels),
        "matrix_sha256": {
            "K": _digest(endpoint.gauge_map),
            "K_sharp": _digest(endpoint.adjoint_map),
            "Theta": _digest(endpoint.quotient_map),
            "quotient_section": _digest(endpoint.quotient_section),
            "obstruction_projector": _digest(endpoint.obstruction_projector),
        },
        "proved": [
            "perfect-pairing adjoint identity J_GI K^sharp=K^T J_ME",
            "well-defined canonical map from the endpoint cokernel to Z^*",
            "exact quotient inverse and kernel/image equality",
            "dual compact 4+7+4 grading",
        ],
        "not_proved": [
            "time-slice BV-to-BFV transgression scalar lambda",
            "identification of the bulk endpoint coordinate itself with b_a",
            "polarized state-row completeness",
            "analytic completion",
        ],
    }


def latex() -> str:
    return "\n".join(
        [
            "% Generated by verify_dual_cokernel.py",
            r"\begin{equation}",
            r"\Theta:\operatorname{coker}K^\sharp\xrightarrow{\ \sim\ }(\ker K)^*,",
            r"\qquad \Theta([u])(z)=\langle z,u\rangle_{G,I}.",
            r"\end{equation}",
            r"\[\dim\ker K=\dim\operatorname{coker}K^\sharp=15.\]",
            "",
        ]
    )


def main() -> None:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--emit", action="store_true")
    parser.add_argument("--claim-bfv-transgression", action="store_true")
    parser.add_argument("--claim-endpoint-is-bfv-momentum", action="store_true")
    args = parser.parse_args()
    if args.claim_bfv_transgression:
        raise SystemExit(
            "REFUSED: endpoint duality alone is not the time-slice suspension; "
            "the normalized suspension is certified by its companion executable"
        )
    if args.claim_endpoint_is_bfv_momentum:
        raise SystemExit(
            "REFUSED: the bulk endpoint and BFV momentum have different degrees; "
            "they are related only after the separately certified degree suspension"
        )
    data = certificate_data()
    if args.emit:
        CERTIFICATE_PATH.parent.mkdir(parents=True, exist_ok=True)
        LATEX_PATH.parent.mkdir(parents=True, exist_ok=True)
        CERTIFICATE_PATH.write_text(
            json.dumps(data, indent=2, sort_keys=True) + "\n", encoding="utf-8"
        )
        LATEX_PATH.write_text(latex(), encoding="utf-8")
        print("wrote", CERTIFICATE_PATH.relative_to(ROOT))
        print("wrote", LATEX_PATH.relative_to(ROOT))
    print("CONFORMAL FIELD-BV DUAL ENDPOINT: ALL PASS")


if __name__ == "__main__":
    main()
