#!/usr/bin/env python3
"""Generate a fail-closed dependency delta from flat scalar biwave to Weyl BV."""
from __future__ import annotations
import argparse,hashlib,json
from pathlib import Path
from typing import Any
ROOT=Path(__file__).resolve().parents[1]
OUTPUT=ROOT/"foundations/results/FOUNDATIONAL_SCALAR_BIWAVE_TO_WEYL_BV_DEPENDENCY_DELTA_V1.json"
REPORT=ROOT/"foundations/reports/scalar-biwave-to-weyl-bv-dependency-delta-v1.md"
INPUTS=[
 ("foundations/results/FOUNDATIONAL_SCALAR_MINKOWSKI_BIWAVE_GREEN_V1.json","proved scalar source"),
 ("foundations/results/FOUNDATIONAL_TYPED_BIWAVE_GREEN_DEPENDENCY_AUDIT_V1.json","general analytic dependency cut"),
 ("foundations/results/FOUNDATIONAL_NORMAL_HYPERBOLIC_FACTOR_ATLAS_V1.json","normally-hyperbolic literature boundary"),
 ("quantum-weyl/classical_import/certificates/CLASSICAL_IMPORT_CERTIFICATE.json","authoritative fail-closed classical import gate"),
 ("d_quotient_classical/certificates/NARIAI_METRIC_BIWAVE_GREEN_HOMOTOPY_V1.json","scoped positive four-row Weyl metric BV example"),
 ("quantum-weyl/lorentzian/certificates/BERGER_METRIC_MIXED_ORDER_GREEN_CONTRACT.json","Berger mixed-order realization contract"),
 ("covariant_completion/certificates/final_claim_dependencies.json","24-field scalar-symbol no-go scope"),
 ("covariant_completion/certificates/curved_expanded_relative_witness_r6_first_order_no_go.json","46-parameter fixed-temporal no-go scope"),
 ("quantum-weyl/lorentzian/certificates/CURVATURE_IMAGE_PRESYMPLECTIC_CCR_ALGEBRA.json","residual-class particle firewall"),
]
def sha(p:Path)->str:return hashlib.sha256(p.read_bytes()).hexdigest()
def row(id:str,source:str,target:str,status:str,missing:str,evidence:list[str],boundary:str)->dict[str,Any]:
    return {"id":id,"scalar_source_capability":source,"weyl_bv_target_requirement":target,"status":status,"missing_certificate":missing,"evidence":evidence,"does_not_establish":boundary}
def digest(v:dict[str,Any])->str:
    keys=("status_vocabulary","dependency_delta","existing_scoped_architectures","classical_import_gate","lifecycle_gate","forbidden_inferences")
    return hashlib.sha256(json.dumps({k:v[k] for k in keys},sort_keys=True,separators=(",",":"),ensure_ascii=False).encode()).hexdigest()
def build()->dict[str,Any]:
    docs={path:json.loads((ROOT/path).read_text()) for path,_ in INPUTS}
    scalar=docs[INPUTS[0][0]];classical=docs[INPUTS[3][0]];nariai=docs[INPUTS[4][0]];berger=docs[INPUTS[5][0]]
    if not scalar["claim_flags"]["strict_causal_support_proved"] or scalar["claim_flags"]["weyl_bv_propagator_constructed"]:raise ValueError("scalar source boundary")
    if classical.get("gate_a_status")!="FAIL_CLOSED" or classical.get("publishable_quantum_results_allowed") is not False:raise ValueError("classical gate unexpectedly promoted")
    if "constructs no advanced or retarded Green operator" not in berger.get("claim_boundary",""):raise ValueError("Berger boundary drift")
    nariai_statement=nariai.get("claim_boundary",{}).get("statement","")
    if "complete four-row metric Bach BV complex" not in nariai_statement:raise ValueError("Nariai scope drift")
    rows=[
      row("D01_SCALAR_FACTOR","explicit flat scalar P Green maps","normally-hyperbolic factor Green maps on the target bundle","PROVED_SCALAR","variable-coefficient bundle factor theorem","FOUNDATIONAL_SCALAR_MINKOWSKI_BIWAVE_GREEN_V1".split(),"A scalar line-bundle formula is not a tensor-bundle theorem."),
      row("D02_FOURTH_ORDER_COMPOSITION","canonical H=G o G for P^2","factorization or direct Green theorem for the gauge-fixed fourth-order metric operator","PROVED_SCALAR","principal and lower-order Weyl operator identification",["FOUNDATIONAL_SCALAR_MINKOWSKI_BIWAVE_GREEN_V1","FOUNDATIONAL_TYPED_BIWAVE_GREEN_DEPENDENCY_AUDIT_V1"],"Matching differential order does not identify operators."),
      row("D03_TENSOR_CARRIER","scalar functions with scalar pairing","symmetric-tensor, ghost, antifield, and nonminimal bundles with graded pairing","MISSING_CERTIFICATE","complete degreewise carrier and nondegenerate graded pairing",[],"No tensor or graded structure transfers from the scalar carrier."),
      row("D04_GAUGE_FIXING","no gauge symmetry","gauge fixing whose full kinetic complex is Green-hyperbolic","MISSING_CERTIFICATE","full off-shell gauge-fixed Weyl BV operator and gauge-fixing independence",["CLASSICAL_IMPORT_CERTIFICATE"],"A metric-sector or reduced-row inverse is not a full BV inverse."),
      row("D05_CURVED_LOWER_ORDER","zero lower-order couplings in flat space","curvature-dependent subprincipal and lower-order terms controlled on a globally hyperbolic background","MISSING_CERTIFICATE","bundle energy estimates and Volterra convergence for the chosen Weyl background",["FOUNDATIONAL_TYPED_BIWAVE_GREEN_DEPENDENCY_AUDIT_V1"],"Flat causal support does not prove curved well-posedness."),
      row("D06_CONSTRAINT_PROPAGATION","none","gauge constraints and subsidiary equations preserved by evolution","MISSING_CERTIFICATE","constraint-propagation chain theorem",[],"Solving the metric equation alone need not preserve the BV constraint surface."),
      row("D07_DEGREEWISE_INVERSES","B H=H B=id on scalar code domains","degreewise P_BV G=id and G P_BV=id on declared compact section domains","MISSING_CERTIFICATE","full-complex two-sided Green identities",["CLASSICAL_IMPORT_CERTIFICATE"],"Partial rows and principal symbols cannot be assembled implicitly."),
      row("D08_BRST_COMPATIBILITY","no BRST differential","[q,G]=0 or a certified causal homotopy identity compatible with the BV differential","MISSING_CERTIFICATE","BRST-compatible causal Green homotopy",[],"Causal inversion without a chain identity does not descend to cohomology."),
      row("D09_SUPPORT_MICROLOCAL","exact flat cone support","curved causal support plus wavefront-set and microlocal compatibility","MISSING_CERTIFICATE","full-complex support and microlocal spectrum certificate",[],"Support control alone is not a Hadamard or wavefront-set theorem."),
      row("D10_CLASSICAL_FREEZE","no classical BV import","nilpotency, contraction, chain maps, cyclicity, residual cohomology, and pairing independently frozen","FAIL_CLOSED_IMPORT","all missing exports and ten blocked checks listed by CLASSICAL_IMPORT_CERTIFICATE",["CLASSICAL_IMPORT_CERTIFICATE"],"Integrity of a partial snapshot is not the classical freeze gate."),
      row("D11_NARIAI_POSITIVE_SLICE","no curved example","complete four-row metric Bach BV Green homotopy on unit Nariai","SCOPED_WEYL_RESULT","extension from the certified four-row Nariai complex to the full off-shell metric BV complex",["NARIAI_METRIC_BIWAVE_GREEN_HOMOTOPY_V1"],"This positive curved result is background- and carrier-scoped and has no Hadamard or quantum promotion."),
      row("D12_BERGER_ROUTE","scalar composition suggests a factor route","Berger hybrid retained chain with convergent causal Volterra resolvent","OPEN_SEEDED","causal Volterra resolvent and full 26-row homotopy",["BERGER_METRIC_MIXED_ORDER_GREEN_REALIZATION_CONTRACT"],"The contract explicitly constructs no advanced or retarded Green operator."),
      row("D13_24_FIELD_NO_GO","scalar P^2 has a scalar principal symbol","24-field pointwise-pairing first-order companion with scalar normally-hyperbolic symbol","SCOPED_NO_GO","a materially different bundle, gauge, pairing, or architecture",["PURE_WEYL_FINAL_COVARIANT_CLAIM_DEPENDENCIES"],"The rank 11>9 obstruction rules out only the declared 24-field scalar-symbol architecture."),
      row("D14_46_PARAMETER_NO_GO","scalar factorization is semisimple","fixed-temporal cyclic 46-parameter first-order strongly-hyperbolic family","SCOPED_NO_GO","changed temporal normalization, incidence, scalar branch, or enlarged prolongation",["CURVED_EXPANDED_RELATIVE_WITNESS_R6_FIRST_ORDER_NO_GO"],"The persistent Jordan chain rules out only this fixed-temporal family."),
      row("D15_RESIDUAL_CLASSES","scalar solutions can be viewed as states only in the scalar model","[W_+^2] and [W_-^2] retain their certified deformation/vertex meaning","FORBIDDEN_TRANSFER","a separate one-particle cohomology and positivity construction",["CURVATURE_IMAGE_PRESYMPLECTIC_CCR_ALGEBRA"],"The centered Weyl-square classes are not one-particle gravitons."),
      row("D16_QUANTUM_CAUSAL","classical scalar Green maps only","BRST-compatible Hadamard state, renormalized time-ordered products, causal pAQFT, and Lorentzian QME","MISSING_CERTIFICATE","all four quantum causal constructions in lifecycle order",[],"No classical Green map, including a full one, automatically establishes quantum causal theory."),
    ]
    value={
      "schema_version":"foundational-scalar-biwave-to-weyl-bv-dependency-delta-v1","result_id":"FOUNDATIONAL_SCALAR_BIWAVE_TO_WEYL_BV_DEPENDENCY_DELTA_V1","result_kind":"FAIL_CLOSED_CROSS_THEORY_DEPENDENCY_DELTA","lifecycle":"CERTIFIED_DEPENDENCY_DELTA","created":"2026-08-14","repository_base_commit":"b5601e3e7f616cc03ea094be3ea6cc577043931d","dependency_tags":["LOCAL-ALGEBRAIC","LORENTZIAN-CAUSAL"],
      "question":"What, exactly, must be added before the certified flat scalar Box^2 Green construction supports a Lorentzian Weyl BV propagator claim?",
      "answer":"The scalar construction supplies an exact causal fourth-order benchmark, not a transfer theorem. Sixteen typed gates separate it from the target. Two are proved only in the scalar source, one is a positive but background-scoped Nariai Weyl result, one is an open-but-seeded Berger route, two are scoped architectural no-go theorems, one is a forbidden particle reinterpretation, and the remaining target gates are missing or fail closed. The authoritative classical import gate itself remains pending, so no full-complex Lorentzian or quantum lifecycle promotion is permitted.",
      "status_vocabulary":[
        {"id":"PROVED_SCALAR","meaning":"Proved exactly for the displayed flat scalar carrier only."},{"id":"SCOPED_WEYL_RESULT","meaning":"A genuine Weyl/BV result exists, but only for the explicitly named background and subcomplex."},{"id":"OPEN_SEEDED","meaning":"Concrete operators or contracts exist, but the stated target theorem is still absent."},{"id":"MISSING_CERTIFICATE","meaning":"The target requires a new object or proof not supplied by current evidence."},{"id":"FAIL_CLOSED_IMPORT","meaning":"Inputs exist, but the authoritative acceptance gate explicitly fails closed."},{"id":"SCOPED_NO_GO","meaning":"A precisely named architecture is ruled out; neighboring architectures remain open."},{"id":"FORBIDDEN_TRANSFER","meaning":"The proposed interpretation conflicts with an explicit scientific scope boundary."}],
      "dependency_delta":rows,
      "existing_scoped_architectures":[
        {"id":"NARIAI_FOUR_ROW","status":"SCOPED_WEYL_RESULT","establishes":nariai_statement,"next_missing":"full off-shell BV carrier, Hadamard control, and quantum lifecycle"},
        {"id":"BERGER_HYBRID_RETAINED","status":"OPEN_SEEDED","establishes":"exact realization contract, normalized tensor-biwave form, companion SDR, and route selection","next_missing":"causal Volterra convergence and full 26-row Green homotopy"}],
      "classical_import_gate":{"source":"CLASSICAL_IMPORT_CERTIFICATE","status":classical["gate_a_status"],"claim_state":classical["claim_state"],"publishable_quantum_results_allowed":classical["publishable_quantum_results_allowed"],"blocked_or_failed_checks":classical["blocked_or_failed_freeze_checks"],"missing_exports":classical["missing_or_incomplete_exports"]},
      "lifecycle_gate":{"current_highest":"CLASSICAL_SCALAR_GREEN_ONLY","target_order":["CLASSIFIED","COEFFICIENT_COMPUTED","QME_RESTORED","RESIDUAL_TRANSFERRED","LORENTZIAN_CERTIFIED"],"states_reached_for_full_weyl_bv":[],"rule":"No quantum correction may transfer before QME restoration, and no Lorentzian certification follows from local, Euclidean, reduced-mode, scalar, or scoped-background evidence."},
      "forbidden_inferences":["scalar Box^2 formula implies the Weyl kinetic operator is factorized","principal-symbol agreement implies a two-sided Green operator","metric-sector inversion implies a full BV propagator","a residual deformation class is a one-particle state","a scoped no-go refutes the classical BRST complex or physical spectrum","causal support implies Hadamard wavefront control","Euclidean or reduced-mode evidence implies LORENTZIAN-CAUSAL"],
      "provenance":{"inputs":[{"path":path,"sha256":sha(ROOT/path),"role":role} for path,role in INPUTS]},
      "independent_checker":{"path":"foundations/check_scalar_biwave_to_weyl_bv_delta.py","checks":["sixteen unique typed gates","status-vocabulary closure","source-versus-target positive-claim firewall","classical gate exact replay","quantum lifecycle remains empty","scoped no-go language","provenance hashes","canonical digest"],"expected_digest":""},
      "claim_flags":{"scalar_biwave_green_imported":True,"transfer_requirements_classified":True,"scoped_nariai_weyl_result_recorded":True,"scoped_architectural_no_gos_recorded":True,"classical_import_gate_passed":False,"full_weyl_bv_propagator_constructed":False,"brst_compatible_hadamard_state_constructed":False,"renormalized_lorentzian_products_constructed":False,"causal_paqft_constructed":False,"lorentzian_qme_restored":False,"residual_quantum_transfer_completed":False,"lorentzian_full_complex_certified":False},
      "does_not_establish":["a full off-shell Lorentzian Weyl metric BV propagator","a BRST-compatible Hadamard state","renormalized Lorentzian time-ordered products","a causal perturbative AQFT construction","a Lorentzian quantum-master-equation theorem","a passed classical import freeze gate","that the two scoped no-go theorems rule out other architectures","that the centered Weyl-square deformation classes are particles","a weakest-base reversal for curved tensor PDE","empirical adequacy or a complete physical theory"],
      "next_gate":"The most direct positive route is to close the Berger causal Volterra resolvent and full 26-row Green homotopy while independently repairing the authoritative classical import gate; the Nariai four-row result is the control showing that a scoped Weyl BV Green homotopy is possible.",
      "human_report":"foundations/reports/scalar-biwave-to-weyl-bv-dependency-delta-v1.md"}
    value["independent_checker"]["expected_digest"]=digest(value);return value
def render(v:dict[str,Any])->str:
    lines=["# From scalar biwave to Lorentzian Weyl BV: fail-closed dependency delta","",f"**Result:** `{v['result_id']}`","","## Outcome","",v["answer"],"","## What transfers, and what does not","","| gate | scalar input | Weyl/BV requirement | status | exact missing object |","|---|---|---|---|---|"]
    for x in v["dependency_delta"]:lines.append(f"| `{x['id']}` | {x['scalar_source_capability']} | {x['weyl_bv_target_requirement']} | `{x['status']}` | {x['missing_certificate']} |")
    lines += ["","## The two live positive routes","","- **Nariai control:** a genuine complete four-row metric Bach BV Green homotopy already exists on global unit Nariai. It proves feasibility in that scoped background and carrier.","- **Berger frontier:** the exact mixed-order contract and companion SDR exist, but causal Volterra convergence and the full 26-row homotopy do not.","","## Why the gate is red","",f"The authoritative classical import is `{v['classical_import_gate']['status']}` with {len(v['classical_import_gate']['blocked_or_failed_checks'])} blocked or failed checks and {len(v['classical_import_gate']['missing_exports'])} missing or incomplete exports. Artifact integrity is not acceptance of the snapshot.","","## Scoped no-go results","","The 24-field scalar-symbol and fixed-temporal 46-parameter first-order architectures are ruled out only in their declared families. They do not refute the classical BRST complex, residual cohomology, or spectrum, and they do not close different gauge, bundle, temporal, or prolonged architectures.","","## Reproduction","","```text","python3 foundations/build_scalar_biwave_to_weyl_bv_delta.py --check","python3 foundations/check_scalar_biwave_to_weyl_bv_delta.py","python3 foundations/verify_scalar_biwave_to_weyl_bv_delta.py","python3 -m unittest foundations.tests.test_scalar_biwave_to_weyl_bv_delta","```","","## Boundaries",""]
    lines += ["- This does not establish "+x+"." for x in v["does_not_establish"]];return "\n".join(lines)+"\n"
def generated()->tuple[bytes,bytes]:
    v=build();return (json.dumps(v,indent=2,ensure_ascii=False)+"\n").encode(),render(v).encode()
def main()->int:
    p=argparse.ArgumentParser();p.add_argument("--check",action="store_true");a=p.parse_args();rb,mb=generated();outputs=((OUTPUT,rb),(REPORT,mb));stale=[str(p.relative_to(ROOT)) for p,c in outputs if not p.is_file() or p.read_bytes()!=c]
    if a.check:print("FOUNDATIONAL_SCALAR_BIWAVE_TO_WEYL_BV_DEPENDENCY_DELTA_V1: "+("generated artifacts current" if not stale else "stale: "+", ".join(stale)));return bool(stale)
    for p,c in outputs:p.write_bytes(c)
    print("FOUNDATIONAL_SCALAR_BIWAVE_TO_WEYL_BV_DEPENDENCY_DELTA_V1: wrote result and report");return 0
if __name__=="__main__":raise SystemExit(main())
