#!/usr/bin/env python3
"""Render the foundations coverage, completion, and literature ledgers as Markdown."""
from __future__ import annotations

import argparse
from collections import Counter
import hashlib
import json
import os
from pathlib import Path
import sys
from typing import Any

ROOT = Path(__file__).resolve().parents[1]
COVERAGE = ROOT / "foundations/results/FOUNDATIONAL_COVERAGE_MATRIX_V0.json"
COMPLETION = ROOT / "foundations/results/FOUNDATIONAL_RANKED_OPPORTUNITY_COMPLETION_MATRIX_V1.json"
LEDGERS = (
    ROOT / "foundations/literature-ledger.json",
    ROOT / "foundations/literature-supplement-known-attempts-v1.json",
)
DEFAULT_OUTPUT = ROOT / "foundations/reports/completion-matrix.md"
AXES = (
    ("LOGIC", "Logic"),
    ("SET_EXISTENCE", "Set/existence"),
    ("INFINITY", "Infinity"),
    ("CARRIER_GEOMETRY", "Carrier"),
    ("PHYSICAL_POSTULATES", "Physical postulates"),
    ("TARGET_CLAIMS", "Target claims"),
)
STATUS_SYMBOL = {"DIRECT": "D", "PARTIAL": "P", "ADJACENT": "A", "ABSENT": "-", "UNKNOWN": "?"}


def load(path: Path) -> dict[str, Any]:
    return json.loads(path.read_text())


def sha256_text(text: str) -> str:
    return hashlib.sha256(text.encode()).hexdigest()


def cell(value: Any) -> str:
    return " ".join(str(value).split()).replace("|", "\\|")


def report_link(result_path: str, output: Path) -> str:
    result = load(ROOT / result_path)
    report = ROOT / result["human_report"]
    return Path(os.path.relpath(report, output.parent)).as_posix()


def render(*, output: Path = DEFAULT_OUTPUT) -> str:
    coverage = load(COVERAGE)
    completion = load(COMPLETION)
    literature = []
    ledger_unresolved = []
    for path in LEDGERS:
        ledger = load(path)
        literature.extend(ledger["entries"])
        ledger_unresolved.extend((path.name, item) for item in ledger.get("unresolved", []))

    attempts = coverage["attempts"]
    opportunities = {item["id"]: item for item in coverage["opportunities"]}
    completed = completion["entries"]
    if len(attempts) != 16 or len(completed) != 9 or len(literature) != 25:
        raise ValueError("unexpected matrix dimensions")
    if {item["opportunity_id"] for item in completed} != set(opportunities):
        raise ValueError("completion rows do not match ranked opportunities")
    if len({item["id"] for item in literature}) != len(literature):
        raise ValueError("duplicate literature identifiers")

    coverage_counts = Counter(
        item["status"] for attempt in attempts for item in attempt["coverage"].values()
    )
    pin_counts = Counter(item["artifact"]["status"] for item in literature)
    kind_counts = Counter(item["source_kind"] for item in literature)
    lines = [
        "<!-- Generated by foundations/render_completion_matrix_md.py; do not edit by hand. -->",
        "# Foundations coverage and completion matrix",
        "",
        f"**Coverage result:** `{coverage['result_id']}`",
        "",
        f"**Completion result:** `{completion['result_id']}`",
        "",
        f"**Lifecycle:** `{completion['lifecycle']}`",
        "",
        f"**Dependencies:** {', '.join(f'`{x}`' for x in completion['dependency_tags'])}",
        "",
        "## Size",
        "",
        "| Layer | Size | Meaning |",
        "|---|---:|---|",
        f"| Assumption coverage | {len(attempts)} programmes × {len(AXES)} axes = **{len(attempts) * len(AXES)} cells** | Six independent assumption/claim axes |",
        f"| Opportunity closure | **{len(completed)} rows**, **{completion['aggregate']['distinct_artifact_count']} certificates** | Ranked first artifacts, evidence, status, and open gates |",
        f"| Literature corpus | **{len(literature)} records** | Imported proposition plus transfer boundary |",
        "",
        "Coverage-cell distribution: "
        + ", ".join(f"{coverage_counts[name]} `{name}`" for name in ("DIRECT", "PARTIAL", "ADJACENT", "ABSENT", "UNKNOWN"))
        + ".",
        "",
        "Literature provenance: "
        + ", ".join(f"{count} `{name}`" for name, count in sorted(pin_counts.items()))
        + "; source kinds: "
        + ", ".join(f"{count} `{name}`" for name, count in sorted(kind_counts.items()))
        + ".",
        "",
        "## Assumption coverage: 16 × 6",
        "",
        "`D` = direct, `P` = partial, `A` = adjacent, `-` = absent, and `?` = unknown. A direct cell says the programme deliberately changes or classifies the axis; it does not assert completeness.",
        "",
        "| Programme | " + " | ".join(label for _, label in AXES) + " | Unresolved intersection |",
        "|---|" + "|".join(":---:" for _ in AXES) + "|---|",
    ]
    for attempt in attempts:
        marks = [STATUS_SYMBOL[attempt["coverage"][key]["status"]] for key, _ in AXES]
        lines.append(
            f"| {cell(attempt['programme'])} | "
            + " | ".join(marks)
            + f" | {cell(attempt['unresolved_intersection'])} |"
        )

    lines += [
        "",
        "## Ranked opportunity completion: 9 rows",
        "",
        "`COMPLETE` means only that the source ranking's bounded first artifact exists and passes its verifier. It does not mean the deeper programme is complete.",
        "",
        "| Rank | Score | Opportunity | Artifact | Status | Evidence | Deeper gate |",
        "|---:|---:|---|---|---|---|---|",
    ]
    for row in sorted(completed, key=lambda item: item["rank"]):
        opportunity = opportunities[row["opportunity_id"]]
        link = report_link(row["artifact"]["path"], output)
        lines.append(
            f"| {row['rank']} | {opportunity['scores']['priority_score']} | `{row['opportunity_id']}` — {cell(row['title'])} "
            f"| [{row['artifact']['result_id']}]({link}) | `{row['first_artifact_status']}` / `{row['scientific_status']}` "
            f"| {cell(row['evidence'])} | {cell(row['deeper_gate'])} |"
        )

    lines += [
        "",
        "Ranks 1 and 3 deliberately share the finite BV certificate: it proves a weak-base sufficiency upper bound and retains the explicit witness that avoids a general separation theorem for that displayed derivation.",
        "",
        "## Literature points: 25 records",
        "",
        "Each row reports only the proposition imported into this programme. The boundary column prevents transfer from a source theorem to a stronger physics or foundations claim.",
        "",
        "| Year | Source | Pin | Point imported | Boundary |",
        "|---:|---|---|---|---|",
    ]
    for item in sorted(literature, key=lambda x: (x.get("year", 9999), x["id"])):
        url = item.get("stable_url")
        source = f"[{item['id']}]({url})" if url else f"`{item['id']}`"
        point = " ".join(item.get("supported_statements", []))
        lines.append(
            f"| {item.get('year', '—')} | {source} | `{item['artifact']['status']}` | {cell(point)} | {cell(item['boundary'])} |"
        )

    lines += [
        "",
        "## Corpus-level open boundaries",
        "",
    ]
    for ledger_name, item in ledger_unresolved:
        lines.append(f"- `{ledger_name}`: {cell(item)}")

    lines += [
        "",
        "## Closure boundary",
        "",
        completion["completion_meaning"],
        "",
        "The matrix establishes no literature-completeness result, universal weakest base, constructive interacting Weyl QFT, full Lorentzian off-shell BV propagator, BRST-compatible Hadamard state, renormalized Lorentzian time-ordered products, or Lorentzian QME theorem.",
        "",
        "## Regenerate or check",
        "",
        "```bash",
        "python3 foundations/render_completion_matrix_md.py",
        "python3 foundations/render_completion_matrix_md.py --check",
        "```",
        "",
    ]
    return "\n".join(lines)


def main(argv: list[str] | None = None) -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--output", type=Path, default=DEFAULT_OUTPUT)
    parser.add_argument("--check", action="store_true", help="fail if the output differs from a fresh render")
    args = parser.parse_args(argv)
    output = args.output if args.output.is_absolute() else ROOT / args.output
    text = render(output=output)
    if args.check:
        if not output.is_file() or output.read_text() != text:
            print(f"STALE: {output}", file=sys.stderr)
            return 1
        print(f"PASS: {output} sha256={sha256_text(text)}")
        return 0
    output.parent.mkdir(parents=True, exist_ok=True)
    output.write_text(text)
    print(f"WROTE: {output} sha256={sha256_text(text)}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
