#!/usr/bin/env python3
"""Render the foundations coverage, completion, and literature ledgers as Markdown."""
from __future__ import annotations

import argparse
from collections import Counter
import hashlib
import json
import os
from pathlib import Path
import sys
from typing import Any

ROOT = Path(__file__).resolve().parents[1]
COVERAGE = ROOT / "foundations/results/FOUNDATIONAL_COVERAGE_MATRIX_V0.json"
COMPLETION = ROOT / "foundations/results/FOUNDATIONAL_RANKED_OPPORTUNITY_COMPLETION_MATRIX_V1.json"
CUBE = ROOT / "foundations/results/FOUNDATIONAL_INTERSECTION_CUBE_V0.json"
LEDGERS = (
    ROOT / "foundations/literature-ledger.json",
    ROOT / "foundations/literature-supplement-known-attempts-v1.json",
    ROOT / "foundations/literature-expansion-v2.json",
)
DEFAULT_OUTPUT = ROOT / "foundations/reports/completion-matrix.md"
AXES = (
    ("LOGIC", "Logic"),
    ("SET_EXISTENCE", "Set/existence"),
    ("INFINITY", "Infinity"),
    ("CARRIER_GEOMETRY", "Carrier"),
    ("PHYSICAL_POSTULATES", "Physical postulates"),
    ("TARGET_CLAIMS", "Target claims"),
)
STATUS_LABEL = {
    "DIRECT": "Direct",
    "PARTIAL": "Partial",
    "ADJACENT": "Adjacent",
    "ABSENT": "Not addressed",
    "UNKNOWN": "Not yet classified",
}
DIMENSION_LABEL = {
    "FOUNDATION": "Mathematical regime",
    "CARRIER": "Carrier/analysis",
    "OBLIGATION": "Physical obligation",
}


def load(path: Path) -> dict[str, Any]:
    return json.loads(path.read_text())


def sha256_text(text: str) -> str:
    return hashlib.sha256(text.encode()).hexdigest()


def cell(value: Any) -> str:
    return " ".join(str(value).split()).replace("|", "\\|")


def report_link(result_path: str, output: Path) -> str:
    result = load(ROOT / result_path)
    report = ROOT / result["human_report"]
    return Path(os.path.relpath(report, output.parent)).as_posix()


def render(*, output: Path = DEFAULT_OUTPUT) -> str:
    coverage = load(COVERAGE)
    completion = load(COMPLETION)
    cube = load(CUBE)
    literature = []
    ledger_unresolved = []
    for path in LEDGERS:
        ledger = load(path)
        literature.extend(ledger["entries"])
        ledger_unresolved.extend((path.name, item) for item in ledger.get("unresolved", []))

    attempts = coverage["attempts"]
    opportunities = {item["id"]: item for item in coverage["opportunities"]}
    completed = completion["entries"]
    if len(attempts) != 16 or len(completed) != 9 or len(literature) < 25:
        raise ValueError("unexpected matrix dimensions")
    if {item["opportunity_id"] for item in completed} != set(opportunities):
        raise ValueError("completion rows do not match ranked opportunities")
    if len({item["id"] for item in literature}) != len(literature):
        raise ValueError("duplicate literature identifiers")

    coverage_counts = Counter(
        item["status"] for attempt in attempts for item in attempt["coverage"].values()
    )
    pin_counts = Counter(item["artifact"]["status"] for item in literature)
    kind_counts = Counter(item["source_kind"] for item in literature)
    cube_axes = {axis["id"]: axis for axis in cube["axes"]}
    foundation_keys = cube_axes["FOUNDATION"]["keys"]
    carrier_keys = cube_axes["CARRIER"]["keys"]
    obligation_keys = cube_axes["OBLIGATION"]["keys"]
    cube_cells = {(x["foundation"], x["carrier"], x["obligation"]): x for x in cube["cells"]}
    cube_status = {x["id"]: x for x in cube["cell_statuses"]}
    cube_counts = Counter(x["status"] for x in cube["cells"])
    cube_counts["NOT_MAPPED"] = 216 - len(cube["cells"])
    if len(cube_cells) != len(cube["cells"]) or any(len(x["keys"]) != 6 for x in cube["axes"]):
        raise ValueError("invalid cube dimensions or duplicate cells")
    lines = [
        "<!-- Generated by foundations/render_completion_matrix_md.py; do not edit by hand. -->",
        "# Foundations coverage and completion matrix",
        "",
        f"**Coverage result:** `{coverage['result_id']}`",
        "",
        f"**Completion result:** `{completion['result_id']}`",
        "",
        f"**Cube result:** `{cube['result_id']}`",
        "",
        f"**Lifecycle:** `{completion['lifecycle']}`",
        "",
        f"**Dependencies:** {', '.join(f'`{x}`' for x in completion['dependency_tags'])}",
        "",
        "## Size",
        "",
        "| Layer | Size | Meaning |",
        "|---|---:|---|",
        f"| Assumption coverage | {len(attempts)} programmes × {len(AXES)} axes = **{len(attempts) * len(AXES)} cells** | Six independent assumption/claim axes |",
        f"| Intersection cube | 6 mathematical regimes × 6 carriers × 6 physical obligations = **216 cells** | Simplified three-dimensional overview rendered as six slices |",
        f"| Opportunity closure | **{len(completed)} rows**, **{completion['aggregate']['distinct_artifact_count']} certificates** | Ranked first artifacts, evidence, status, and open gates |",
        f"| Literature corpus | **{len(literature)} records** | Imported proposition plus transfer boundary |",
        "",
        "Coverage-cell distribution: "
        + ", ".join(f"{coverage_counts[name]} **{STATUS_LABEL[name].lower()}**" for name in ("DIRECT", "PARTIAL", "ADJACENT", "ABSENT", "UNKNOWN"))
        + ".",
        "",
        "Literature provenance: "
        + ", ".join(f"{count} `{name}`" for name, count in sorted(pin_counts.items()))
        + "; source kinds: "
        + ", ".join(f"{count} `{name}`" for name, count in sorted(kind_counts.items()))
        + ".",
        "",
        "## Simplified three-dimensional overview",
        "",
        "The detailed 16-by-6 table below asks six separate questions about each research programme. That is useful for auditing, but difficult to hold in one's head. This cube compresses those questions into three practical dimensions:",
        "",
        "1. **Mathematical regime:** what rules of logic, existence, Choice, and infinity are allowed?",
        "2. **Carrier/analysis:** what kind of mathematical object carries the theory?",
        "3. **Physical obligation:** what job must that framework actually perform?",
        "",
        cube["cartesian_product_warning"],
        "",
        "### The keys on each dimension",
        "",
        "| Dimension | Question | Six keys |",
        "|---|---|---|",
    ]
    for axis_id in ("FOUNDATION", "CARRIER", "OBLIGATION"):
        axis = cube_axes[axis_id]
        lines.append(f"| {DIMENSION_LABEL[axis_id]} | {cell(axis['question'])} | " + "; ".join(f"**{cell(k['label'])}**" for k in axis["keys"]) + " |")
    lines += [
        "",
        "The grouped keys mean:",
        "",
        "| Dimension | Key | Included ideas |",
        "|---|---|---|",
    ]
    for axis_id in ("FOUNDATION", "CARRIER", "OBLIGATION"):
        for key in cube_axes[axis_id]["keys"]:
            extra = "; ".join(key.get("includes", []))
            explanation = key["meaning"] + ((" Includes: " + extra + ".") if extra else "")
            if key.get("warning"): explanation += " Warning: " + key["warning"]
            lines.append(f"| {DIMENSION_LABEL[axis_id]} | **{cell(key['label'])}** | {cell(explanation)} |")
    lines += [
        "",
        "### What a cube cell says",
        "",
        "| Cell text | Meaning |",
        "|---|---|",
    ]
    for status_id in ("LOCAL_RESULT", "LITERATURE_RESULT", "PIECES_ONLY", "PRIORITY_GAP", "NOT_MAPPED"):
        status = cube_status[status_id]
        lines.append(f"| **{cell(status['label'])}** | {cell(status['meaning'])} |")
    lines += [
        "",
        "A result label marks the strongest bounded evidence currently attached to that coordinate. It never means that every problem in the cell is solved. Conversely, **Not mapped** means 'not assessed by this pass,' while **Priority gap** means 'assessed, meaningful, and presently missing.'",
        "",
        "### Coverage at a glance",
        "",
        "| Cube classification | Cells | Share of all 216 cells |",
        "|---|---:|---:|",
    ]
    for status_id in ("LOCAL_RESULT", "LITERATURE_RESULT", "PIECES_ONLY", "PRIORITY_GAP", "NOT_MAPPED"):
        count = cube_counts[status_id]
        lines.append(f"| {cube_status[status_id]['label']} | {count} | {100 * count / 216:.1f}% |")
    lines += [
        "",
        f"**{len(cube['cells'])} of 216 cells ({100 * len(cube['cells']) / 216:.1f}%)** have now been deliberately assessed. The remaining not-mapped cells are unreviewed coordinates, not evidence of impossibility or absence from the literature.",
        "",
        "Coverage by mathematical regime:",
        "",
        "| Mathematical regime | Local results | Literature results | Pieces only | Priority gaps | Not mapped |",
        "|---|---:|---:|---:|---:|---:|",
    ]
    for foundation in foundation_keys:
        counts = Counter(cube_cells.get((foundation["id"], carrier["id"], obligation["id"]), {"status":"NOT_MAPPED"})["status"] for carrier in carrier_keys for obligation in obligation_keys)
        lines.append(f"| {cell(foundation['label'])} | {counts['LOCAL_RESULT']} | {counts['LITERATURE_RESULT']} | {counts['PIECES_ONLY']} | {counts['PRIORITY_GAP']} | {counts['NOT_MAPPED']} |")
    lines += [
        "",
        "### The six cube slices",
        "",
        "Each slice fixes one mathematical regime. Rows choose the carrier; columns choose the physical obligation. The table prints full status words rather than color or unexplained symbols.",
        "",
    ]
    for foundation in foundation_keys:
        lines += [
            f"#### {foundation['label']}",
            "",
            f"{foundation['meaning']}",
            "",
            "| Carrier ↓ / obligation → | " + " | ".join(x["label"] for x in obligation_keys) + " |",
            "|---|" + "|".join(":---:" for _ in obligation_keys) + "|",
        ]
        for carrier in carrier_keys:
            statuses=[]
            for obligation in obligation_keys:
                entry=cube_cells.get((foundation["id"],carrier["id"],obligation["id"]))
                statuses.append(cube_status[entry["status"]]["label"] if entry else cube_status["NOT_MAPPED"]["label"])
            lines.append(f"| **{cell(carrier['label'])}** | " + " | ".join(statuses) + " |")
        lines.append("")
    foundation_labels={x["id"]:x["label"] for x in foundation_keys}
    carrier_labels={x["id"]:x["label"] for x in carrier_keys}
    obligation_labels={x["id"]:x["label"] for x in obligation_keys}
    lines += [
        "### The five missing faces to investigate thoroughly",
        "",
        "These are groups of related cube cells, not single projects. They show where multiple missing intersections share the same underlying machinery.",
        "",
        "| Missing face | Mathematical regimes | Carriers | Physical obligations | Why it matters |",
        "|---|---|---|---|---|",
    ]
    for face in cube["missing_faces"]:
        coordinates=face["coordinates"]
        lines.append(
            f"| **{cell(face['label'])}** | "
            + ", ".join(foundation_labels[x] for x in coordinates["foundations"])
            + " | " + ", ".join(carrier_labels[x] for x in coordinates["carriers"])
            + " | " + ", ".join(obligation_labels[x] for x in coordinates["obligations"])
            + f" | {cell(face['why'])} |"
        )
    lines += [
        "",
        "The most important structural absence is the **constructive/internal gauge-QFT face**: constructive Hilbert results, localic spectra, and synthetic classical gravity exist, but their intersection with BV cohomology, causal distributions, anomalies, renormalization, and the QME is almost entirely a priority gap. The most approachable high-leverage face is **nonstandard carriers × physical probability**, because explicit Krein and separable C*-objects already exist while state selection remains sharply isolated.",
        "",
        "## Assumption coverage: 16 × 6",
        "",
        "This is a map of **what each programme explicitly investigates**, not a grade for correctness, importance, or quality. Each row is a research programme. Each of the six middle columns is a different question about that programme. The final column names the important connection that is still missing.",
        "",
        "### What the six columns ask",
        "",
        "| Column | Plain-language question |",
        "|---|---|",
        "| Logic | Does the programme deliberately change or analyse the permitted rules of reasoning—for example classical versus intuitionistic logic? |",
        "| Set/existence | Does it analyse what kinds of mathematical objects may be asserted to exist, including Choice, comprehension, or constructive existence requirements? |",
        "| Infinity | Does it deliberately distinguish finite, potentially infinite, countably infinite, or completed infinite structures? |",
        "| Carrier | Does it change or analyse the mathematical space carrying states and observables—for example Hilbert, Krein, C*-algebraic, localic, or finite-field structures? |",
        "| Physical postulates | Does it begin from, vary, or derive explicit physical principles such as locality, continuity, purification, causality, or probability rules? |",
        "| Target claims | Does it clearly state the theorem or physical conclusion whose assumptions are being assessed? |",
        "",
        "### What a cell says",
        "",
        "| Cell text | Meaning | What it does **not** mean | Example from this matrix |",
        "|---|---|---|---|",
        "| **Direct** | The axis is a central, explicit object of the programme: it is changed, derived, or formally classified. | It does not mean the programme completely solves that axis or that its conclusions transfer to Weyl gravity. | Hilbert spaces in ZF directly study set/existence assumptions. |",
        "| **Partial** | The programme treats a real part of the axis, but leaves substantial parts fixed, implicit, or outside its scope. | It does not mean weak evidence or a partly correct theorem. It describes limited scope. | Separable C*-algebras in ZF partially touch physical postulates through the algebra-first motivation, but do not reconstruct physics. |",
        "| **Adjacent** | The programme supplies a nearby result or changes something that bears on the axis indirectly, without analysing that axis itself. | It is not evidence for a direct implication. An additional bridge theorem is required. | Reverse physics is adjacent to infinity because laws may involve infinite structures, but it does not classify infinity principles. |",
        "| **Not addressed** | The reviewed sources for that programme do not substantially discuss this axis. | It does not mean the programme is incompatible with the axis or that no such work exists anywhere. | The reviewed operational reconstructions do not address classical versus intuitionistic logic. |",
        "| **Not yet classified** | The axis may be relevant, but this audit does not yet have enough evidence to label the relationship. | It is not the same as 'not addressed'; it marks an open audit question. | The set/existence strength of the operational reconstruction proofs is not yet classified. |",
        "",
        "The full words are printed in every cell so the table can be read without memorizing abbreviations.",
        "",
        "| Programme | " + " | ".join(label for _, label in AXES) + " | Unresolved intersection |",
        "|---|" + "|".join(":---:" for _ in AXES) + "|---|",
    ]
    for attempt in attempts:
        marks = [STATUS_LABEL[attempt["coverage"][key]["status"]] for key, _ in AXES]
        lines.append(
            f"| {cell(attempt['programme'])} | "
            + " | ".join(marks)
            + f" | {cell(attempt['unresolved_intersection'])} |"
        )

    lines += [
        "",
        "## Ranked opportunity completion: 9 rows",
        "",
        "The numeric **score** is a work-priority heuristic: scientific leverage + repository readiness + boundedness + literature underexposure − dependency cost. It ranks tractable next steps; it is not a measure of truth, importance, or literature quality.",
        "",
        "The status terms have deliberately narrow meanings:",
        "",
        "| Status | Plain-language meaning |",
        "|---|---|",
        "| `COMPLETE` | The bounded first deliverable named in the original ranking exists and passes its verifier. The larger research problem remains open. |",
        "| `SUFFICIENCY_PROVED` | A stated mathematical base is strong enough for the displayed construction. Necessity or weakest possible strength has not been proved unless separately stated. |",
        "| `SEPARATED` | Previously conflated assumptions or conclusions have been distinguished and pinned to different stages. This need not be a new theorem. |",
        "| `AVOIDANCE_PROVED_FOR_DISPLAYED_CERTIFICATE` | This particular finite derivation uses an explicit witness and therefore avoids the named general theorem. It says nothing universal about other derivations. |",
        "| `DEPENDENCY_CUT_COMPLETE` | The assumptions used by the selected theorem have been divided into explicit layers. The layers have not all been reconstructed over weak foundations. |",
        "| `LITERATURE_SCOPED` | Sources, terminology, and obstacles have been mapped, but no formal construction or theorem has been claimed. |",
        "",
        "| Rank | Score | Opportunity | Artifact | Status | Evidence | Deeper gate |",
        "|---:|---:|---|---|---|---|---|",
    ]
    for row in sorted(completed, key=lambda item: item["rank"]):
        opportunity = opportunities[row["opportunity_id"]]
        link = report_link(row["artifact"]["path"], output)
        lines.append(
            f"| {row['rank']} | {opportunity['scores']['priority_score']} | `{row['opportunity_id']}` — {cell(row['title'])} "
            f"| [{row['artifact']['result_id']}]({link}) | `{row['first_artifact_status']}` / `{row['scientific_status']}` "
            f"| {cell(row['evidence'])} | {cell(row['deeper_gate'])} |"
        )

    lines += [
        "",
        "Ranks 1 and 3 deliberately share the finite BV certificate: it proves a weak-base sufficiency upper bound and retains the explicit witness that avoids a general separation theorem for that displayed derivation.",
        "",
        f"## Literature points: {len(literature)} records",
        "",
        "Each row reports only the proposition imported into this programme. The boundary column prevents transfer from a source theorem to a stronger physics or foundations claim.",
        "",
        "The **Pin** column reports provenance, not scientific quality: `CONTENT_PINNED` means the consulted full-text bytes have a recorded hash; `GIT_BLOB_PINNED` means a local repository document is fixed by a Git object; `METADATA_ONLY` means only the bibliographic record is currently pinned, so that source blocks a content freeze.",
        "",
        "| Year | Source | Pin | Point imported | Boundary |",
        "|---:|---|---|---|---|",
    ]
    for item in sorted(literature, key=lambda x: (x.get("year", 9999), x["id"])):
        url = item.get("stable_url")
        source = f"[{item['id']}]({url})" if url else f"`{item['id']}`"
        point = " ".join(item.get("supported_statements", []))
        lines.append(
            f"| {item.get('year', '—')} | {source} | `{item['artifact']['status']}` | {cell(point)} | {cell(item['boundary'])} |"
        )

    lines += [
        "",
        "## Corpus-level open boundaries",
        "",
    ]
    for ledger_name, item in ledger_unresolved:
        lines.append(f"- `{ledger_name}`: {cell(item)}")

    lines += [
        "",
        "## Closure boundary",
        "",
        completion["completion_meaning"],
        "",
        "The matrix establishes no literature-completeness result, universal weakest base, constructive interacting Weyl QFT, full Lorentzian off-shell BV propagator, BRST-compatible Hadamard state, renormalized Lorentzian time-ordered products, or Lorentzian QME theorem.",
        "",
        "## Regenerate or check",
        "",
        "```bash",
        "python3 foundations/render_completion_matrix_md.py",
        "python3 foundations/render_completion_matrix_md.py --check",
        "```",
        "",
    ]
    return "\n".join(lines)


def main(argv: list[str] | None = None) -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--output", type=Path, default=DEFAULT_OUTPUT)
    parser.add_argument("--check", action="store_true", help="fail if the output differs from a fresh render")
    args = parser.parse_args(argv)
    output = args.output if args.output.is_absolute() else ROOT / args.output
    text = render(output=output)
    if args.check:
        if not output.is_file() or output.read_text() != text:
            print(f"STALE: {output}", file=sys.stderr)
            return 1
        print(f"PASS: {output} sha256={sha256_text(text)}")
        return 0
    output.parent.mkdir(parents=True, exist_ok=True)
    output.write_text(text)
    print(f"WROTE: {output} sha256={sha256_text(text)}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
