#!/usr/bin/env python3
from __future__ import annotations

from collections import Counter
import hashlib
import json
from pathlib import Path
import sys

ROOT=Path(__file__).resolve().parents[1]
if str(ROOT) not in sys.path:sys.path.insert(0,str(ROOT))
from foundations.render_completion_matrix_md import DEFAULT_OUTPUT,LEDGERS,COMPLETION,COVERAGE,render

RESULT=ROOT/"foundations/results/FOUNDATIONAL_COMPLETION_MATRIX_MARKDOWN_RENDER_V1.json"
SCHEMA=ROOT/"foundations/schema/foundational-completion-matrix-markdown-render-v1.schema.json"

def load(path):return json.loads(Path(path).read_text())
def sha_bytes(data):return hashlib.sha256(data).hexdigest()
def sha(path):return sha_bytes(Path(path).read_bytes())

def verify(*,result=None,report=None):
    r=load(RESULT) if result is None else result;load(SCHEMA);errors=[];checks=["artifacts parse"]
    if r.get("result_id")!="FOUNDATIONAL_COMPLETION_MATRIX_MARKDOWN_RENDER_V1" or r.get("lifecycle")!="SEPARATED" or r.get("dependency_tags")!=["LOCAL-ALGEBRAIC","REDUCED-MODE","LORENTZIAN-CAUSAL"]:errors.append("identity/lifecycle/tags")
    for pin in r.get("inputs",[]):
        path=ROOT/pin.get("path","")
        if not path.is_file() or sha(path)!=pin.get("sha256"):errors.append("input pin "+str(pin.get("path")))
    generator=r.get("generator",{});generator_path=ROOT/generator.get("path","")
    if not generator_path.is_file() or sha(generator_path)!=generator.get("sha256"):errors.append("generator pin")
    checks.append("input and generator pins")
    expected=render(output=DEFAULT_OUTPUT);actual=DEFAULT_OUTPUT.read_text() if report is None else report
    output=r.get("generated_report",{})
    if actual!=expected:errors.append("render drift")
    if sha_bytes(actual.encode())!=output.get("sha256") or len(actual.splitlines())!=output.get("line_count") or len(actual.split())!=output.get("word_count") or len(actual.encode())!=output.get("byte_count"):errors.append("output metrics")
    checks.append("deterministic Markdown")
    coverage=load(COVERAGE);completion=load(COMPLETION);literature=[]
    for ledger in LEDGERS:literature.extend(load(ledger)["entries"])
    dims=r.get("dimensions",{});statuses=Counter(x["status"] for a in coverage["attempts"] for x in a["coverage"].values());pins=Counter(x["artifact"]["status"] for x in literature)
    expected_dims=(len(coverage["attempts"]),6,len(coverage["attempts"])*6,len(completion["entries"]),completion["aggregate"]["distinct_artifact_count"],len(literature))
    if expected_dims!=(dims.get("programmes"),dims.get("axes"),dims.get("coverage_cells"),dims.get("ranked_opportunities"),dims.get("distinct_completion_certificates"),dims.get("literature_records")):errors.append("dimension counts")
    if dict(statuses)!=dims.get("coverage_status_counts") or dict(pins)!=dims.get("literature_pin_counts"):errors.append("status counts")
    checks.append("96 cells, 9 completions, 25 sources")
    flags=r.get("claim_flags",{})
    for key in ("markdown_matches_current_inputs","plain_language_legend_rendered","all_coverage_cells_rendered","all_completion_rows_rendered","all_literature_points_and_boundaries_rendered"):
        if flags.get(key) is not True:errors.append("positive flag "+key)
    for key in ("literature_complete","deeper_programmes_complete","new_lorentzian_claim"):
        if flags.get(key) is not False:errors.append("boundary flag "+key)
    checks.append("fail-closed flags")
    for token in ("Generated by foundations/render_completion_matrix_md.py","16 programmes × 6 axes = **96 cells**","What the six columns ask","What a cell says","**Direct**","**Partial**","**Adjacent**","**Not addressed**","**Not yet classified**","The full words are printed in every cell","The status terms have deliberately narrow meanings","The **Pin** column reports provenance, not scientific quality","Ranked opportunity completion: 9 rows","Literature points: 25 records","Point imported","Boundary","full Lorentzian off-shell BV propagator"):
        if token not in actual:errors.append("report token "+token)
    checks.append("report content")
    return errors,checks

def main():
    errors,checks=verify();print("FOUNDATIONAL_COMPLETION_MATRIX_MARKDOWN_RENDER_V1: "+("PASS" if not errors else "FAIL"))
    for item in (checks if not errors else errors):print("  - "+item)
    return bool(errors)
if __name__=="__main__":raise SystemExit(main())
