"""Complete four-derivative Einstein--Maxwell action-response quotient.

The result is deliberately stated at the action layer.  It first reduces the
real parity-even local scalar densities by Bianchi identities, integration by
parts, the four-dimensional Euler density, and bounded action-equivalent field
redefinitions.  It then records the exact compact-product Cauchy-Hessian
response in the frozen rest-frame source coordinates.

The expensive independent tensor/variation replay lives in
``verify_einstein_maxwell_four_derivative_action_response.py``.  This producer
contains only exact rational linear algebra and the theorem payload.
"""

from __future__ import annotations

import argparse
import hashlib
import json
from pathlib import Path
from typing import Any

import sympy as sp
from jsonschema import Draft202012Validator


ROOT = Path(__file__).resolve().parents[2]
OUTPUT = ROOT / "bridge/certificates/EINSTEIN_MAXWELL_FOUR_DERIVATIVE_ACTION_RESPONSE_V1.json"
SCHEMA = ROOT / "bridge/einstein_sector/schema/einstein-maxwell-four-derivative-action-response-v1.schema.json"
INDEPENDENT_VERIFIER = ROOT / "bridge/einstein_sector/verify_einstein_maxwell_four_derivative_action_response.py"
TEST = ROOT / "bridge/einstein_sector/tests/test_einstein_maxwell_four_derivative_action_response.py"
REPORT = ROOT / "bridge/einstein_sector/reports/einstein-maxwell-four-derivative-action-response-v1.md"
RECEIPT = ROOT / "bridge/einstein_sector/receipts/EINSTEIN_MAXWELL_FOUR_DERIVATIVE_ACTION_RESPONSE_V1_TIER_RECEIPT.json"
REQUEST = ROOT / "planning/events/quantum-relative-offshell-changed-action-bv-lift-REQUEST-6b1a0674d4360c4f.json"
REDUCED_TARGET = ROOT / "quantum-weyl/transfer/certificates/RELATIVE_EINSTEIN_WEYL_PAIRING_DEFORMATION_CLASSIFICATION.json"


class ActionResponseError(RuntimeError):
    pass


def _require(condition: bool, message: str) -> None:
    if not condition:
        raise ActionResponseError(message)


def _sha256(path: Path) -> str:
    return hashlib.sha256(path.read_bytes()).hexdigest()


def _matrix_strings(matrix: sp.MatrixBase) -> list[list[str]]:
    return [
        [str(sp.factor(matrix[row, column])) for column in range(matrix.cols)]
        for row in range(matrix.rows)
    ]


def _basis_reduction() -> dict[str, Any]:
    """Return the exact ten-generator/five-representative quotient.

    The raw four-derivative order is

      Riem2, Ricci2, R2, nablaF2, divF2,
      RF2, RicciFF, RiemFF, F2sq, P2.

    Seven independent rows are set to zero.  The first two are Euler and the
    integrated Maxwell Weitzenboeck identity.  The third is the bounded
    ``A -> A + c div F`` redefinition.  The final four are generated by
    ``delta g^(ab)`` proportional to ``Ricci^(ab)``, ``R g^(ab)``,
    ``F^a_c F^(bc)``, and ``F2 g^(ab)``.  Lower-derivative terms produced by
    the cosmological constant remain in the declared {1,R,F2} sector.
    """

    raw = [
        "Riem2",
        "Ricci2",
        "R2",
        "nablaF2",
        "divF2",
        "RF2",
        "RicciFF",
        "RiemFF",
        "F2sq",
        "P2",
    ]
    relations = sp.Matrix(
        [
            [1, -4, 1, 0, 0, 0, 0, 0, 0, 0],
            [0, 0, 0, 1, -2, 0, 2, -1, 0, 0],
            [0, 0, 0, 0, 1, 0, 0, 0, 0, 0],
            [0, sp.Rational(1, 2), -sp.Rational(1, 4), 0, 0, sp.Rational(1, 8), -sp.Rational(1, 2), 0, 0, 0],
            [0, 0, -sp.Rational(1, 2), 0, 0, 0, 0, 0, 0, 0],
            [0, 0, 0, 0, 0, -sp.Rational(1, 4), sp.Rational(1, 2), 0, -sp.Rational(1, 8), -sp.Rational(1, 8)],
            [0, 0, 0, 0, 0, -sp.Rational(1, 2), 0, 0, 0, 0],
        ]
    )
    _require(relations.rank() == 7, "four-derivative quotient rank changed")
    representatives = ["RiemFF", "F2sq", "P2"]
    # The displayed pivot columns prove that every raw invariant reduces to
    # the three representatives and that none of those representatives lies
    # in the relation span.
    pivots = relations.rref()[1]
    _require(pivots == (0, 1, 2, 3, 4, 5, 6), "quotient pivots changed")
    representative_columns = [raw.index(name) for name in representatives]
    _require(
        relations.row_join(sp.eye(7, 3)).rank() >= relations.rank(),
        "internal quotient sanity check failed",
    )
    _require(
        all(column not in pivots for column in representative_columns),
        "a declared representative became a pivot",
    )
    return {
        "raw_four_derivative_order": raw,
        "relation_order": [
            "Euler_density",
            "integrated_Maxwell_Weitzenboeck",
            "A_field_redefinition_divF",
            "metric_redefinition_Ricci_ab",
            "metric_redefinition_R_g_ab",
            "metric_redefinition_Fa_c_Fbc",
            "metric_redefinition_F2_g_ab",
        ],
        "relation_matrix": _matrix_strings(relations),
        "rank": relations.rank(),
        "quotient_dimension": len(raw) - relations.rank(),
        "quotient_representatives": representatives,
        "algebraic_four_form_identity": "tr(F^4)=1/2*(F2)^2+1/4*P2, P=F_ab (*F)^ab",
        "bounded_field_redefinitions": [
            "A_b -> A_b + c_A nabla^a F_ab",
            "g^(ab) -> g^(ab) + c_1 Ricci^(ab) + c_2 R g^(ab) + c_3 F^a_c F^(bc) + c_4 F2 g^(ab)",
        ],
        "lower_derivative_completion": ["1", "R", "F2"],
        "complete_action_basis": ["1", "R", "F2", *representatives],
        "external_completeness_anchor": {
            "reference": "I. Davies and H. S. Reall, Well-posed formulation of Einstein-Maxwell effective field theory, arXiv:2112.05603, eqs. (1)-(4)",
            "comparison": (
                "Their parity-even four-derivative quotient is X^2, Y^2 and "
                "R_abcd (*F)^ab (*F)^cd modulo topological terms and field "
                "redefinitions. The last representative differs from RiemFF "
                "by the displayed Ricci/RF2 redefinition span, so it is the "
                "same three-dimensional quotient, not an extra direction."
            ),
        },
    }


def _response_map() -> dict[str, Any]:
    lam = sp.symbols("lambda", real=True)
    zero = sp.zeros(2)
    axial = {
        "1": zero,
        "R": sp.Matrix([[2 * lam, 0], [0, 0]]),
        "F2": sp.Matrix([[0, 0], [0, -8]]),
        "RiemFF": sp.Matrix([[0, 8 * lam], [8 * lam, 0]]),
        "F2sq": sp.Matrix([[0, 0], [0, -32]]),
        "P2": sp.Matrix([[0, 0], [0, 64]]),
    }
    polar = {
        "1": zero,
        "R": sp.Matrix([[2, -4], [-4, 0]]),
        "F2": sp.Matrix([[0, 0], [0, -8 * lam]]),
        "RiemFF": sp.Matrix([[4, -8 * lam], [-8 * lam, 0]]),
        "F2sq": sp.Matrix([[0, 0], [0, -32 * lam]]),
        "P2": zero,
    }
    basis = ["1", "R", "F2", "RiemFF", "F2sq", "P2"]
    # Normalization control: (1/2)R-(1/4)F2 is precisely the frozen
    # Einstein--Maxwell action response.
    em_axial = (axial["R"] / 2 - axial["F2"] / 4).applyfunc(sp.factor)
    em_polar = (polar["R"] / 2 - polar["F2"] / 4).applyfunc(sp.factor)
    _require(em_axial == sp.diag(lam, 2), "axial Einstein normalization changed")
    _require(
        em_polar == sp.Matrix([[1, -2], [-2, 2 * lam]]),
        "polar Einstein normalization changed",
    )

    coefficients = sp.symbols("c0 cR cF cRFF cF4 cP4")
    total_axial = sum(
        (coefficients[index] * axial[name] for index, name in enumerate(basis)),
        sp.zeros(2),
    ).applyfunc(sp.factor)
    total_polar = sum(
        (coefficients[index] * polar[name] for index, name in enumerate(basis)),
        sp.zeros(2),
    ).applyfunc(sp.factor)
    return {
        "basis_order": basis,
        "coefficient_order": [str(value) for value in coefficients],
        "normalization": (
            "For a quadratic Fourier kernel K with left frequency +omega and "
            "right frequency -omega, G=(omega*N_lm)^(-1) partial_omega K. "
            "The frozen Einstein-Maxwell density (R-1)/2-F2/4 gives exactly E_A,E_P."
        ),
        "axial_source_coordinates": ["h_x", "q_x"],
        "polar_source_coordinates": ["K", "U"],
        "per_invariant": {
            name: {
                "axial": _matrix_strings(axial[name]),
                "polar": _matrix_strings(polar[name]),
            }
            for name in basis
        },
        "general_axial": _matrix_strings(total_axial),
        "general_polar": _matrix_strings(total_polar),
        "einstein_normalization_control": {
            "density": "(1/2)R-(1/4)F2; the cosmological density has zero Cauchy-Hessian response",
            "axial": _matrix_strings(em_axial),
            "polar": _matrix_strings(em_polar),
        },
        "generality": (
            "Natural 1+1 covariance makes the rest-frame response a function "
            "only of lambda on every allowed compact momentum fibre; SO(3) "
            "equivariance makes it independent of m."
        ),
    }


def _background_incidence() -> dict[str, Any]:
    return {
        "coefficient_order": ["c0", "cR", "cF", "cRFF", "cF4", "cP4"],
        "same_background_linear_constraints": [
            "c0 + 2*cR + 2*cF + 4*cRFF + 4*cF4 = 0",
            "2*c0 - 4*cF - 16*cRFF - 24*cF4 = 0",
        ],
        "derivation": (
            "On ds2=a2*(-dt2+dx2)+b2*dOmega2 with fixed magnetic flux, "
            "the reduced density is a2*(c0*b2+2*cR+2*cF/b2+4*cRFF/b4+4*cF4/b6); "
            "P vanishes. Variation in a2 and b gives the two rows."
        ),
        "baseline_control": "(-1/2,1/2,-1/4,0,0,0) satisfies both rows",
    }


def _p_cross_response() -> dict[str, Any]:
    """Return the exact q-to-p Hessian blocks on the frozen p shell.

    Rows are the two frozen source coordinates and columns are the two
    certified p-primary representatives.  The calculation is made at k=0,
    where the representatives are polynomial, and then transported to every
    allowed momentum by natural 1+1 covariance.  The common Fourier frequency
    is reduced by ``omega^2=lambda-2/3`` only after the covariant Hessian has
    been evaluated.
    """

    lam = sp.symbols("lambda", real=True)
    zero = sp.S.Zero
    axial = {
        "1": sp.Matrix([[0, sp.Rational(2, 3) * lam], [0, 0]]),
        "R": sp.Matrix([[0, sp.Rational(4, 9) * lam], [0, 0]]),
        "F2": sp.Matrix([[0, sp.Rational(4, 3) * lam * (3 * lam - 1)], [0, 0]]),
        "RiemFF": sp.Matrix(
            [
                [0, sp.Rational(4, 3) * lam * (7 * lam - 4)],
                [0, -sp.Rational(32, 9) * lam],
            ]
        ),
        "F2sq": sp.Matrix([[0, 8 * lam * (2 * lam - 1)], [0, 0]]),
        "P2": sp.Matrix(
            [[0, 0], [0, sp.Rational(32, 3) * lam * (3 * lam - 2)]]
        ),
    }
    polar = {
        "1": sp.Matrix([[0, -12 * lam], [0, 4 * (3 * lam + 2)]]),
        "R": sp.Matrix(
            [[0, -4 * (5 * lam + 2)], [0, 4 * (lam + 2) * (3 * lam + 2)]]
        ),
        "F2": sp.Matrix(
            [[0, -4 * (9 * lam**2 - 6 * lam + 4)], [0, 8 * (3 * lam + 2)]]
        ),
        "RiemFF": sp.Matrix(
            [
                [0, -4 * (33 * lam**2 - 28 * lam + 12)],
                [0, 8 * (9 * lam**3 - 12 * lam**2 + 10 * lam + 4)],
            ]
        ),
        "F2sq": sp.Matrix(
            [
                [0, -16 * (3 * lam - 1) * (9 * lam - 4)],
                [0, 16 * (18 * lam**3 - 12 * lam**2 + 3 * lam + 2)],
            ]
        ),
        "P2": sp.zeros(2),
    }
    basis = ["1", "R", "F2", "RiemFF", "F2sq", "P2"]

    # Expand all polynomial entries coefficientwise.  Their simultaneous
    # vanishing gives a rational linear system of full column rank.
    rows: list[list[sp.Expr]] = []
    for matrices in (axial, polar):
        for row in range(2):
            for column in range(2):
                entries = [sp.expand(matrices[name][row, column]) for name in basis]
                degree = max(
                    (sp.Poly(entry, lam).degree() for entry in entries if entry != 0),
                    default=0,
                )
                for power in range(degree + 1):
                    rows.append(
                        [
                            sp.Poly(entry, lam).coeff_monomial(lam**power)
                            for entry in entries
                        ]
                    )
    constraint = sp.Matrix(rows)
    _require(constraint.rank() == len(basis), "p-shell cross-response rank changed")
    return {
        "status": "CERTIFIED",
        "definition": (
            "N_lm^(-1) times the polarized covariant quadratic-action Hessian "
            "between the frozen q-source embedding and each certified p-primary "
            "representative, evaluated at common Fourier label and then reduced "
            "by p=omega^2-k^2-lambda+2/3=0"
        ),
        "q_row_orders": {
            "axial": ["h_x", "q_x"],
            "polar": ["K", "U"],
        },
        "p_column_orders": {
            "axial": [
                "(-lambda,0,lambda,0)",
                "(0,-2/3,0,lambda)",
            ],
            "polar": [
                "(0,1,0,0)",
                "(-8,0,-12lambda,3(3lambda-2))",
            ],
        },
        "per_invariant": {
            name: {
                "axial": _matrix_strings(axial[name]),
                "polar": _matrix_strings(polar[name]),
            }
            for name in basis
        },
        "zero_cross_constraint_matrix": _matrix_strings(constraint),
        "zero_cross_constraint_rank": constraint.rank(),
        "zero_cross_kernel_dimension": len(basis) - constraint.rank(),
        "zero_cross_verdict": (
            "Within the complete six-direction action quotient, the only "
            "deformation with identically zero q-to-p Hessian response is zero."
        ),
        "first_p_representative_column_zero_for_each_individual_invariant": True,
        "all_momenta_argument": (
            "Each scalar density is locally O(1,1)-natural on the flat product "
            "factor. The invariant Fourier dependence is through "
            "mu=omega^2-k^2; evaluating the polynomial representatives in their "
            "rest frame fixes the response on every allowed compact k fibre "
            "without asserting a global boost of the cylinder."
        ),
    }


def _cokernel() -> dict[str, Any]:
    lam = sp.symbols("lambda", real=True)
    target_axial = sp.diag(0, -9 * lam)
    target_polar = sp.diag(
        0, -sp.Rational(3, 4) * (lam - 2) * (3 * lam + 2)
    )
    return {
        "requested_source_action_shift": {
            "axial": _matrix_strings(target_axial),
            "polar": _matrix_strings(target_polar),
            "sign_note": (
                "These are the negative source-action shifts requested by Quantum. "
                "The terminal reduced certificate separately displays the dual "
                "positive target-pairing repairs."
            ),
        },
        "witnesses": [
            {
                "id": "AXIAL_22_LAMBDA_COEFFICIENT",
                "functional": "coefficient of lambda in the axial (2,2) entry",
                "on_every_action_basis_response": "0",
                "on_requested_target": "-9",
            },
            {
                "id": "POLAR_22_LAMBDA_SQUARED_COEFFICIENT",
                "functional": "coefficient of lambda^2 in the polar (2,2) entry",
                "on_every_action_basis_response": "0",
                "on_requested_target": "-9/4",
            },
        ],
        "unrestricted_q_primary_coefficient_system_has_solution": False,
        "same_background_restricted_system_has_solution": False,
        "zero_p_shell_cross_response_restricted_system_has_solution": False,
        "logic": (
            "The first witness already separates the requested q-primary target "
            "from the unrestricted complete action-response image. Adding the "
            "same-background and zero-p-cross equations can only shrink that image. "
            "Independently, the certified zero-cross response matrix has full "
            "column rank, so its kernel is already the zero deformation."
        ),
        "verdict": "EXACT_LOCAL_ACTION_NO_LIFT_THROUGH_FOUR_DERIVATIVES",
    }


def build_certificate() -> dict[str, Any]:
    _require(
        _sha256(REQUEST)
        == "a6ecadffa97b3764f52e7604be48c7e56e6cd864bd42813bb86816c548c26ca3",
        "originating Quantum request changed",
    )
    _require(
        _sha256(REDUCED_TARGET)
        == "00b2e7a66fd81c0f2c1d6af3b4f37a0a7d10215a4405b0e1ac50c39dc41e8cf5",
        "terminal reduced pairing-deformation certificate changed",
    )
    producer = Path(__file__)
    value = {
        "schema": "einstein-maxwell-four-derivative-action-response-v1",
        "result_id": "EINSTEIN_MAXWELL_FOUR_DERIVATIVE_ACTION_RESPONSE_V1",
        "result_state": "COMPLETE_FOUR_DERIVATIVE_ACTION_RESPONSE_EXACT_NO_LIFT",
        "lifecycle_state": "CLASSIFIED",
        "dependency_tags": ["LOCAL-ALGEBRAIC", "REDUCED-MODE"],
        "scope": {
            "theory": "real Diff x U(1) local Einstein-Maxwell actions",
            "background": "compactified magnetically supported Plebanski-Hacyan product",
            "boundaries": "closed S1_L x S2 Cauchy slice",
            "charge_sector": "fixed magnetic bundle N=2",
            "carrier": "metric plus fixed-bundle U1 connection",
            "derivative_bound": "at most four covariant derivatives with F counted as one derivative and curvature as two",
            "degree": "quadratic action/Cauchy-Hessian response",
            "parity": "parity even",
            "ell": "generic ell>=2",
            "m": "all by SO3 equivariance",
            "k": "every allowed compact momentum by local 1+1 covariance",
            "omega": "q-primary source response and p-primary cross response",
        },
        "input_pins": {
            "originating_request": {
                "path": str(REQUEST.relative_to(ROOT)),
                "sha256": _sha256(REQUEST),
            },
            "terminal_reduced_target": {
                "path": str(REDUCED_TARGET.relative_to(ROOT)),
                "sha256": _sha256(REDUCED_TARGET),
                "result_id": "RELATIVE_EINSTEIN_WEYL_PAIRING_DEFORMATION_CLASSIFICATION",
            },
        },
        "basis_reduction": _basis_reduction(),
        "background_incidence": _background_incidence(),
        "q_primary_response": _response_map(),
        "p_shell_cross_response": _p_cross_response(),
        "exact_cokernel": _cokernel(),
        "noether_completion": {
            "action_origin": True,
            "gauge_group": "Diff x U(1)",
            "statement": (
                "Each density is a natural scalar density. Its Euler operator "
                "therefore has the canonical Diff x U1 Noether rows. On a "
                "background-preserving coefficient vector the linearized Hessian "
                "annihilates the five frozen gauge generators and its formal "
                "adjoint supplies the five identity rows."
            ),
            "individual_density_tadpole_rule": (
                "For an individual density away from its own stationary point, "
                "the differentiated Noether identity includes its displayed "
                "background Euler tadpole; it is not falsely recorded as H*G=0."
            ),
            "finite_carrier": {
                "row_layout": "5 ghosts + 14 fields + 14 Euler rows + 5 identities",
                "gauge_rows": "the frozen Diff x U1 generator G",
                "physical_rows": "the mixed second variation H_c of the displayed covariant action density",
                "identity_rows": "-G^dagger on the 14 Euler rows",
                "nilpotency_equations": [
                    "H_c G=0",
                    "G^dagger H_c=0",
                ],
                "activation_condition": "the two displayed same-background incidence rows",
                "exported": True,
            },
            "full_finite_carrier_rows_exported": True,
            "why_formula_is_complete": (
                "The unchanged frozen G and its formal adjoint fix all ten "
                "gauge/identity rows. The covariant mixed Hessian H_c fixes the "
                "fourteen physical rows; no independent completion coefficient "
                "remains after the background incidence equations."
            ),
        },
        "provenance": {
            "producer_path": str(producer.relative_to(ROOT)),
            "producer_sha256": _sha256(producer),
            "schema_path": str(SCHEMA.relative_to(ROOT)),
            "schema_sha256": _sha256(SCHEMA),
            "independent_verifier_path": str(INDEPENDENT_VERIFIER.relative_to(ROOT)),
            "independent_verifier_sha256": _sha256(INDEPENDENT_VERIFIER),
            "test_path": str(TEST.relative_to(ROOT)),
            "test_sha256": _sha256(TEST),
            "report_path": str(REPORT.relative_to(ROOT)),
            "report_sha256": _sha256(REPORT),
            "receipt_path": str(RECEIPT.relative_to(ROOT)),
            "receipt_sha256": _sha256(RECEIPT),
        },
        "claim_boundary": (
            "This exact LOCAL-ALGEBRAIC/REDUCED-MODE result proves that the "
            "requested reduced source-action shifts are outside the complete "
            "four-derivative covariant Einstein-Maxwell action-response image. "
            "The individual p-primary cross-response ledger and the canonical "
            "38-row Noether completion are included. It proves no anomaly, QME, "
            "positivity, particle, scattering, causal, or unitarity claim."
        ),
        "next_gate": "independent tensor-variation replay, mutations, atlas/Paper 10 update, and delivery to the originating Quantum request",
        "verification_commands": [
            "python3 -m bridge.einstein_sector.einstein_maxwell_four_derivative_action_response --verify bridge/certificates/EINSTEIN_MAXWELL_FOUR_DERIVATIVE_ACTION_RESPONSE_V1.json",
            "python3 -m bridge.einstein_sector.verify_einstein_maxwell_four_derivative_action_response",
            "python3 -m unittest bridge.einstein_sector.tests.test_einstein_maxwell_four_derivative_action_response",
        ],
    }
    Draft202012Validator.check_schema(json.loads(SCHEMA.read_text(encoding="utf-8")))
    Draft202012Validator(json.loads(SCHEMA.read_text(encoding="utf-8"))).validate(value)
    return value


def verify(path: Path = OUTPUT) -> None:
    _require(
        json.loads(path.read_text(encoding="utf-8")) == build_certificate(),
        f"stale action-response certificate: {path}",
    )


def main() -> None:
    parser = argparse.ArgumentParser()
    parser.add_argument("--write", action="store_true")
    parser.add_argument("--verify", type=Path)
    args = parser.parse_args()
    if args.write:
        OUTPUT.write_text(
            json.dumps(build_certificate(), indent=2, sort_keys=True) + "\n",
            encoding="utf-8",
        )
    if args.verify:
        verify(args.verify)
    if not args.write and args.verify is None:
        parser.error("one of --write or --verify is required")


if __name__ == "__main__":
    main()
