"""Exceptional global Einstein--Maxwell symplectic completion."""

from __future__ import annotations

import argparse
import hashlib
import json
from pathlib import Path
from typing import Any

import sympy as sp

from bridge.einstein_sector.einstein_maxwell_radiative_lee_wald_fixture import (
    _sphere_integral,
    _symplectic_current_time,
)


ROOT = Path(__file__).resolve().parents[2]
EXCEPTIONAL_CERTIFICATE = ROOT / "bridge/certificates/einstein_maxwell_polar_exceptional_complex.json"
AXIAL_CERTIFICATE = ROOT / "bridge/certificates/einstein_maxwell_axial_master_complex.json"
RADIATIVE_CERTIFICATE = ROOT / "bridge/certificates/einstein_maxwell_radiative_symplectic_matching.json"
DEFAULT_OUTPUT = ROOT / "bridge/certificates/einstein_maxwell_exceptional_global_symplectic.json"
SCHEMA_PATH = ROOT / "bridge/einstein_sector/schema/einstein_maxwell_exceptional_global_symplectic.schema.json"


class ExceptionalGlobalSymplecticError(RuntimeError):
    pass


def _require(condition: bool, message: str) -> None:
    if not condition:
        raise ExceptionalGlobalSymplecticError(message)


def _load(path: Path) -> dict[str, Any]:
    return json.loads(path.read_text(encoding="utf-8"))


def _sha256(path: Path) -> str:
    return hashlib.sha256(path.read_bytes()).hexdigest()


def _ell0_variation(
    parameters: tuple[sp.Expr, ...],
    time: sp.Symbol,
    sine: sp.Expr,
) -> tuple[sp.Matrix, sp.Matrix]:
    radion_position, radion_velocity, circumference, circumference_velocity, electric, wilson = parameters
    sphere_scale = radion_position + radion_velocity * time
    circle_scale = (
        radion_position * time**2
        + radion_velocity * time**3 / 3
        + circumference
        + circumference_velocity * time
    )
    metric = sp.zeros(4)
    metric[1, 1] = circle_scale
    metric[2, 2] = sphere_scale
    metric[3, 3] = sphere_scale * sine**2
    potential = sp.zeros(4, 1)
    potential[1] = wilson + electric * time
    return metric, potential


def _twist_variation(
    twist: sp.Expr,
    twist_velocity: sp.Expr,
    time: sp.Symbol,
    harmonic: sp.Expr,
    axial_one_form: sp.Expr,
) -> tuple[sp.Matrix, sp.Matrix]:
    amplitude = twist + twist_velocity * time
    metric = sp.zeros(4)
    metric[1, 3] = metric[3, 1] = amplitude * axial_one_form
    potential = sp.zeros(4, 1)
    potential[1] = -amplitude * harmonic
    return metric, potential


def _direct_currents() -> dict[str, sp.Expr]:
    time, space, theta, azimuth = sp.symbols("t x theta phi", real=True)
    coordinates = (time, space, theta, azimuth)
    sine = sp.sin(theta)
    metric_background = sp.diag(-1, 1, 1, sine**2)
    field_background = sp.zeros(4)
    field_background[2, 3] = sine
    field_background[3, 2] = -sine

    first_parameters = sp.symbols("a1 b1 c1 d1 e1 w1", real=True)
    second_parameters = sp.symbols("a2 b2 c2 d2 e2 w2", real=True)
    ell0_current = _symplectic_current_time(
        metric_background,
        field_background,
        _ell0_variation(first_parameters, time, sine),
        _ell0_variation(second_parameters, time, sine),
        coordinates,
    )

    first_twist, first_velocity, second_twist, second_velocity = sp.symbols(
        "A1 B1 A2 B2", real=True
    )
    harmonic = sp.cos(theta)
    axial_one_form = -sine * sp.diff(harmonic, theta)
    twist_current = _symplectic_current_time(
        metric_background,
        field_background,
        _twist_variation(
            first_twist,
            first_velocity,
            time,
            harmonic,
            axial_one_form,
        ),
        _twist_variation(
            second_twist,
            second_velocity,
            time,
            harmonic,
            axial_one_form,
        ),
        coordinates,
    )
    return {
        "ell0_omega_t_per_unit_x": _sphere_integral(
            ell0_current, theta, azimuth
        ),
        "twist_omega_t_per_unit_x": _sphere_integral(
            twist_current, theta, azimuth
        ),
    }


def _ell0_theorem() -> dict[str, Any]:
    matrix = sp.Matrix(
        [
            [0, -1, 0, -1, 0, 0],
            [1, 0, 1, 0, 0, 0],
            [0, -1, 0, 0, 0, 0],
            [1, 0, 0, 0, 0, 0],
            [0, 0, 0, 0, 0, -2],
            [0, 0, 0, 0, 2, 0],
        ]
    )
    _require(matrix.rank() == 6, "ell=0 global pairing lost rank")
    _require(matrix.det() == 4, "ell=0 global pairing determinant changed")
    return {
        "parameter_order": ["a", "b", "c", "d", "Q_e", "W_x"],
        "representative": [
            "K=a+b*t",
            "C=a*t^2+(b/3)*t^3+c+d*t",
            "A_x=W_x+Q_e*t",
        ],
        "new_potential_level_mode": "W_x is the flat S1 connection coefficient. It is absent from a field-strength-only classification but is not generated by a smooth periodic identity-component U(1) parameter.",
        "large_gauge_statement": "including winding U(1) transformations makes the holonomy L*W_x periodic; the tangent symplectic form is unchanged",
        "Cauchy_form": "Omega_ell0=-2*pi*L[da^db+da^dd-db^dc+2*dQ_e^dW_x]",
        "dimensionless_matrix_after_factor_2piL": [
            [str(value) for value in matrix.row(row)] for row in range(6)
        ],
        "matrix_rank": int(matrix.rank()),
        "matrix_determinant": int(matrix.det()),
        "Darboux_reorganization": "with beta=b+d, Omega_grav=-2*pi*L*da^d beta+2*pi*L*db^dc; the named radion pair (a,b) and circumference pair (c,d) mix symplectically",
        "Maxwell_Darboux_pair": "mathcal W=L*W_x and mathcal Q_e=4*pi*Q_e obey Omega_Maxwell=d mathcal W^d mathcal Q_e",
        "fixed_bundle_scope": "uniform magnetic variation remains excluded; W_x changes flat holonomy, not c1(P_N)",
    }


def _twist_theorem() -> dict[str, Any]:
    return {
        "all_m_representative": "for each real ell=1 harmonic Y_(1m), h_(x,a)=(A_m+B_m*t)X_a and a_x=-(A_m+B_m*t)Y_(1m)",
        "equation": "the ell=1 minus eigenvector (H,Q)=(1,-1) has zero master eigenvalue, so ddot(A_m+B_m*t)=0",
        "periodic_gauge_audit": "generating either A_m or B_m*t requires the axial gauge parameter s=x*(A_m+B_m*t), which is not periodic on S1 unless A_m=B_m=0",
        "Cauchy_form": "Omega_twist=2*L*sum_m N_1m*dA_m^dB_m; for Y_10=cos(theta), N_10=4*pi/3 and the coefficient is 8*pi*L/3",
        "rank_per_real_harmonic": 2,
        "SO3_statement": "SO(3) equivariance makes three identical real Darboux blocks; cross-m pairings vanish in an orthogonal real harmonic basis",
        "interpretation": "the constant twist is not an isolated presymplectic null direction once the generalized time-linear solution is included; A_m and B_m form a global canonical pair",
    }


def _direct_fixture() -> dict[str, Any]:
    currents = _direct_currents()
    a1, b1, c1, d1, e1, w1 = sp.symbols("a1 b1 c1 d1 e1 w1", real=True)
    a2, b2, c2, d2, e2, w2 = sp.symbols("a2 b2 c2 d2 e2 w2", real=True)
    A1, B1, A2, B2 = sp.symbols("A1 B1 A2 B2", real=True)
    expected_ell0 = 2 * sp.pi * (
        a1 * b2
        + a1 * d2
        - a2 * b1
        - a2 * d1
        - b1 * c2
        + b2 * c1
        + 2 * e1 * w2
        - 2 * e2 * w1
    )
    expected_twist = -8 * sp.pi * (A1 * B2 - A2 * B1) / 3
    _require(
        sp.simplify(currents["ell0_omega_t_per_unit_x"] - expected_ell0) == 0,
        "ell=0 direct Lee-Wald current changed",
    )
    _require(
        sp.simplify(currents["twist_omega_t_per_unit_x"] - expected_twist)
        == 0,
        "twist direct Lee-Wald current changed",
    )
    return {
        "current_convention": "omega^t=delta1 theta^t(delta2)-delta2 theta^t(delta1); Omega_Sigma=-L*int_S2 omega^t",
        "ell0_coordinate_current_per_unit_x": str(expected_ell0),
        "twist_coordinate_current_per_unit_x": str(expected_twist),
        "ell0_time_dependence_after_equations": "0",
        "twist_time_dependence_after_equations": "0",
        "remainders": {"ell0": "0", "twist": "0"},
    }


def _completion_ledger() -> list[dict[str, Any]]:
    return [
        {
            "certificate": "bridge/certificates/einstein_maxwell_polar_exceptional_complex.json",
            "json_pointer": "/ell0_complex/global_moduli",
            "addition": "the potential-level phase space includes the flat S1 holonomy W_x conjugate to the already classified electric coefficient Q_e",
            "scope": "completion, not contradiction: W_x has zero field strength and was invisible in the prior field-strength complex",
        },
        {
            "certificate": "bridge/certificates/einstein_maxwell_axial_master_complex.json",
            "json_pointer": "/ell1_quotient/global_zero_mode",
            "addition": "the constant axial twist A_m has the generalized solution B_m*t as its nondegenerate symplectic partner",
            "scope": "generalized zero-frequency completion; the prior constant-twist classification remains valid",
        },
    ]


def build_certificate() -> dict[str, Any]:
    exceptional = _load(EXCEPTIONAL_CERTIFICATE)
    axial = _load(AXIAL_CERTIFICATE)
    radiative = _load(RADIATIVE_CERTIFICATE)
    _require(
        exceptional["result_id"] == "COMPACT_EM_POLAR_EXCEPTIONAL_COMPLEX",
        "exceptional input changed",
    )
    _require(
        axial["result_id"] == "COMPACT_EM_AXIAL_MASTER_COMPLEX",
        "axial input changed",
    )
    _require(
        radiative["result_id"] == "COMPACT_EM_RADIATIVE_SYMPLECTIC_MATCHING",
        "radiative input changed",
    )
    _require(
        "global_moduli" in exceptional["ell0_complex"],
        "ell=0 completion pointer changed",
    )
    _require(
        "global_zero_mode" in axial["ell1_quotient"],
        "axial-twist completion pointer changed",
    )
    return {
        "schema": "einstein-maxwell-exceptional-global-symplectic-v1",
        "schema_path": str(SCHEMA_PATH.relative_to(ROOT)),
        "schema_sha256": _sha256(SCHEMA_PATH),
        "result_id": "COMPACT_EM_EXCEPTIONAL_GLOBAL_SYMPLECTIC",
        "result_state": "ELL0_AND_AXIAL_ELL1_GLOBAL_PAIRINGS_CERTIFIED_WEYL_PULLBACK_OPEN",
        "lifecycle_state": "CLASSIFIED",
        "dependency_tags": ["LOCAL-ALGEBRAIC", "REDUCED-MODE"],
        "generality_level": "G2_FIXED_BUNDLE_STANDARD_HARMONIC_GLOBAL_COMPLETION",
        "provenance": {
            "generator_path": str(Path(__file__).relative_to(ROOT)),
            "generator_sha256": _sha256(Path(__file__)),
            "inputs": {
                str(path.relative_to(ROOT)): _sha256(path)
                for path in (
                    EXCEPTIONAL_CERTIFICATE,
                    AXIAL_CERTIFICATE,
                    RADIATIVE_CERTIFICATE,
                )
            },
        },
        "domain": "generalized zero-frequency Einstein-Maxwell solutions on R_t x S1_L x S2 at fixed magnetic bundle P_N; smooth periodic identity-component Diff x U(1); before final residual quotient",
        "ell0_global_theorem": _ell0_theorem(),
        "axial_ell1_twist_theorem": _twist_theorem(),
        "direct_lee_wald_fixture": _direct_fixture(),
        "completes": _completion_ledger(),
        "classification": {
            "ell0_metric_global_form_nondegenerate": True,
            "electric_charge_holonomy_pair_complete": True,
            "axial_ell1_twist_generalized_pair_complete": True,
            "all_three_real_ell1_harmonics": True,
            "fixed_bundle_standard_harmonic_symplectic_completion": True,
            "bounded_in_time_subspace_theorem": False,
            "one_particle_complex_structure_constructed": False,
            "Weyl_Maxwell_pullback_matching": False,
            "final_residual_quotient_computed": False,
            "Lorentzian_causal_or_scattering_theorem": False,
        },
        "interpretation": "The compact Einstein-Maxwell tangent has a nondegenerate global zero-frequency phase space before the final residual quotient. Radion and circumference solution labels mix in the symplectic form, electric charge is paired with S1 holonomy, and each axial ell=1 constant twist is paired with its time-linear generalized solution. These global canonical pairs are distinct from local radiative modes and from final SO(4,2)-reduced states.",
        "next_gate": "compute the pullback of the Weyl-Maxwell Lee-Wald form to the now-complete fixed-bundle standard Einstein-Maxwell harmonic phase space, keeping radiative and generalized global blocks separate",
        "claim_boundary": "This LOCAL-ALGEBRAIC/REDUCED-MODE theorem completes the integrated Einstein-Maxwell symplectic pairing on the declared generalized zero-frequency standard harmonic sector. It permits polynomial-in-time Jordan solutions; a bounded-in-time restriction would define a different, generally degenerate subspace. It does not compute a one-particle norm, the Weyl-Maxwell pullback, the final residual quotient, causal boundary conditions, scattering, or quantum theory.",
        "verification_commands": [
            "python3 -m bridge.einstein_sector.einstein_maxwell_exceptional_global_symplectic --verify bridge/certificates/einstein_maxwell_exceptional_global_symplectic.json",
            "python3 bridge/einstein_sector/verify_einstein_maxwell_exceptional_global_symplectic.py",
            "python3 -m unittest bridge.einstein_sector.tests.test_einstein_maxwell_exceptional_global_symplectic",
        ],
    }


def verify_certificate(path: Path = DEFAULT_OUTPUT) -> None:
    _require(
        _load(path) == build_certificate(),
        f"exceptional global symplectic certificate stale: {path}",
    )


def main() -> None:
    parser = argparse.ArgumentParser()
    parser.add_argument("--write", action="store_true")
    parser.add_argument("--verify", type=Path)
    args = parser.parse_args()
    if args.write:
        DEFAULT_OUTPUT.write_text(
            json.dumps(build_certificate(), indent=2, sort_keys=True) + "\n",
            encoding="utf-8",
        )
    if args.verify:
        verify_certificate(args.verify)
    if not args.write and not args.verify:
        parser.error("one of --write or --verify is required")


if __name__ == "__main__":
    main()
