"""Generate fail-closed atlas row for the two-jet derived charge carrier."""
import argparse,hashlib,json
from pathlib import Path
ROOT=Path(__file__).resolve().parents[2];CERT=ROOT/"bridge/certificates/EINSTEIN_WEYL_CONSTRAINT_ALGEBROID_KURANISHI_CARRIER_V1.json";OUT=ROOT/"residual_atlas/einstein-weyl-constraint-algebroid-kuranishi-fragment-v1.json"
def sha(p):return hashlib.sha256(p.read_bytes()).hexdigest()
def build():
 c=json.loads(CERT.read_text());return {"schema":"pure-weyl-residual-atlas-fragment-v1","schema_version":"1.0.0","team":"einstein_nonlinear","generated_by":str(Path(__file__).relative_to(ROOT)),"generated_by_sha256":sha(Path(__file__)),"description_axes":["causal","symplectic","nonlinear","observational","quantum"],"status_vocabulary":["CERTIFIED","OBSTRUCTED","OPEN","NOT_APPLICABLE","NO_CERTIFIED_MAP"],"entries":[{"id":"einstein.ph.wm.constraint_algebroid.kuranishi_two_jet","scope":c["scope"],"descriptions":{"causal":"NO_CERTIFIED_MAP","symplectic":"OBSTRUCTED","nonlinear":"CERTIFIED","observational":"NO_CERTIFIED_MAP","quantum":"NO_CERTIFIED_MAP"},"mode_data":{"dispersion":{"status":"NOT_APPLICABLE","statement":"Cauchy constraint carrier."},"lee_wald":{"status":"CERTIFIED","statement":"Ambient Schur form restricts along inclusions but does not descend through the obstructed extra projection."},"taub_maps":{"status":"CERTIFIED","statement":"The two-jet Koszul carrier has five generators H,P_x,J_i and restricts to the finite-harmonic moment maps."},"resonance":{"status":"OPEN","statement":"Carrier-dependent spacetime resonances remain separate."},"second_order":{"equation":"L_barPhi v = -(1/2) D^2 E_barPhi[u,u]","bounded_or_finite_quasiperiodic":{"status":"OPEN","statement":"Cauchy version is DC v=-(1/2)D^2C[u,u]; no bounded promotion."},"smooth_secular":{"status":"OPEN","statement":"Not promoted."},"causal_retarded":{"status":"NO_CERTIFIED_MAP","statement":"No retarded carrier."}}},"evidence":[{"path":str(CERT.relative_to(ROOT)),"result_id":c["result_id"],"sha256":sha(CERT)}],"claim_boundary":c["claim_boundary"]}],"verification_commands":["python3 -m bridge.einstein_sector.generate_constraint_algebroid_kuranishi_atlas --check","python3 residual_atlas/validate_fragment.py residual_atlas/einstein-weyl-constraint-algebroid-kuranishi-fragment-v1.json"]}
def main():
 p=argparse.ArgumentParser();p.add_argument("--write",action="store_true");p.add_argument("--check",action="store_true");a=p.parse_args();x=build()
 if a.write:OUT.write_text(json.dumps(x,indent=2,sort_keys=True)+"\n")
 if a.check:assert json.loads(OUT.read_text())==x
if __name__=="__main__":main()
