"""Exact multilinear jet algebra for the compact 2+2 product.

The Berger Taylor producers use a left-invariant PBW algebra and therefore
cannot be reused on ``R x S1 x S2``.  This module keeps coordinate-dependent
background coefficients until every derivative has acted and only then
evaluates the exhaustive jet at the equatorial base point.  Coordinate
derivatives commute; curvature is generated by the exact product metric, not
inserted by a fitted commutator table.

The storage convention is the polarized Taylor convention: bilinear and
trilinear entries are derivatives, with no factorial absorbed.
"""

from __future__ import annotations

from dataclasses import dataclass
from functools import lru_cache
from itertools import combinations_with_replacement, permutations, product
from typing import Iterable, Sequence

import sympy as sp


COORDINATES = sp.symbols("t x theta phi", real=True)
T, X, THETA, PHI = COORDINATES
BASE_POINT = {T: 0, X: 0, THETA: sp.pi / 2, PHI: 0}
PAIRS = tuple((a, b) for a in range(4) for b in range(a, 4))
PAIR_INDEX = {pair: index for index, pair in enumerate(PAIRS)}


def _normalize_coefficient(value: sp.Expr) -> sp.Expr:
    """Keep construction cheap while removing exact zeros when apparent."""

    value = sp.sympify(value)
    if value == 0:
        return sp.S.Zero
    return value


def _base_coefficient(value: sp.Expr) -> sp.Rational:
    # Every coordinate derivative has already acted.  Substitution first is
    # dramatically cheaper than globally simplifying thousands of trigonometric
    # coefficient expressions and is exact at the homogeneous base point.
    value = sp.cancel(sp.sympify(value).subs(BASE_POINT))
    if value == 0:
        return sp.S.Zero
    if not value.is_Rational:
        raise ValueError(f"product coefficient did not reduce to Q: {value}")
    return sp.Rational(value)


@dataclass(frozen=True)
class LinearOperator:
    terms: tuple[tuple[int, tuple[int, ...], sp.Expr], ...] = ()

    @staticmethod
    def from_terms(terms: Iterable[tuple[int, Sequence[int], sp.Expr]]) -> "LinearOperator":
        combined: dict[tuple[int, tuple[int, ...]], sp.Expr] = {}
        for component, word, coefficient in terms:
            word = tuple(sorted(int(axis) for axis in word))
            coefficient = _normalize_coefficient(coefficient)
            if coefficient != 0:
                key = (int(component), word)
                combined[key] = combined.get(key, sp.S.Zero) + coefficient
        return LinearOperator(tuple((*key, value) for key, value in sorted(combined.items()) if value != 0))

    @staticmethod
    def basis(component: int) -> "LinearOperator":
        return LinearOperator(((component, (), sp.S.One),))

    def __add__(self, other: "LinearOperator") -> "LinearOperator":
        return LinearOperator.from_terms((*self.terms, *other.terms))

    def __neg__(self) -> "LinearOperator":
        return self.scale(-1)

    def __sub__(self, other: "LinearOperator") -> "LinearOperator":
        return self + (-other)

    def scale(self, coefficient: sp.Expr) -> "LinearOperator":
        return LinearOperator.from_terms((component, word, coefficient * value) for component, word, value in self.terms)

    def derivative(self, axis: int) -> "LinearOperator":
        coordinate = COORDINATES[axis]
        return LinearOperator.from_terms(
            term
            for component, word, coefficient in self.terms
            for term in (
                (component, word, sp.diff(coefficient, coordinate)),
                (component, (*word, axis), coefficient),
            )
        )

    def at_base_point(self) -> "LinearOperator":
        return LinearOperator.from_terms((component, word, _base_coefficient(coefficient)) for component, word, coefficient in self.terms)

    @property
    def maximum_total_order(self) -> int:
        return max((len(word) for _, word, _ in self.terms), default=-1)


LZERO = LinearOperator()


@dataclass(frozen=True)
class BilinearOperator:
    terms: tuple[tuple[int, tuple[int, ...], int, tuple[int, ...], sp.Expr], ...] = ()

    @staticmethod
    def from_terms(terms: Iterable[tuple[int, Sequence[int], int, Sequence[int], sp.Expr]]) -> "BilinearOperator":
        combined: dict[tuple[int, tuple[int, ...], int, tuple[int, ...]], sp.Expr] = {}
        for left, left_word, right, right_word, coefficient in terms:
            key = (int(left), tuple(sorted(int(axis) for axis in left_word)), int(right), tuple(sorted(int(axis) for axis in right_word)))
            coefficient = _normalize_coefficient(coefficient)
            if coefficient != 0:
                combined[key] = combined.get(key, sp.S.Zero) + coefficient
        return BilinearOperator(tuple((*key, value) for key, value in sorted(combined.items()) if value != 0))

    def __add__(self, other: "BilinearOperator") -> "BilinearOperator":
        return BilinearOperator.from_terms((*self.terms, *other.terms))

    def __neg__(self) -> "BilinearOperator":
        return self.scale(-1)

    def __sub__(self, other: "BilinearOperator") -> "BilinearOperator":
        return self + (-other)

    def scale(self, coefficient: sp.Expr) -> "BilinearOperator":
        return BilinearOperator.from_terms((left, lw, right, rw, coefficient * value) for left, lw, right, rw, value in self.terms)

    def derivative(self, axis: int) -> "BilinearOperator":
        coordinate = COORDINATES[axis]
        return BilinearOperator.from_terms(
            term
            for left, left_word, right, right_word, coefficient in self.terms
            for term in (
                (left, left_word, right, right_word, sp.diff(coefficient, coordinate)),
                (left, (*left_word, axis), right, right_word, coefficient),
                (left, left_word, right, (*right_word, axis), coefficient),
            )
        )

    def at_base_point(self) -> "BilinearOperator":
        return BilinearOperator.from_terms((left, lw, right, rw, _base_coefficient(coefficient)) for left, lw, right, rw, coefficient in self.terms)

    def koszul_swapped(self, parities: Sequence[int]) -> "BilinearOperator":
        return BilinearOperator.from_terms(
            (
                right,
                right_word,
                left,
                left_word,
                (-1 if parities[left] * parities[right] else 1) * coefficient,
            )
            for left, left_word, right, right_word, coefficient in self.terms
        )

    @property
    def maximum_total_order(self) -> int:
        return max((len(lw) + len(rw) for _, lw, _, rw, _ in self.terms), default=-1)


BZERO = BilinearOperator()


@dataclass(frozen=True)
class TrilinearOperator:
    terms: tuple[tuple[int, tuple[int, ...], int, tuple[int, ...], int, tuple[int, ...], sp.Expr], ...] = ()

    @staticmethod
    def from_terms(terms: Iterable[tuple]) -> "TrilinearOperator":
        combined: dict[tuple, sp.Expr] = {}
        for first, fw, second, sw, third, tw, coefficient in terms:
            key = (
                int(first), tuple(sorted(int(axis) for axis in fw)),
                int(second), tuple(sorted(int(axis) for axis in sw)),
                int(third), tuple(sorted(int(axis) for axis in tw)),
            )
            coefficient = _normalize_coefficient(coefficient)
            if coefficient != 0:
                combined[key] = combined.get(key, sp.S.Zero) + coefficient
        return TrilinearOperator(tuple((*key, value) for key, value in sorted(combined.items()) if value != 0))

    def __add__(self, other: "TrilinearOperator") -> "TrilinearOperator":
        return TrilinearOperator.from_terms((*self.terms, *other.terms))

    def __neg__(self) -> "TrilinearOperator":
        return self.scale(-1)

    def __sub__(self, other: "TrilinearOperator") -> "TrilinearOperator":
        return self + (-other)

    def scale(self, coefficient: sp.Expr) -> "TrilinearOperator":
        return TrilinearOperator.from_terms((a, aw, b, bw, c, cw, coefficient * value) for a, aw, b, bw, c, cw, value in self.terms)

    def derivative(self, axis: int) -> "TrilinearOperator":
        coordinate = COORDINATES[axis]
        return TrilinearOperator.from_terms(
            term
            for first, fw, second, sw, third, tw, coefficient in self.terms
            for term in (
                (first, fw, second, sw, third, tw, sp.diff(coefficient, coordinate)),
                (first, (*fw, axis), second, sw, third, tw, coefficient),
                (first, fw, second, (*sw, axis), third, tw, coefficient),
                (first, fw, second, sw, third, (*tw, axis), coefficient),
            )
        )

    def at_base_point(self) -> "TrilinearOperator":
        return TrilinearOperator.from_terms((a, aw, b, bw, c, cw, _base_coefficient(value)) for a, aw, b, bw, c, cw, value in self.terms)

    def koszul_permuted(self, order: tuple[int, int, int], parities: Sequence[int]) -> "TrilinearOperator":
        terms = []
        for first, fw, second, sw, third, tw, coefficient in self.terms:
            slots = ((first, fw), (second, sw), (third, tw))
            exponent = 0
            for left in range(3):
                for right in range(left + 1, 3):
                    if order[left] > order[right]:
                        exponent += parities[slots[order[left]][0]] * parities[slots[order[right]][0]]
            terms.append(
                (
                    slots[order[0]][0], slots[order[0]][1],
                    slots[order[1]][0], slots[order[1]][1],
                    slots[order[2]][0], slots[order[2]][1],
                    (-1 if exponent % 2 else 1) * coefficient,
                )
            )
        return TrilinearOperator.from_terms(terms)

    @property
    def maximum_total_order(self) -> int:
        return max((len(aw) + len(bw) + len(cw) for _, aw, _, bw, _, cw, _ in self.terms), default=-1)


TZERO = TrilinearOperator()


def _sum_linear(values: Iterable[LinearOperator]) -> LinearOperator:
    return LinearOperator.from_terms(term for value in values for term in value.terms)


def _sum_bilinear(values: Iterable[BilinearOperator]) -> BilinearOperator:
    return BilinearOperator.from_terms(term for value in values for term in value.terms)


def _sum_trilinear(values: Iterable[TrilinearOperator]) -> TrilinearOperator:
    return TrilinearOperator.from_terms(term for value in values for term in value.terms)


def _outer(first: LinearOperator, second: LinearOperator) -> BilinearOperator:
    return BilinearOperator.from_terms((a, aw, b, bw, av * bv) for a, aw, av in first.terms for b, bw, bv in second.terms)


def _outer3(first: LinearOperator, second: LinearOperator, third: LinearOperator) -> TrilinearOperator:
    return TrilinearOperator.from_terms((a, aw, b, bw, c, cw, av * bv * cv) for a, aw, av in first.terms for b, bw, bv in second.terms for c, cw, cv in third.terms)


def _sym_outer3(first: LinearOperator, second: LinearOperator, third: LinearOperator) -> TrilinearOperator:
    values = (first, second, third)
    return _sum_trilinear(_outer3(values[order[0]], values[order[1]], values[order[2]]) for order in permutations(range(3)))


def _sym_linear_bilinear(linear: LinearOperator, bilinear: BilinearOperator) -> TrilinearOperator:
    return TrilinearOperator.from_terms(
        term
        for a, aw, av in linear.terms
        for b, bw, c, cw, value in bilinear.terms
        for term in (
            (a, aw, b, bw, c, cw, av * value),
            (b, bw, a, aw, c, cw, av * value),
            (b, bw, c, cw, a, aw, av * value),
        )
    )


@dataclass(frozen=True)
class TaylorJet:
    background: sp.Expr = sp.S.Zero
    linear: LinearOperator = LZERO
    bilinear: BilinearOperator = BZERO
    trilinear: TrilinearOperator = TZERO

    @staticmethod
    def constant(value: sp.Expr) -> "TaylorJet":
        return TaylorJet(sp.sympify(value))

    @staticmethod
    def field(component: int, background: sp.Expr = sp.S.Zero) -> "TaylorJet":
        return TaylorJet(sp.sympify(background), LinearOperator.basis(component), BZERO, TZERO)

    def __add__(self, other: "TaylorJet") -> "TaylorJet":
        return TaylorJet(self.background + other.background, self.linear + other.linear, self.bilinear + other.bilinear, self.trilinear + other.trilinear)

    def __neg__(self) -> "TaylorJet":
        return self.scale(-1)

    def __sub__(self, other: "TaylorJet") -> "TaylorJet":
        return self + (-other)

    def scale(self, coefficient: sp.Expr) -> "TaylorJet":
        return TaylorJet(coefficient * self.background, self.linear.scale(coefficient), self.bilinear.scale(coefficient), self.trilinear.scale(coefficient))

    def __mul__(self, other: "TaylorJet") -> "TaylorJet":
        return TaylorJet(
            self.background * other.background,
            self.linear.scale(other.background) + other.linear.scale(self.background),
            self.bilinear.scale(other.background) + other.bilinear.scale(self.background) + _outer(self.linear, other.linear) + _outer(other.linear, self.linear),
            self.trilinear.scale(other.background) + other.trilinear.scale(self.background) + _sym_linear_bilinear(self.linear, other.bilinear) + _sym_linear_bilinear(other.linear, self.bilinear),
        )

    def reciprocal(self) -> "TaylorJet":
        if self.background == 0:
            raise ZeroDivisionError("Taylor reciprocal needs nonzero background")
        inverse = 1 / self.background
        return TaylorJet(
            inverse,
            self.linear.scale(-inverse**2),
            self.bilinear.scale(-inverse**2) + _outer(self.linear, self.linear).scale(2 * inverse**3),
            self.trilinear.scale(-inverse**2) + _sym_linear_bilinear(self.linear, self.bilinear).scale(2 * inverse**3) + _outer3(self.linear, self.linear, self.linear).scale(-6 * inverse**4),
        )

    def __truediv__(self, other: "TaylorJet") -> "TaylorJet":
        return self * other.reciprocal()

    def derivative(self, axis: int) -> "TaylorJet":
        return TaylorJet(sp.diff(self.background, COORDINATES[axis]), self.linear.derivative(axis), self.bilinear.derivative(axis), self.trilinear.derivative(axis))

    def power(self, exponent: int) -> "TaylorJet":
        if exponent < 0:
            return self.reciprocal().power(-exponent)
        output = TaylorJet.constant(1)
        for _ in range(exponent):
            output = output * self
        return output

    def sqrt(self) -> "TaylorJet":
        root = sp.sqrt(self.background).xreplace({sp.Abs(sp.sin(THETA)): sp.sin(THETA)})
        first = sp.Rational(1, 2) / root
        second = -sp.Rational(1, 4) / self.background**sp.Rational(3, 2)
        third = sp.Rational(3, 8) / self.background**sp.Rational(5, 2)
        return TaylorJet(
            root,
            self.linear.scale(first),
            self.bilinear.scale(first) + _outer(self.linear, self.linear).scale(second),
            self.trilinear.scale(first) + _sym_linear_bilinear(self.linear, self.bilinear).scale(second) + _outer3(self.linear, self.linear, self.linear).scale(third),
        )


JZERO = TaylorJet()


def sum_jets(values: Iterable[TaylorJet]) -> TaylorJet:
    values = tuple(values)
    if not values:
        return JZERO
    return TaylorJet(
        sum((value.background for value in values), sp.S.Zero),
        _sum_linear(value.linear for value in values),
        _sum_bilinear(value.bilinear for value in values),
        _sum_trilinear(value.trilinear for value in values),
    )


def metric_jet() -> dict[tuple[int, int], TaylorJet]:
    background = sp.diag(-1, 1, 1, sp.sin(THETA) ** 2)
    return {
        (a, b): TaylorJet.field(PAIR_INDEX[tuple(sorted((a, b)))], background[a, b])
        for a, b in product(range(4), repeat=2)
    }


def inverse_metric(metric: dict[tuple[int, int], TaylorJet]) -> dict[tuple[int, int], TaylorJet]:
    background_inverse = sp.diag(-1, 1, 1, sp.sin(THETA) ** -2)
    output: dict[tuple[int, int], TaylorJet] = {}
    for a, b in product(range(4), repeat=2):
        linear = _sum_linear(
            metric[(i, j)].linear.scale(-background_inverse[a, i] * background_inverse[j, b])
            for i, j in product(range(4), repeat=2)
        )
        bilinear = _sum_bilinear(
            (_outer(metric[(i, j)].linear, metric[(k, l)].linear) + _outer(metric[(k, l)].linear, metric[(i, j)].linear)).scale(background_inverse[a, i] * background_inverse[j, k] * background_inverse[l, b])
            for i, j, k, l in product(range(4), repeat=4)
        )
        trilinear = _sum_trilinear(
            _sym_outer3(metric[(i, j)].linear, metric[(k, l)].linear, metric[(m, n)].linear).scale(
                -background_inverse[a, i]
                * background_inverse[j, k]
                * background_inverse[l, m]
                * background_inverse[n, b]
            )
            for i, j, k, l, m, n in product(range(4), repeat=6)
        )
        output[(a, b)] = TaylorJet(background_inverse[a, b], linear, bilinear, trilinear)
    return output


def determinant(metric: dict[tuple[int, int], TaylorJet]) -> TaylorJet:
    terms = []
    for permutation in permutations(range(4)):
        inversions = sum(permutation[a] > permutation[b] for a in range(4) for b in range(a + 1, 4))
        value = TaylorJet.constant(-1 if inversions % 2 else 1)
        for row, column in enumerate(permutation):
            value = value * metric[(row, column)]
        terms.append(value)
    return sum_jets(terms)


def volume_ratio(metric: dict[tuple[int, int], TaylorJet]) -> TaylorJet:
    return (determinant(metric).scale(-1).sqrt()).scale(1 / sp.sin(THETA))


def connection(metric: dict[tuple[int, int], TaylorJet], inverse: dict[tuple[int, int], TaylorJet]) -> dict[tuple[int, int, int], TaylorJet]:
    return {
        (target, left, right): sum_jets(
            inverse[(target, index)]
            * (metric[(index, right)].derivative(left) + metric[(index, left)].derivative(right) - metric[(left, right)].derivative(index)).scale(sp.Rational(1, 2))
            for index in range(4)
        )
        for target, left, right in product(range(4), repeat=3)
    }


def covariant_derivative(tensor: dict[tuple[int, ...], TaylorJet], variance: tuple[int, ...], gamma: dict[tuple[int, int, int], TaylorJet]) -> dict[tuple[int, ...], TaylorJet]:
    output: dict[tuple[int, ...], TaylorJet] = {}
    for axis in range(4):
        for indices in product(range(4), repeat=len(variance)):
            value = tensor.get(indices, JZERO).derivative(axis)
            for position, sign in enumerate(variance):
                current = indices[position]
                if sign == -1:
                    value = value - sum_jets(
                        gamma[(replacement, axis, current)] * tensor.get(indices[:position] + (replacement,) + indices[position + 1 :], JZERO)
                        for replacement in range(4)
                    )
                else:
                    value = value + sum_jets(
                        gamma[(current, axis, replacement)] * tensor.get(indices[:position] + (replacement,) + indices[position + 1 :], JZERO)
                        for replacement in range(4)
                    )
            output[(axis, *indices)] = value
    return output


@lru_cache(maxsize=1)
def metric_geometry() -> dict[str, object]:
    metric = metric_jet()
    inverse = inverse_metric(metric)
    gamma = connection(metric, inverse)
    riemann = {
        (target, vector, first, second): gamma[(target, second, vector)].derivative(first)
        - gamma[(target, first, vector)].derivative(second)
        + sum_jets(
            gamma[(middle, second, vector)] * gamma[(target, first, middle)]
            - gamma[(middle, first, vector)] * gamma[(target, second, middle)]
            for middle in range(4)
        )
        for target, vector, first, second in product(range(4), repeat=4)
    }
    ricci = {(a, b): sum_jets(riemann[(index, a, index, b)] for index in range(4)) for a, b in product(range(4), repeat=2)}
    scalar = sum_jets(inverse[(a, b)] * ricci[(a, b)] for a, b in product(range(4), repeat=2))
    return {"metric": metric, "inverse": inverse, "connection": gamma, "riemann": riemann, "ricci": ricci, "scalar": scalar, "volume_ratio": volume_ratio(metric)}


@lru_cache(maxsize=None)
def _coefficient_jet(value: sp.Expr, word: tuple[int, ...]) -> sp.Rational:
    current = value
    for axis in word:
        current = sp.diff(current, COORDINATES[axis])
    return _base_coefficient(current)


def operation_record(
    operator: LinearOperator | BilinearOperator | TrilinearOperator,
    *,
    output_row: int,
    coefficient_jet_order: int = 2,
) -> list[dict[str, object]]:
    records = []
    for term in operator.terms:
        if isinstance(operator, LinearOperator):
            component, word, coefficient = term
            inputs = [{"row": component, "word": list(word)}]
        elif isinstance(operator, BilinearOperator):
            left, lw, right, rw, coefficient = term
            inputs = [{"row": left, "word": list(lw)}, {"row": right, "word": list(rw)}]
        else:
            first, fw, second, sw, third, tw, coefficient = term
            inputs = [{"row": first, "word": list(fw)}, {"row": second, "word": list(sw)}, {"row": third, "word": list(tw)}]
        jets = []
        for order in range(coefficient_jet_order + 1):
            for word in combinations_with_replacement(range(4), order):
                value = _coefficient_jet(coefficient, word)
                if value != 0:
                    jets.append({"word": list(word), "coefficient": str(value)})
        base = next((item["coefficient"] for item in jets if item["word"] == []), "0")
        if base == "0":
            # A term whose coefficient vanishes at the base point can still
            # contribute after an outer derivative hits it, so it remains in
            # the executable table with its nonzero higher coefficient jets.
            if not jets:
                continue
        records.append({
            "output_row": output_row,
            "inputs": inputs,
            "coefficient": base,
            "coefficient_jets": jets,
        })
    return records


def compose_linear(
    outer: LinearOperator,
    inner_rows: Sequence[LinearOperator],
) -> LinearOperator:
    """Compose scalar-row ``outer`` with a column of coordinate operators."""

    terms = []
    for middle, word, coefficient in outer.terms:
        current = inner_rows[middle]
        for axis in word:
            current = current.derivative(axis)
        terms.extend((component, inner_word, coefficient * value) for component, inner_word, value in current.terms)
    return LinearOperator.from_terms(terms)


def formal_adjoint_scalar(operator: LinearOperator) -> LinearOperator:
    """Formal adjoint for the fixed product measure ``sin(theta) d^4x``."""

    log_measure_derivative = (sp.S.Zero, sp.S.Zero, sp.cot(THETA), sp.S.Zero)
    output = LZERO
    for component, word, coefficient in operator.terms:
        states = LinearOperator(((component, (), coefficient),))
        for axis in reversed(word):
            coordinate = COORDINATES[axis]
            divergence = log_measure_derivative[axis]
            states = LinearOperator.from_terms(
                term
                for source, source_word, value in states.terms
                for term in (
                    (source, source_word, -sp.diff(value, coordinate) - divergence * value),
                    (source, (*source_word, axis), -value),
                )
            )
        output = output + states
    return output


def formal_adjoint_matrix(matrix: Sequence[Sequence[LinearOperator]]) -> tuple[tuple[LinearOperator, ...], ...]:
    rows = len(matrix)
    columns = len(matrix[0]) if rows else 0
    if any(len(row) != columns for row in matrix):
        raise ValueError("ragged operator matrix")
    output = [[LZERO for _ in range(rows)] for _ in range(columns)]
    for row in range(rows):
        for column in range(columns):
            adjoint = formal_adjoint_scalar(matrix[row][column])
            output[column][row] = LinearOperator.from_terms(
                (row, word, coefficient) for _source, word, coefficient in adjoint.terms
            )
    return tuple(tuple(row) for row in output)


def graded_complete_bilinear(operator: BilinearOperator, parities: Sequence[int]) -> BilinearOperator:
    return operator + operator.koszul_swapped(parities)


def graded_complete_trilinear(operator: TrilinearOperator, parities: Sequence[int]) -> TrilinearOperator:
    return _sum_trilinear(
        operator.koszul_permuted(order, parities) for order in permutations(range(3))
    )


def _adjoint_product_states(
    word: tuple[int, ...],
    other_words: tuple[tuple[int, ...], ...],
    coefficient: sp.Expr,
) -> tuple[tuple[tuple[tuple[int, ...], ...], tuple[int, ...], sp.Expr], ...]:
    """Move ``word`` to a dual input using the fixed product measure."""

    divergence = (sp.S.Zero, sp.S.Zero, sp.cot(THETA), sp.S.Zero)
    states: dict[tuple[tuple[tuple[int, ...], ...], tuple[int, ...]], sp.Expr] = {
        (other_words, ()): coefficient
    }
    for axis in reversed(word):
        updated: dict[tuple[tuple[tuple[int, ...], ...], tuple[int, ...]], sp.Expr] = {}
        for (current_others, dual_word), value in states.items():
            def add(key, amount):
                updated[key] = updated.get(key, sp.S.Zero) + amount

            add((current_others, dual_word), -sp.diff(value, COORDINATES[axis]) - divergence[axis] * value)
            for position in range(len(current_others)):
                changed = list(current_others)
                changed[position] = tuple(sorted((*changed[position], axis)))
                add((tuple(changed), dual_word), -value)
            add((current_others, tuple(sorted((*dual_word, axis)))), -value)
        states = updated
    return tuple((others, dual, value) for (others, dual), value in states.items() if value != 0)


def negative_transpose_bilinear_right(
    operator: BilinearOperator,
    *,
    dual_output: int,
) -> dict[int, BilinearOperator]:
    grouped: dict[int, list[tuple]] = {}
    for left, left_word, right, right_word, coefficient in operator.terms:
        for (new_left,), dual_word, value in _adjoint_product_states(right_word, (left_word,), coefficient):
            grouped.setdefault(right, []).append((left, new_left, dual_output, dual_word, -value))
    return {row: BilinearOperator.from_terms(terms) for row, terms in grouped.items()}


def negative_transpose_bilinear_left(
    operator: BilinearOperator,
    *,
    dual_output: int,
) -> dict[int, BilinearOperator]:
    grouped: dict[int, list[tuple]] = {}
    for left, left_word, right, right_word, coefficient in operator.terms:
        for (new_right,), dual_word, value in _adjoint_product_states(left_word, (right_word,), coefficient):
            grouped.setdefault(left, []).append((right, new_right, dual_output, dual_word, -value))
    return {row: BilinearOperator.from_terms(terms) for row, terms in grouped.items()}


def negative_transpose_trilinear_slot(
    operator: TrilinearOperator,
    *,
    slot: int,
    dual_output: int,
) -> dict[int, TrilinearOperator]:
    """Move one ternary input through the fixed product pairing.

    The returned key is the row dual to the selected input.  The remaining
    two inputs retain their order and the original output dual is appended as
    the third input.  Callers perform the Koszul completion once, after
    selecting a nonredundant ordered vertex.
    """

    if slot not in (0, 1, 2):
        raise ValueError("trilinear slot must be zero, one, or two")
    grouped: dict[int, list[tuple]] = {}
    for first, first_word, second, second_word, third, third_word, coefficient in operator.terms:
        rows = (first, second, third)
        words = (first_word, second_word, third_word)
        selected = rows[slot]
        selected_word = words[slot]
        other_rows = tuple(rows[index] for index in range(3) if index != slot)
        other_words = tuple(words[index] for index in range(3) if index != slot)
        for new_words, dual_word, value in _adjoint_product_states(
            selected_word, other_words, coefficient
        ):
            grouped.setdefault(selected, []).append(
                (
                    other_rows[0], new_words[0],
                    other_rows[1], new_words[1],
                    dual_output, dual_word,
                    -value,
                )
            )
    return {
        row: TrilinearOperator.from_terms(terms)
        for row, terms in grouped.items()
    }
