#!/usr/bin/env python3
"""Render and exactly verify the endpoint factorization no-go receipt."""

from __future__ import annotations

import argparse
import hashlib
import json
from pathlib import Path

import sympy as sp


ROOT = Path(__file__).resolve().parents[1]
CERTIFICATE = (
    ROOT
    / "covariant_completion"
    / "certificates"
    / "curved_endpoint_metric_factorization_no_go.json"
)
OUTPUT = ROOT / "paper" / "generated" / "endpoint_factorization_nullstellensatz.tex"


def _sha256(path: Path) -> str:
    return hashlib.sha256(path.read_bytes()).hexdigest()


def _signed_terms(expr: sp.Expr) -> list[tuple[str, sp.Expr]]:
    terms = sp.expand(expr).as_ordered_terms()
    result: list[tuple[str, sp.Expr]] = []
    for term in terms:
        if term.could_extract_minus_sign():
            result.append(("-", -term))
        else:
            result.append(("+", term))
    return result


def _wrapped_math(
    expr: sp.Expr, *, lhs: str | None = None, terms_per_line: int = 2
) -> str:
    """Format a polynomial as narrow aligned lines without changing it."""

    factored = sp.factor(expr)
    coefficient, core = factored.as_coeff_Mul()
    if not isinstance(core, sp.Add):
        prefix = rf"{lhs}=" if lhs else ""
        return rf"\(\displaystyle {prefix}{sp.latex(factored)}\)"

    terms = _signed_terms(core)
    lines: list[str] = []
    for start in range(0, len(terms), terms_per_line):
        chunk = terms[start : start + terms_per_line]
        rendered = ""
        for offset, (sign, term) in enumerate(chunk):
            absolute = sp.latex(term)
            if start == 0 and offset == 0:
                rendered += ("-" if sign == "-" else "") + absolute
            else:
                rendered += rf"\mathbin{{{sign}}}{absolute}"
        lines.append(rendered)

    if coefficient == 1:
        coefficient_tex = ""
    elif coefficient == -1:
        coefficient_tex = "-"
    else:
        coefficient_tex = sp.latex(coefficient)
    if coefficient_tex:
        lines[0] = coefficient_tex + rf"\Bigl({lines[0]}"
        lines[-1] += r"\Bigr)"
    body = r" \\ &\quad ".join(lines)
    prefix = rf"{lhs}&=" if lhs else "&"
    return rf"\(\begin{{aligned}} {prefix}{body}\end{{aligned}}\)"


def render(certificate_path: Path) -> str:
    payload = json.loads(certificate_path.read_text(encoding="utf-8"))
    order2 = payload["staged_solve"]["order2"]
    entries = order2["polynomial_nullstellensatz_certificate"]
    if len(entries) != 12:
        raise AssertionError(f"expected 12 nonzero multipliers, found {len(entries)}")
    if order2["identity"] != "sum_i weight_i constraint_i=1":
        raise AssertionError("certificate identity label drifted")
    if order2["certificate_multiplier_degree"] != 2:
        raise AssertionError("certificate multiplier degree drifted")

    symbols = {f"am{i}": sp.Symbol(f"a_{i}") for i in range(9)}
    total = sp.Integer(0)
    rows: list[str] = []
    for entry in entries:
        index = int(entry["constraint_index"])
        constraint = sp.sympify(entry["constraint"], locals=symbols)
        weight = sp.sympify(entry["weight"], locals=symbols)
        if sp.Poly(weight, *symbols.values()).total_degree() > 2:
            raise AssertionError(f"multiplier w_{index} exceeds degree two")
        total += constraint * weight
        rows.extend(
            [
                r"\noindent"
                + _wrapped_math(constraint, lhs=rf"f_{{{index}}}")
                + r"\par",
                r"\noindent"
                + _wrapped_math(weight, lhs=rf"w_{{{index}}}")
                + r"\par\medskip",
            ]
        )
    if sp.expand(total - 1) != 0:
        raise AssertionError("stored Nullstellensatz multipliers do not sum to one")

    digest = _sha256(certificate_path)
    return "\n".join(
        [
            "% Generated by symbolic/generate_endpoint_factorization_nullstellensatz_tex.py.",
            f"% Source certificate SHA-256: {digest}",
            "% Do not edit this receipt by hand.",
            r"\begingroup",
            r"\scriptsize",
            *rows,
            r"With all omitted multipliers equal to zero, direct expansion gives",
            r"\[",
            r"\boxed{\displaystyle \sum_{i\in\{0,1,2,4,7,9,14,15,17,18,19,25\}}"
            r" w_i f_i=1.}",
            r"\]",
            r"The multiplier degrees are at most two.  Thus the residual order-two",
            r"ideal is the unit ideal over $\mathbb Q[a_0,\ldots,a_8]$.",
            r"\endgroup",
            "",
        ]
    )


def main() -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--check", action="store_true", help="fail if output drifts")
    args = parser.parse_args()

    rendered = render(CERTIFICATE)
    if args.check:
        if not OUTPUT.exists() or OUTPUT.read_text(encoding="utf-8") != rendered:
            raise AssertionError("generated endpoint factorization TeX receipt drifted")
        print("[PASS] endpoint factorization TeX receipt is exact and current")
        return 0

    OUTPUT.parent.mkdir(parents=True, exist_ok=True)
    OUTPUT.write_text(rendered, encoding="utf-8")
    print("wrote", OUTPUT.relative_to(ROOT))
    print("[PASS] exact 12-term Nullstellensatz identity")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
