#!/usr/bin/env python3
"""Certify field residues, branch Sobolev spaces, and mode Krein isometry."""

from __future__ import annotations

import argparse
import json
from pathlib import Path
import sys


ROOT = Path(__file__).resolve().parents[1]
if str(ROOT) not in sys.path:
    sys.path.insert(0, str(ROOT))

from covariant_completion.sobolev import BranchSobolevRealization, RawBachGraphSpace
from covariant_completion.symplectic import BranchResidues, PositiveFrequencyTransform


CERTIFICATE_DIR = ROOT / "covariant_completion" / "certificates"
GENERATED_DIR = ROOT / "covariant_completion" / "generated"

OVERCLAIM_FLAGS = {
    "--claim-vector-residue-order-zero": "the field action gives R_A=2(A_A^2-4), of order two",
    "--claim-vector-h-half": "the vector Cauchy space is H^(3/2) plus H^(1/2)",
    "--claim-product-sobolev": "the raw fourth-order data currently carry a mixed pullback graph norm",
    "--claim-factorization-fixes-pairing": "the pairing is fixed by the reduced field action, not equation factorization alone",
    "--claim-covariant-distributional": "this theorem is a fixed-cylinder Cauchy-Sobolev realization",
    "--claim-hadamard": "no microlocal spectrum or Hadamard theorem is proved",
}


def certificate_data() -> dict[str, dict[str, object]]:
    return {
        "branch_residue_operators.json": BranchResidues().certificate(),
        "positive_frequency_transform.json": PositiveFrequencyTransform().certificate(),
        "branch_sobolev_orders.json": BranchSobolevRealization().certificate(),
        "raw_bach_graph_space.json": RawBachGraphSpace().certificate(),
        "energy_mode_isometry.json": {
            "schema": "pure-weyl-energy-mode-isometry-v1",
            "source": "field-induced branch Cauchy Hilbert/Krein space",
            "target": "energy-mode E/A/L one-particle Krein completion",
            "algebraic_core_isometry": True,
            "dense_extension": True,
            "surjective_by_all_energy_multiplicity_exhaustion": True,
            "krein_unitary": True,
            "fundamental_symmetry": "+1_E direct_sum -1_A direct_sum -1_L",
        },
    }


def latex() -> str:
    return "\n".join(
        [
            "% Generated by symbolic/verify_conformal_cauchy_sobolev.py",
            r"\begin{theorem}[Cylinder Cauchy--Sobolev realization]",
            r"For $S=-\alpha_g\int C^2$ with $\alpha_g>0$, the positive",
            r"branch residues are",
            r"\[R_E=R_L=4|\mathcal C_2|,\qquad R_A=2(A_A^2-4),\]",
            r"with Krein signs $(+,-,-)$.  Consequently the reduced Cauchy",
            r"spaces are",
            r"\[(H^1_{\rm TT}\oplus L^2_{\rm TT})_E\oplus",
            r"(H^{3/2}_{\rm T}\oplus H^{1/2}_{\rm T})_A\oplus",
            r"(H^1_{\rm TT}\oplus L^2_{\rm TT})_L.\]",
            r"The positive-frequency harmonic transform extends to a",
            r"Krein-unitary isomorphism onto the certified energy-mode",
            r"$E/A/L$ completion.",
            r"\end{theorem}",
            "",
        ]
    )


def main() -> None:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--emit", action="store_true")
    for flag in OVERCLAIM_FLAGS:
        parser.add_argument(flag, action="store_true")
    args = parser.parse_args()
    for flag, reason in OVERCLAIM_FLAGS.items():
        if getattr(args, flag[2:].replace("-", "_")):
            raise SystemExit(f"REFUSED: {reason}")

    data = certificate_data()
    if args.emit:
        CERTIFICATE_DIR.mkdir(parents=True, exist_ok=True)
        for name, value in data.items():
            path = CERTIFICATE_DIR / name
            path.write_text(json.dumps(value, indent=2, sort_keys=True) + "\n", encoding="utf-8")
            print("wrote", path.relative_to(ROOT))
        GENERATED_DIR.mkdir(parents=True, exist_ok=True)
        path = GENERATED_DIR / "cauchy_sobolev.tex"
        path.write_text(latex(), encoding="utf-8")
        print("wrote", path.relative_to(ROOT))
    print("CONFORMAL CAUCHY-SOBOLEV REALIZATION: ALL PASS")


if __name__ == "__main__":
    main()
