#!/usr/bin/env python3
"""Sprint-4a certificate for the independent residual ``SO(4,2)`` BFV package."""

from __future__ import annotations

import argparse
from itertools import combinations
import json
from pathlib import Path
import sys

import sympy as sp

ROOT = Path(__file__).resolve().parents[1]
if str(ROOT) not in sys.path:
    sys.path.insert(0, str(ROOT))

from bridge.residual_bfv import ConformalCE


CERTIFICATE_PATH = ROOT / "bridge" / "certificates" / "residual_bfv.json"
LATEX_PATH = ROOT / "bridge" / "generated" / "residual_bfv.tex"


def check(label: str, condition: object) -> None:
    if not bool(condition):
        raise AssertionError(label)
    print("[OK ] " + label)


def pairing_skew_regression(ce: ConformalCE, maximum_degree: int = 4) -> int:
    """Check CE integration by parts against every relevant complement."""

    full = set(range(ce.dimension))
    count = 0
    for degree in range(maximum_degree + 1):
        for first in combinations(range(ce.dimension), degree):
            d_first = ce.differential({first: 1})
            for output in d_first:
                second = tuple(sorted(full - set(output)))
                left = ce.top_coefficient(ce.wedge(d_first, {second: 1}))
                right = ce.top_coefficient(
                    ce.wedge({first: 1}, ce.differential({second: 1}))
                )
                if sp.simplify(left + (-1) ** degree * right) != 0:
                    raise AssertionError("CE top pairing is not graded skew")
                count += 1
    return count


def certificate_data() -> dict[str, object]:
    ce = ConformalCE.build()
    ce.verify_ce(maximum_degree=5)
    check("S4-R1: residual algebra has exact 4+7+4 grading", ce.generator_degrees == (0,) * 7 + (1,) * 4 + (-1,) * 4)
    check(
        "S4-R1: ghost grading is the opposite compact grading",
        ce.ghost_degrees == (0,) * 7 + (-1,) * 4 + (1,) * 4,
    )
    check(
        "S4-R2: CE differential is nilpotent on all fifteen generators",
        all(not ce.differential(image) for image in ce.ghost_differentials),
    )

    # Cartan identity on the complete exterior basis through degree five is
    # already checked by verify_ce; record a direct nontrivial monomial here.
    test = (0, 7, 8, 12)
    element = {test: sp.Integer(1)}
    cartan = ce.differential(ce.contract(0, element))
    for key, value in ce.contract(0, ce.differential(element)).items():
        cartan[key] = sp.simplify(cartan.get(key, 0) + value)
        if cartan[key] == 0:
            del cartan[key]
    check(
        "S4-R3: [d,i_D]_+=L_D on a mixed-grade four-ghost monomial",
        cartan == ce.lie_d(element),
    )

    pairing_checks = pairing_skew_regression(ce)
    check(
        "S4-R4: unimodular complementary-degree pairing is graded CE-skew",
        pairing_checks > 0,
    )
    saturation = ce.wedge(
        ce.wedge({ce.raising_ghosts: 1}, {ce.zero_ghosts: 1}),
        {ce.lowering_ghosts: 1},
    )
    check(
        "S4-R5: v_+ wedge Theta_0 wedge v_- saturates all fifteen ghosts",
        len(saturation) == 1 and next(iter(saturation)) == ce.top,
    )
    check(
        "S4-R5: centered four-ghost representative has degree (gh,D)=(4,-4)",
        len(ce.lowering_ghosts) == 4
        and ce.compact_degree(ce.lowering_ghosts) == -4,
    )
    check(
        "S4-R5: canonical polarized ghost norm is one",
        ce.polarized_pair(ce.lowering_ghosts, ce.lowering_ghosts) == 1,
    )

    return {
        "schema": "pure-weyl-residual-bfv-v1",
        "basis": list(ce.names),
        "generator_compact_degrees": list(ce.generator_degrees),
        "ghost_compact_degrees": list(ce.ghost_degrees),
        "dimension": ce.dimension,
        "exterior_dimension": 2**ce.dimension,
        "lowering_ghosts": list(ce.lowering_ghosts),
        "zero_ghosts": list(ce.zero_ghosts),
        "raising_ghosts": list(ce.raising_ghosts),
        "vacuum": {
            "ghost_number": 4,
            "compact_degree": -4,
            "norm": 1,
        },
        "identities": [
            "Jacobi",
            "d^2=0",
            "[d,i_D]_+=L_D",
            "graded CE skew-adjointness under top pairing",
            "v_+ wedge Theta_0 wedge v_-=top",
        ],
        "pairing_regression_count": pairing_checks,
        "scope": {
            "proved": "intrinsic residual CE/BFV ghost package and pairing",
            "not_yet_proved": "induction of this package from the local pure-Weyl BV retract",
        },
    }


def latex(data: dict[str, object]) -> str:
    return "\n".join(
        [
            "% Generated by symbolic/verify_conformal_residual_bfv_bridge.py",
            r"\begin{equation}",
            r"\dim\mathfrak g_{-1}\oplus\dim\mathfrak g_0\oplus\dim\mathfrak g_{+1}=4+7+4,",
            r"\qquad \operatorname{gh}(v_-)=4,\quad D_{\rm gh}(v_-)=-4,\quad (v_-,v_-)_{\rm gh}=1.",
            r"\end{equation}",
            "",
        ]
    )


def main() -> None:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--emit", action="store_true")
    parser.add_argument(
        "--claim-transferred-pure-weyl-pairing",
        action="store_true",
        help="fail closed: intrinsic residual pairing is not yet the local-BV transfer",
    )
    args = parser.parse_args()
    if args.claim_transferred_pure_weyl_pairing:
        raise SystemExit(
            "REFUSED: the canonical residual BFV pairing is exact internally; "
            "its equality to the pairing of the complete field-theory pure-Weyl BV domain remains conditional"
        )
    data = certificate_data()
    if args.emit:
        CERTIFICATE_PATH.parent.mkdir(parents=True, exist_ok=True)
        LATEX_PATH.parent.mkdir(parents=True, exist_ok=True)
        CERTIFICATE_PATH.write_text(
            json.dumps(data, indent=2, sort_keys=True) + "\n", encoding="utf-8"
        )
        LATEX_PATH.write_text(latex(data), encoding="utf-8")
        print("wrote", CERTIFICATE_PATH.relative_to(ROOT))
        print("wrote", LATEX_PATH.relative_to(ROOT))
    print("CONFORMAL S4 RESIDUAL BFV: ALL PASS")


if __name__ == "__main__":
    main()
