#!/usr/bin/env python3
"""Certify the auxiliary symbol witness and 66-to-30 Fourier-complex SDR."""

from __future__ import annotations

import argparse
import json
from pathlib import Path
import sys


ROOT = Path(__file__).resolve().parents[1]
if str(ROOT) not in sys.path:
    sys.path.insert(0, str(ROOT))

from covariant_completion.auxiliary_witness import (
    CausalAuxiliaryReduction,
    FullMetricFactorizationBoundary,
    OrdinaryDerivativeWeylSystem,
)
from covariant_completion.green_complex import AuxiliaryFullGreenWitness


CERTIFICATE_DIR = ROOT / "covariant_completion" / "certificates"
GENERATED_DIR = ROOT / "covariant_completion" / "generated"


def main() -> None:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--emit", action="store_true")
    parser.add_argument("--claim-direct-factorization", action="store_true")
    parser.add_argument("--claim-direct-original-causal-homotopy", action="store_true")
    parser.add_argument("--claim-curved-globalization", action="store_true")
    parser.add_argument("--claim-causal-homotopy", action="store_true")
    args = parser.parse_args()
    if args.claim_direct_factorization:
        raise SystemExit(
            "REFUSED: no full-bundle same-bundle H_- H_+ identity is certified"
        )
    if args.claim_direct_original_causal_homotopy:
        raise SystemExit(
            "REFUSED: neither a direct same-bundle homotopy nor the curved auxiliary "
            "Green homotopy is certified by this symbol-level verifier"
        )
    if args.claim_curved_globalization:
        raise SystemExit(
            "REFUSED: the complete curved first/zeroth-order witness and adjoint "
            "table has not been emitted"
        )
    if args.claim_causal_homotopy:
        raise SystemExit(
            "REFUSED: Lambda_plus/minus=W G_plus/minus is an exact recognition "
            "identity, conditional on the still-open curved Green operators"
        )

    boundary = FullMetricFactorizationBoundary().certificate()
    auxiliary = OrdinaryDerivativeWeylSystem.build().certificate()
    reduction = CausalAuxiliaryReduction.build().certificate()
    full_witness_object = AuxiliaryFullGreenWitness.build()
    full_witness = full_witness_object.certificate(reverify=False)
    if args.emit:
        CERTIFICATE_DIR.mkdir(parents=True, exist_ok=True)
        payloads = {
            "field_biwave_factorization_status.json": boundary,
            "ordinary_derivative_auxiliary_system.json": auxiliary,
            "causal_auxiliary_reduction.json": reduction,
            "auxiliary_full_bv_green_witness.json": full_witness,
        }
        for name, payload in payloads.items():
            path = CERTIFICATE_DIR / name
            path.write_text(
                json.dumps(payload, indent=2, sort_keys=True) + "\n",
                encoding="utf-8",
            )
            print("wrote", path.relative_to(ROOT))
        GENERATED_DIR.mkdir(parents=True, exist_ok=True)
        theorem_path = GENERATED_DIR / "auxiliary_green_witness.tex"
        theorem_path.write_text(
            "\n".join(
                [
                    "% Generated by symbolic/verify_conformal_auxiliary_green_realization.py",
                    r"\begin{proposition}[Auxiliary symbol witness and Fourier-complex SDR]",
                    r"For the Lorentzian conformal cylinder, the local",
                    r"ordinary-derivative tensor--tensor--vector BV Fourier complex",
                    r"contracts from $66$ to the $30$-component metric BV core.",
                    r"Its exact four-row Fourier symbols obey",
                    r"\[Q^2=0,\qquad QW_{\rm aux}+W_{\rm aux}Q=P_{\rm aux},\qquad",
                    r"W_{\rm aux}^{\sharp}=W_{\rm aux},\]",
                    r"and every diagonal block has scalar metric principal symbol.",
                    r"The generalized auxiliary and Stueckelberg cotangent sector",
                    r"has an explicit all-row contraction whose formulas are finite",
                    r"differential or pointwise maps and therefore preserve support.",
                    r"The trace/Weyl and nonminimal doublets reattach as",
                    r"support-preserving contractible summands.  This proposition does",
                    r"not assert the curved lower-order chain-map and Green-witness",
                    r"theorem, causal homotopies, or a direct same-bundle factorization of",
                    r"$B_{\rm lin}+\frac12KT$.",
                    r"\end{proposition}",
                    "",
                ]
            ),
            encoding="utf-8",
        )
        print("wrote", theorem_path.relative_to(ROOT))
    print("CONFORMAL AUXILIARY SYMBOL WITNESS AND RETRACT: ALL PASS")


if __name__ == "__main__":
    main()
