#!/usr/bin/env python3
"""Certify Stage 1 of the complete minimal-BV Green's-witness programme."""

from __future__ import annotations

import argparse
import json
from pathlib import Path
import sys


ROOT = Path(__file__).resolve().parents[1]
if str(ROOT) not in sys.path:
    sys.path.insert(0, str(ROOT))

from covariant_completion.minimal_witness import (
    CompanionFormalAdjoint,
    GaugeFixedMetricBiwave,
    GhostGaugeCompanion,
    LinearizedBach,
    MinimalWitnessMatrix,
    MinimalWitnessPrincipalSymbols,
)


CERTIFICATE_DIR = ROOT / "covariant_completion" / "certificates"
GENERATED_DIR = ROOT / "covariant_completion" / "generated"


OVERCLAIM_FLAGS = {
    "--claim-symbol-implies-green": (
        "a scalar biwave principal symbol does not construct causal Green operators"
    ),
    "--claim-exact-factorization": (
        "the exact ghost factorization is certified, but the full-metric "
        "same-bundle factorization is not yet certified here"
    ),
    "--claim-full-witness": (
        "the graded witness matrix, trace/nonminimal causal blocks, and Green "
        "homotopies require the later stages"
    ),
    "--remove-ckv-locally": (
        "global conformal-Killing cohomology must not be removed by a nonlocal "
        "projector from the local causal operator"
    ),
}


def main() -> None:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--emit", action="store_true")
    parser.add_argument("--guards", action="store_true")
    for flag, help_text in OVERCLAIM_FLAGS.items():
        parser.add_argument(flag, action="store_true", help="fail closed: " + help_text)
    args = parser.parse_args()

    for flag, reason in OVERCLAIM_FLAGS.items():
        if getattr(args, flag[2:].replace("-", "_")):
            raise SystemExit("REFUSED: " + reason)

    certificate = MinimalWitnessPrincipalSymbols.build().certificate()
    ghost = GhostGaugeCompanion.build()
    ghost_certificate = ghost.certificate()
    # Build and exhaust the expensive local Bach rail once.  The field
    # intertwiner then follows from this Ward identity and the already tested
    # ghost identity, rather than from a redundant fifth-order expansion.
    bach = LinearizedBach.build()
    bach.verify()
    bach_certificate = bach.certificate(verify=False)
    field_certificate = GaugeFixedMetricBiwave(bach.geometry).certificate(
        verify=False
    )
    adjoint_certificate = CompanionFormalAdjoint().certificate()
    witness_certificate = MinimalWitnessMatrix.build().certificate()
    if args.emit:
        CERTIFICATE_DIR.mkdir(parents=True, exist_ok=True)
        for name in (
            "gauge_companion_principal_symbol.json",
            "ghost_biwave_symbol.json",
            "field_biwave_symbol.json",
        ):
            path = CERTIFICATE_DIR / name
            path.write_text(
                json.dumps(certificate, indent=2, sort_keys=True) + "\n",
                encoding="utf-8",
            )
            print("wrote", path.relative_to(ROOT))
        ghost_path = CERTIFICATE_DIR / "ghost_biwave_factorization.json"
        ghost_path.write_text(
            json.dumps(ghost_certificate, indent=2, sort_keys=True) + "\n",
            encoding="utf-8",
        )
        print("wrote", ghost_path.relative_to(ROOT))
        additional = {
            "linearized_bach.json": bach_certificate,
            "field_biwave_intertwiner.json": field_certificate,
            "companion_formal_adjoint.json": adjoint_certificate,
            "minimal_witness_matrix.json": witness_certificate,
        }
        for name, payload in additional.items():
            path = CERTIFICATE_DIR / name
            path.write_text(
                json.dumps(payload, indent=2, sort_keys=True) + "\n",
                encoding="utf-8",
            )
            print("wrote", path.relative_to(ROOT))
        GENERATED_DIR.mkdir(parents=True, exist_ok=True)
        theorem_path = GENERATED_DIR / "minimal_ghost_witness.tex"
        theorem_path.write_text(
            "\n".join(
                [
                    "% Generated by symbolic/verify_conformal_minimal_witness.py",
                    r"\begin{theorem}[Exact local ghost witness on the cylinder]",
                    r"On the unit Lorentzian conformal cylinder, set",
                    r"\[T=\Box\delta-\frac13d\delta^2+\frac R3\delta",
                    r"-\operatorname{Ric}\circ\delta+\frac13d\langle\operatorname{Ric},h\rangle.\]",
                    r"Then $TK=\Box(\Box+2)$ on one-forms.  With the",
                    r"action-normalized $B_{\rm lin}$ and",
                    r"$H=B_{\rm lin}+\frac12KT$, one has",
                    r"\[B_{\rm lin}K=0,\qquad HK=\frac12K\Box(\Box+2).\]",
                    r"The ghost block is a composition of two normally hyperbolic",
                    r"operators.  The graded self-adjoint backward blocks",
                    r"$(T,2\sharp^{-1},T^\sharp)$ give field block $2H$.",
                    r"No direct same-bundle factorization of $H$ is asserted.",
                    r"\end{theorem}",
                    "",
                ]
            ),
            encoding="utf-8",
        )
        print("wrote", theorem_path.relative_to(ROOT))

    if args.guards:
        for flag, reason in OVERCLAIM_FLAGS.items():
            if not reason:
                raise AssertionError(f"empty guard reason for {flag}")
        print(f"MINIMAL WITNESS OVERCLAIM GUARDS: {len(OVERCLAIM_FLAGS)}/{len(OVERCLAIM_FLAGS)} PASS")

    print("MINIMAL WITNESS STRUCTURAL IDENTITIES: ALL PASS")


if __name__ == "__main__":
    main()
