#!/usr/bin/env python3
"""Exact finite-dimensional geometry of the seeded C2b Taub zero locus.

C2b reconstructs four signed-frequency-lowering proper-conformal charge
kernels on the 36-complex-dimensional direct sum

    E+ + E- + A+ + A- + L+ + L-.

For complex oscillator coordinates ``z`` their known quadratic functions are

    mu_q(z,zbar) = zbar^T M_q z,   q=(+/-1/2,+/-1/2).

This certificate constructs those polynomials exactly, verifies the C2b
four-mode cancellation, and computes both the Wirtinger and real Jacobian
ranks at that point.  It also checks the tangent directions generated by the
seven continuous symmetries whose action matrices are independently known on
this oscillator space: compact energy and the six SO(4) rotations.

The proper-conformal *charge kernels* are known, but their Hamiltonian vector
fields are not: converting a kernel M into a generator requires the relevant
symplectic/Poisson structure and real-form normalization.  They are therefore
not inserted as orbit tangents here.

For the real Jacobian the coefficient variables obey the ordinary oscillator
slice ``zbar=conjugate(z)``.  This has not yet been identified with the
``J_conf`` real slice on globally reduced cohomology.

This is a seeded Taub-constraint calculation.  The symplectic identity that
would promote these functions to moment-map components, the seven Killing
functions, other oscillator blocks, self/anomalous bilinears, full SO(4,2)
orbit, and global BRST quotient remain absent.  Explicit guards fail closed
if any of those stronger conclusions are requested.
"""

from __future__ import annotations

import argparse
from dataclasses import dataclass

import sympy as sp

try:
    from symbolic.verify_conformal_taub_charge import charge_from_slice
    from symbolic.verify_conformal_taub_multiplets import (
        A_MINUS,
        A_PLUS,
        E_MINUS,
        E_PLUS,
        HALF,
        LOW_IRREPS,
        L_MINUS,
        L_PLUS,
        MAGNETIC_COMPONENTS,
        R,
        Seed,
        direct_sum_operator,
        low_energy_kernels,
        reconstruct,
    )
except ModuleNotFoundError:  # direct ``python symbolic/script.py`` execution
    from verify_conformal_taub_charge import charge_from_slice
    from verify_conformal_taub_multiplets import (
        A_MINUS,
        A_PLUS,
        E_MINUS,
        E_PLUS,
        HALF,
        LOW_IRREPS,
        L_MINUS,
        L_PLUS,
        MAGNETIC_COMPONENTS,
        R,
        Seed,
        direct_sum_operator,
        low_energy_kernels,
        reconstruct,
    )


def check(label: str, condition: object) -> None:
    if not bool(condition):
        raise AssertionError(label)
    print("[OK ] " + label)


def exact_zero_matrix(matrix: sp.Matrix) -> bool:
    return all(sp.simplify(entry) == 0 for entry in matrix)


@dataclass(frozen=True)
class PartialData:
    lowering: dict[tuple[sp.Rational, sp.Rational], sp.Matrix]
    offsets: dict[str, int]
    dimension: int


def reconstruct_partial_data() -> PartialData:
    seed_component = (HALF, -HALF)
    parity_component = (-HALF, HALF)
    seeds = (
        Seed(
            "A+ -> E+",
            A_PLUS,
            E_PLUS,
            (R(3, 2), HALF),
            (R(2), R(0)),
            seed_component,
            charge_from_slice(-1, reverse=False),
        ),
        Seed(
            "A- -> E- (parity)",
            A_MINUS,
            E_MINUS,
            (HALF, R(3, 2)),
            (R(0), R(2)),
            parity_component,
            charge_from_slice(-1, reverse=False, parity=True),
        ),
        Seed(
            "L+ -> A+ (parity)",
            L_PLUS,
            A_PLUS,
            (R(2), R(0)),
            (R(3, 2), HALF),
            parity_component,
            charge_from_slice(-1, reverse=True, parity=True),
        ),
        Seed(
            "L- -> A-",
            L_MINUS,
            A_MINUS,
            (R(0), R(2)),
            (HALF, R(3, 2)),
            seed_component,
            charge_from_slice(-1, reverse=True),
        ),
    )
    families = tuple(reconstruct(seed) for seed in seeds)
    lowering = low_energy_kernels(families)
    offsets: dict[str, int] = {}
    cursor = 0
    for irrep in LOW_IRREPS:
        offsets[irrep.label] = cursor
        cursor += irrep.dimension
    check("C2d: reconstructed low oscillator space has dimension 36", cursor == 36)
    check(
        "C2d: every known proper-conformal polynomial has sixteen exact monomials",
        all(sum(entry != 0 for entry in matrix) == 16 for matrix in lowering.values()),
    )
    return PartialData(lowering, offsets, cursor)


def state_index(
    data: PartialData,
    irrep: object,
    magnetic: tuple[sp.Rational, sp.Rational],
) -> int:
    return data.offsets[irrep.label] + irrep.basis.index(magnetic)


def cancellation_point(data: PartialData) -> tuple[sp.Matrix, tuple[int, ...]]:
    selected = (
        state_index(data, E_PLUS, (R(2), R(0))),
        state_index(data, A_PLUS, (R(3, 2), HALF)),
        state_index(data, A_MINUS, (HALF, R(3, 2))),
        state_index(data, L_MINUS, (R(0), R(2))),
    )
    point = sp.zeros(data.dimension, 1)
    for index, value in zip(selected, (1, 1, 1, 1 / sp.sqrt(2))):
        point[index] = value
    return point, selected


def polynomial_data(
    data: PartialData,
) -> tuple[
    tuple[sp.Symbol, ...],
    tuple[sp.Symbol, ...],
    dict[tuple[sp.Rational, sp.Rational], sp.Expr],
]:
    z = sp.symbols(f"z0:{data.dimension}")
    zbar = sp.symbols(f"zb0:{data.dimension}")
    z_column = sp.Matrix(z)
    zbar_row = sp.Matrix(1, data.dimension, zbar)
    polynomials = {
        component: sp.expand((zbar_row * matrix * z_column)[0])
        for component, matrix in data.lowering.items()
    }
    check(
        "C2d: all known charge functions are exact bidegree-(1,1) polynomials",
        all(
            len(sp.Add.make_args(polynomial)) == 16
            and all(
                sum(term.as_powers_dict().get(variable, 0) for variable in z) == 1
                and sum(
                    term.as_powers_dict().get(variable, 0) for variable in zbar
                )
                == 1
                for term in sp.Add.make_args(polynomial)
            )
            for polynomial in polynomials.values()
        ),
    )
    return z, zbar, polynomials


def verify_cancellation(
    data: PartialData,
    point: sp.Matrix,
    selected: tuple[int, ...],
    z: tuple[sp.Symbol, ...],
    zbar: tuple[sp.Symbol, ...],
    polynomials: dict[tuple[sp.Rational, sp.Rational], sp.Expr],
) -> None:
    substitution = {
        **{variable: point[index] for index, variable in enumerate(z)},
        **{variable: point[index] for index, variable in enumerate(zbar)},
    }
    check(
        "C2d: four-mode point lies on every reconstructed proper-conformal quadratic",
        all(sp.simplify(polynomial.subs(substitution)) == 0 for polynomial in polynomials.values()),
    )
    check(
        "C2d: cancelling point is not a common operator kernel",
        any(data.lowering[component] * point != sp.zeros(data.dimension, 1) for component in MAGNETIC_COMPONENTS),
    )

    e, ap, am, ell = sp.symbols("e a_plus a_minus ell")
    selected_symbols = (e, ap, am, ell)
    slice_substitution = {
        **{variable: 0 for variable in z},
        **{variable: 0 for variable in zbar},
    }
    for index, variable in zip(selected, selected_symbols):
        slice_substitution[z[index]] = variable
        slice_substitution[zbar[index]] = sp.conjugate(variable)
    restricted = {
        component: sp.simplify(polynomial.subs(slice_substitution))
        for component, polynomial in polynomials.items()
    }
    seed_component = (HALF, -HALF)
    expected = (
        -sp.sqrt(5) * sp.conjugate(e) * ap / (5 * sp.pi)
        + sp.sqrt(10) * sp.conjugate(am) * ell / (5 * sp.pi)
    )
    check(
        "C2d: exact four-mode slice has one complex quadratic and three identically zero components",
        sp.simplify(restricted[seed_component] - expected) == 0
        and all(
            restricted[component] == 0
            for component in MAGNETIC_COMPONENTS
            if component != seed_component
        ),
    )
    print("four-mode partial charge polynomial:", expected)


@dataclass(frozen=True)
class JacobianData:
    wirtinger: sp.Matrix
    real: sp.Matrix
    full_wirtinger_rank: int
    full_real_rank: int
    slice_wirtinger_rank: int
    slice_real_rank: int


def jacobians(
    data: PartialData,
    point: sp.Matrix,
    selected: tuple[int, ...],
) -> JacobianData:
    n = data.dimension
    wirtinger_rows: list[sp.Matrix] = []
    real_rows: list[sp.Matrix] = []
    imaginary_rows: list[sp.Matrix] = []
    for component in MAGNETIC_COMPONENTS:
        matrix = data.lowering[component]
        # At the real cancellation point all matrices and first derivatives
        # are real.  A=d mu/dz and B=d mu/dzbar.
        A = point.T * matrix
        B = (matrix * point).T
        check(
            f"C2d: {component} cancellation-point derivatives are exactly real",
            all(sp.im(entry) == 0 for entry in A.row_join(B)),
        )
        wirtinger_rows.append(A.row_join(B))
        # z=x+i y, zbar=x-i y gives
        # d Re(mu)=(A+B)dx and d Im(mu)=(A-B)dy at this point.
        real_rows.append((A + B).row_join(sp.zeros(1, n)))
        imaginary_rows.append(sp.zeros(1, n).row_join(A - B))

    wirtinger = sp.Matrix.vstack(*wirtinger_rows)
    real = sp.Matrix.vstack(*real_rows, *imaginary_rows)
    full_wirtinger_rank = wirtinger.rank()
    full_real_rank = real.rank()
    slice_columns = list(selected) + [n + index for index in selected]
    slice_wirtinger_rank = wirtinger[:, slice_columns].rank()
    slice_real_rank = real[:, slice_columns].rank()
    check(
        "C2d: partial map has maximal complex Wirtinger rank four at the cancelling point",
        full_wirtinger_rank == 4,
    )
    check(
        "C2d: partial map has maximal real rank eight at the cancelling point",
        full_real_rank == 8,
    )
    check(
        "C2d: effective four-mode slice equation has complex rank one and real rank two",
        slice_wirtinger_rank == 1 and slice_real_rank == 2,
    )
    return JacobianData(
        wirtinger,
        real,
        full_wirtinger_rank,
        full_real_rank,
        slice_wirtinger_rank,
        slice_real_rank,
    )


def compact_generators(data: PartialData) -> dict[str, sp.Matrix]:
    energy = sp.diag(
        *(
            sp.Integer(irrep.energy)
            for irrep in LOW_IRREPS
            for _ in range(irrep.dimension)
        )
    )
    output = {"D": energy}
    for side, label in (("left", "L"), ("right", "R")):
        z = direct_sum_operator(side, "z")
        raising = direct_sum_operator(side, "+")
        lowering = direct_sum_operator(side, "-")
        output[f"J{label}x"] = (raising + lowering) / 2
        output[f"J{label}y"] = (raising - lowering) / (2 * sp.I)
        output[f"J{label}z"] = z
    check(
        "C2d: all seven available continuous generator matrices are Hermitian",
        all(generator == generator.conjugate().T for generator in output.values()),
    )
    return output


@dataclass(frozen=True)
class OrbitData:
    real_tangents: sp.Matrix
    wirtinger_tangents: sp.Matrix
    real_rank: int
    complex_rank: int
    slice_cartan_rank: int


def orbit_tangents(
    data: PartialData,
    point: sp.Matrix,
    selected: tuple[int, ...],
    jacobian: JacobianData,
) -> OrbitData:
    n = data.dimension
    generators = compact_generators(data)
    real_columns: list[sp.Matrix] = []
    wirtinger_columns: list[sp.Matrix] = []
    for generator in generators.values():
        delta = -sp.I * generator * point
        real_delta = delta.applyfunc(sp.re).col_join(delta.applyfunc(sp.im))
        conjugate_delta = delta.applyfunc(sp.conjugate)
        real_columns.append(real_delta)
        wirtinger_columns.append(delta.col_join(conjugate_delta))
    real_tangents = sp.Matrix.hstack(*real_columns)
    wirtinger_tangents = sp.Matrix.hstack(*wirtinger_columns)
    real_rank = real_tangents.rank()
    complex_rank = wirtinger_tangents.rank()
    check(
        "C2d: available D plus SO(4) compact orbit has exact real rank seven",
        real_rank == 7,
    )
    check(
        "C2d: its combined (z,zbar) tangent columns also have complex rank seven",
        complex_rank == 7,
    )
    check(
        "C2d: every available compact orbit tangent lies in the seeded real zero-locus tangent",
        exact_zero_matrix(jacobian.real * real_tangents),
    )
    check(
        "C2d: every available compact orbit tangent lies in the Wirtinger kernel",
        exact_zero_matrix(jacobian.wirtinger * wirtinger_tangents),
    )

    selected_real = list(selected) + [n + index for index in selected]
    outside_real = [index for index in range(2 * n) if index not in selected_real]
    slice_pairs = [
        (name, column)
        for name, column in zip(generators, real_columns)
        if exact_zero_matrix(column.extract(outside_real, [0]))
    ]
    slice_names = tuple(name for name, _ in slice_pairs)
    slice_columns = [column for _, column in slice_pairs]
    slice_tangents = sp.Matrix.hstack(*slice_columns)
    slice_cartan_rank = slice_tangents.rank()
    check(
        "C2d: only D and the two Cartan rotations remain tangent to the four-mode coordinate slice",
        slice_names == ("D", "JLz", "JRz") and slice_cartan_rank == 3,
    )
    return OrbitData(
        real_tangents,
        wirtinger_tangents,
        real_rank,
        complex_rank,
        slice_cartan_rank,
    )


def main() -> None:
    parser = argparse.ArgumentParser()
    parser.add_argument(
        "--show-polynomials",
        action="store_true",
        help="print all four exact sixteen-term reconstructed quadratics",
    )
    parser.add_argument(
        "--require-full-cone",
        action="store_true",
        help="fail closed: the complete fifteen-component Taub/moment-map construction is absent",
    )
    parser.add_argument(
        "--require-full-orbit",
        action="store_true",
        help="fail closed: proper-conformal Hamiltonian vector fields need the symplectic/Poisson normalization",
    )
    parser.add_argument(
        "--require-global-brst",
        action="store_true",
        help="fail closed: no global-BRST quotient is constructed",
    )
    args = parser.parse_args()

    data = reconstruct_partial_data()
    point, selected = cancellation_point(data)
    z, zbar, polynomials = polynomial_data(data)
    verify_cancellation(data, point, selected, z, zbar, polynomials)
    jacobian = jacobians(data, point, selected)
    orbit = orbit_tangents(data, point, selected, jacobian)

    if args.show_polynomials:
        for component in MAGNETIC_COMPONENTS:
            print(f"mu_{component} =", polynomials[component])
    print("full partial-map Wirtinger rank:", jacobian.full_wirtinger_rank)
    print("full partial-map real rank:", jacobian.full_real_rank)
    print("four-mode effective Wirtinger rank:", jacobian.slice_wirtinger_rank)
    print("four-mode effective real rank:", jacobian.slice_real_rank)
    print("available compact orbit real rank:", orbit.real_rank)
    print("available compact orbit combined-complex rank:", orbit.complex_rank)
    print("four-mode-slice Cartan orbit rank:", orbit.slice_cartan_rank)
    print("seeded real zero-locus tangent dimension:", 2 * data.dimension - jacobian.full_real_rank)
    print("formal seeded tangent modulo available compact orbit dimension:", 2 * data.dimension - jacobian.full_real_rank - orbit.real_rank)
    print(
        "C2d STATUS: THE C2b CANCELLING POINT IS REGULAR FOR THE PARTIAL "
        "FOUR-COMPLEX-COMPONENT PROPER-CONFORMAL TAUB-CONSTRAINT MAP. This "
        "says nothing about regularity of a complete fifteen-component map "
        "or its symplectic moment-map identification. "
        "Only D and SO(4) orbit tangents are compared; proper-conformal "
        "Hamiltonian vector fields and global BRST remain unavailable."
    )
    if args.require_full_cone:
        raise SystemExit(
            "the seven Killing charges, unknown proper-CK blocks, and full Taub/moment-map construction remain open"
        )
    if args.require_full_orbit:
        raise SystemExit(
            "the symplectic/Poisson normalization needed to construct proper-conformal orbit tangents is absent"
        )
    if args.require_global_brst:
        raise SystemExit(
            "the global Diff x Weyl BRST quotient has not been constructed"
        )


if __name__ == "__main__":
    main()
