#!/usr/bin/env python3
"""C2i-D: exact action-derived audit for finite pure-Weyl detour blocks.

The theorem-level local statement is recorded in
``notes/conformal-local-detour.md``.  This executable checks precisely the
part represented by the repository's cylinder action matrices:

* the four-dimensional curvature normalization

      Ric^2 - R^2/3 = (C^2-E4)/2;

* the unit coefficient of the mixed quadratic ``C1`` pairing at a
  conformally flat background;
* formal self-adjointness of the independently action-derived scalar
  cylinder Hessians; and
* their exact right and left Diff x Weyl Ward kernels.

The scalar Hessian coefficients were independently generated by
``verify_conformal_quartic_hessian.py``.  This fast bridge does not construct
the geometric cylinder-harmonic linearized-Weyl matrix ``C1``.  The separate
``verify_conformal_detour_polynomial.py`` constructs actual Euclidean
homogeneous-polynomial K, C1 and B1 matrices at finite degrees. Neither script
claims all-level Lorentzian cylinder or local-BV cohomology.
"""

from __future__ import annotations

import argparse

import sympy as sp

try:
    from symbolic.verify_conformal_quartic_exchange import (
        BLOCKS,
        COVARIANT_KAPPA,
    )
except ModuleNotFoundError:  # direct ``python symbolic/script.py`` execution
    from verify_conformal_quartic_exchange import BLOCKS, COVARIANT_KAPPA


def check(label: str, condition: object) -> None:
    if not bool(condition):
        raise AssertionError(label)
    print("[OK ] " + label)


def verify_action_normalization() -> None:
    riemann2, ricci2, scalar2 = sp.symbols(
        "Riemann2 Ricci2 Scalar2", real=True
    )
    weyl2 = riemann2 - 2 * ricci2 + scalar2 / 3
    euler4 = riemann2 - 4 * ricci2 + scalar2
    reduced = ricci2 - scalar2 / 3
    check(
        "C2i-D: reduced Weyl density is exactly (C^2-E4)/2 in four dimensions",
        sp.expand(reduced - (weyl2 - euler4) / 2) == 0,
    )

    # At C(bar g)=0, write C=C1[a h+b k]+O((a,b)^2).  The target-fibre
    # metric is deliberately indefinite here: the coefficient is unaffected.
    a, b = sp.symbols("a b", real=True)
    h = sp.Matrix(sp.symbols("h0:4"))
    k = sp.Matrix(sp.symbols("k0:4"))
    fibre_form = sp.diag(1, -1, 2, -3)
    curvature = a * h + b * k
    quadratic_action = sp.expand(
        sp.Rational(1, 2) * (curvature.T * fibre_form * curvature)[0]
    )
    mixed_hessian = sp.diff(quadratic_action, a, b)
    check(
        "C2i-D: the conformally-flat mixed Hessian has unit C1-adjoint-C1 coefficient",
        sp.expand(mixed_hessian - (h.T * fibre_form * k)[0]) == 0,
    )


def scalar_hessian(label: str) -> sp.Matrix:
    block = BLOCKS[label]
    return sp.simplify(
        COVARIANT_KAPPA[label]
        * block.current_plus_basis
        * block.current_minus_basis.T
    )


def verify_scalar_detour_blocks() -> None:
    for label, block in BLOCKS.items():
        hessian = scalar_hessian(label)
        check(
            f"C2i-D: {label} plus/minus gauge generators are frequency-adjoint partners",
            block.B_minus == block.B_plus.conjugate(),
        )
        check(
            f"C2i-D: {label} action Hessian is exactly formally self-adjoint",
            hessian == hessian.conjugate().T,
        )
        check(
            f"C2i-D: {label} Hessian annihilates the complete right Diff x Weyl orbit",
            hessian * block.B_plus
            == sp.zeros(block.dimension, block.B_plus.cols),
        )
        check(
            f"C2i-D: {label} formal adjoint gauge operator annihilates the Hessian on the left",
            block.B_minus.T * hessian
            == sp.zeros(block.B_minus.cols, block.dimension),
        )

        if COVARIANT_KAPPA[label] == 0:
            check(
                f"C2i-D: {label} is retained as a Hessian-null constraint block",
                label == "t" and hessian == sp.zeros(block.dimension),
            )
        else:
            check(
                f"C2i-D: {label} Hessian kernel is exactly the finite scalar gauge orbit",
                hessian.rank() == 1
                and len(hessian.nullspace()) == block.B_plus.cols
                and sp.Matrix.hstack(*hessian.nullspace(), block.B_plus).rank()
                == block.B_plus.rank(),
            )


def main() -> None:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument(
        "--require-explicit-cylinder-c1",
        action="store_true",
        help="fail closed: no curved-cylinder harmonic matrix for linearized Weyl curvature exists yet",
    )
    parser.add_argument(
        "--require-all-harmonics",
        action="store_true",
        help="fail closed: only the existing scalar s,t,u blocks are audited",
    )
    parser.add_argument(
        "--claim-global-cohomology",
        action="store_true",
        help="fail closed: local detour identities do not compute global cylinder cohomology",
    )
    args = parser.parse_args()
    if args.require_explicit_cylinder_c1:
        raise SystemExit(
            "the cylinder-harmonic C1 matrix and its Weyl-fibre pairing require new code"
        )
    if args.require_all_harmonics:
        raise SystemExit("scalar, vector, TT, ghost, and antifield blocks are not all assembled")
    if args.claim_global_cohomology:
        raise SystemExit("formal local detour identities do not prove global/all-level exactness")

    verify_action_normalization()
    verify_scalar_detour_blocks()
    print(
        "C2i-D STATUS: EXACT ACTION-NORMALIZED FORMAL FACTORIZATION INPUT "
        "AND FINITE SCALAR-BLOCK DETOUR IDENTITIES. The explicit geometric "
        "cylinder C1 matrix, all harmonic sectors, and global/local-BV "
        "cohomology remain open and are guarded."
    )


if __name__ == "__main__":
    main()
