#!/usr/bin/env python3
"""C2g-R: first relative global-BRST kernel in the pure-Weyl sector.

Use the standard cylinder residual-ghost polarization, for which the ghost
vacuum contributes compact energy ``-4``.  At relative ghost number zero the
matter representative must therefore obey

    (D-4)|psi> = 0,   R|psi> = 0,   K^-_M|psi> = 0.

This script constructs the complete pure-Weyl bosonic Fock space of matter
energy four: all one-particle energy-four modes and ``Sym^2(E_2^+ + E_2^-)``.
It proves that the relative kernel is exactly two dimensional, generated by
the two chiral Weyl-square scalars, and restricts the matter Krein form to
that kernel.

This is not promoted to absolute pure-Weyl BRST cohomology.  Deriving the
residual ghost vacuum and the zero-mode splitting from the complete local
Diff x Weyl BV complex remains a separate acceptance condition.
"""

from __future__ import annotations

import argparse
from itertools import combinations_with_replacement

import sympy as sp

try:
    from symbolic import verify_conformal_generator_ansatz as generators
    from symbolic.verify_conformal_taub_multiplets import MAGNETIC_COMPONENTS
except ModuleNotFoundError:  # direct ``python symbolic/script.py`` execution
    import verify_conformal_generator_ansatz as generators
    from verify_conformal_taub_multiplets import MAGNETIC_COMPONENTS


R = sp.Rational


def check(label: str, condition: object) -> None:
    if not bool(condition):
        raise AssertionError(label)
    print("[OK ] " + label)


def indices_at_energy(space: generators.RepresentationSpace, energy: int) -> tuple[int, ...]:
    return tuple(
        index
        for mode in space.irreps
        if mode.energy == energy
        for index in range(
            space.offsets[mode.label],
            space.offsets[mode.label] + mode.dimension,
        )
    )


def extracted(matrix: sp.Matrix, rows: tuple[int, ...], columns: tuple[int, ...]) -> sp.Matrix:
    return matrix.extract(rows, columns)


def symmetric_square_generator(matrix: sp.Matrix) -> tuple[sp.Matrix, tuple[tuple[int, int], ...]]:
    """Bosonic generator on normalized occupation states ``|i,j>``, ``i<=j``."""

    dimension = matrix.rows
    pairs = tuple(combinations_with_replacement(range(dimension), 2))
    pair_index = {pair: position for position, pair in enumerate(pairs)}
    output = sp.zeros(len(pairs))
    for column, (first, second) in enumerate(pairs):
        source_normalization = sp.sqrt(1 + int(first == second))
        for target, coefficient in enumerate(matrix[:, first]):
            if coefficient == 0:
                continue
            pair = tuple(sorted((target, second)))
            row = pair_index[pair]
            target_normalization = sp.sqrt(1 + int(pair[0] == pair[1]))
            output[row, column] += sp.simplify(
                coefficient * target_normalization / source_normalization
            )
        for target, coefficient in enumerate(matrix[:, second]):
            if coefficient == 0:
                continue
            pair = tuple(sorted((first, target)))
            row = pair_index[pair]
            target_normalization = sp.sqrt(1 + int(pair[0] == pair[1]))
            output[row, column] += sp.simplify(
                coefficient * target_normalization / source_normalization
            )
    return output, pairs


def combined_compact(
    plus: generators.RepresentationSpace,
    minus: generators.RepresentationSpace,
    energy: int,
) -> tuple[sp.Matrix, ...]:
    plus_indices = indices_at_energy(plus, energy)
    minus_indices = indices_at_energy(minus, energy)
    output = []
    for side, axis in (
        ("left", "x"),
        ("left", "y"),
        ("left", "z"),
        ("right", "x"),
        ("right", "y"),
        ("right", "z"),
    ):
        plus_matrix = extracted(getattr(plus, side)[axis], plus_indices, plus_indices)
        minus_matrix = extracted(getattr(minus, side)[axis], minus_indices, minus_indices)
        output.append(sp.diag(plus_matrix, minus_matrix))
    return tuple(output)


def combined_lowering(
    plus: generators.RepresentationSpace,
    minus: generators.RepresentationSpace,
) -> tuple[sp.Matrix, ...]:
    raising = generators.canonical_raising()
    plus_ansatz = generators.assemble_ansatz(
        plus, generators.CANONICAL_LOWERING, raising
    )
    minus_ansatz = generators.assemble_ansatz(
        minus, generators.CANONICAL_LOWERING, raising
    )
    plus_rows = indices_at_energy(plus, 3)
    minus_rows = indices_at_energy(minus, 3)
    plus_columns = indices_at_energy(plus, 4)
    minus_columns = indices_at_energy(minus, 4)
    return tuple(
        sp.diag(
            extracted(plus_ansatz.lowering[component], plus_rows, plus_columns),
            extracted(minus_ansatz.lowering[component], minus_rows, minus_columns),
        )
        for component in MAGNETIC_COMPONENTS
    )


def normalized_chiral_singlets(
    one_particle_dimension: int,
    pairs: tuple[tuple[int, int], ...],
) -> tuple[sp.Matrix, sp.Matrix]:
    """Normalized spin-two singlets in ``Sym^2 E_2^+`` and ``Sym^2 E_2^-``."""

    pair_index = {pair: position for position, pair in enumerate(pairs)}
    total_dimension = one_particle_dimension + len(pairs)
    plus = sp.zeros(total_dimension, 1)
    minus = sp.zeros(total_dimension, 1)
    # Descending m=2,1,0,-1,-2 in each chirality.  The normalized symmetric
    # Clebsch--Gordan scalar has coefficients (+sqrt2,-sqrt2,+1)/sqrt5.
    for vector, offset in ((plus, 0), (minus, 5)):
        vector[one_particle_dimension + pair_index[(offset + 0, offset + 4)]] = sp.sqrt(R(2, 5))
        vector[one_particle_dimension + pair_index[(offset + 1, offset + 3)]] = -sp.sqrt(R(2, 5))
        vector[one_particle_dimension + pair_index[(offset + 2, offset + 2)]] = 1 / sp.sqrt(5)
    return plus, minus


def main() -> None:
    parser = argparse.ArgumentParser()
    parser.add_argument(
        "--claim-absolute-cohomology",
        action="store_true",
        help="fail closed: the local Diff x Weyl zero-mode split is not derived here",
    )
    parser.add_argument(
        "--discard-parity-odd",
        action="store_true",
        help="report the optional parity-even restriction after the full kernel",
    )
    args = parser.parse_args()

    plus = generators.representation_space(+1)
    minus = generators.representation_space(-1)

    compact_four = combined_compact(plus, minus, 4)
    compact_two = combined_compact(plus, minus, 2)
    symmetric_compact_and_pairs = tuple(
        symmetric_square_generator(matrix) for matrix in compact_two
    )
    pairs = symmetric_compact_and_pairs[0][1]
    check(
        "C2g-R1: every induced symmetric-square generator uses the same 55-state basis",
        all(item[1] == pairs for item in symmetric_compact_and_pairs),
    )

    one_particle_dimension = compact_four[0].rows
    two_particle_dimension = len(pairs)
    total_dimension = one_particle_dimension + two_particle_dimension
    check(
        "C2g-R1: complete matter-weight-four Fock space has dimension 82+55=137",
        one_particle_dimension == 82
        and two_particle_dimension == 55
        and total_dimension == 137,
    )

    compact_constraints = tuple(
        sp.diag(one_particle, symmetric[0])
        for one_particle, symmetric in zip(
            compact_four, symmetric_compact_and_pairs
        )
    )
    lowering_one_particle = combined_lowering(plus, minus)
    lowering_constraints = tuple(
        matrix.row_join(sp.zeros(matrix.rows, two_particle_dimension))
        for matrix in lowering_one_particle
    )
    constraint = sp.Matrix.vstack(*compact_constraints, *lowering_constraints)

    plus_singlet, minus_singlet = normalized_chiral_singlets(
        one_particle_dimension, pairs
    )
    candidates = sp.Matrix.hstack(plus_singlet, minus_singlet)
    check(
        "C2g-R2: both chiral Weyl-square states obey rotations and every K-minus condition",
        constraint * candidates == sp.zeros(constraint.rows, 2),
    )
    rank = constraint.rank()
    check(
        "C2g-R2: the complete relative primary-scalar kernel is exactly two dimensional",
        rank == total_dimension - 2 and candidates.rank() == 2,
    )

    # One-particle signs at energy four are +E,-A,-L in each chirality.  The
    # two-particle sector uses only positive E2 quanta and is therefore +I.
    one_particle_signs = []
    for space in (plus, minus):
        for mode in space.irreps:
            if mode.energy != 4:
                continue
            sign = generators.CANONICAL_SIGNS[mode.label]
            one_particle_signs.extend([sign] * mode.dimension)
    ambient_form = sp.diag(
        *one_particle_signs,
        *(sp.Integer(1) for _ in range(two_particle_dimension)),
    )
    check(
        "C2g-R3: ambient weight-four Krein form is nondegenerate with signature (97,40)",
        one_particle_signs.count(1) + two_particle_dimension == 97
        and one_particle_signs.count(-1) == 40
        and ambient_form.det() != 0,
    )
    induced = sp.simplify(candidates.conjugate().T * ambient_form * candidates)
    check(
        "C2g-R3: the matter-form restriction on the relative kernel is exactly positive identity",
        induced == sp.eye(2),
    )

    parity_even = sp.simplify((plus_singlet + minus_singlet) / sp.sqrt(2))
    parity_odd = sp.simplify((plus_singlet - minus_singlet) / sp.sqrt(2))
    parity_basis = sp.Matrix.hstack(parity_even, parity_odd)
    check(
        "C2g-R3: parity-even and parity-odd scalar combinations remain orthonormal and positive",
        parity_basis.conjugate().T * ambient_form * parity_basis == sp.eye(2),
    )

    print("matter-weight-four dimension:", total_dimension)
    print("constraint rank:", rank)
    print("relative kernel dimension:", total_dimension - rank)
    print("ambient signature: (97,40)")
    print("relative-kernel matter Gram matrix:", induced)
    if args.discard_parity_odd:
        print("optional parity-even restriction: dimension 1, Gram matrix [1]")
    print(
        "C2g-R STATUS: COMPLETE WEIGHT-FOUR RELATIVE PRIMARY-SCALAR KERNEL "
        "FOR THE PURE-WEYL OSCILLATOR FOCK SECTOR. It is two dimensional "
        "before an optional parity-even restriction and its matter-sector "
        "pairing is positive. Absolute local-plus-global BRST cohomology and "
        "the centered ghost insertion are not yet claimed."
    )
    if args.claim_absolute_cohomology:
        raise SystemExit(
            "the residual ghost polarization has not been derived from the full pure-Weyl local BV complex"
        )


if __name__ == "__main__":
    main()
