#!/usr/bin/env python3
"""Reconstruct the proper-conformal Taub multiplets from the C2a seeds.

The direct curvature certificate ``verify_conformal_taub_charge.py`` fixes
two action-normalized matrix elements of the signed-frequency ``-1`` charge,

    <E_+|Q_-|A_+> = -sqrt(5)/(5 pi),
    <A_-|Q_-|L_-> =  sqrt(10)/(5 pi).

They are not self-charges of ``AA`` or ``EL``.  They are two reduced matrix
elements in adjacent compact-energy blocks.  The proper conformal Killing
parameters transform as ``(1/2,1/2)`` under
``SU(2)_L x SU(2)_R``.  Since this representation occurs with multiplicity
one in each relevant tensor product, Wigner--Eckart reconstructs every
magnetic component of these two blocks from the two curvature seeds.

This certificate performs that reconstruction exactly.  It verifies

* multiplicity one in the ``A -> E`` and ``L -> A`` blocks;
* the two seed normalizations and their parity partners;
* all left/right tensor-operator ladder identities;
* the compact-energy grading ``[D,Q_-]=-Q_-``;
* parity covariance and the reverse-curvature ordinary kernel-dagger relation;
* exact agreement with the independently assembled restricted C2a matrices.

The resulting matrices are *partial* Taub moment-map data.  They cover the
complete ``(1/2,1/2)`` magnetic multiplets generated by the two mixed seeds,
not the seven compact-energy-preserving Killing charges, other oscillator
towers, diagonal/self-charge blocks, the nonlinear zero locus, or global
BRST cohomology.  Explicit fail-closed switches protect those distinctions.
The generated entries use SymPy's standard Condon--Shortley convention and
the intrinsic parity phase fixed by the direct seed rails.  The abstract
ladder identities are exact; a coordinate-level cylinder-harmonic ladder
comparison for every generated entry remains optional hardening.
"""

from __future__ import annotations

import argparse
from dataclasses import dataclass
from itertools import product

import sympy as sp
from sympy.physics.wigner import clebsch_gordan

try:
    from symbolic.verify_conformal_taub_charge import (
        charge_from_slice,
        low_energy_charge_matrices,
    )
except ModuleNotFoundError:  # direct ``python symbolic/script.py`` execution
    from verify_conformal_taub_charge import (
        charge_from_slice,
        low_energy_charge_matrices,
    )


R = sp.Rational
HALF = R(1, 2)
TENSOR_SPIN = (HALF, HALF)
MAGNETIC_COMPONENTS = tuple(product((HALF, -HALF), repeat=2))


def check(label: str, condition: object) -> None:
    if not bool(condition):
        raise AssertionError(label)
    print("[OK ] " + label)


def exact_matrix_equal(first: sp.Matrix, second: sp.Matrix) -> bool:
    if first.shape != second.shape:
        return False
    return all(sp.simplify(value) == 0 for value in first - second)


def magnetic_values(spin: sp.Rational) -> tuple[sp.Rational, ...]:
    return tuple(spin - index for index in range(int(2 * spin) + 1))


@dataclass(frozen=True)
class Irrep:
    label: str
    energy: int
    left: sp.Rational
    right: sp.Rational

    @property
    def dimension(self) -> int:
        return int((2 * self.left + 1) * (2 * self.right + 1))

    @property
    def basis(self) -> tuple[tuple[sp.Rational, sp.Rational], ...]:
        return tuple(product(magnetic_values(self.left), magnetic_values(self.right)))

    def parity_conjugate(self, label: str) -> "Irrep":
        return Irrep(label, self.energy, self.right, self.left)


E_PLUS = Irrep("E+", 2, R(2), R(0))
A_PLUS = Irrep("A+", 3, R(3, 2), HALF)
L_PLUS = Irrep("L+", 4, R(2), R(0))
E_MINUS = E_PLUS.parity_conjugate("E-")
A_MINUS = A_PLUS.parity_conjugate("A-")
L_MINUS = L_PLUS.parity_conjugate("L-")
LOW_IRREPS = (E_PLUS, E_MINUS, A_PLUS, A_MINUS, L_PLUS, L_MINUS)


def coupled_spins(first: sp.Rational, second: sp.Rational) -> tuple[sp.Rational, ...]:
    lower = abs(first - second)
    upper = first + second
    return tuple(lower + index for index in range(int(upper - lower) + 1))


def tensor_multiplicity(source: Irrep, target: Irrep) -> int:
    left = coupled_spins(source.left, TENSOR_SPIN[0]).count(target.left)
    right = coupled_spins(source.right, TENSOR_SPIN[1]).count(target.right)
    return left * right


def component_matrix(
    source: Irrep,
    target: Irrep,
    component: tuple[sp.Rational, sp.Rational],
    reduced_coefficient: sp.Expr = sp.Integer(1),
) -> sp.Matrix:
    """Wigner--Eckart matrix in the exact SymPy CG convention.

    Rows are target states and columns are source states, both in descending
    ``(m_L,m_R)`` order.  The reduced coefficient includes all normalization
    choices not fixed by spatial representation theory.
    """

    q_left, q_right = component
    output = sp.zeros(target.dimension, source.dimension)
    for row, (target_left, target_right) in enumerate(target.basis):
        for column, (source_left, source_right) in enumerate(source.basis):
            output[row, column] = sp.simplify(
                reduced_coefficient
                * clebsch_gordan(
                    source.left,
                    TENSOR_SPIN[0],
                    target.left,
                    source_left,
                    q_left,
                    target_left,
                )
                * clebsch_gordan(
                    source.right,
                    TENSOR_SPIN[1],
                    target.right,
                    source_right,
                    q_right,
                    target_right,
                )
            )
    return output


@dataclass(frozen=True)
class Seed:
    label: str
    source: Irrep
    target: Irrep
    source_magnetic: tuple[sp.Rational, sp.Rational]
    target_magnetic: tuple[sp.Rational, sp.Rational]
    component: tuple[sp.Rational, sp.Rational]
    value: sp.Expr


@dataclass(frozen=True)
class ReconstructedFamily:
    seed: Seed
    reduced_coefficient: sp.Expr
    components: dict[tuple[sp.Rational, sp.Rational], sp.Matrix]


def reconstruct(seed: Seed) -> ReconstructedFamily:
    unit = component_matrix(seed.source, seed.target, seed.component)
    row = seed.target.basis.index(seed.target_magnetic)
    column = seed.source.basis.index(seed.source_magnetic)
    seed_clebsch = sp.simplify(unit[row, column])
    if seed_clebsch == 0:
        raise AssertionError(f"{seed.label}: selected seed CG coefficient vanishes")
    reduced = sp.simplify(seed.value / seed_clebsch)
    components = {
        component: component_matrix(seed.source, seed.target, component, reduced)
        for component in MAGNETIC_COMPONENTS
    }
    check(
        f"C2b: {seed.label} seed is reproduced exactly",
        sp.simplify(components[seed.component][row, column] - seed.value) == 0,
    )
    return ReconstructedFamily(seed, reduced, components)


def spin_operators(
    spin: sp.Rational,
) -> tuple[sp.Matrix, sp.Matrix, sp.Matrix]:
    values = magnetic_values(spin)
    raising = sp.zeros(len(values))
    for column, magnetic in enumerate(values):
        raised = magnetic + 1
        if raised <= spin:
            row = values.index(raised)
            raising[row, column] = sp.sqrt(
                (spin - magnetic) * (spin + magnetic + 1)
            )
    lowering = raising.conjugate().T
    return sp.diag(*values), raising, lowering


def product_operator(irrep: Irrep, side: str, operator: str) -> sp.Matrix:
    left = spin_operators(irrep.left)
    right = spin_operators(irrep.right)
    index = {"z": 0, "+": 1, "-": 2}[operator]
    if side == "left":
        return sp.kronecker_product(left[index], sp.eye(int(2 * irrep.right + 1)))
    if side == "right":
        return sp.kronecker_product(sp.eye(int(2 * irrep.left + 1)), right[index])
    raise ValueError("side must be left or right")


def tensor_covariance_checks(family: ReconstructedFamily) -> None:
    source = family.seed.source
    target = family.seed.target
    components = family.components
    z_checks: list[bool] = []
    raising_checks: list[bool] = []
    lowering_checks: list[bool] = []
    for side, component_index in (("left", 0), ("right", 1)):
        source_z = product_operator(source, side, "z")
        target_z = product_operator(target, side, "z")
        source_plus = product_operator(source, side, "+")
        target_plus = product_operator(target, side, "+")
        source_minus = product_operator(source, side, "-")
        target_minus = product_operator(target, side, "-")
        for component, matrix in components.items():
            magnetic = component[component_index]
            z_checks.append(
                exact_matrix_equal(
                    target_z * matrix - matrix * source_z,
                    magnetic * matrix,
                )
            )

            raised = list(component)
            raised[component_index] += 1
            raising_coefficient = sp.sqrt(
                (HALF - magnetic) * (HALF + magnetic + 1)
            )
            raising_target = (
                raising_coefficient * components[tuple(raised)]
                if tuple(raised) in components
                else sp.zeros(*matrix.shape)
            )
            raising_checks.append(
                exact_matrix_equal(
                    target_plus * matrix - matrix * source_plus,
                    raising_target,
                )
            )

            lowered = list(component)
            lowered[component_index] -= 1
            lowering_coefficient = sp.sqrt(
                (HALF + magnetic) * (HALF - magnetic + 1)
            )
            lowering_target = (
                lowering_coefficient * components[tuple(lowered)]
                if tuple(lowered) in components
                else sp.zeros(*matrix.shape)
            )
            lowering_checks.append(
                exact_matrix_equal(
                    target_minus * matrix - matrix * source_minus,
                    lowering_target,
                )
            )
    check(
        f"C2b: {family.seed.label} obeys all left/right Jz tensor identities",
        all(z_checks),
    )
    check(
        f"C2b: {family.seed.label} obeys all left/right J+ tensor identities",
        all(raising_checks),
    )
    check(
        f"C2b: {family.seed.label} obeys all left/right J- tensor identities",
        all(lowering_checks),
    )


def parity_matrix() -> sp.Matrix:
    offsets: dict[str, int] = {}
    cursor = 0
    for irrep in LOW_IRREPS:
        offsets[irrep.label] = cursor
        cursor += irrep.dimension
    output = sp.zeros(cursor)
    partners = {
        "E+": E_MINUS,
        "E-": E_PLUS,
        "A+": A_MINUS,
        "A-": A_PLUS,
        "L+": L_MINUS,
        "L-": L_PLUS,
    }
    for irrep in LOW_IRREPS:
        partner = partners[irrep.label]
        for column_local, (left, right) in enumerate(irrep.basis):
            row_local = partner.basis.index((right, left))
            output[
                offsets[partner.label] + row_local,
                offsets[irrep.label] + column_local,
            ] = 1
    return output


def direct_sum_operator(side: str, operator: str) -> sp.Matrix:
    return sp.diag(*(product_operator(irrep, side, operator) for irrep in LOW_IRREPS))


def low_energy_kernels(
    families: tuple[ReconstructedFamily, ...],
) -> dict[tuple[sp.Rational, sp.Rational], sp.Matrix]:
    offsets: dict[str, int] = {}
    cursor = 0
    for irrep in LOW_IRREPS:
        offsets[irrep.label] = cursor
        cursor += irrep.dimension
    output = {component: sp.zeros(cursor) for component in MAGNETIC_COMPONENTS}
    for family in families:
        row_offset = offsets[family.seed.target.label]
        column_offset = offsets[family.seed.source.label]
        for component, block in family.components.items():
            output[component][
                row_offset : row_offset + family.seed.target.dimension,
                column_offset : column_offset + family.seed.source.dimension,
            ] = block
    return output


def selected_projection(matrix: sp.Matrix) -> sp.Matrix:
    offsets: dict[str, int] = {}
    cursor = 0
    for irrep in LOW_IRREPS:
        offsets[irrep.label] = cursor
        cursor += irrep.dimension
    selected = (
        offsets["E+"] + E_PLUS.basis.index((R(2), R(0))),
        offsets["A+"] + A_PLUS.basis.index((R(3, 2), HALF)),
        offsets["A-"] + A_MINUS.basis.index((HALF, R(3, 2))),
        offsets["L-"] + L_MINUS.basis.index((R(0), R(2))),
    )
    return matrix.extract(selected, selected)


def full_checks(
    lowering: dict[tuple[sp.Rational, sp.Rational], sp.Matrix],
) -> None:
    dimension = sum(irrep.dimension for irrep in LOW_IRREPS)
    energy = sp.diag(
        *(
            value
            for irrep in LOW_IRREPS
            for value in [sp.Integer(irrep.energy)] * irrep.dimension
        )
    )
    parity = parity_matrix()
    check("C2b: low-energy parity is an exact involution", parity * parity == sp.eye(dimension))

    check(
        "C2b: every reconstructed proper-CK component lowers compact energy by one",
        all(
            exact_matrix_equal(energy * matrix - matrix * energy, -matrix)
            for matrix in lowering.values()
        ),
    )
    check(
        "C2b: every reconstructed proper-CK component has rank sixteen",
        all(matrix.rank() == 16 for matrix in lowering.values()),
    )
    check(
        "C2b: parity swaps all reconstructed (q_L,q_R) components",
        all(
            exact_matrix_equal(
                parity * matrix * parity,
                lowering[(component[1], component[0])],
            )
            for component, matrix in lowering.items()
        ),
    )

    assembled_z_checks: list[bool] = []
    assembled_raising_checks: list[bool] = []
    for side, component_index in (("left", 0), ("right", 1)):
        rotation_z = direct_sum_operator(side, "z")
        rotation_plus = direct_sum_operator(side, "+")
        for component, matrix in lowering.items():
            magnetic = component[component_index]
            assembled_z_checks.append(
                exact_matrix_equal(
                    rotation_z * matrix - matrix * rotation_z,
                    magnetic * matrix,
                )
            )
            raised = list(component)
            raised[component_index] += 1
            coefficient = sp.sqrt(
                (HALF - magnetic) * (HALF + magnetic + 1)
            )
            target = (
                coefficient * lowering[tuple(raised)]
                if tuple(raised) in lowering
                else sp.zeros(dimension)
            )
            assembled_raising_checks.append(
                exact_matrix_equal(
                    rotation_plus * matrix - matrix * rotation_plus,
                    target,
                )
            )
    check(
        "C2b: assembled low-energy matrices obey all Jz tensor identities",
        all(assembled_z_checks),
    )
    check(
        "C2b: assembled low-energy matrices obey all J+ tensor identities",
        all(assembled_raising_checks),
    )

    seed_component = (HALF, -HALF)
    restricted_minus, restricted_plus = low_energy_charge_matrices()
    reconstructed_minus = selected_projection(lowering[seed_component])
    reconstructed_plus = selected_projection(lowering[seed_component].conjugate().T)
    check(
        "C2b: reconstructed lowering seed agrees with the direct curvature matrix",
        exact_matrix_equal(reconstructed_minus, restricted_minus),
    )
    check(
        "C2b: reconstructed seed dagger agrees with the direct reverse kernel",
        exact_matrix_equal(reconstructed_plus, restricted_plus),
    )


def partial_moment_map_checks(
    lowering: dict[tuple[sp.Rational, sp.Rational], sp.Matrix],
) -> None:
    """Exhibit the quadratic, non-projector nature of the known charge data.

    This is only the reconstructed proper-CK part of the moment map.  The
    example is not asserted to solve the still-unknown complete constraints.
    """

    offsets: dict[str, int] = {}
    cursor = 0
    for irrep in LOW_IRREPS:
        offsets[irrep.label] = cursor
        cursor += irrep.dimension

    def state_index(irrep: Irrep, magnetic: tuple[sp.Rational, sp.Rational]) -> int:
        return offsets[irrep.label] + irrep.basis.index(magnetic)

    e_index = state_index(E_PLUS, (R(2), R(0)))
    ap_index = state_index(A_PLUS, (R(3, 2), HALF))
    am_index = state_index(A_MINUS, (HALF, R(3, 2)))
    l_index = state_index(L_MINUS, (R(0), R(2)))

    check(
        "C2b: no individual seed basis vector is excluded by a mixed entry alone",
        all(
            sp.simplify((basis.conjugate().T * matrix * basis)[0]) == 0
            for index in (e_index, ap_index, am_index, l_index)
            for basis in [sp.eye(cursor).col(index)]
            for matrix in lowering.values()
        ),
    )

    charged = sp.zeros(cursor, 1)
    charged[e_index] = 1
    charged[ap_index] = 1
    charged_values = {
        component: sp.simplify((charged.conjugate().T * matrix * charged)[0])
        for component, matrix in lowering.items()
    }
    check(
        "C2b: a mixed E/A superposition carries a nonzero reconstructed Taub charge",
        charged_values[(HALF, -HALF)] == -sp.sqrt(5) / (5 * sp.pi)
        and sum(value != 0 for value in charged_values.values()) == 1,
    )

    cancelled = sp.zeros(cursor, 1)
    cancelled[e_index] = 1
    cancelled[ap_index] = 1
    cancelled[am_index] = 1
    cancelled[l_index] = 1 / sp.sqrt(2)
    check(
        "C2b: distinct mixed blocks can cancel on the reconstructed quadratic cone",
        all(
            sp.simplify((cancelled.conjugate().T * matrix * cancelled)[0]) == 0
            and sp.simplify(
                (cancelled.conjugate().T * matrix.conjugate().T * cancelled)[0]
            )
            == 0
            for matrix in lowering.values()
        ),
    )


def main() -> None:
    parser = argparse.ArgumentParser()
    parser.add_argument(
        "--require-full-moment-map",
        action="store_true",
        help="fail closed: mixed proper-CK seed multiplets are not the full moment map",
    )
    parser.add_argument(
        "--require-global-brst",
        action="store_true",
        help="fail closed: global conformal BRST cohomology is not constructed",
    )
    args = parser.parse_args()

    seed_component = (HALF, -HALF)
    ea_seed = Seed(
        "A+ -> E+",
        A_PLUS,
        E_PLUS,
        (R(3, 2), HALF),
        (R(2), R(0)),
        seed_component,
        charge_from_slice(-1, reverse=False),
    )
    al_seed = Seed(
        "L- -> A-",
        L_MINUS,
        A_MINUS,
        (R(0), R(2)),
        (HALF, R(3, 2)),
        seed_component,
        charge_from_slice(-1, reverse=True),
    )
    check(
        "C2b: (1/2,1/2) occurs once in each curvature-seeded transition block",
        tensor_multiplicity(ea_seed.source, ea_seed.target) == 1
        and tensor_multiplicity(al_seed.source, al_seed.target) == 1,
    )

    ea = reconstruct(ea_seed)
    al = reconstruct(al_seed)
    check(
        "C2b: exact reduced coefficients are fixed by the two curvature seeds",
        ea.reduced_coefficient == -sp.sqrt(10) / (5 * sp.pi)
        and al.reduced_coefficient == sp.sqrt(2) / (2 * sp.pi),
    )
    tensor_covariance_checks(ea)
    tensor_covariance_checks(al)

    parity_component = (-HALF, HALF)
    ea_parity_seed = Seed(
        "A- -> E- (parity)",
        A_MINUS,
        E_MINUS,
        (HALF, R(3, 2)),
        (R(0), R(2)),
        parity_component,
        charge_from_slice(-1, reverse=False, parity=True),
    )
    al_parity_seed = Seed(
        "L+ -> A+ (parity)",
        L_PLUS,
        A_PLUS,
        (R(2), R(0)),
        (R(3, 2), HALF),
        parity_component,
        charge_from_slice(-1, reverse=True, parity=True),
    )
    ea_parity = reconstruct(ea_parity_seed)
    al_parity = reconstruct(al_parity_seed)
    check(
        "C2b: parity preserves both reduced coefficients in the fixed intrinsic-phase convention",
        ea_parity.reduced_coefficient == ea.reduced_coefficient
        and al_parity.reduced_coefficient == al.reduced_coefficient,
    )
    tensor_covariance_checks(ea_parity)
    tensor_covariance_checks(al_parity)

    families = (ea, ea_parity, al_parity, al)
    lowering = low_energy_kernels(families)
    full_checks(lowering)
    partial_moment_map_checks(lowering)

    print("C2b seed component q_L,q_R:", seed_component)
    print("A -> E reduced coefficient:", ea.reduced_coefficient)
    print("L -> A reduced coefficient:", al.reduced_coefficient)
    print("low one-particle basis dimension:", sum(irrep.dimension for irrep in LOW_IRREPS))
    print("nonzero rank of each reconstructed lowering component: 16")
    print(
        "C2b STATUS: EXACT WIGNER--ECKART RECONSTRUCTION OF THE TWO "
        "CURVATURE-SEEDED PROPER-CONFORMAL TAUB MULTIPLETS. The matrices "
        "are energy-graded mixed bilinear data. They do not decide AA/EL "
        "self-charges, the full quadratic zero locus, or global BRST "
        "cohomology."
    )
    if args.require_full_moment_map:
        raise SystemExit(
            "the seven Killing sectors, self-charge blocks, other towers, "
            "and full quadratic moment map remain open"
        )
    if args.require_global_brst:
        raise SystemExit(
            "the energy-graded global Diff x Weyl BRST cohomology remains open"
        )


if __name__ == "__main__":
    main()
