#!/usr/bin/env python3
"""Sprint-3a certificate for the cyclic free-BV split-basis retract."""

from __future__ import annotations

import argparse
import json
from pathlib import Path
import sys

import sympy as sp

ROOT = Path(__file__).resolve().parents[1]
if str(ROOT) not in sys.path:
    sys.path.insert(0, str(ROOT))

from bridge.cyclic_retract import CyclicBVRetraction, sharp


CERTIFICATE_PATH = ROOT / "bridge" / "certificates" / "cyclic_bv_retract.json"
LATEX_PATH = ROOT / "bridge" / "generated" / "cyclic_bv_retract.tex"


def check(label: str, condition: object) -> None:
    if not bool(condition):
        raise AssertionError(label)
    print("[OK ] " + label)


def certificate_data(maximum_energy: int) -> dict[str, object]:
    levels = []
    for energy in range(2, maximum_energy + 1):
        cyclic = CyclicBVRetraction.build(energy)
        block = cyclic.block
        check(
            f"S3-C1[{energy}]: cyclic SDR has j^sharp=p and q^sharp=s^sharp=-operator",
            sharp(block.inclusion, cyclic.reduced_form, cyclic.full_form)
            == block.projection
            and sharp(block.q, cyclic.full_form, cyclic.full_form) == -block.q
            and sharp(block.homotopy, cyclic.full_form, cyclic.full_form)
            == -block.homotopy,
        )
        check(
            f"S3-C2[{energy}]: compact generator commutes with p,j,s",
            cyclic.compact_energy * block.homotopy
            == block.homotopy * cyclic.compact_energy
            and cyclic.compact_energy * block.inclusion
            == block.inclusion
            * (energy * sp.SparseMatrix.eye(block.physical_dimension))
            and block.projection * cyclic.compact_energy
            == (energy * sp.SparseMatrix.eye(block.physical_dimension))
            * block.projection,
        )
        check(
            f"S3-C3[{energy}]: bare/dressed-zero inclusion is an exact isometry",
            block.inclusion.conjugate().T
            * cyclic.full_form
            * block.inclusion
            == cyclic.reduced_form,
        )
        positive = sum(1 for value in cyclic.reduced_form.diagonal() if value == 1)
        negative = sum(1 for value in cyclic.reduced_form.diagonal() if value == -1)
        levels.append(
            {
                "energy": energy,
                "full_dimension": block.dimension,
                "reduced_dimension": block.physical_dimension,
                "reduced_signature": [positive, negative],
            }
        )
    return {
        "schema": "pure-weyl-cyclic-bv-retract-v1",
        "category": "BGG-split algebraic free BV blocks",
        "levels": levels,
        "identities": [
            "p j=1",
            "j p=1-q s-s q",
            "q^sharp=-q",
            "s^sharp=-s",
            "j^sharp=p",
            "[D,p]=[D,j]=[D,s]=0",
            "j^sharp j=1_H",
        ],
        "compact_so4_equivariance": "basis chosen by compact-isotypic BGG splitting; compact averaging is valid",
        "noncompact_equivariance": "not yet instantiated on the contractible rows",
    }


def latex(data: dict[str, object]) -> str:
    return "\n".join(
        [
            "% Generated by symbolic/verify_conformal_cyclic_bv_retract.py",
            r"\begin{equation}",
            r"p\jmath=1,\qquad \jmath p=1-qs-sq,\qquad q^\sharp=-q,\quad s^\sharp=-s,\quad \jmath^\sharp=p.",
            r"\end{equation}",
            "",
        ]
    )


def main() -> None:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--max-energy", type=int, default=6)
    parser.add_argument("--emit", action="store_true")
    parser.add_argument(
        "--claim-full-so42-equivariance",
        action="store_true",
        help="fail closed until K+/- are represented on contractible BV rows",
    )
    args = parser.parse_args()
    if args.claim_full_so42_equivariance:
        raise SystemExit(
            "REFUSED: this split model certifies compact equivariance and "
            "cyclicity only. A separate raw polynomial calculation finds "
            "nonzero but q-homotopic K+/- defects; strict equivariance of this "
            "representative SDR is false."
        )
    data = certificate_data(args.max_energy)
    if args.emit:
        CERTIFICATE_PATH.parent.mkdir(parents=True, exist_ok=True)
        LATEX_PATH.parent.mkdir(parents=True, exist_ok=True)
        CERTIFICATE_PATH.write_text(
            json.dumps(data, indent=2, sort_keys=True) + "\n", encoding="utf-8"
        )
        LATEX_PATH.write_text(latex(data), encoding="utf-8")
        print("wrote", CERTIFICATE_PATH.relative_to(ROOT))
        print("wrote", LATEX_PATH.relative_to(ROOT))
    print("CONFORMAL S3 CYCLIC BV RETRACT: COMPACT/CYCLIC PART ALL PASS")


if __name__ == "__main__":
    main()
