#!/usr/bin/env python3
"""Certify the one-particle, generator-domain, Fock, and block theorem."""

from __future__ import annotations

import argparse
import json
from pathlib import Path
import sys


ROOT = Path(__file__).resolve().parents[1]
if str(ROOT) not in sys.path:
    sys.path.insert(0, str(ROOT))

from analytic_completion import (
    BosonicKreinFock,
    ClosedGeneratorCertificate,
    OneParticleKreinCompletion,
    ResidualGhostFactor,
    TotalDegreeBlocks,
)


CERTIFICATE_DIR = ROOT / "analytic_completion" / "certificates"
GENERATED_DIR = ROOT / "analytic_completion" / "generated"

OVERCLAIM_FLAGS = {
    "--claim-pontryagin": "both Krein indices are infinite",
    "--claim-positive-graviton-hilbert": "the completed E/A/L form is indefinite",
    "--claim-bounded-generators": "proper and compact generators are unbounded closed operators",
    "--claim-group-representation": "Lie-algebra common-core identities do not prove exponentiation",
    "--claim-formal-adjoint-domains": "maximal Krein-adjoint domain equality is proved separately",
    "--claim-covariant-sobolev": "only the cylinder energy-mode Sobolev scale is constructed",
}


def _write_json(name: str, value: dict[str, object]) -> None:
    path = CERTIFICATE_DIR / name
    path.parent.mkdir(parents=True, exist_ok=True)
    path.write_text(json.dumps(value, indent=2, sort_keys=True) + "\n", encoding="utf-8")
    print("wrote", path.relative_to(ROOT))


def certificate_data() -> dict[str, dict[str, object]]:
    one = OneParticleKreinCompletion().certificate()
    generators = ClosedGeneratorCertificate()
    growth = generators.bounds_certificate()
    domains = generators.domains_certificate()
    fock = BosonicKreinFock().certificate()
    ghosts = ResidualGhostFactor.build().certificate()
    blocks = TotalDegreeBlocks.build().certificate()
    return {
        "one_particle_krein.json": one,
        "generator_bounds.json": growth,
        "generator_domains.json": domains,
        "fock_fundamental_symmetry.json": fock,
        "ghost_hilbert_factor.json": ghosts,
        "finite_total_degree_blocks.json": blocks,
    }


def latex(data: dict[str, dict[str, object]]) -> str:
    one = data["one_particle_krein.json"]
    blocks = data["finite_total_degree_blocks.json"]
    return "\n".join(
        [
            "% Generated by symbolic/verify_conformal_energy_mode_krein.py",
            r"\begin{theorem}[Energy-mode Krein--Fock foundation]",
            r"The normalized parity-complete $E/A/L$ module completes to an",
            r"infinite-index Krein space with fundamental symmetry",
            r"$\mathfrak J_1=+1_E\oplus(-1_A)\oplus(-1_L)$.",
            r"The proper conformal generators have closed maximal weighted-shift",
            r"realizations with the finite-energy vectors as graph cores, and",
            r"$(\overline K^-)^\sharp=\overline K^+$ including equality of domains.",
            r"The symmetric Fock completion has fundamental symmetry",
            r"$\Gamma_s(\mathfrak J_1)$.  Every total compact-degree block after",
            r"tensoring the residual ghost exterior space is finite-dimensional.",
            r"In particular, $\dim\mathscr K_0=" + str(blocks["centered_total_dimension"]) + r"$.",
            r"\end{theorem}",
            "% classification: " + str(one["classification"]),
            "",
        ]
    )


def main() -> None:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--emit", action="store_true")
    for flag in OVERCLAIM_FLAGS:
        parser.add_argument(flag, action="store_true")
    args = parser.parse_args()
    for flag, reason in OVERCLAIM_FLAGS.items():
        if getattr(args, flag[2:].replace("-", "_")):
            raise SystemExit(f"REFUSED: {reason}")

    data = certificate_data()
    if args.emit:
        for name, value in data.items():
            _write_json(name, value)
        GENERATED_DIR.mkdir(parents=True, exist_ok=True)
        path = GENERATED_DIR / "energy_mode_krein.tex"
        path.write_text(latex(data), encoding="utf-8")
        print("wrote", path.relative_to(ROOT))
    print("CONFORMAL ENERGY-MODE KREIN FOUNDATION: ALL PASS")


if __name__ == "__main__":
    main()
