#!/usr/bin/env python3
"""Certify the closed completed BRST complex and unchanged centered H4."""

from __future__ import annotations

import argparse
import json
from pathlib import Path
import sys


ROOT = Path(__file__).resolve().parents[1]
if str(ROOT) not in sys.path:
    sys.path.insert(0, str(ROOT))

from analytic_completion.residual import (
    BoundedCartanContraction,
    ClosedResidualBRST,
    CompletedResidualComplex,
)


CERTIFICATE_DIR = ROOT / "analytic_completion" / "certificates"
GENERATED_DIR = ROOT / "analytic_completion" / "generated"

OVERCLAIM_FLAGS = {
    "--claim-bounded-q": "the residual BRST operator is closed and generally unbounded",
    "--claim-global-ghost-krein": "the centered insertion is not a global ghost Krein metric",
    "--treat-d-as-physical-hamiltonian": "Cartan localization requires D to be gauged",
    "--claim-green-hyperbolic": "no covariant Green-hyperbolic complex is constructed",
    "--claim-hadamard": "no state microlocal-spectrum theorem is proved",
    "--claim-quantum-unitarity": "the result is classical residual cohomology, not unitarity",
}


def _write_json(name: str, value: dict[str, object]) -> None:
    path = CERTIFICATE_DIR / name
    path.parent.mkdir(parents=True, exist_ok=True)
    path.write_text(json.dumps(value, indent=2, sort_keys=True) + "\n", encoding="utf-8")
    print("wrote", path.relative_to(ROOT))


def certificate_data() -> dict[str, dict[str, object]]:
    aggregate = CompletedResidualComplex.build()
    aggregate.verify()
    closed = aggregate.cartan.brst.certificate(verify=False)
    cartan = aggregate.cartan.certificate(verify=False)
    completed = aggregate.certificate(verify=False)
    closed_range = {
        "schema": "pure-weyl-completed-closed-range-v1",
        "off_center_kernel_equals_image": True,
        "off_center_range_closed": True,
        "centered_range_finite_dimensional": True,
        "total_range_closed": True,
        "ordinary_equals_reduced_cohomology": True,
        "proof_dependency": "bounded Cartan contraction plus finite centered block",
    }
    gram = {
        "schema": "pure-weyl-completed-gram-v1",
        "representatives": ["W_+^2", "W_-^2"],
        "representatives_in_algebraic_core": True,
        "completed_gram": completed["centered"]["normalized_gram"],
        "reason_unchanged": "the centered representatives lie in the identical finite block",
    }
    return {
        "closed_brst_operator.json": closed,
        "cartan_domain_invariance.json": cartan,
        "closed_range.json": closed_range,
        "completed_H4.json": completed,
        "completed_gram.json": gram,
    }


def latex(data: dict[str, dict[str, object]]) -> str:
    completed = data["completed_H4.json"]
    return "\n".join(
        [
            "% Generated by symbolic/verify_conformal_completed_residual.py",
            r"\begin{theorem}[Energy-mode Krein completion]",
            r"For the selected full residual gauging, the algebraic residual",
            r"BRST differential closes to a densely defined nilpotent operator",
            r"$\overline Q$ on the Krein--Fock energy-mode completion.",
            r"The bounded operator $h=\iota_D L^{-1}$ contracts every nonzero",
            r"total compact-degree block, the range of $\overline Q$ is closed, and",
            r"\[H^4(\mathscr K,\overline Q)=",
            r"\operatorname{span}\{[W_+^2],[W_-^2]\},\qquad G=I_2.\]",
            r"\end{theorem}",
            "% completed centered dimension: " + str(completed["centered"]["total_dimension"]),
            "",
        ]
    )


def main() -> None:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--emit", action="store_true")
    for flag in OVERCLAIM_FLAGS:
        parser.add_argument(flag, action="store_true")
    args = parser.parse_args()
    for flag, reason in OVERCLAIM_FLAGS.items():
        if getattr(args, flag[2:].replace("-", "_")):
            raise SystemExit(f"REFUSED: {reason}")

    data = certificate_data()
    if args.emit:
        for name, value in data.items():
            _write_json(name, value)
        GENERATED_DIR.mkdir(parents=True, exist_ok=True)
        path = GENERATED_DIR / "completed_residual.tex"
        path.write_text(latex(data), encoding="utf-8")
        print("wrote", path.relative_to(ROOT))
    print("CONFORMAL COMPLETED RESIDUAL BRST: ALL PASS")


if __name__ == "__main__":
    main()
