#!/usr/bin/env python3
"""Independent integer check of the central two-particle residual rank.

This deliberately does not import the project's conformal-generator, Fock,
or BRST implementations.  It reconstructs only the representation-theoretic
lowest two-particle block

    Sym^2((2,0) + (0,2))

from the integral spin-two ``sl(2)`` action.  The six compact raising,
lowering, and Cartan constraints have rank 53 on the 55-dimensional block.
Their kernel is generated by one singlet in each chirality.  At the lowest
two-particle centered weight there is no incoming degree-three cochain, so
this is an independent small cross-check of the rank-53 outgoing residual
calculation used in the paper.

The check is intentionally narrower than the main residual program: it does
not reconstruct the one-particle 290 -> 1311 -> 3657 window, the complete CE
differential, the BV-to-BFV transfer, or the cohomological pairing.
"""

from __future__ import annotations

from itertools import combinations_with_replacement


SPIN = 2
CHIRAL_DIMENSION = 2 * SPIN + 1
ONE_PARTICLE_DIMENSION = 2 * CHIRAL_DIMENSION
PRIMES = (239, 241)

Pair = tuple[int, int]
SparseRow = dict[int, int]


def symmetric_basis() -> tuple[Pair, ...]:
    return tuple(
        combinations_with_replacement(range(ONE_PARTICLE_DIMENSION), 2)
    )


BASIS = symmetric_basis()
INDEX = {pair: position for position, pair in enumerate(BASIS)}


def one_particle_action(
    chirality: int, generator: str
) -> dict[int, tuple[int, int]]:
    """Integral spin-two action in the binary-quartic basis.

    A chirality is the five-state span ``k=0,...,4``.  On that span,

      E e_k = (4-k) e_(k+1),
      F e_k = k e_(k-1),
      H e_k = 2(k-2) e_k.
    """

    offset = chirality * CHIRAL_DIMENSION
    output: dict[int, tuple[int, int]] = {}
    for k in range(CHIRAL_DIMENSION):
        source = offset + k
        if generator == "E" and k < 2 * SPIN:
            output[source] = (source + 1, 2 * SPIN - k)
        elif generator == "F" and k > 0:
            output[source] = (source - 1, k)
        elif generator == "H":
            output[source] = (source, 2 * (k - SPIN))
    return output


def induced_rows(action: dict[int, tuple[int, int]]) -> tuple[SparseRow, ...]:
    """Induce a one-particle derivation on the unnormalized symmetric square."""

    rows: list[SparseRow] = [dict() for _ in BASIS]
    for column, pair in enumerate(BASIS):
        for slot, source in enumerate(pair):
            target_data = action.get(source)
            if target_data is None:
                continue
            target, coefficient = target_data
            result = list(pair)
            result[slot] = target
            result_pair = tuple(sorted(result))
            row = INDEX[result_pair]
            rows[row][column] = rows[row].get(column, 0) + coefficient
    return tuple({column: value for column, value in row.items() if value} for row in rows)


def constraint_rows() -> tuple[SparseRow, ...]:
    rows: list[SparseRow] = []
    for chirality in (0, 1):
        for generator in ("E", "F", "H"):
            rows.extend(induced_rows(one_particle_action(chirality, generator)))
    return tuple(row for row in rows if row)


def modular_rank(
    rows: tuple[SparseRow, ...], columns: tuple[int, ...], prime: int
) -> int:
    """Sparse row reduction over a prime field, implemented with stdlib only."""

    selected = {column: local for local, column in enumerate(columns)}
    work = [
        {
            selected[column]: value % prime
            for column, value in row.items()
            if column in selected and value % prime
        }
        for row in rows
    ]
    work = [row for row in work if row]
    pivot_row = 0
    for column in range(len(columns)):
        pivot = next(
            (row for row in range(pivot_row, len(work)) if work[row].get(column)),
            None,
        )
        if pivot is None:
            continue
        work[pivot_row], work[pivot] = work[pivot], work[pivot_row]
        row = work[pivot_row]
        inverse = pow(row[column], -1, prime)
        row = {key: value * inverse % prime for key, value in row.items()}
        work[pivot_row] = row
        for other in range(len(work)):
            if other == pivot_row:
                continue
            factor = work[other].get(column, 0)
            if not factor:
                continue
            reduced = dict(work[other])
            for key, value in row.items():
                new_value = (reduced.get(key, 0) - factor * value) % prime
                if new_value:
                    reduced[key] = new_value
                else:
                    reduced.pop(key, None)
            work[other] = reduced
        pivot_row += 1
        if pivot_row == len(work):
            break
    return pivot_row


def apply(rows: tuple[SparseRow, ...], vector: dict[int, int]) -> tuple[int, ...]:
    return tuple(
        sum(value * vector.get(column, 0) for column, value in row.items())
        for row in rows
    )


def chiral_singlet(chirality: int) -> dict[int, int]:
    """The binary-quartic invariant e0 e4 - 4 e1 e3 + 3 e2^2."""

    offset = chirality * CHIRAL_DIMENSION
    coefficients = {
        (offset, offset + 4): 1,
        (offset + 1, offset + 3): -4,
        (offset + 2, offset + 2): 3,
    }
    return {INDEX[pair]: value for pair, value in coefficients.items()}


def main() -> None:
    rows = constraint_rows()
    all_columns = tuple(range(len(BASIS)))
    plus_columns = tuple(
        index for index, (left, right) in enumerate(BASIS) if right < 5
    )
    mixed_columns = tuple(
        index for index, (left, right) in enumerate(BASIS) if left < 5 <= right
    )
    minus_columns = tuple(
        index for index, (left, _right) in enumerate(BASIS) if left >= 5
    )

    assert len(BASIS) == 55
    assert tuple(map(len, (plus_columns, mixed_columns, minus_columns))) == (15, 25, 15)

    plus_singlet = chiral_singlet(0)
    minus_singlet = chiral_singlet(1)
    assert not any(apply(rows, plus_singlet))
    assert not any(apply(rows, minus_singlet))
    assert set(plus_singlet).isdisjoint(minus_singlet)

    for prime in PRIMES:
        block_ranks = tuple(
            modular_rank(rows, columns, prime)
            for columns in (plus_columns, mixed_columns, minus_columns)
        )
        assert block_ranks == (14, 25, 14), (prime, block_ranks)
        assert modular_rank(rows, all_columns, prime) == 53

    # Modular rank 53 is a characteristic-zero lower bound.  The two exact,
    # independent kernel vectors give the opposite upper bound 55-2=53.
    print("independent decomposition: 55 = 15 + 25 + 15")
    print("independent block ranks: 53 = 14 + 25 + 14")
    print("exact kernel generators: chiral binary-quartic singlets")
    print("INDEPENDENT RESIDUAL RANK CHECK: rank=53 kernel=2 PASS")


if __name__ == "__main__":
    main()
