#!/usr/bin/env python3
"""Certify tensor/vector curl, local factors, projectors, and E/A/L origin."""

from __future__ import annotations

import argparse
import json
from pathlib import Path
import sys


ROOT = Path(__file__).resolve().parents[1]
if str(ROOT) not in sys.path:
    sys.path.insert(0, str(ROOT))

from covariant_completion import (
    EALFieldDictionary,
    TTBachFactorization,
    TTBranchProjectors,
    TensorCurlCertificate,
    VectorCurlCertificate,
    VectorWaveFactor,
)


CERTIFICATE_DIR = ROOT / "covariant_completion" / "certificates"
GENERATED_DIR = ROOT / "covariant_completion" / "generated"

OVERCLAIM_FLAGS = {
    "--claim-arbitrary-background": "the theorem is specific to the unit conformal cylinder",
    "--claim-local-tt-projector": "TT is a differential constraint and its projector is nonlocal",
    "--claim-local-branch-split": "the |C_2| E/L split is spectral and spatially nonlocal",
    "--claim-causal-branch-split": "the nonlocal E/L split is not asserted to preserve causal support",
    "--include-vector-killing-as-a2": "the metric-derived A tower excludes the r=0 Killing band",
    "--claim-full-bv-green": "only the reduced physical E/A/L system is Green-hyperbolic here",
}


def certificate_data() -> dict[str, dict[str, object]]:
    return {
        "tensor_curl_square.json": TensorCurlCertificate().certificate(),
        "vector_curl_square.json": VectorCurlCertificate().certificate(),
        "tt_local_factorization.json": TTBachFactorization().certificate(),
        "vector_wave_operator.json": VectorWaveFactor().certificate(),
        "branch_spectrum.json": TTBranchProjectors().certificate(),
        "EAL_multiplicity_match.json": EALFieldDictionary().certificate(),
    }


def latex() -> str:
    return "\n".join(
        [
            "% Generated by symbolic/verify_conformal_covariant_factorization.py",
            r"\begin{theorem}[Cylinder curl factorization and branch dictionary]",
            r"On transverse tensors and vectors on the unit three-sphere,",
            r"$\mathcal C_2^2=-D^2+3$ and $\mathcal C_1^2=-D^2+2$.",
            r"The Lorentzian reduced operators factor as",
            r"\[B_{\rm TT}=[\partial_t^2+(\mathcal C_2-1)^2]",
            r"[\partial_t^2+(\mathcal C_2+1)^2],\qquad",
            r"P_A=\partial_t^2+\mathcal C_1^2.\]",
            r"The lower TT, non-Killing transverse-vector, and upper TT branches",
            r"are exactly the parity-complete $E$, $A$, and $L$ towers at every",
            r"energy, including the low-energy exceptions $N_E\ge2$, $N_A\ge3$",
            r"and $N_L\ge4$.",
            r"\end{theorem}",
            "",
        ]
    )


def main() -> None:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--emit", action="store_true")
    for flag in OVERCLAIM_FLAGS:
        parser.add_argument(flag, action="store_true")
    args = parser.parse_args()
    for flag, reason in OVERCLAIM_FLAGS.items():
        if getattr(args, flag[2:].replace("-", "_")):
            raise SystemExit(f"REFUSED: {reason}")

    data = certificate_data()
    if args.emit:
        CERTIFICATE_DIR.mkdir(parents=True, exist_ok=True)
        for name, value in data.items():
            path = CERTIFICATE_DIR / name
            path.write_text(json.dumps(value, indent=2, sort_keys=True) + "\n", encoding="utf-8")
            print("wrote", path.relative_to(ROOT))
        GENERATED_DIR.mkdir(parents=True, exist_ok=True)
        path = GENERATED_DIR / "curl_factorization.tex"
        path.write_text(latex(), encoding="utf-8")
        print("wrote", path.relative_to(ROOT))
    print("CONFORMAL COVARIANT CURL FACTORIZATION: ALL PASS")


if __name__ == "__main__":
    main()
