#!/usr/bin/env python3
"""Sprint-4b certificate: explicit closed-universe residual BFV choice."""

from __future__ import annotations

import argparse
import json
from pathlib import Path
import sys


ROOT = Path(__file__).resolve().parents[1]
if str(ROOT) not in sys.path:
    sys.path.insert(0, str(ROOT))

from bridge.residual_bfv import ClosedUniverseBFVChoice, ConformalCE


CERTIFICATE_PATH = ROOT / "bridge" / "certificates" / "closed_universe_bfv.json"
LATEX_PATH = ROOT / "bridge" / "generated" / "closed_universe_bfv.tex"


def check(label: str, condition: object) -> None:
    if not bool(condition):
        raise AssertionError(label)
    print("[OK ] " + label)


def certificate_data() -> dict[str, object]:
    choice = ClosedUniverseBFVChoice.build()
    ce = ConformalCE.build()
    check(
        "S4-B1: the selected S3 Cauchy surface has no boundary charge sector",
        not choice.boundary_components and choice.surface_charge_rank == 0,
    )
    check(
        "S4-B2: all fifteen conformal reducibilities are BFV constraints",
        choice.residual_constraints == ce.names
        and len(choice.residual_constraints) == 15,
    )
    check(
        "S4-B3: D is constrained, so the Cartan homotopy is admissible",
        choice.cartan_contraction_allowed,
    )
    alternative = choice.retain_compact_time_as_charge()
    check(
        "S4-B4: retaining D defines a distinct problem and disables Cartan contraction",
        "D" not in alternative.residual_constraints
        and not alternative.cartan_contraction_allowed,
    )
    return {
        "schema": "pure-weyl-closed-universe-bfv-choice-v1",
        "spatial_slice": choice.spatial_slice,
        "boundary_components": [],
        "surface_charge_rank": choice.surface_charge_rank,
        "constraints": list(choice.residual_constraints),
        "compact_time_is_constraint": True,
        "cartan_contraction_allowed": True,
        "interpretation": (
            "closed boundaryless Dirac/BFV sector; this is an explicit "
            "boundary choice, not a universal consequence of compactness"
        ),
        "alternative": {
            "compact_time_is_charge": True,
            "cartan_contraction_allowed": False,
            "description": "boundary, clock, asymptotic, or deparametrized sector",
        },
    }


def latex(data: dict[str, object]) -> str:
    return "\n".join(
        [
            "% Generated by symbolic/verify_conformal_closed_universe_bfv.py",
            r"\begin{equation}",
            r"\partial S^3=\varnothing,\qquad \operatorname{rank}Q_{\partial}=0,\qquad \{G_A\}_{A=1}^{15}\ \text{are BFV constraints},\quad D\in\{G_A\}.",
            r"\end{equation}",
            "",
        ]
    )


def main() -> None:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--emit", action="store_true")
    parser.add_argument(
        "--claim-universal-D-gauging",
        action="store_true",
        help="fail closed: gauging D is a selected boundary problem",
    )
    args = parser.parse_args()
    if args.claim_universal_D_gauging:
        raise SystemExit(
            "REFUSED: the certificate selects the closed-universe BFV sector; "
            "boundary, asymptotic, clock, and deparametrized sectors may retain D"
        )
    data = certificate_data()
    if args.emit:
        CERTIFICATE_PATH.parent.mkdir(parents=True, exist_ok=True)
        LATEX_PATH.parent.mkdir(parents=True, exist_ok=True)
        CERTIFICATE_PATH.write_text(
            json.dumps(data, indent=2, sort_keys=True) + "\n", encoding="utf-8"
        )
        LATEX_PATH.write_text(latex(data), encoding="utf-8")
        print("wrote", CERTIFICATE_PATH.relative_to(ROOT))
        print("wrote", LATEX_PATH.relative_to(ROOT))
    print("CONFORMAL S4 CLOSED-UNIVERSE BFV CHOICE: ALL PASS")


if __name__ == "__main__":
    main()
