"""Single source of truth for the full Berger Diff x Weyl companion.

The ghost order is ``(xi_1,xi_2,xi_3,tau,sigma)`` and the metric component
order is the authoritative ten-component ``PAIRS`` order.  The construction
is covariant in the invariant Berger frame and includes every PBW lower-order
term generated by the Levi--Civita connection.
"""

from __future__ import annotations

from itertools import product

import sympy as sp

from d_quotient_classical.backreacted_clock.berger_linearized_bach_pbw import (
    ALPHA_B,
    ETA,
    GAMMA,
    PAIRS,
    LinearOperator,
    ZERO,
    _covariant_derivative_operator,
    _metric_perturbation,
    _split_operator_vector,
    _sum_ops,
)


def full_metric_gauge() -> list[list[LinearOperator]]:
    """Exact metric gauge generator, ordered spatial/temporal/Weyl."""

    vector: list[LinearOperator] = []
    for first, second in PAIRS:
        value = ZERO
        for component in range(4):
            if second == component:
                value = value + LinearOperator.from_terms(((component, (first,), 1),))
            if first == component:
                value = value + LinearOperator.from_terms(((component, (second,), 1),))
            value = value - LinearOperator.basis(component).scale(
                GAMMA[component][first][second]
            )
            value = value - LinearOperator.basis(component).scale(
                GAMMA[component][second][first]
            )
        vector.append(value)
    diffeomorphism = _split_operator_vector(vector, 4)
    diffeomorphism = [[row[index] for index in (1, 2, 3, 0)] for row in diffeomorphism]
    return [
        row
        + [
            LinearOperator.from_terms(
                ((0, (), 2 * ETA[first, second]),)
            )
        ]
        for row, (first, second) in zip(diffeomorphism, PAIRS, strict=True)
    ]


def _box_scalar(operator: LinearOperator) -> LinearOperator:
    gradient = {(axis,): operator.derivative(axis) for axis in range(4)}
    hessian = _covariant_derivative_operator(gradient, (-1,))
    return _sum_ops(
        hessian[(axis, axis)].scale(ETA[axis, axis]) for axis in range(4)
    )


def _box_covector(vector: list[LinearOperator]) -> list[LinearOperator]:
    first = _covariant_derivative_operator(
        {(axis,): vector[axis] for axis in range(4)}, (-1,)
    )
    second = _covariant_derivative_operator(first, (-1, -1))
    return [
        _sum_ops(
            second[(axis, axis, component)].scale(ETA[axis, axis])
            for axis in range(4)
        )
        for component in range(4)
    ]


def curved_companion() -> list[list[LinearOperator]]:
    """Exact local companion with the certified scalar-biwave principal."""

    metric = _metric_perturbation()
    derivative = _covariant_derivative_operator(metric, (-1, -1))
    trace = _sum_ops(
        metric[(first, second)].scale(ETA[first, second])
        for first, second in product(range(4), repeat=2)
    )
    divergence = [
        _sum_ops(
            derivative[(axis, axis, component)].scale(ETA[axis, axis])
            for axis in range(4)
        )
        for component in range(4)
    ]
    derivative_divergence = _covariant_derivative_operator(
        {(component,): divergence[component] for component in range(4)}, (-1,)
    )
    double_divergence = _sum_ops(
        derivative_divergence[(axis, axis)].scale(ETA[axis, axis])
        for axis in range(4)
    )
    wave_divergence = _box_covector(divergence)
    wave_gradient_trace = _box_covector(
        [trace.derivative(component) for component in range(4)]
    )
    diffeomorphism = [
        wave_divergence[component]
        - wave_gradient_trace[component].scale(sp.Rational(1, 6))
        - double_divergence.derivative(component).scale(sp.Rational(1, 3))
        for component in range(4)
    ]
    weyl = _box_scalar(_box_scalar(trace)).scale(sp.Rational(1, 6)) - _box_scalar(
        double_divergence
    ).scale(sp.Rational(1, 6))
    return _split_operator_vector(
        [diffeomorphism[index] for index in (1, 2, 3, 0)] + [weyl], 10
    )


def metric_fibre_identification() -> list[list[LinearOperator]]:
    """Nondegenerate raised-index map J=(4/alpha_B) R_raise."""

    diagonal = [
        sp.Rational(
            4,
            (1 if first == second else 2)
            * ETA[first, first]
            * ETA[second, second],
        )
        / ALPHA_B
        for first, second in PAIRS
    ]
    return [
        [
            LinearOperator.from_terms(((0, (), diagonal[row]),))
            if row == column
            else ZERO
            for column in range(10)
        ]
        for row in range(10)
    ]
