"""BH-0h: what universality of gamma costs the scalar sector.

BH0F closed the constant-vev reading of the BH0E dilemma: a constant scalar
vacuum expectation value pins the Ricci scalar and forces gamma = 0.  It
handed forward the only place branch two can still live -- a NON-constant
scalar -- with a precise question attached:

    the question to pose is not whether a profile exists (one does) but what
    UNIVERSALITY it must have.  BH0C requires gamma to be the same constant
    for every galaxy, and gamma is now tied to the scalar profile, so the
    requirement transfers to the profile.

This makes that transfer explicit, and the route is shorter than expected
because two results already in this line combine.

THE ROUTE, in one paragraph.  BH0G established that the Bach tensor has
conformal weight -2, so Bach flatness is a property of a CONFORMAL CLASS,
not of a metric.  BH0B established that in the gauge b = 1/B the general
Bach-vacuum solution is the four-parameter family B = w - u/r + gamma r -
k r^2 subject to w^2 + 3 u gamma = 1.  Put together, the conformal group
must ACT on that four-parameter family.  This computes the action.  It is
generated by a single Moebius map of the radius, the gauge condition
b = 1/B fixes it uniquely up to one constant C, and its effect on the
parameters is

    u -> u,   w -> w + 3 u C,   gamma -> gamma - 2 w C - 3 u C^2,
    k -> k + C gamma - C^2 w - C^3 u

so that gamma is NOT a conformal invariant.  Starting from a member with
gamma = 0 and moving by C produces gamma = -2 w C - 3 u C^2, nonzero
whenever C is.

WHAT THAT MEANS FOR THE SCALAR.  A conformally coupled scalar has weight
-1, so the frame in which it is CONSTANT is reached by exactly such a
transformation with Omega = S / S_0.  In that frame BH0F applies and gamma
vanishes.  Therefore, for a non-constant scalar, the linear potential in the
physical frame is generated entirely by the scalar's own profile, and the
transfer BH0F asked for is explicit:

    S(r) = S_0 / (1 - C r)      and      C = (S'/S) at the origin

so gamma is fixed by the scalar's FRACTIONAL RADIAL GRADIENT and by nothing
else about the profile.  "gamma is the same constant for every galaxy" is
therefore exactly "S'/S is the same for every galaxy" -- a statement about
the symmetry-breaking sector, now an equation rather than a worry.

WHAT THIS DOES NOT DO.  It does not adjudicate Flanagan-Mannheim.  It
locates it precisely: the two frames are conformally related and only one of
them has a linear potential, so the dispute is entirely about WHICH FRAME
MATTER FOLLOWS, which is a premise about the coupling and not a fact about
the vacuum.  Both frames are exhibited here; neither is preferred.

Run:  python3 bh0h_universality_transfer.py
"""

from __future__ import annotations

import sympy as sp

from weyl_geometry import Geometry, static_spherical_metric

FAILURES: list[str] = []


def check(cond: bool, label: str) -> None:
    print(("  PASS  " if cond else "  FAIL  ") + label)
    if not cond:
        FAILURES.append(label)


def mk_params(B, r):
    """Read (w, u, gamma, k) off a metric function in the forced family."""
    P = sp.Poly(sp.expand(sp.together(B) * r), r)
    c = P.all_coeffs()            # [r^3, r^2, r^1, r^0] of B*r
    return {
        "w": sp.expand(c[2]),
        "u": sp.expand(-c[3]),
        "gamma": sp.expand(c[1]),
        "k": sp.expand(-c[0]),
    }


def main() -> int:
    r, rh = sp.symbols("r hat_r", positive=True)
    C = sp.Symbol("C")
    w, u, gam, k = sp.symbols("w u gamma k")
    S0 = sp.Symbol("S_0", positive=True)

    print("1. the gauge-preserving radial map is forced, not chosen")
    # Under g -> Omega^-2 ghat the angular part fixes Omega = hat_r / r, and demanding the
    # image stay in the gauge b = 1/B gives a first-order ODE.  Solving it -- rather than
    # guessing a map and checking it -- is what makes the one-parameter family complete.
    f = sp.Function("f")
    sol = sp.dsolve(sp.Eq(sp.diff(f(r), r), (f(r) / r) ** 2), f(r))
    print(f"     gauge condition  d hat_r/dr = (hat_r/r)^2  =>  {sol}")
    rhat = r / (1 - C * r)
    check(sp.simplify(sp.diff(rhat, r) - (rhat / r) ** 2) == 0,
          "hat_r = r/(1 - C r) satisfies the gauge ODE")
    # and it is the general solution: sympy's constant matches C up to sign
    check(sp.simplify(sol.rhs.subs(sp.Symbol("C1"), C) - rhat) == 0
          or sp.simplify(sol.rhs.subs(sp.Symbol("C1"), -C) - rhat) == 0,
          "and it is the GENERAL solution -- one constant, no further freedom")

    Omega = sp.simplify(rhat / r)
    print(f"     the conformal factor is Omega = {Omega}")

    print("\n2. the induced action on the four parameters, COMPUTED")
    Bh = w - u / rhat + gam * rhat - k * rhat ** 2
    B = sp.expand(sp.simplify((r / rhat) ** 2 * Bh))
    p = mk_params(B, r)
    print(f"     w      -> {p['w']}")
    print(f"     u      -> {p['u']}")
    print(f"     gamma  -> {p['gamma']}")
    print(f"     k      -> {p['k']}")
    check(sp.simplify(p["u"] - u) == 0, "u is invariant")
    check(sp.simplify(p["w"] - (w + 3 * u * C)) == 0, "w -> w + 3 u C")
    check(sp.simplify(p["gamma"] - (gam - 2 * w * C - 3 * u * C ** 2)) == 0,
          "gamma -> gamma - 2 w C - 3 u C^2")
    check(sp.simplify(p["k"] - (k + C * gam - C ** 2 * w - C ** 3 * u)) == 0,
          "k -> k + C gamma - C^2 w - C^3 u")

    print("\n3. the image is still a Bach vacuum -- both BH0B conditions")
    # (i) (r B)'''' = 0, which is BH0B's linear half
    check(sp.simplify(sp.diff(sp.expand(B * r), r, 4)) == 0,
          "(r B)'''' = 0, so the image is in the general solution")
    # (ii) the algebraic constraint is PRESERVED, not merely satisfiable
    lhs = sp.expand(p["w"] ** 2 + 3 * p["u"] * p["gamma"])
    check(sp.simplify(lhs - (w ** 2 + 3 * u * gam)) == 0,
          f"w^2 + 3 u gamma is invariant   [image value = {sp.simplify(lhs)}]")

    print("\n4. gamma is NOT a conformal invariant, and that is the whole point")
    # start from a gamma = 0 member.  w^2 + 3 u gamma = 1 with gamma = 0 forces w = 1.
    g0 = {w: 1, gam: 0}
    gamma_new = sp.simplify(p["gamma"].subs(g0))
    print(f"     from gamma = 0, w = 1:   gamma -> {gamma_new}")
    check(sp.simplify(gamma_new + 2 * C + 3 * u * C ** 2) == 0,
          "gamma = -2C - 3 u C^2 from a gamma = 0 member")
    check(sp.simplify(gamma_new.subs(C, 0)) == 0,
          "C = 0 gives gamma = 0 -- the identity element (control)")
    check(sp.simplify(gamma_new.subs({u: 0, C: 1})) != 0,
          "and some C gives gamma != 0 -- the action is not trivial (non-vacuity)")

    print("\n5. the scalar profile that does it")
    # A conformally coupled scalar has weight -1: hat_S = Omega^-1 S.  Demanding hat_S = S_0
    # constant -- the frame BH0F analysed -- gives S = Omega S_0 directly.
    S = sp.simplify(Omega * S0)
    print(f"     hat_S = S_0 constant   =>   S(r) = {S}")
    frac = sp.simplify(sp.diff(S, r) / S)
    print(f"     fractional gradient S'/S = {frac}")
    check(sp.simplify(frac.subs(r, 0) - C) == 0,
          "C = (S'/S) at the origin -- the transfer, in closed form")
    check(sp.simplify(sp.diff(S, r).subs(C, 0)) == 0,
          "C = 0 is the constant scalar, which is BH0F's case (control)")

    print("\n6. THE TRANSFER: gamma as a functional of the profile")
    sigma = sp.Symbol("sigma")          # sigma := (S'/S) at the origin
    gamma_of_S = sp.expand(gamma_new.subs(C, sigma))
    print(f"     with sigma := (S'/S)(0),   gamma = {gamma_of_S}")
    print("     so gamma is fixed by the scalar's fractional radial gradient and by")
    print("     nothing else about the profile, with the u-term a mass correction.")
    # to leading order gamma = -2 S'/S, so universality of gamma is universality of S'/S
    lead = sp.simplify(sp.series(gamma_of_S, sigma, 0, 2).removeO())
    check(sp.simplify(lead + 2 * sigma) == 0,
          f"to leading order gamma = -2 (S'/S)   [{lead}]")

    print("\n7. CONTROLS")
    # the composition law: two transformations compose to one, so this really is a group
    C2 = sp.Symbol("C2")
    Bh2 = (p["w"] - p["u"] / rhat + p["gamma"] * rhat - p["k"] * rhat ** 2).subs(C, C2)
    # careful: apply the SECOND map to the image of the first
    im1 = {w: p["w"], u: p["u"], gam: p["gamma"], k: p["k"]}
    # `simultaneous=True` is load-bearing: a sequential dict substitution rewrites `w` inside
    # the image of `gamma` a second time and silently composes the wrong thing. The first
    # version of this check failed for that reason and not for a mathematical one.
    p2 = {kk: sp.expand(vv.subs(C, C2).subs(im1, simultaneous=True)) for kk, vv in p.items()}
    check(sp.simplify(p2["gamma"] - p["gamma"].subs(C, C + C2)) == 0,
          "the maps compose: C then C2 is C + C2 (a one-parameter group)")
    check(sp.simplify(p2["w"] - p["w"].subs(C, C + C2)) == 0,
          "and the same on w")

    # a direct Bach computation on one numeric member, as an independent rail on step 3
    print("     an independent rail: the Bach tensor of one image member, computed")
    t, rr, th, ph = sp.symbols("t r_c theta phi")
    num = {w: 1, gam: 0, u: sp.Rational(1, 5), k: sp.Rational(1, 7), C: sp.Rational(1, 3)}
    Bnum = sp.simplify(B.subs(num).subs(r, rr))
    geo = Geometry([t, rr, th, ph], static_spherical_metric(Bnum, 1 / Bnum, rr, th))
    bach = geo.bach()
    worst = max(sp.simplify(bach[a, b]) != 0 for a in range(4) for b in range(4))
    check(not worst, f"Bach tensor of the image vanishes identically  [B = {Bnum}]")
    # and the member it came from must NOT already have gamma
    check(sp.simplify(mk_params(Bnum, rr)["gamma"]) != 0,
          f"that member has gamma = {sp.simplify(mk_params(Bnum, rr)['gamma'])} != 0")

    print()
    if FAILURES:
        print(f"FAILED {len(FAILURES)}: " + "; ".join(FAILURES))
        return 1
    print("ALL PASS")
    print("  gamma is not a conformal invariant of the Bach vacuum: the conformal group")
    print("  acts on BH0B's four parameters and shifts it.  For a conformally coupled")
    print("  scalar the frame where S is constant is reached by exactly that map, and")
    print("  BH0F kills gamma there -- so for a NON-constant scalar the linear potential")
    print("  is generated by the profile, with gamma = -2 (S'/S) to leading order.")
    print("  BH0C's demand that gamma be universal across galaxies is therefore exactly")
    print("  the demand that S'/S be universal across galaxies.")
    print("  Both frames are exhibited; which one matter follows is NOT decided here.")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
