"""BH-0i: which frame matter follows, computed rather than stated.

BH0H showed that gamma is not a conformal invariant: the conformal group acts
on BH0B's four parameters, and the frame in which a conformally coupled scalar
is CONSTANT -- where BH0F forces gamma = 0 -- is reached from a frame with
gamma != 0 by one Moebius map.  Both frames describe the same Bach vacuum.

It left the obvious question open on purpose: WHICH frame does matter follow?
That is the premise the Flanagan-Mannheim dispute turns on, and BH0H stated it
rather than computing it.  This computes it, and the computation is short
because the answer is a variational identity rather than a dynamical solution.

THE IDENTITY.  A point particle whose mass is m follows the extremals of
-int m ds.  If the mass is GENERATED by the symmetry-breaking scalar -- which
is the entire purpose of the scalar, and is a Yukawa coupling m = h S -- then

    -int h S ds_g  =  -int h sqrt( -S^2 g_ab dx^a dx^b )  =  -int h ds_{S^2 g}

so the trajectory is a geodesic of S^2 g and NOT of g.  The mass scale is the
conformal factor.  Since S^2 g is proportional to the frame where S is
constant, a particle whose mass tracks S follows geodesics of the frame BH0F
analysed -- the one with gamma = 0.

WHAT THAT DOES AND DOES NOT SETTLE.  It does not refute conformal gravity and
it does not adjudicate the dispute.  It converts the premise into a fork with
two computed branches:

    m constant, independent of S   ->  geodesics of g      ->  gamma acts
    m = h S, generated by S        ->  geodesics of S^2 g  ->  gamma does not

Both branches are exhibited below with their circular-orbit velocities.  A
rotation-curve fit needs the first; the second is what the symmetry breaking
was introduced to provide.  Whether a matter sector can have the first while
still breaking conformal invariance is a question about that sector, and this
does not answer it.

SCOPE.  Rotation curves are measured OUTSIDE the baryonic disc, where the
metric is a Bach vacuum, which is where BH0B, BH0F and BH0H all apply.  The
interior, and the matching that fixes the profile, are not treated here.

Run:  python3 bh0i_which_frame_matter_follows.py
"""

from __future__ import annotations

import sympy as sp

from weyl_geometry import Geometry, static_spherical_metric

FAILURES: list[str] = []


def check(cond: bool, label: str) -> None:
    print(("  PASS  " if cond else "  FAIL  ") + label)
    if not cond:
        FAILURES.append(label)


def circular_v2(B, r):
    """(v/c)^2 for a circular geodesic orbit of diag(-B, 1/B, r^2, ...)."""
    return sp.simplify(r * sp.diff(B, r) / (2 * B))


def main() -> int:
    r, tau = sp.symbols("r tau", positive=True)
    C, u = sp.symbols("C u")
    S0, h = sp.symbols("S_0 h", positive=True)

    print("1. the identity: a mass generated by S rescales the metric it moves in")
    # For a general static spherically symmetric metric, compare the point-particle
    # Lagrangian with mass h*S against the geodesic Lagrangian of S^2 g. They must be the
    # same function, which is what makes 'mass scale' and 'conformal factor' the same thing.
    t = sp.Function("t")(tau)
    rr = sp.Function("r")(tau)
    a = sp.Function("a")
    # S is declared POSITIVE, which is what lets sqrt(S^2 X) = S sqrt(X) close. That is not a
    # convenience: a vacuum expectation value with a sign change passes through zero, where the
    # generated mass vanishes and the conformal factor degenerates, so the identity below is
    # exactly as valid as the frame change of BH0H and no more.
    Sf = sp.Function("S", positive=True)
    # -ds^2 = -a(r) dt^2 + dr^2 / a(r)   (equatorial, radial+time part suffices for the point)
    ds_g = sp.sqrt(a(rr) * sp.diff(t, tau) ** 2 - sp.diff(rr, tau) ** 2 / a(rr))
    L_mass = h * Sf(rr) * ds_g
    # the geodesic Lagrangian of S^2 g: replace a -> S^2 a and 1/a -> S^2 / a
    ds_conf = sp.sqrt(Sf(rr) ** 2 * a(rr) * sp.diff(t, tau) ** 2
                      - Sf(rr) ** 2 * sp.diff(rr, tau) ** 2 / a(rr))
    check(sp.simplify(L_mass - h * ds_conf) == 0,
          "-int h S ds_g  =  -int h ds_{S^2 g}   (the mass scale IS the conformal factor)")
    # and it is not vacuous: with S constant the two frames coincide
    check(sp.simplify((L_mass - h * ds_g).subs(Sf(rr), 1)) == 0,
          "with S = 1 the rescaling is the identity (control)")
    check(sp.simplify(L_mass - h * ds_g) != 0,
          "with S non-constant they DIFFER, so the fork is real (non-vacuity)")

    print("\n2. the two frames of BH0H, side by side")
    # hatted frame: the S-constant frame, where BH0F forces gamma = 0 and w = 1
    Bhat = 1 - u / r - sp.Symbol("k") * r ** 2
    # physical frame: its image under BH0H's map, which carries gamma = -2C - 3 u C^2
    rhat = r / (1 - C * r)
    B = sp.expand(sp.simplify((r / rhat) ** 2
                              * (1 - u / rhat - sp.Symbol("k") * rhat ** 2)))
    gam = sp.expand(sp.Poly(sp.expand(B * r), r).all_coeffs()[1])
    print(f"     hatted (S constant):  B_hat = {Bhat}")
    print(f"     physical:             gamma = {gam}")
    check(sp.simplify(gam + 2 * C + 3 * u * C ** 2) == 0,
          "the physical frame carries BH0H's gamma = -2C - 3 u C^2")
    check(sp.simplify(sp.Poly(sp.expand(Bhat * r), r).all_coeffs()[1]) == 0,
          "and the hatted frame carries gamma = 0 (BH0F)")

    print("\n3. circular-orbit velocities in each frame")
    v2_phys = circular_v2(B, r)
    v2_hat = circular_v2(Bhat, r)
    # the linear-in-r piece is the whole rotation-curve effect: read it off the weak-field
    # expansion, where v^2 = u/(2r) + gamma r/2 - k r^2
    lin_phys = sp.simplify(sp.series(sp.expand(r * sp.diff(B, r) / 2), r, 0, 2)
                           .removeO().coeff(r, 1))
    lin_hat = sp.simplify(sp.series(sp.expand(r * sp.diff(Bhat, r) / 2), r, 0, 2)
                          .removeO().coeff(r, 1))
    print(f"     physical frame: linear coefficient of v^2 = {lin_phys}")
    print(f"     hatted frame:   linear coefficient of v^2 = {lin_hat}")
    check(sp.simplify(lin_hat) == 0,
          "the S-constant frame has NO linearly rising term in v^2")
    check(sp.simplify(lin_phys) != 0,
          "the physical frame does -- so the frames disagree about rotation curves")
    check(sp.simplify(lin_phys - gam / 2) == 0,
          "and that term is exactly gamma/2, matching BH0C's weak-field formula")

    print("\n4. THE FORK, with both branches computed")
    print("     m constant  ->  geodesics of g      ->  v^2 rises linearly with "
          f"coefficient {sp.simplify(gam / 2)}")
    print("     m = h S     ->  geodesics of S^2 g  ->  v^2 has no linear term at all")
    # S^2 g is proportional to the hatted metric, so branch two lands in the gamma = 0 frame
    Om = sp.simplify(rhat / r)
    S = sp.simplify(Om * S0)
    check(sp.simplify(sp.diff(S, r).subs(C, 0)) == 0,
          "S is constant exactly when C = 0, i.e. when the frames coincide (control)")
    check(sp.simplify((S / S0) ** 2 * sp.simplify(B) - sp.simplify(Bhat.subs(r, rhat))) == 0,
          "S^2 g is the hatted metric up to the constant S_0^2, so branch two sees gamma = 0")

    print("\n5. CONTROLS")
    # an independent rail: both metrics are Bach vacua, computed
    tt, rc, th, ph = sp.symbols("t r_c theta phi")
    num = {u: sp.Rational(1, 5), sp.Symbol("k"): sp.Rational(1, 7), C: sp.Rational(1, 3)}
    for name, expr in (("physical", B), ("hatted", Bhat)):
        Bn = sp.simplify(expr.subs(num).subs(r, rc))
        geo = Geometry([tt, rc, th, ph], static_spherical_metric(Bn, 1 / Bn, rc, th))
        bad = any(sp.simplify(geo.bach()[i, j]) != 0 for i in range(4) for j in range(4))
        check(not bad, f"the {name} frame is a Bach vacuum (independent rail)")
    # the effect is not an artefact of the weak-field expansion: the exact v^2 differs too
    check(sp.simplify(v2_phys - v2_hat) != 0,
          "the exact circular-orbit velocities differ, not only their expansions")

    print()
    if FAILURES:
        print(f"FAILED {len(FAILURES)}: " + "; ".join(FAILURES))
        return 1
    print("ALL PASS")
    print("  A mass generated by the symmetry-breaking scalar makes that scalar the")
    print("  conformal factor of the metric the particle moves in.  Such a particle")
    print("  therefore follows geodesics of the frame where S is constant, which BH0F")
    print("  and BH0H put at gamma = 0 -- so the linear potential does not bend its")
    print("  orbit.  A particle whose mass does NOT track S follows the other frame,")
    print("  where it does.  The dispute is that fork, and both branches are computed")
    print("  here; which one a real matter sector realises is NOT decided.")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
