(** * Degree-of-freedom independence becomes additivity of the exponent.

    [ReversePhysicsRelationalCount.v] showed that in a conformally invariant
    theory the absolute degree-of-freedom count is replaced by a RELATIVE one,
    and that the relative count is generated by a single number: the scale
    factor f is multiplicative, so f(2^n) = f(2)^n.  It also stated, WITHOUT
    PROOF, what should become of Carcassi and Aidala's independence assumption:

      "#states = product of #confDOF" is a product of COUNTS.  Products of
      RATIOS are sums of EXPONENTS, so independence should survive as ADDITIVITY
      OF THE EXPONENT over independent subsystems.

    This file proves it.

    ** Stating additivity without logarithms

    "Exponent" suggests a logarithm, which would leave the rationals and break
    the exactness this stream depends on.  It is not needed.  If the scale
    factors are g_A = 2^{d_A} and g_B = 2^{d_B}, then

      exponents add          <=>       g_{AB} = g_A * g_B

    because 2^{d_A + d_B} = 2^{d_A} 2^{d_B}.  The multiplicative statement IS the
    additive one, and it is exactly rational.  [Qpower_plus] supplies the last
    step over Z exponents.

    ** The results

      [independence_makes_scale_factors_multiply]
          f_{AB}(t) = f_A(t) f_B(t), directly from the product structure
      [generating_numbers_multiply]
          g_{AB} = g_A g_B
      [exponents_add]
          and if g_A = 2^{d_A}, g_B = 2^{d_B}, then g_{AB} = 2^{d_A + d_B}
      [composite_scaling_law]
          f_{AB}(2^n) = (g_A g_B)^n

    ** Modelling boundary

    The product structure is a hypothesis: that composite regions are products,
    that the composite dilation acts diagonally, and that the relative count
    factorises across independent subsystems -- the last being precisely the
    translation of their independence assumption.  Nothing here derives that
    factorisation; it is what is being transposed, not what is being proved.

    The exponents are taken to be INTEGERS on dyadic scales.  A real-valued
    exponent needs a regularity argument this stream does not have, and the
    dyadic integer case already carries the content. *)

Require Import QArith.
Require Import Qpower.
Require Import Lqa.
Require Import ReversePhysicsRelationalCount.

Open Scope Q_scope.

(** ** Powers of a product *)

Lemma qpow_mul :
  forall x y n, qpow x n * qpow y n == qpow (x * y) n.
Proof.
  intros x y n. induction n as [| k IH]; simpl.
  - ring.
  - rewrite <- IH. ring.
Qed.

(** ** Independence makes the scale factors multiply *)

(** [RegA], [RegB], [RegAB] are the region types of two subsystems and their
    composite; [pair_region] builds a composite region; the composite dilation
    acts diagonally; and [nuAB] factorises -- that last hypothesis IS the
    independence assumption, transposed to the relational setting. *)
Theorem independence_makes_scale_factors_multiply :
  forall (RegA RegB RegAB : Type)
         (pair_region : RegA -> RegB -> RegAB)
         (nuA : RegA -> RegA -> Q)
         (nuB : RegB -> RegB -> Q)
         (nuAB : RegAB -> RegAB -> Q)
         (dilA : Q -> RegA -> RegA)
         (dilB : Q -> RegB -> RegB)
         (dilAB : Q -> RegAB -> RegAB)
         (refA : RegA) (refB : RegB),
    (* the composite dilation acts diagonally *)
    (forall c U V, dilAB c (pair_region U V) = pair_region (dilA c U) (dilB c V)) ->
    (* independence: the relative count factorises *)
    (forall U1 V1 U2 V2,
        nuAB (pair_region U1 V1) (pair_region U2 V2) == nuA U1 U2 * nuB V1 V2) ->
    forall t,
      nuAB (dilAB t (pair_region refA refB)) (pair_region refA refB)
      == nuA (dilA t refA) refA * nuB (dilB t refB) refB.
Proof.
  intros RegA RegB RegAB pair_region nuA nuB nuAB dilA dilB dilAB refA refB
         Hdiag Hindep t.
  rewrite (Hdiag t refA refB).
  apply Hindep.
Qed.

(** ** The generating numbers multiply *)

Theorem generating_numbers_multiply :
  forall (RegA RegB RegAB : Type)
         (pair_region : RegA -> RegB -> RegAB)
         (nuA : RegA -> RegA -> Q)
         (nuB : RegB -> RegB -> Q)
         (nuAB : RegAB -> RegAB -> Q)
         (dilA : Q -> RegA -> RegA)
         (dilB : Q -> RegB -> RegB)
         (dilAB : Q -> RegAB -> RegAB)
         (refA : RegA) (refB : RegB),
    (forall c U V, dilAB c (pair_region U V) = pair_region (dilA c U) (dilB c V)) ->
    (forall U1 V1 U2 V2,
        nuAB (pair_region U1 V1) (pair_region U2 V2) == nuA U1 U2 * nuB V1 V2) ->
    nuAB (dilAB 2 (pair_region refA refB)) (pair_region refA refB)
    == nuA (dilA 2 refA) refA * nuB (dilB 2 refB) refB.
Proof.
  intros RegA RegB RegAB pair_region nuA nuB nuAB dilA dilB dilAB refA refB
         Hdiag Hindep.
  apply (independence_makes_scale_factors_multiply
           RegA RegB RegAB pair_region nuA nuB nuAB dilA dilB dilAB refA refB
           Hdiag Hindep 2).
Qed.

(** ** THE ADDITIVITY *)

(** A scale factor HAS exponent [d] when it equals two to the [d]. *)
Definition has_exponent (g : Q) (d : Z) : Prop := g == 2 ^ d.

(** Independence adds the exponents.  No logarithm appears: the multiplicative
    statement about generating numbers IS the additive statement about
    exponents, because 2^(dA + dB) = 2^dA * 2^dB. *)
Theorem exponents_add :
  forall (gA gB gAB : Q) (dA dB : Z),
    has_exponent gA dA ->
    has_exponent gB dB ->
    gAB == gA * gB ->
    has_exponent gAB (dA + dB).
Proof.
  intros gA gB gAB dA dB HA HB Hmul.
  unfold has_exponent in *.
  rewrite Hmul, HA, HB.
  symmetry. apply Qpower_plus. discriminate.
Qed.

(** Assembled: the composite of two independent subsystems has the sum of their
    exponents. *)
Theorem independent_subsystems_add_their_exponents :
  forall (RegA RegB RegAB : Type)
         (pair_region : RegA -> RegB -> RegAB)
         (nuA : RegA -> RegA -> Q)
         (nuB : RegB -> RegB -> Q)
         (nuAB : RegAB -> RegAB -> Q)
         (dilA : Q -> RegA -> RegA)
         (dilB : Q -> RegB -> RegB)
         (dilAB : Q -> RegAB -> RegAB)
         (refA : RegA) (refB : RegB) (dA dB : Z),
    (forall c U V, dilAB c (pair_region U V) = pair_region (dilA c U) (dilB c V)) ->
    (forall U1 V1 U2 V2,
        nuAB (pair_region U1 V1) (pair_region U2 V2) == nuA U1 U2 * nuB V1 V2) ->
    has_exponent (nuA (dilA 2 refA) refA) dA ->
    has_exponent (nuB (dilB 2 refB) refB) dB ->
    has_exponent
      (nuAB (dilAB 2 (pair_region refA refB)) (pair_region refA refB))
      (dA + dB).
Proof.
  intros RegA RegB RegAB pair_region nuA nuB nuAB dilA dilB dilAB refA refB dA dB
         Hdiag Hindep HA HB.
  apply (exponents_add (nuA (dilA 2 refA) refA) (nuB (dilB 2 refB) refB)
                       _ dA dB HA HB).
  apply (generating_numbers_multiply
           RegA RegB RegAB pair_region nuA nuB nuAB dilA dilB dilAB refA refB
           Hdiag Hindep).
Qed.

(** ** The composite scaling law *)

(** And the composite obeys the same power law, with the product generating
    number -- equivalently, with the summed exponent. *)
Theorem composite_scaling_law :
  forall (gA gB : Q) (n : nat) (fABn : Q),
    fABn == qpow gA n * qpow gB n ->
    fABn == qpow (gA * gB) n.
Proof.
  intros gA gB n fABn H. rewrite H. apply qpow_mul.
Qed.

(** ** What this settles *)

(** Their assumption "#states = product of #confDOF" was a product of COUNTS,
    and counts do not exist in a conformally invariant theory.  It transposes:
    the relative count factorises across independent subsystems, and the single
    number generating each subsystem's scaling multiplies -- which is to say the
    exponents add.  The assumption survives the loss of the count. *)

(** ** The honest ledger *)

Print Assumptions qpow_mul.
Print Assumptions independence_makes_scale_factors_multiply.
Print Assumptions generating_numbers_multiply.
Print Assumptions exponents_add.
Print Assumptions independent_subsystems_add_their_exponents.
Print Assumptions composite_scaling_law.
