(** * What replaces a count: a single exponent.

    [ReversePhysicsNoConformalCount.v] refuted the ABSOLUTE degree-of-freedom
    count: on flat space every ball ties, additivity is never used, and all three
    branches of the Carcassi-Aidala trilemma close.  That left the question the
    refutation does not answer -- if "how many degrees of freedom are in this
    region" is not well posed, what does their DOF-independence assumption
    become?

    This file answers it.  Something does survive, and it is sharply constrained.

    ** The move

    Replace the absolute count mu(U) by a RELATIVE one,

      nu(U, V)  =  degrees of freedom in U relative to V.

    Naturality and constant Weyl invariance still give dilation invariance, but
    now on BOTH arguments: nu(dil_c U, dil_c V) = nu(U, V).  Applied to balls
    that says nu(B_r, B_s) depends only on the RATIO r/s -- which is not
    degenerate at all.  It is the familiar content of conformal invariance:
    there is no length, only ratios of lengths.

    ** The result

    Add the one property any relative count must have, the chain rule
    nu(U,W) = nu(U,V) nu(V,W), and write f(t) = nu(B_t, B_1).  Then

      [scale_factor_is_multiplicative]     f(ab) = f(a) f(b)
      [generated_by_a_single_number]       f(2^n) = f(2)^n

    So the entire family is generated by ONE NUMBER.  Whatever survives of "how
    many degrees of freedom" in a conformally invariant theory is not a function
    on regions -- it is a single scaling exponent.

    ** And the two results are one phenomenon

    [a_reference_region_forces_a_trivial_exponent]: if some region could serve as
    an absolute reference -- if nu(-, B_1) were itself dilation invariant -- then
    f(2) = 1 and the exponent collapses.  The exponent is nonzero PRECISELY
    BECAUSE there is no conformally invariant reference.  The refutation and this
    file are the same fact seen from two sides.

    ** What their assumption becomes

    "#states = product of #confDOF" is a PRODUCT of counts.  Products of ratios
    are sums of exponents, so DOF-independence survives as ADDITIVITY OF THE
    EXPONENT over independent subsystems, not as a product of counts.  That
    reading is prose; only the scaling law is proved here.

    ** Modelling boundary

    As in the companion files, the geometric inputs -- that dilating a ball of
    radius a by b gives one of radius ab, that a ball is a dilation of the unit
    ball -- are explicit HYPOTHESES of the theorems, not derived from
    differential geometry.  Only constant rescalings are used.  Monotonicity is
    not assumed, so the exponent is not here shown to be positive or to equal a
    dimension; that reading is prose too. *)

Require Import QArith.
Require Import Lqa.

Open Scope Q_scope.

(** ** Powers, self-contained *)

Fixpoint pow2 (n : nat) : Q :=
  match n with O => 1 | S k => 2 * pow2 k end.

Fixpoint qpow (x : Q) (n : nat) : Q :=
  match n with O => 1 | S k => x * qpow x k end.

Lemma pow2_pos : forall n, 0 < pow2 n.
Proof. induction n as [| k IH]; simpl; lra. Qed.

(** [qpow] is not a setoid morphism for [Qeq], so compatibility is proved
    explicitly rather than rewritten under. *)
Lemma qpow_compat : forall x y n, x == y -> qpow x n == qpow y n.
Proof.
  intros x y n H. induction n as [| k IH]; simpl.
  - reflexivity.
  - rewrite IH, H. reflexivity.
Qed.

Lemma qpow_one : forall n, qpow 1 n == 1.
Proof.
  induction n as [| k IH]; simpl; [reflexivity | rewrite IH; ring].
Qed.

(** ** A relative count is one at every region *)

Theorem self_ratio_is_one :
  forall (Region : Type) (nu : Region -> Region -> Q),
    (forall U V W, nu U W == nu U V * nu V W) ->
    (forall U V, ~ (nu U V == 0)) ->
    forall U, nu U U == 1.
Proof.
  intros Region nu Hchain Hnz U.
  assert (H := Hchain U U U).
  apply (proj1 (Qmult_inj_l (nu U U) 1 (nu U U) (Hnz U U))).
  rewrite <- H. ring.
Qed.

(** ** Ratios of balls see only the ratio of radii *)

Theorem ratio_sees_only_the_scale_ratio :
  forall (Region : Type)
         (nu : Region -> Region -> Q)
         (dil : Q -> Region -> Region)
         (ball : Q -> Region),
    (forall c U V, 0 < c -> nu (dil c U) (dil c V) == nu U V) ->
    (forall a b, 0 < a -> 0 < b -> ball (a * b) = dil b (ball a)) ->
    forall a b c, 0 < a -> 0 < b -> 0 < c ->
      nu (ball (a * c)) (ball (b * c)) == nu (ball a) (ball b).
Proof.
  intros Region nu dil ball Hdil Hmul a b c Ha Hb Hc.
  rewrite (Hmul a c Ha Hc), (Hmul b c Hb Hc).
  apply Hdil. exact Hc.
Qed.

(** ** THE SCALING LAW *)

(** [f t = nu (ball t) (ball 1)] is multiplicative. *)
Theorem scale_factor_is_multiplicative :
  forall (Region : Type)
         (nu : Region -> Region -> Q)
         (dil : Q -> Region -> Region)
         (ball : Q -> Region),
    (forall U V W, nu U W == nu U V * nu V W) ->
    (forall c U V, 0 < c -> nu (dil c U) (dil c V) == nu U V) ->
    (forall a b, 0 < a -> 0 < b -> ball (a * b) = dil b (ball a)) ->
    (forall b, 0 < b -> ball b = dil b (ball 1)) ->
    forall a b, 0 < a -> 0 < b ->
      nu (ball (a * b)) (ball 1)
      == nu (ball a) (ball 1) * nu (ball b) (ball 1).
Proof.
  intros Region nu dil ball Hchain Hdil Hmul Hunit a b Ha Hb.
  assert (E : nu (ball (a * b)) (ball b) == nu (ball a) (ball 1)).
  { rewrite (Hmul a b Ha Hb), (Hunit b Hb). apply Hdil. exact Hb. }
  rewrite (Hchain (ball (a * b)) (ball b) (ball 1)).
  rewrite E. reflexivity.
Qed.

(** The whole family is generated by a single number. *)
Theorem generated_by_a_single_number :
  forall (Region : Type)
         (nu : Region -> Region -> Q)
         (dil : Q -> Region -> Region)
         (ball : Q -> Region),
    (forall U V W, nu U W == nu U V * nu V W) ->
    (forall U V, ~ (nu U V == 0)) ->
    (forall c U V, 0 < c -> nu (dil c U) (dil c V) == nu U V) ->
    (forall a b, 0 < a -> 0 < b -> ball (a * b) = dil b (ball a)) ->
    (forall b, 0 < b -> ball b = dil b (ball 1)) ->
    forall n,
      nu (ball (pow2 n)) (ball 1) == qpow (nu (ball 2) (ball 1)) n.
Proof.
  intros Region nu dil ball Hchain Hnz Hdil Hmul Hunit n.
  induction n as [| k IH].
  - simpl. apply (self_ratio_is_one Region nu Hchain Hnz).
  - simpl.
    rewrite <- IH.
    apply (scale_factor_is_multiplicative Region nu dil ball
             Hchain Hdil Hmul Hunit 2 (pow2 k)).
    + lra.
    + apply pow2_pos.
Qed.

(** ** The refutation, seen from the other side *)

(** If some region could serve as an absolute reference -- if [nu(-, ball 1)]
    were itself dilation invariant, which is exactly what having an absolute
    count would mean -- then the generating number is one and the exponent
    collapses.  The exponent is nonzero precisely because no conformally
    invariant reference exists. *)
Theorem a_reference_region_forces_a_trivial_exponent :
  forall (Region : Type)
         (nu : Region -> Region -> Q)
         (dil : Q -> Region -> Region)
         (ball : Q -> Region),
    (forall U V W, nu U W == nu U V * nu V W) ->
    (forall U V, ~ (nu U V == 0)) ->
    (forall b, 0 < b -> ball b = dil b (ball 1)) ->
    (* the reference assumption: an absolute count exists *)
    (forall c U, 0 < c -> nu (dil c U) (ball 1) == nu U (ball 1)) ->
    nu (ball 2) (ball 1) == 1.
Proof.
  intros Region nu dil ball Hchain Hnz Hunit Href.
  rewrite (Hunit 2 ltac:(lra)).
  rewrite (Href 2 (ball 1) ltac:(lra)).
  apply (self_ratio_is_one Region nu Hchain Hnz).
Qed.

(** And then every dyadic scale ties, which is the refutation's conclusion
    recovered inside the relational language. *)
Corollary trivial_exponent_makes_every_dyadic_scale_tie :
  forall (Region : Type)
         (nu : Region -> Region -> Q)
         (dil : Q -> Region -> Region)
         (ball : Q -> Region),
    (forall U V W, nu U W == nu U V * nu V W) ->
    (forall U V, ~ (nu U V == 0)) ->
    (forall c U V, 0 < c -> nu (dil c U) (dil c V) == nu U V) ->
    (forall a b, 0 < a -> 0 < b -> ball (a * b) = dil b (ball a)) ->
    (forall b, 0 < b -> ball b = dil b (ball 1)) ->
    (forall c U, 0 < c -> nu (dil c U) (ball 1) == nu U (ball 1)) ->
    forall n, nu (ball (pow2 n)) (ball 1) == 1.
Proof.
  intros Region nu dil ball Hchain Hnz Hdil Hmul Hunit Href n.
  transitivity (qpow (nu (ball 2) (ball 1)) n).
  - apply (generated_by_a_single_number Region nu dil ball
             Hchain Hnz Hdil Hmul Hunit n).
  - transitivity (qpow 1 n).
    + apply qpow_compat.
      apply (a_reference_region_forces_a_trivial_exponent Region nu dil ball
               Hchain Hnz Hunit Href).
    + apply qpow_one.
Qed.

(** ** The honest ledger *)

Print Assumptions pow2_pos.
Print Assumptions qpow_compat.
Print Assumptions qpow_one.
Print Assumptions self_ratio_is_one.
Print Assumptions ratio_sees_only_the_scale_ratio.
Print Assumptions scale_factor_is_multiplicative.
Print Assumptions generated_by_a_single_number.
Print Assumptions a_reference_region_forces_a_trivial_exponent.
Print Assumptions trivial_exponent_makes_every_dyadic_scale_tie.
