#!/usr/bin/env bash
# run.sh — the reverse-physics torus GATE.
#
# Eighteen developments, all zero-axiom, in dependency order.  The first four are the
# torus chain, the next four an INDEPENDENT stochastic carrier, and the last two
# engage Carcassi-Aidala directly: a BRIDGE restating the torus results in their
# notation, and a PARITY OBSTRUCTION on their degree-of-freedom counting.
#
#   ReversePhysicsTorus.v          the TOPOLOGICAL step: at every mode with a
#                                  nonzero frequency closed = exact, so the
#                                  symplectic-to-Hamiltonian gap is carried
#                                  entirely by the zero mode -- for every
#                                  truncation, with no induction.
#   ReversePhysicsTorusChain.v     the REST of the chain: Hamiltonian <=
#                                  symplectic <= marginal <= volume-preserving at
#                                  every mode, both remaining inclusions proved
#                                  STRICT, and the marginal condition localised
#                                  as exactly the intra-DOF content.
#   ReversePhysicsTorusReversal.v  the REVERSAL: the law is EQUIVALENT to three
#                                  independent assumptions, each derived FROM the
#                                  law, with an independence witness per
#                                  assumption.
#   ReversePhysicsTorusSplit.v     WHY the third assumption is not physical: the
#                                  split-dependence of the first cancels against
#                                  it exactly, so the decomposition into a
#                                  "physical" and a "geometric" part is NOT
#                                  canonical.  Also corrects the earlier
#                                  split-dependence theorem, which had used an
#                                  ISOTROPIC pairing.
#   ReversePhysicsStochastic.v     a DIFFERENT carrier -- finite-state stochastic
#                                  evolution -- where determinism and
#                                  reversibility can actually FAIL, so the two
#                                  assumptions the stream had only ever consumed
#                                  can finally be tested.  Result: reversibility
#                                  is NOT independent; it is exactly determinism
#                                  plus information conservation.
#   ReversePhysicsSecondLaw.v      a SECOND LAW on that carrier: information
#                                  conservation entails that disorder never
#                                  decreases.  Exactly rational -- purity
#                                  (Renyi-2) rather than Shannon entropy, so no
#                                  logarithms.
#   ReversePhysicsEntropyEquality.v  the EQUALITY case, forward half: reversible
#                                  evolution preserves purity EXACTLY, and
#                                  spreading over states of differing probability
#                                  strictly produces entropy.
#   ReversePhysicsEntropyConverse.v  the CONVERSE, and so the BICONDITIONAL:
#                                  preserving purity on one distribution with
#                                  distinct entries forces reversibility.  The
#                                  loop between the stream's two laws is closed.
#   ReversePhysicsAOPBridge.v      the BRIDGE: our omega is proved to be their
#                                  J (x) I_n, their two tensor factors are shown
#                                  to be bookkeeping rather than physics, and
#                                  their open GR conjecture is shown to need a
#                                  topological term the finite-dimensional
#                                  theorem does not have.
#   ReversePhysicsConformalCount.v  the FOURTH DESIDERATUM: adding conformal
#                                  invariance to their DOF-counting trilemma
#                                  excludes the density branch in ODD dimension
#                                  by parity.  A Cauchy surface is
#                                  three-dimensional.
#   ReversePhysicsNoConformalCount.v  the LAST BRANCH: on flat space a dilation
#                                  is conformal, so every ball has the count of
#                                  the unit ball.  Additivity is never used, so
#                                  the non-additive resolution does not escape
#                                  either.  All three branches are closed.
#   ReversePhysicsRelationalCount.v  WHAT REPLACES IT: a RELATIVE count survives
#                                  the dilation argument, is multiplicative, and
#                                  is generated by a single number -- one
#                                  scaling exponent, not a function on regions.
#   ReversePhysicsExponentAdditivity.v  and DOF-INDEPENDENCE becomes ADDITIVITY
#                                  OF THAT EXPONENT.  Stated without logarithms:
#                                  2^(dA+dB) = 2^dA * 2^dB, so the multiplicative
#                                  statement IS the additive one, exactly.
#   CoprimeHierarchyOrderLaw.v     the COPRIME-RATIO ORDER LAW, proved: a word at
#                                  order n has degree exactly n+2, and at degree
#                                  p+q coprimality leaves only the conversion
#                                  kernel, so the obstruction can appear only at
#                                  order p+q-2.  Closes the "no ansatz proof
#                                  exists" line on sf:program/conjecture/
#                                  coprime-ratio-hierarchy for the order clause.
#   CoprimeHierarchyKernelParity.v which kernel appears: an involution fixing the
#                                  vertex forces symmetric iff q even.
#   WeylActionClassification.v     REVERSE PHYSICS ON THE SUBJECT ITSELF: the
#                                  conformal-gravity action is EQUIVALENT to
#                                  five assumptions, modulo topological terms,
#                                  and each is independent.  The derivative
#                                  order is DERIVED, not assumed.
#   WeylParityAndTopology.v        and the sharper half: parity invariance is
#                                  INDEPENDENT on the space of actions and
#                                  REDUNDANT on the space of field equations.
#                                  The gap is a gravitational theta-angle, and
#                                  W_+^2, W_-^2 -- the programme's own certified
#                                  residual classes -- are its eigenbasis.
#   CoprimeHierarchyChargeBound.v  an AUDIT of the physics gloss on those two:
#                                  J = p n1 + q n2 has the resonant sector as its
#                                  exact commutant, so EVERY possible obstruction
#                                  conserves it -- and J is positive, so it BOUNDS
#                                  both occupations.  The obstruction is the
#                                  benign conversion channel, not the ghost's
#                                  escape route.  Pair creation, which does run
#                                  away, is proved to break J.
#
# Print Assumptions must say "Closed under the global context" for every
# theorem, and coqchk must list NO axioms.
#
# Gates: [1] coqc  [2] source hygiene (no Axiom/Parameter/Admitted/admit)
#        [3] Print Assumptions all closed  [4] coqchk + empty axiom section
#        [5] fail-closed negative controls (FALSE claims must be REJECTED)
#
#   cd weyl-gravity/rocq && ./run.sh
set -u

HERE="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
cd "$HERE"

MODULES=(ReversePhysicsTorus ReversePhysicsTorusChain ReversePhysicsTorusReversal ReversePhysicsTorusSplit ReversePhysicsStochastic ReversePhysicsSecondLaw ReversePhysicsEntropyEquality ReversePhysicsEntropyConverse ReversePhysicsAOPBridge ReversePhysicsConformalCount ReversePhysicsNoConformalCount ReversePhysicsRelationalCount ReversePhysicsExponentAdditivity CoprimeHierarchyOrderLaw CoprimeHierarchyKernelParity CoprimeHierarchyChargeBound WeylActionClassification WeylParityAndTopology)
pass=0
fail=0

echo "=== reverse-physics torus gate (Rocq) ==="
command -v coqc >/dev/null || { echo "coqc not found"; exit 1; }
coqc --version | head -1

echo; echo "[1] coqc (in dependency order)"
: > /tmp/rp_coqc.log
for m in "${MODULES[@]}"; do
  if coqc "$m.v" >>/tmp/rp_coqc.log 2>&1; then
    echo "  coqc $m.v OK"; pass=$((pass+1))
  else
    echo "  coqc $m.v FAILED:"; sed -n '1,40p' /tmp/rp_coqc.log; fail=$((fail+1))
  fi
done

echo; echo "[2] source hygiene"
hyg=0
for m in "${MODULES[@]}"; do
  if command grep -nE '^[[:space:]]*(Axiom|Parameter|Hypothesis|Conjecture|Admitted)\b|\badmit\b' "$m.v"; then
    echo "  $m.v declares an assumption or admits — REJECT"; hyg=1
  fi
done
if [ "$hyg" -eq 0 ]; then
  echo "  no Axiom/Parameter/Hypothesis/Conjecture/Admitted/admit in any module"; pass=$((pass+1))
else
  fail=$((fail+1))
fi

echo; echo "[3] Print Assumptions all closed"
want_n=0
for m in "${MODULES[@]}"; do
  want_n=$((want_n + $(command grep -c "^Print Assumptions" "$m.v")))
done
closed_n=$(command grep -c "^Closed under the global context" /tmp/rp_coqc.log)
if [ "$want_n" -gt 0 ] && [ "$closed_n" -eq "$want_n" ]; then
  echo "  $closed_n/$want_n closed under the global context"; pass=$((pass+1))
else
  echo "  NOT all closed ($closed_n/$want_n) — REJECT"; fail=$((fail+1))
fi

echo; echo "[4] coqchk (standalone kernel) + empty axiom section"
if coqchk -silent -o "${MODULES[@]}" >/tmp/rp_chk.log 2>&1; then
  echo "  coqchk OK (${MODULES[*]})"; pass=$((pass+1))
else
  echo "  coqchk FAILED:"; cat /tmp/rp_chk.log; fail=$((fail+1))
fi
if command grep -q '^\* Axioms: <none>' /tmp/rp_chk.log; then
  echo "  coqchk axiom section: <none> (fully closed development)"; pass=$((pass+1))
else
  echo "  coqchk REPORTS AXIOMS — REJECT:"; sed -n '/Axioms/,/^$/p' /tmp/rp_chk.log; fail=$((fail+1))
fi

echo; echo "[5] fail-closed negative controls"

# (a) The zero mode DOES carry classes, so 'closed implies exact' is FALSE there.
cat > _neg_a.v <<'NEG'
Require Import ReversePhysicsTorus.
(* FALSE on purpose: uniform translation is closed but NOT exact at the zero
   mode. A gate that accepts this proves nothing. *)
Theorem bogus_translation_is_exact :
  forall k, zero_mode k -> exact_form k (unit_form i0) zero_form.
Proof.
  intros k Hz.
  apply (proj2 (exact_at_zero_mode_iff_vanishing k (unit_form i0) zero_form Hz)).
  intros j. destruct j; split; reflexivity.
Qed.
NEG

# (b) The chain must not collapse: marginal does NOT imply symplectic.
cat > _neg_b.v <<'NEG'
Require Import ReversePhysicsTorus.
Require Import ReversePhysicsTorusChain.
(* FALSE on purpose: the shear witness is marginal and not symplectic, so a
   proof that marginal implies symplectic would collapse the chain. *)
Theorem bogus_marginal_implies_symplectic :
  forall k a b, marginal k a b -> symplectic k a b.
Proof.
  intros k a b Hm. exact Hm.
Qed.
NEG


# (c) The law is strictly stronger than A1 alone: a proof that marginal
#     information conservation suffices would contradict A2/A3 independence.
cat > _neg_c.v <<'NEG'
Require Import ReversePhysicsTorus.
Require Import ReversePhysicsTorusChain.
Require Import ReversePhysicsTorusReversal.
(* FALSE on purpose: dropping A2 and A3 must not still give the law. *)
Theorem bogus_marginal_suffices :
  forall k a b, marginal k a b -> hamiltonian k a b.
Proof.
  intros k a b Hm. exact Hm.
Qed.
NEG


# (d) marginal is NOT invariant across admissible symplectic splits.
cat > _neg_d.v <<'NEG'
Require Import ReversePhysicsTorus.
Require Import ReversePhysicsTorusChain.
Require Import ReversePhysicsTorusReversal.
Require Import ReversePhysicsTorusSplit.
(* FALSE on purpose: if marginal were split-invariant the whole point of
   ReversePhysicsTorusSplit.v would collapse. *)
Theorem bogus_marginal_is_split_invariant :
  forall k a b, marginal k a b -> marginal_rot k a b.
Proof.
  intros k a b H. exact H.
Qed.
NEG


# (e) Determinism alone must NOT give reversibility: the collapse map is
#     deterministic and destroys information.
cat > _neg_e.v <<'NEG'
Require Import ReversePhysicsStochastic.
(* FALSE on purpose: if determinism sufficed, the collapse witness would be
   contradictory and the stochastic result vacuous. *)
Theorem bogus_determinism_suffices :
  forall M, deterministic M -> reversible M.
Proof.
  intros M H. exact H.
Qed.
NEG


# (f) Disorder is not merely conserved -- the mixer strictly increases it.
cat > _neg_f.v <<'NEG'
Require Import QArith.
Require Import ReversePhysicsStochastic.
Require Import ReversePhysicsSecondLaw.
Open Scope Q_scope.
(* FALSE on purpose: a doubly stochastic evolution can strictly DECREASE purity,
   so claiming conservation would make the second law vacuous. *)
Theorem bogus_purity_is_conserved :
  forall M p, nonneg M -> (forall j, col_sum M j == 1) -> conserves_information M ->
    purity (evolve M p) == purity p.
Proof.
  intros. reflexivity.
Qed.
NEG


# (g) Preserving purity must NOT be automatic for doubly stochastic maps.
cat > _neg_g.v <<'NEG'
Require Import QArith.
Require Import ReversePhysicsStochastic.
Require Import ReversePhysicsSecondLaw.
Require Import ReversePhysicsEntropyEquality.
Open Scope Q_scope.
(* FALSE on purpose: the mixer is doubly stochastic and strictly loses purity,
   so preservation cannot follow from double stochasticity alone. *)
Theorem bogus_all_doubly_stochastic_preserve_purity :
  forall M p, conserves_information M -> purity (evolve M p) == purity p.
Proof.
  intros M p H. reflexivity.
Qed.
NEG


# (h) The test distribution must have DISTINCT entries.  Every doubly stochastic
#     map preserves the uniform distribution, so a uniform test detects nothing.
cat > _neg_h.v <<'NEG'
Require Import QArith.
Require Import ReversePhysicsStochastic.
Require Import ReversePhysicsSecondLaw.
Require Import ReversePhysicsEntropyEquality.
Require Import ReversePhysicsEntropyConverse.
Open Scope Q_scope.
Definition p_unif : St -> Q := fun _ => 1 # 4.
(* FALSE on purpose: the mixer preserves the uniform distribution exactly and is
   not reversible, so a uniform test distribution proves nothing.  This is why
   p_test has pairwise distinct entries. *)
Theorem bogus_uniform_test_suffices :
  forall M, (forall a b, 0 <= M a b) -> (forall j, col_sum M j == 1) ->
    conserves_information M ->
    purity (evolve M p_unif) == purity p_unif -> reversible M.
Proof.
  intros M Hnn Hcol Hrow Heq. exact Heq.
Qed.
NEG


# (i) Preserving omega must NOT give a global Hamiltonian on a state space with
#     b_1 =/= 0 -- this is exactly the term the AoP GR conjecture would need.
cat > _neg_i.v <<'NEG'
Require Import ReversePhysicsTorus.
Require Import ReversePhysicsTorusChain.
Require Import ReversePhysicsAOPBridge.
(* FALSE on purpose: uniform translation on T^4 preserves omega and admits no
   global Hamiltonian.  If this compiled, finding 3 of the bridge would be
   vacuous. *)
Theorem bogus_omega_preservation_suffices :
  forall k a b, symplectic k a b -> hamiltonian k a b.
Proof.
  intros k a b H. exact H.
Qed.
NEG


# (j) There is no conformally invariant DOF density on a 3-manifold.
cat > _neg_j.v <<'NEG'
Require Import ZArith.
Require Import ReversePhysicsConformalCount.
(* FALSE on purpose: the parity obstruction says no curvature scalar balances
   the volume weight in odd dimension.  If this compiled, the fourth
   desideratum would be vacuous. *)
Theorem bogus_conformal_density_in_three :
  exists c, is_conformal_density 3 c.
Proof.
  exists weyl_squared_weights. reflexivity.
Qed.
NEG


# (k) A conformally invariant count cannot grow with the radius.
cat > _neg_k.v <<'NEG'
Require Import QArith.
Require Import ReversePhysicsNoConformalCount.
Open Scope Q_scope.
(* FALSE on purpose: no_informative_conformal_count says all balls tie.  If a
   count could grow with radius the refutation would be vacuous. *)
Theorem bogus_count_grows_with_radius :
  forall (Metric Region : Type)
         (mu : Metric -> Region -> Q)
         (scale : Q -> Metric -> Metric)
         (dil : Q -> Region -> Region)
         (flat : Metric)
         (ball : Q -> Region),
    (forall lam U, 0 < lam -> mu flat (dil lam U) == mu (scale lam flat) U) ->
    (forall lam m U, 0 < lam -> mu (scale lam m) U == mu m U) ->
    (forall r, 0 < r -> ball r = dil r (ball 1)) ->
    mu flat (ball 1) < mu flat (ball 2).
Proof.
  intros. reflexivity.
Qed.
NEG


# (l) The relative count must NOT be trivial without a reference region -- if it
#     were, the relational answer would be empty too.
cat > _neg_l.v <<'NEG'
Require Import QArith.
Require Import ReversePhysicsRelationalCount.
Open Scope Q_scope.
(* FALSE on purpose: the exponent collapses ONLY under the reference
   assumption.  Without it the relative count is genuinely non-degenerate. *)
Theorem bogus_relative_count_is_always_trivial :
  forall (Region : Type)
         (nu : Region -> Region -> Q)
         (dil : Q -> Region -> Region)
         (ball : Q -> Region),
    (forall U V W, nu U W == nu U V * nu V W) ->
    (forall U V, ~ (nu U V == 0)) ->
    (forall c U V, 0 < c -> nu (dil c U) (dil c V) == nu U V) ->
    (forall a b, 0 < a -> 0 < b -> ball (a * b) = dil b (ball a)) ->
    (forall b, 0 < b -> ball b = dil b (ball 1)) ->
    nu (ball 2) (ball 1) == 1.
Proof.
  intros. reflexivity.
Qed.
NEG


# (m) The composite exponent must be the SUM, not either summand.
cat > _neg_m.v <<'NEG'
Require Import QArith.
Require Import ReversePhysicsExponentAdditivity.
Open Scope Q_scope.
(* FALSE on purpose: if the composite carried only one subsystem's exponent,
   independence would not add anything and the result would be vacuous. *)
Theorem bogus_composite_keeps_one_exponent :
  forall (gA gB gAB : Q) (dA dB : Z),
    has_exponent gA dA -> has_exponent gB dB -> gAB == gA * gB ->
    has_exponent gAB dA.
Proof.
  intros gA gB gAB dA dB HA HB Hmul. assumption.
Qed.
NEG


# (n) The obstruction must NOT be able to appear below the critical order.
cat > _neg_n.v <<'NEG'
Require Import ZArith.
Require Import CoprimeHierarchyOrderLaw.
Open Scope Z_scope.
(* FALSE on purpose: the degree count forbids the kernel below order p+q-2.
   If this compiled the selection rule would be vacuous. *)
Theorem bogus_kernel_below_critical_order :
  word_degree 2 = total_degree (kernel 5 3).
Proof.
  reflexivity.
Qed.
NEG

# (o) The two kernel combinations must not BOTH survive.
cat > _neg_o.v <<'NEG'
Require Import Bool Arith.
Require Import CoprimeHierarchyKernelParity.
(* FALSE on purpose: exactly one combination can carry the obstruction. *)
Theorem bogus_both_kernels_survive :
  forall p q,
    symmetric_kernel_parity p = antisymmetric_kernel_parity p.
Proof.
  intros p q. reflexivity.
Qed.
NEG

# (p) The conversion kernel and pair creation must NOT carry the same charge --
#     that distinction is the entire content of the audit.
cat > _neg_p.v <<'NEG'
Require Import ZArith.
Require Import CoprimeHierarchyOrderLaw.
Require Import CoprimeHierarchyChargeBound.
Open Scope Z_scope.
(* FALSE on purpose: pair creation has charge (+q,+p) and breaks J.  If it
   conserved J too, the contrast between a conversion channel and an
   instability would collapse and the audit would be vacuous. *)
Theorem bogus_pair_creation_conserves_charge :
  forall p q, conserves_charge p q (pair_creation p q).
Proof.
  intros p q. apply kernel_conserves_charge.
Qed.
NEG

# (q) A positive charge is what does the bounding -- an indefinite one must not.
cat > _neg_q.v <<'NEG'
Require Import QArith.
Require Import CoprimeHierarchyChargeBound.
Open Scope Q_scope.
(* FALSE on purpose: the level set of p n1 - q n2 is an unbounded ray of
   physical states.  If the indefinite charge bounded n1 as well, positivity of
   J would be doing no work. *)
Theorem bogus_indefinite_charge_bounds :
  forall p q n1 n2 J : Q,
    0 < p -> 0 < q -> 0 <= n1 -> 0 <= n2 ->
    p * n1 - q * n2 == J ->
    p * n1 <= J.
Proof.
  intros p q n1 n2 J Hp Hq H1 H2 Heq. lra.
Qed.
NEG

# (r) R^2 must NOT be Weyl invariant -- if it were, RP-WEYL would cut nothing
#     and the classification would be vacuous.
cat > _neg_r.v <<'NEG'
Require Import QArith.
Require Import WeylActionClassification.
Open Scope Q_scope.
(* FALSE on purpose: the anomaly of R^2 is 3, not 0.  A gate that accepted this
   would be accepting a three-dimensional answer as one-dimensional. *)
Theorem bogus_r_sq_is_weyl_invariant : anomaly r_sq == 0.
Proof. apply weyl_sq_is_invariant. Qed.
NEG

# (s) The Euler density must NOT be a multiple of the Weyl square -- otherwise
#     the topological quotient removes nothing and cannot be load-bearing.
cat > _neg_s.v <<'NEG'
Require Import QArith.
Require Import WeylActionClassification.
Open Scope Q_scope.
(* FALSE on purpose: E4 and C^2 are independent.  If E4 were a multiple of C^2
   the "modulo topological terms" clause would be empty. *)
Theorem bogus_euler_is_a_multiple_of_weyl_sq : qeq euler (qscale 1 weyl_sq).
Proof. unfold qeq, qscale, euler, weyl_sq. cbn. repeat split; reflexivity. Qed.
NEG

# (t) The Weyl square must NOT be topological -- otherwise conformal gravity has
#     no field equations at all and every theorem about it is empty.
cat > _neg_t.v <<'NEG'
Require Import QArith.
Require Import WeylParityAndTopology.
Open Scope Q_scope.
(* FALSE on purpose: weyl_sq_is_not_topological.  If C^2 were topological the
   entire parity result would be about an empty theory. *)
Theorem bogus_weyl_sq_is_topological : topological weyl_sq4.
Proof. exists 1, 0. unfold q4eq, q4add, q4scale, weyl_sq4, euler4, pont. cbn.
  repeat split; reflexivity. Qed.
NEG

# (u) W_+^2 must NOT lie in the parity-even span -- otherwise parity invariance
#     is vacuous as an assumption on actions.
cat > _neg_u.v <<'NEG'
Require Import QArith.
Require Import WeylParityAndTopology.
Open Scope Q_scope.
(* FALSE on purpose: W_+^2 has a nonzero Pontryagin component.  If it were
   parity-even, "parity is independent on actions" would say nothing. *)
Theorem bogus_w_plus_is_parity_even :
  q4eq w_plus (q4add (q4scale (1#2) weyl_sq4) (q4scale 0 euler4)).
Proof. unfold q4eq, q4add, q4scale, w_plus, weyl_sq4, euler4. cbn.
  repeat split; reflexivity. Qed.
NEG

neg_ok=0
for n in _neg_a _neg_b _neg_c _neg_d _neg_e _neg_f _neg_g _neg_h _neg_i _neg_j _neg_k _neg_l _neg_m _neg_n _neg_o _neg_p _neg_q _neg_r _neg_s _neg_t _neg_u; do
  if coqc "$n.v" >/tmp/rp_neg.log 2>&1; then
    echo "  $n: FALSE claim was ACCEPTED — REJECT"; neg_ok=1
  else
    echo "  $n: false claim -> coqc REJECTS (fail-closed)"
  fi
done
if [ "$neg_ok" -eq 0 ]; then pass=$((pass+1)); else fail=$((fail+1)); fi
rm -f _neg_[a-u].v _neg_[a-u].vo _neg_[a-u].vok _neg_[a-u].vos _neg_[a-u].glob ._neg_[a-u].aux

echo
if [ "$fail" -eq 0 ]; then
  echo "RESULT: $pass green (0 red)"
  echo "GATE: PASS"
  exit 0
else
  echo "RESULT: $pass green ($fail red)"
  echo "GATE: FAIL"
  exit 1
fi
