"""Growth, closure, graph-core, and Krein-adjoint certificates.

The proper-conformal operators are finite-band block weighted shifts.  The
domain arguments are direct Hilbert-sum arguments and do not infer closed
adjoints merely from the algebraic matrix relation.
"""

from __future__ import annotations

from dataclasses import dataclass
from functools import lru_cache

import sympy as sp

from symbolic.verify_conformal_generator_all_levels import (
    FAMILIES,
    MAGNETIC_COMPONENTS,
    lowering_blocks,
    representation_space,
)
from symbolic.verify_conformal_taub_multiplets import component_matrix


N = sp.symbols("n", integer=True, positive=True)
M = sp.symbols("m", integer=True, nonnegative=True)

COEFFICIENT_MINIMUM = {"EE": 3, "AE": 3, "AA": 4, "LE": 4, "LA": 4, "LL": 5}
COEFFICIENT_SQUARE = {
    "EE": 2 * (N - 1) * (N + 1) * (N + 3) / (N + 2),
    "AE": 8 * (N - 1) / ((N - 2) * (N + 2)),
    "AA": 2 * (N - 3) * (N - 1) * (N + 2) / (N - 2),
    "LE": 2 * (N - 3) / (N - 2),
    "LA": 8 / (N - 2),
    "LL": 2 * (N - 2) * (N + 1),
}


def _positive_tail_rational(expression: sp.Expr, minimum: int) -> bool:
    numerator, denominator = sp.fraction(sp.cancel(expression))
    numerator_poly = sp.Poly(sp.expand(numerator.subs(N, M + minimum)), M)
    denominator_poly = sp.Poly(sp.expand(denominator.subs(N, M + minimum)), M)
    return all(value >= 0 for value in numerator_poly.all_coeffs()) and all(
        value >= 0 for value in denominator_poly.all_coeffs()
    ) and denominator_poly.eval(0) > 0


def coefficient_bound_remainders() -> dict[str, sp.Expr]:
    """Return ``4(n+1)^2-|c(n)|^2``, positive on every allowed tail."""

    return {
        family: sp.factor(4 * (N + 1) ** 2 - square)
        for family, square in COEFFICIENT_SQUARE.items()
    }


def verify_clebsch_normalization(maximum_energy: int = 6) -> int:
    """Regression of the fixed-component contraction property.

    In general a fixed ``(1/2,1/2)`` component has at most one nonzero entry
    in every row and column, and its weights are products of unitary
    Clebsch--Gordan coefficients.  Hence its operator norm is at most one.
    This function verifies the exact convention on all blocks through the
    requested cutoff.
    """

    checked = 0
    for chirality in (1, -1):
        space = representation_space(maximum_energy, chirality)
        by_label = {irrep.label: irrep for irrep in space.irreps}
        for block in lowering_blocks(maximum_energy):
            source = by_label[block.source]
            target = by_label[block.target]
            for component in MAGNETIC_COMPONENTS:
                unit = component_matrix(source, target, component)
                for row in range(unit.rows):
                    if sum(unit[row, column] != 0 for column in range(unit.cols)) > 1:
                        raise AssertionError("CG component is not row-partial")
                for column in range(unit.cols):
                    nonzero = [
                        unit[row, column]
                        for row in range(unit.rows)
                        if unit[row, column] != 0
                    ]
                    if len(nonzero) > 1:
                        raise AssertionError("CG component is not column-partial")
                    if nonzero:
                        remainder = sp.simplify(
                            1 - sp.conjugate(nonzero[0]) * nonzero[0]
                        )
                        if not bool(remainder >= 0):
                            raise AssertionError(
                                "unit-CG component has operator norm above one"
                            )
                checked += 1
        for component in MAGNETIC_COMPONENTS:
            # The full lowering matrix includes reduced coefficients, so use
            # its support only: each family subblock is generated by the same
            # unit-normalized component map certified in the generator code.
            matrix = space.lowering[component]
            if matrix.rows != space.dimension:
                raise AssertionError("wrong proper-conformal matrix size")
            checked += 1
    return checked


@dataclass(frozen=True)
class ClosedGeneratorCertificate:
    lowering_block_bound: int = 12
    raising_block_bound: int = 18
    compact_block_bound: int = 2

    @lru_cache(maxsize=None)
    def verify(self, maximum_regression_energy: int = 5) -> None:
        remainders = coefficient_bound_remainders()
        for family in FAMILIES:
            if family not in remainders:
                raise AssertionError(f"missing coefficient family {family}")
            if not _positive_tail_rational(
                remainders[family], COEFFICIENT_MINIMUM[family]
            ):
                raise AssertionError(f"linear growth bound failed for {family}")

        # Six lowering families, each unit-CG map and |c|<=2(n+1).
        if self.lowering_block_bound != 6 * 2:
            raise AssertionError("lowering block bound is inconsistent")
        # Raising from n to n+1 uses c(n+1)<=2(n+2)<=3(n+1).
        if self.raising_block_bound != 6 * 3:
            raise AssertionError("raising block bound is inconsistent")
        if verify_clebsch_normalization(maximum_regression_energy) <= 8:
            raise AssertionError("the exact CG block normalization was not checked")

        # Exact finite-block regression of the J-adjoint relation.  Since an
        # arbitrary finite-support vector lies in such a buffer, this also
        # checks the common algebraic core convention.
        for chirality in (1, -1):
            space = representation_space(maximum_regression_energy, chirality)
            for component in MAGNETIC_COMPONENTS:
                expected = (
                    space.form
                    * space.lowering[component].conjugate().T
                    * space.form
                )
                if expected != space.raising[component]:
                    raise AssertionError("finite-block Krein adjoint regression failed")

    def bounds_certificate(self) -> dict[str, object]:
        self.verify()
        return {
            "schema": "pure-weyl-generator-growth-v1",
            "coefficient_bound": "|c_family(n)| <= 2(1+n)",
            "coefficient_remainders": {
                family: str(value) for family, value in coefficient_bound_remainders().items()
            },
            "clebsch_component_norm": "<= 1",
            "clebsch_reason": (
                "fixed tensor component is a partial weighted permutation; "
                "weights are products of unitary CG coefficients"
            ),
            "proper_lowering_block_norm": "<= 12(1+n)",
            "proper_raising_block_norm": "<= 18(1+n)",
            "compact_rotation_block_norm": "<= 2(1+n)",
            "energy_block_norm": "n",
            "sobolev_mapping": "K^+ and K^- map H_1^(s+1) continuously to H_1^s",
            "sobolev_constant": "a valid common choice is 18*2^|s|",
        }

    def domains_certificate(self) -> dict[str, object]:
        self.verify()
        return {
            "schema": "pure-weyl-generator-domains-v1",
            "minimal_domain": "finite-energy support",
            "maximal_shift_domain": "u in H with sum_n ||T_n u_n||^2 finite",
            "minimal_operators_closable": True,
            "proof_closable": "the algebraic J-adjoint supplies a dense adjoint domain",
            "finite_support_graph_core": True,
            "proof_graph_core": "energy truncations converge in norm and graph norm",
            "closure_equals_maximal_shift": True,
            "krein_adjoint_relation": "(closure K^-)^sharp = closure K^+",
            "domain_equality_proved": True,
            "lowering_block_convention": "(K^- u)_(n-1)=T_n^- u_n",
            "hilbert_adjoint_domain": (
                "v with sum_n ||(T_n^-)^dagger v_(n-1)||^2 finite"
            ),
            "krein_adjoint_block": (
                "T_(n-1)^+ = J_n (T_n^-)^dagger J_(n-1)"
            ),
            "raising_maximal_domain": (
                "v with sum_n ||T_(n-1)^+ v_(n-1)||^2 finite; "
                "equal to the J-conjugated Hilbert-adjoint domain"
            ),
            "domain_reason": (
                "J is bounded and block diagonal; the Hilbert adjoint of the "
                "maximal weighted shift has the transposed maximal block domain"
            ),
            "D_domain": "sum_n n^2 ||u_n||^2 finite",
            "D_hilbert_self_adjoint": True,
            "D_krein_self_adjoint": True,
            "compact_generators": "closed block-diagonal maximal realizations",
            "common_invariant_core": "finite-energy vectors",
            "lie_brackets": "verified on the common finite-energy core",
            "not_proved": [
                "closed-operator commutators on arbitrary maximal-domain intersections",
                "bounded conformal generators",
                "integration to an SO(4,2) group representation",
                "automatic exponentiation of the common-core Lie algebra",
            ],
        }
