"""Ghost parity cannot be MANIFEST on a coincident double pole.

WHY THIS EXISTS.  The recommended next step for the ghost programme was: test
whether Bateman-Turok's ghost-parity involution survives on the gravitational
BRST complex, the cheap version being "does kappa commute with the BRST
differential s at linear order".  Scoping that test properly changes it.  The
binding requirement is not the BRST commutator.  It is one level earlier and
it is visible in 2x2 algebra.

THE COMPUTATION.  Take the general exchange-covariant two-field quadratic
Lagrangian -- the shape any O(1,1)-style embedding must reduce to:

    L  =  dOmega . dUpsilon  +  a Omega^2  +  b Upsilon^2

The exchange Omega <-> Upsilon is a symmetry of L if and only if a = b.  The
quadratic form and propagator are, exactly,

    M = [[2a, -k^2], [-k^2, 2b]],     det M = 4ab - k^4,
    <Omega Omega> = 2b / (4ab - k^4).

Three cases exhaust it:

    a = b = 0   exchange-symmetric   <OO> = 0            no double pole at all
    a = 0, b!=0 exchange BROKEN      <OO> = -2b/k^4      THE DOUBLE POLE
    a = b != 0  exchange-symmetric   poles at k^2 = +-2a  SPLIT, two simple

THE THEOREM.  Manifest exchange symmetry implies NO coincident double pole:
either the two-point function vanishes identically, or the poles separate.
Equivalently, a coincident double pole requires a != b, which breaks the
exchange.

WHAT THAT MEANS FOR BATEMAN-TUROK.  Their mechanism is not thereby refuted --
it is explained.  In their model the exchange is a symmetry of the ACTION
(dOmega.dUpsilon and Omega^2 Upsilon^2 are both exchange-symmetric; there is no
lone Omega^2 or Upsilon^2 term), and the asymmetric quadratic term that
produces the double pole is generated by the VACUUM: expanding
Omega = lambda^-1 + omega about <Omega> = lambda^-1 turns the symmetric quartic
(lambda^2/2) Omega^2 Upsilon^2 into (1/2) Upsilon^2 + ..., which is exactly the
b != 0, a = 0 row.  Integrating out Upsilon returns -(1/2)(box omega)^2.

So GHOST PARITY IS SPONTANEOUSLY BROKEN by the vacuum that reproduces the
fourth-order theory: <Omega> = lambda^-1 while <Upsilon> = 0, and the exchange
maps that vacuum to a different one.  This is presumably what "hidden" means in
their title.  It also lines up with their own caveat that the phi and
(Omega, Upsilon) path integrals are inequivalent, "the former integrates over
Omega > 0 whereas the latter integrates over all Omega", and with Paper 05's
regulated masses m_pm^2 = mu^2 +/- sqrt(eps g), which are SPLIT exactly when the
symmetry-breaking parameter eps is nonzero.

WHY THIS CHANGES THE TENSOR TEST, WHICH IS THE POINT.  The test that was queued
-- "does kappa commute with s" -- is the wrong necessary condition, or rather
it is too weak.  What a gravitational lift actually has to supply is:

    a two-field form of the linearized Weyl theory whose ACTION is
    exchange-symmetric, together with a VACUUM that is BRST-invariant and
    simultaneously breaks the exchange in the pattern a = 0, b != 0.

Both halves are demands, and the second is the hard one: in a gauge theory the
vacuum is constrained by BRST invariance, and here it is being asked to break a
discrete symmetry in a specific direction at the same time.  That is a far
sharper target than a commutator check, and it is the honest statement of what
the lift requires.

WHAT THIS DOES NOT ESTABLISH.  It does not test the gravitational case at all --
no tensor field, no gauge symmetry, no BRST differential appears below.  It is
a statement about the quadratic sector of ANY two-field exchange-covariant
embedding, which is why it constrains the gravitational one without deciding
it.  It does not refute Bateman-Turok; their construction is consistent with it
and is the reason the mechanism is called hidden.  Nothing here is
LORENTZIAN-CAUSAL and nothing bears on g-2.

Dependency tag: LOCAL-ALGEBRAIC.
"""

from __future__ import annotations

import argparse
import json
import os
import sys

import sympy as sp

REPO_ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
CERT_PATH = os.path.join(
    REPO_ROOT, "reverse_physics", "certificates",
    "REVERSE_PHYSICS_GHOST_PARITY_DOUBLE_POLE_V1.json")

k2, a, b = sp.symbols("k2 a b", real=True)


def quadratic_form(av=a, bv=b):
    """(1/2) Phi^T M Phi for L = dOmega.dUpsilon + a Omega^2 + b Upsilon^2."""
    return sp.Matrix([[2 * av, -k2], [-k2, 2 * bv]])


def exchange(M):
    """Omega <-> Upsilon acts by conjugation with the swap."""
    S = sp.Matrix([[0, 1], [1, 0]])
    return sp.simplify(S * M * S)


def propagator(M):
    return sp.simplify(M.inv())


def pole_data(av, bv):
    M = quadratic_form(av, bv)
    det = sp.factor(M.det())
    G = propagator(M)
    oo = sp.simplify(G[0, 0])
    poles = sorted(sp.solve(sp.Eq(det, 0), k2), key=str)
    # a coincident DOUBLE pole means <OO> has a k^4 (order-2) pole at k2 = 0
    order = sp.Poly(sp.denom(sp.together(oo)), k2).degree() if oo != 0 else 0
    return {
        "a": str(av), "b": str(bv),
        "exchange_symmetric": sp.simplify(av - bv) == 0,
        "det": str(det),
        "OmegaOmega": str(oo),
        "poles_k2": [str(p) for p in poles],
        "pole_order_in_k2": int(order),
        "has_coincident_double_pole": bool(oo != 0 and int(order) == 2
                                           and poles == [sp.Integer(0)]),
    }


def build():
    Mgen = quadratic_form()
    # the exchange is a symmetry of L iff a = b
    swapped = exchange(Mgen)
    sym_condition = sp.simplify(sp.Matrix(swapped - Mgen))
    symmetric_iff_a_eq_b = sp.solve(
        [sym_condition[i, j] for i in range(2) for j in range(2)], [a, b],
        dict=True)

    rows = [pole_data(0, 0), pole_data(0, 1), pole_data(1, 1),
            pole_data(sp.Rational(3, 2), sp.Rational(3, 2)),
            pole_data(0, sp.Rational(-5, 7))]

    sym_rows = [r for r in rows if r["exchange_symmetric"]]
    asym_rows = [r for r in rows if not r["exchange_symmetric"]]

    theorem = (all(not r["has_coincident_double_pole"] for r in sym_rows)
               and any(r["has_coincident_double_pole"] for r in asym_rows))

    # symbolic form of the theorem: <OO> = 2b/(4ab - k^4); at a = b the
    # denominator factorises into distinct roots unless b = 0, in which case
    # the numerator vanishes.
    oo_gen = sp.simplify(propagator(Mgen)[0, 0])
    at_equal = sp.simplify(oo_gen.subs(a, b))
    det_at_equal = sp.factor(quadratic_form(b, b).det())
    factorises = len(sp.factor_list(det_at_equal)[1]) >= 2
    vanishes_when_b_zero = sp.simplify(at_equal.subs(b, 0)) == 0

    checks = {
        "exchange_is_symmetry_iff_a_equals_b": bool(symmetric_iff_a_eq_b),
        "theorem_symmetric_never_gives_coincident_double_pole": theorem,
        "asymmetric_case_does_give_the_double_pole": any(
            r["has_coincident_double_pole"] for r in asym_rows),
        "at_a_equals_b_the_determinant_factorises_into_distinct_roots":
            bool(factorises),
        "at_a_equals_b_equals_zero_the_two_point_function_vanishes":
            bool(vanishes_when_b_zero),
        "control_rows_cover_both_symmetric_and_broken": (
            len(sym_rows) >= 2 and len(asym_rows) >= 2),
    }
    failures = [k for k, v in checks.items() if not v]

    return {
        "certificate": "REVERSE_PHYSICS_GHOST_PARITY_DOUBLE_POLE_V1",
        "dependency_tag": "LOCAL-ALGEBRAIC",
        "lifecycle_state": "CLASSIFIED",
        "question": "Can the ghost-parity involution be a MANIFEST symmetry of "
                    "a two-field embedding whose propagator carries the "
                    "coincident double pole that pure Weyl gravity has?",
        "answer": "No. Exchange symmetry of the quadratic Lagrangian holds iff "
                  "a = b, and then either the two-point function vanishes "
                  "identically (a = b = 0) or the poles separate to "
                  "k^2 = +-2a. The coincident double pole requires a != b, "
                  "which breaks the exchange. In Bateman-Turok's model the "
                  "asymmetric term is generated by the vacuum: expanding about "
                  "<Omega> = lambda^-1 turns the symmetric quartic into a lone "
                  "Upsilon^2. Ghost parity is a symmetry of the ACTION, "
                  "SPONTANEOUSLY BROKEN by the vacuum that reproduces the "
                  "fourth-order theory -- which is presumably what 'hidden' "
                  "means in their title.",
        "general_propagator": str(sp.simplify(propagator(quadratic_form())[0, 0])),
        "cases": rows,
        "consequence_for_the_tensor_lift": {
            "the_queued_test_was": "does kappa commute with the BRST "
                                   "differential s at linear order",
            "why_that_is_too_weak": "the binding requirement sits one level "
                                    "earlier and is visible in 2x2 algebra",
            "what_a_lift_must_actually_supply": [
                "a two-field form of the linearized Weyl theory whose ACTION "
                "is exchange-symmetric",
                "AND a vacuum that is BRST-invariant while simultaneously "
                "breaking the exchange in the pattern a = 0, b != 0",
            ],
            "which_half_is_hard": "the second: in a gauge theory the vacuum is "
                                  "constrained by BRST invariance, and is here "
                                  "asked to break a discrete symmetry in a "
                                  "specific direction at the same time",
        },
        "corroborating": {
            "their_caveat": "the phi and (Omega,Upsilon) path integrals are "
                            "inequivalent, 'the former integrates over "
                            "Omega > 0 whereas the latter integrates over all "
                            "Omega' -- a statement about the vacuum, not the "
                            "action",
            "paper_05": "the regulated masses m_pm^2 = mu^2 +/- sqrt(eps g) "
                        "are SPLIT exactly when the symmetry-breaking "
                        "parameter eps is nonzero",
        },
        "does_not_establish": [
            "anything about the gravitational case directly: no tensor field, "
            "no gauge symmetry and no BRST differential appears in the "
            "computation. It constrains any two-field embedding without "
            "deciding the gravitational one",
            "any refutation of Bateman-Turok -- their construction is "
            "consistent with this and is the reason the mechanism is hidden",
            "that a suitable BRST-invariant, parity-breaking vacuum does not "
            "exist for linearized Weyl gravity; that is now the open question",
            "anything LORENTZIAN-CAUSAL, and nothing about g-2",
        ],
        "checks": {
            "detail": checks,
            "total": len(checks),
            "passed": sum(1 for v in checks.values() if v),
            "failures": failures,
            "ok": not failures,
        },
        "report": "reverse_physics/reports/ghost-parity-double-pole.md",
    }


def main(argv=None):
    ap = argparse.ArgumentParser(description="ghost parity vs the double pole")
    ap.add_argument("--check", action="store_true")
    ap.add_argument("--emit", action="store_true")
    args = ap.parse_args(argv)
    if not (args.check or args.emit):
        args.check = True

    cert = build()
    print("L = dOmega.dUpsilon + a Omega^2 + b Upsilon^2")
    print("  exchange is a symmetry iff a = b")
    print("  <OmegaOmega> =", cert["general_propagator"])
    print()
    print("  %-9s %-11s %-22s %-14s %s"
          % ("(a,b)", "exch. sym", "<OO>", "poles k^2", "double pole"))
    for r in cert["cases"]:
        print("  %-9s %-11s %-22s %-14s %s"
              % ("(%s,%s)" % (r["a"], r["b"]), r["exchange_symmetric"],
                 r["OmegaOmega"], r["poles_k2"],
                 r["has_coincident_double_pole"]))
    print()
    print("  THEOREM: manifest exchange symmetry => no coincident double pole")
    print("           (either <OO> = 0, or the poles separate)")
    print()
    print("checks %d/%d" % (cert["checks"]["passed"], cert["checks"]["total"]))
    for f in cert["checks"]["failures"]:
        print("FAIL %s" % f)

    if args.emit and cert["checks"]["ok"]:
        with open(CERT_PATH, "w") as fh:
            json.dump(cert, fh, indent=2, sort_keys=True, default=str)
            fh.write("\n")
        print("wrote %s" % os.path.relpath(CERT_PATH, REPO_ROOT))

    print("RESULT: %s" % ("PASS" if cert["checks"]["ok"] else "FAIL"))
    return 0 if cert["checks"]["ok"] else 1


if __name__ == "__main__":
    sys.exit(main())
