"""Provenance record for the SECOND LAW on the stochastic carrier.

Computes no mathematics. The theorems live in `rocq/ReversePhysicsRelationalCount.v`.

Usage:
    PYTHONPATH=. python3 -m reverse_physics.relational_count_rocq --check
"""

from __future__ import annotations

import argparse
import hashlib
import json
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
OUTPUT = ROOT / "reverse_physics/certificates/REVERSE_PHYSICS_RELATIONAL_COUNT_ROCQ_V1.json"

RESULT_ID = "REVERSE_PHYSICS_RELATIONAL_COUNT_ROCQ_V1"
SCHEMA_NAME = "reverse-physics-relational-count-rocq-v1"

PINNED = {"proof": ROOT / "rocq/ReversePhysicsRelationalCount.v"}

THEOREMS = [
    {"name": "self_ratio_is_one", "statement": "a relative count is one at every region"},
    {
        "name": "ratio_sees_only_the_scale_ratio",
        "statement": "nu(ball (a c), ball (b c)) = nu(ball a, ball b)",
        "role": "the dilation argument does not kill a RELATIVE count -- it says exactly that absolute scale is meaningless while ratios of scale are not",
    },
    {
        "name": "scale_factor_is_multiplicative",
        "statement": "f(ab) = f(a) f(b) for f(t) = nu(ball t, ball 1)",
    },
    {
        "name": "generated_by_a_single_number",
        "statement": "f(2^n) = f(2)^n",
        "role": "THE ANSWER. The whole family is generated by one number: what survives is a scaling exponent, not a function on regions.",
    },
    {
        "name": "a_reference_region_forces_a_trivial_exponent",
        "statement": "if nu(-, ball 1) were itself dilation invariant then f(2) = 1",
        "role": "the exponent is nonzero PRECISELY because no conformally invariant reference exists; this and the refutation are one phenomenon seen from two sides",
    },
    {
        "name": "trivial_exponent_makes_every_dyadic_scale_tie",
        "statement": "and then every dyadic scale ties",
        "role": "the refutation's conclusion recovered inside the relational language",
    },
    {"name": "qpow_compat", "statement": "qpow respects Qeq (it is not a setoid morphism, so this is proved explicitly)"},
    {"name": "qpow_one", "statement": "1 to any power is 1"},
    {"name": "pow2_pos", "statement": "dyadic scales are positive"},
]

def sha(path: Path) -> str:
    return hashlib.sha256(path.read_bytes()).hexdigest()


def build() -> dict[str, object]:
    manifest = {}
    for name, path in PINNED.items():
        if not path.exists():
            raise AssertionError(f"pinned {name} missing at {path}")
        manifest[str(path.relative_to(ROOT))] = sha(path)

    return {
        "schema": SCHEMA_NAME,
        "result_id": RESULT_ID,
        "result_state": "WHAT_REPLACES_THE_COUNT_IS_A_SINGLE_SCALING_EXPONENT",
        "generality_level": "G3_ANY_NATURAL_WEYL_INVARIANT_RELATIVE_COUNT_ON_FLAT_SPACE",
        "lifecycle_ladder": "reverse-physics-v0",
        "lifecycle_state": "NECESSITY_CERTIFIED",
        "dependency_tags": ["LOCAL-ALGEBRAIC"],
        "record_kind": "PROVENANCE_IMPORT \u2014 the mathematics is in rocq/ReversePhysicsRelationalCount.v; this file computes nothing",
        "assumption_tags": {
            "consumed": [],
            "under_test": ["RP-CONFORMAL-INVARIANCE"],
            "namespace_note": "RP-* names physical postulates; disjoint from the computational-regime tags in dependency_tags.",
        },
        "closes_gate": {
            "gate": "REVERSE_PHYSICS_WHAT_REPLACES_A_COUNT",
            "opened_by": "REVERSE_PHYSICS_NO_CONFORMAL_COUNT_ROCQ_V1",
            "how": "The refutation killed the ABSOLUTE count and asked what the DOF-independence assumption becomes. A RELATIVE count survives the same dilation argument, and is then pinned down completely: multiplicative, hence generated by a single number.",
        },
        "the_move": {
            "from": "mu(U), an absolute count -- refuted",
            "to": "nu(U, V), degrees of freedom in U relative to V",
            "why_it_survives": (
                "Dilation invariance now acts on BOTH arguments: nu(dil c U, dil c V) = nu(U, V). Applied to "
                "balls that says nu(B_r, B_s) depends only on the ratio r/s, which is not degenerate. It is the "
                "familiar content of conformal invariance -- there is no length, only ratios of lengths."
            ),
        },
        "theorems": THEOREMS,
        "the_finding": {
            "statement": "What survives of 'how many degrees of freedom' in a conformally invariant theory is not a function on regions. It is a single scaling exponent.",
            "derivation": (
                "With the chain rule nu(U,W) = nu(U,V) nu(V,W) and f(t) = nu(ball t, ball 1), chaining through "
                "ball b and using dilation invariance with c = b gives f(ab) = f(a) f(b). Hence f(2^n) = f(2)^n: "
                "the entire family is generated by one number."
            ),
            "the_two_results_are_one": (
                "If some region could serve as an absolute reference -- if nu(-, ball 1) were itself dilation "
                "invariant, which is exactly what having an absolute count would mean -- then f(2) = 1 and the "
                "exponent collapses. The exponent is nonzero PRECISELY because no conformally invariant "
                "reference exists. The refutation and this certificate are the same fact from two sides."
            ),
            "what_their_assumption_becomes": (
                "'#states = product of #confDOF' is a PRODUCT of counts. Products of ratios are sums of "
                "exponents, so DOF-independence survives as ADDITIVITY OF THE EXPONENT over independent "
                "subsystems, not as a product of counts. That reading is prose; only the scaling law is proved."
            ),
        },
        "ledger": {
            "print_assumptions_closed": "9/9 for this module; 93/93 across the twelve modules the shared gate drives",
            "coqchk_axiom_section": "<none>",
            "declared_assumptions_in_source": "none \u2014 no Axiom, Parameter, Hypothesis, Conjecture, Admitted or admit; every geometric input is an explicit hypothesis of the theorem statements",
        },
        "gate_result": "RESULT: 17 green (0 red) \u2014 GATE: PASS",
        "gate_negative_controls": [
            "eleven inherited from the earlier modules, all rejected",
            "a FALSE claim that the relative count is trivial WITHOUT the reference assumption is REJECTED -- so the relational notion is genuinely non-degenerate, not a second collapse",
        ],
        "provenance": {
            "source_manifest": manifest,
            "gate_script_not_pinned": "rocq/run.sh is harness, deliberately not hash-pinned",
        },
        "exact_checks": {
            "zero_axiom_development": True,
            "kernel_rechecked_by_coqchk": True,
            "non_degeneracy_witnessed_by_a_negative_control": True,
            "only_constant_rescalings_used": True,
            "geometric_inputs_are_explicit_hypotheses": True,
        },
        "claim_flags": {
            "RELATIVE_COUNT_SURVIVES": True,
            "SCALING_LAW_PROVED": True,
            "GENERATED_BY_ONE_NUMBER": True,
            "FORMALLY_VERIFIED_IN_A_PROOF_ASSISTANT": True,
            "ZERO_AXIOM_DEVELOPMENT": True,
            "EXPONENT_SHOWN_POSITIVE_OR_EQUAL_TO_A_DIMENSION": False,
            "MONOTONICITY_ASSUMED": False,
            "EXTENSION_BEYOND_DYADIC_SCALES": False,
            "INDEPENDENCE_AS_ADDITIVITY_PROVED": False,
            "CLAIM_ABOUT_GR_OR_ITS_DYNAMICS": False,
            "QUANTUM_CLAIM": False,
        },
        "claim_boundary": (
            "In a zero-axiom Rocq development, a relative count that is natural, invariant under constant Weyl "
            "rescaling and satisfies the chain rule is multiplicative in the scale ratio, hence determined on "
            "dyadic scales by a single number; and that number is forced to one exactly when an absolute "
            "reference region is assumed to exist."
        ),
        "does_not_establish": [
            "that the exponent is positive, or that it equals a dimension. Monotonicity is NOT assumed, so the power-law reading is prose",
            "the scaling law beyond dyadic scales. f(2^n) = f(2)^n is proved; extending to all rationals or reals needs a regularity argument not given here",
            "that DOF-independence really becomes additivity of the exponent. That reading is stated, not proved: no product structure on regions is formalised",
            "the geometric inputs from differential geometry. They are explicit hypotheses, as in the companion files",
            "anything about curved configurations, non-constant conformal factors, or extra structure",
            "any claim about general relativity or its dynamics",
            "a reproduction, confirmation or refutation of Carcassi--Aidala's own derivation",
            "any quantum, causal, or field-theoretic claim",
        ],
        "next_gate": "REVERSE_PHYSICS_EXPONENT_ADDITIVITY: formalise a product structure on regions and prove that DOF-independence becomes additivity of the exponent. That would complete the translation of their assumption into the relational setting.",
        "verification_commands": [
            "cd rocq && ./run.sh",
            "PYTHONPATH=. python3 -m reverse_physics.relational_count_rocq --check",
        ],
    }


def main() -> None:
    parser = argparse.ArgumentParser(description=__doc__)
    group = parser.add_mutually_exclusive_group(required=True)
    group.add_argument("--write", action="store_true")
    group.add_argument("--check", action="store_true")
    args = parser.parse_args()

    payload = build()
    rendered = json.dumps(payload, indent=2, sort_keys=True) + "\n"
    if args.write:
        OUTPUT.write_text(rendered, encoding="utf-8")
    else:
        if not OUTPUT.exists():
            raise AssertionError(f"{RESULT_ID} record missing")
        recorded = json.loads(OUTPUT.read_text(encoding="utf-8"))
        for path, digest in recorded["provenance"]["source_manifest"].items():
            actual = sha(ROOT / path)
            if actual != digest:
                raise AssertionError(f"pinned source DRIFTED: {path} is {actual}, expected {digest}")
        if OUTPUT.read_text(encoding="utf-8") != rendered:
            raise AssertionError(f"{RESULT_ID} record is stale")
    print(f"{RESULT_ID}: PASS (pinned Rocq proof hash-verified)")


if __name__ == "__main__":
    main()
