#!/usr/bin/env python3
"""Generate counterflow physical-state positivity nonactivation."""
from __future__ import annotations
import argparse,hashlib,json
from pathlib import Path
ROOT=Path(__file__).resolve().parents[2]; CERT=ROOT/"quantum-weyl/transfer/certificates/TWO_PHASE_COUNTERFLOW_PHYSICAL_STATE_POSITIVITY_NONACTIVATION_V1.json"; ATLAS=ROOT/"residual_atlas/two-phase-counterflow-physical-state-positivity-nonactivation-fragment-v1.json"; REPORT=ROOT/"quantum-weyl/reports/two-phase-counterflow-physical-state-positivity-nonactivation-v1.md"
SOURCES={"hadamard":ROOT/"quantum-weyl/lorentzian/certificates/TWO_PHASE_COUNTERFLOW_FULL_BV_HADAMARD_NONACTIVATION_V1.json","hadamard_receipt":ROOT/"quantum-weyl/lorentzian/receipts/TWO_PHASE_COUNTERFLOW_FULL_BV_HADAMARD_NONACTIVATION_V1_TIER_RECEIPT.json","health":ROOT/"d_quotient_classical/compensator/TWO_PHASE_COUNTERFLOW_REPAIRED_Q70_HEALTH_ASSEMBLY_MAXIMAL_DOMAIN_V1.json","health_receipt":ROOT/"d_quotient_classical/compensator/receipts/TWO_PHASE_COUNTERFLOW_REPAIRED_Q70_HEALTH_ASSEMBLY_MAXIMAL_DOMAIN_V1_TIER_RECEIPT.json"}
def sha(p): return hashlib.sha256(p.read_bytes()).hexdigest()
def dump(x): return (json.dumps(x,indent=2,sort_keys=True)+"\n").encode()
def cl(s,t): return {"status":s,"statement":t}
def build():
 d={k:json.loads(p.read_text()) for k,p in SOURCES.items()}; refs={k:{"path":str(p.relative_to(ROOT)),"result_id":d[k]["result_id"],"sha256":sha(p)} for k,p in SOURCES.items()}; h=d["hadamard"]; q=d["health"]
 cert={"$schema":"../schema/two-phase-counterflow-physical-state-positivity-nonactivation-v1.schema.json","schema":"two-phase-counterflow-physical-state-positivity-nonactivation-v1","result_id":"TWO_PHASE_COUNTERFLOW_PHYSICAL_STATE_POSITIVITY_NONACTIVATION_V1","result_state":"NOT_ACTIVATED_MISSING_SUCCESSFUL_FULL_BV_HADAMARD_INPUT","lifecycle_state":"NOT_ACTIVATED","dependency_tags":["REDUCED-MODE","LORENTZIAN-CAUSAL"],"source_refs":refs,"activation_gate":{"required_hadamard_state":"SUCCESSFUL_FULL_BV_Q70_V2_HADAMARD","imported_hadamard_state":h["lifecycle_state"],"hadamard_all_70_rows":h["full_bv_hadamard_disposition"]["all_70_rows_covered"],"classical_health_state":q["result_state"],"gate_passed":False,"branch":"REFUSE_PHYSICAL_POSITIVITY_ACTIVATION"},"positivity_disposition":{"physical_brst_cohomology":"NOT_COMPUTED","descended_two_point_form":"NOT_COMPUTED","generic_isotypes":"NOT_COMPUTED","exceptional_isotypes":"NOT_COMPUTED","radical":"NOT_COMPUTED","inertia":"NOT_COMPUTED","unrestricted_Q_rel":"NOT_COMPUTED","fixed_Q_rel":"NOT_COMPUTED","D_Rrel_K_actions":"NOT_COMPUTED","representative_independence":"NOT_TESTED","symplectic_compatibility":"NOT_TESTED","positive_quasifree_state":"NOT_ACTIVATED","particles":"FORBIDDEN","unitarity":"FORBIDDEN"},"mutation_expectations":{k:"REJECT" for k in ["obstructed_hadamard_accepted","generic_for_low_j","charge_conflation","K_rawD","Krein_probability","positivity_promotion"]},"claim_boundary":"Physical-state positivity requires a successful full-q70 BV Hadamard covariance. The imported predecessor is explicitly NOT_ACTIVATED and constructs no 70-row covariance, so descent, radical, inertia and positivity are not defined. The classical health assembly remains valid but cannot replace the missing quantum covariance. No probability, particle, scattering or unitarity claim follows.","provenance":{"generator":"quantum-weyl/transfer/two_phase_counterflow_physical_state_positivity_nonactivation.py","generator_sha256":sha(Path(__file__))}}
 scope={"theory":"same-field two-phase polar-clock Weyl action","background":"selected Berger fixture and repaired-q70 health domain","boundaries":"closed S3 Cauchy slices","charge_sector":"unrestricted and fixed Q_rel kept distinct","carrier":"no descended quantum state carrier","degree":"physical BRST cohomology not activated","parity":"NOT_COMPUTED","ell":"generic and exceptional not computed","m":"NOT_COMPUTED","k":"NOT_COMPUTED","omega":"NOT_COMPUTED"}
 atlas={"schema":"pure-weyl-residual-atlas-fragment-v1","schema_version":"1.0.0","team":"quantum","generated_by":cert["provenance"]["generator"],"generated_by_sha256":sha(Path(__file__)),"status_vocabulary":["CERTIFIED","OBSTRUCTED","OPEN","NOT_APPLICABLE","NO_CERTIFIED_MAP"],"description_axes":["causal","symplectic","nonlinear","observational","quantum"],"entries":[{"id":"quantum.counterflow.phase1.physical_state_positivity_nonactivation","scope":scope,"descriptions":{"causal":"NO_CERTIFIED_MAP","symplectic":"NO_CERTIFIED_MAP","nonlinear":"NO_CERTIFIED_MAP","observational":"NO_CERTIFIED_MAP","quantum":"NO_CERTIFIED_MAP"},"evidence":[refs["hadamard"],refs["health"]],"mode_data":{"dispersion":cl("OBSTRUCTED","Classical health is obstructed and no quantum covariance is available."),"lee_wald":cl("NO_CERTIFIED_MAP","No two-point form descends without the full-BV covariance."),"taub_maps":cl("NO_CERTIFIED_MAP","No interacting bridge is activated."),"resonance":cl("OPEN","No quantum resonance state is defined."),"second_order":{"equation":"L_barPhi v = -(1/2) D^2 E_barPhi[u,u]","bounded_or_finite_quasiperiodic":cl("OBSTRUCTED","The classical robust clock gate failed."),"smooth_secular":cl("NO_CERTIFIED_MAP","No quantum state carrier exists."),"causal_retarded":cl("NO_CERTIFIED_MAP","Classical Green data alone do not define a Hadamard covariance.")}},"claim_boundary":cert["claim_boundary"]}],"verification_commands":["python3 quantum-weyl/transfer/two_phase_counterflow_physical_state_positivity_nonactivation.py --check","python3 quantum-weyl/transfer/verify_two_phase_counterflow_physical_state_positivity_nonactivation.py","python3 residual_atlas/validate_fragment.py residual_atlas/two-phase-counterflow-physical-state-positivity-nonactivation-fragment-v1.json"]}
 report="""# Counterflow physical-state positivity nonactivation\n\nThe required successful full-q70 Hadamard input does not exist: its predecessor is NOT_ACTIVATED and constructs no 70-row covariance. The classical health assembly is imported but cannot substitute for quantum covariance. Physical BRST cohomology, the descended two-point form, radical, inertia, charge-branch actions and positivity are therefore NOT_COMPUTED or NOT_ACTIVATED. No Krein sign is called probability and no particle or unitarity claim follows.\n"""; return cert,atlas,report
def main():
 p=argparse.ArgumentParser(); g=p.add_mutually_exclusive_group(required=True); g.add_argument("--write",action="store_true"); g.add_argument("--check",action="store_true"); a=p.parse_args(); c,x,r=build(); outs={CERT:dump(c),ATLAS:dump(x),REPORT:r.encode()}
 if a.write:
  for f,b in outs.items(): f.parent.mkdir(parents=True,exist_ok=True); f.write_bytes(b)
 else:
  for f,b in outs.items():
   if not f.exists() or f.read_bytes()!=b: raise SystemExit(f"STALE: {f.relative_to(ROOT)}")
 print("TWO_PHASE_COUNTERFLOW_PHYSICAL_STATE_POSITIVITY_NONACTIVATION_V1: PASS")
if __name__=="__main__": main()
