#!/usr/bin/env python3
"""Certify the finite physical massive advanced Cauchy preparation."""
from __future__ import annotations
import argparse,hashlib,json
from fractions import Fraction
from pathlib import Path
from jsonschema import Draft202012Validator
from closed_universe_observers.berger_recoil_interval_stream import RationalInterval
from closed_universe_observers.berger_recoil_massive_diagonal_preparation import evaluate_physical_massive_advanced_cauchy_pair_at_support_left
ROOT=Path(__file__).resolve().parents[1]; PACKAGE=ROOT/"closed_universe_observers"
CERTIFICATE=PACKAGE/"certificates/BERGER_RECOIL_PHYSICAL_MASSIVE_CAUCHY_PREPARATION.json"; SCHEMA=PACKAGE/"schema/berger-recoil-physical-massive-cauchy-preparation-v1.schema.json"; REPORT=PACKAGE/"reports/berger-recoil-physical-massive-cauchy-preparation.md"
DEPENDENCIES={"detector_image":PACKAGE/"certificates/BERGER_GREEN_WEIGHTED_DETECTOR_CODERIVATIVE.json","detector_form":PACKAGE/"certificates/BERGER_RECOIL_DETECTOR_FORM_BINDING.json","profiles":PACKAGE/"certificates/BERGER_EXACT_DETECTOR_SMEARINGS_AND_ADVANCED_COVECTORS.json","switches":PACKAGE/"certificates/BERGER_EXACT_NORMALIZED_EMITTER_SWITCH_PROFILES.json","moments":PACKAGE/"certificates/BERGER_VALIDATED_FLAT_BUMP_MOMENT_ENCLOSURES.json","kernels":PACKAGE/"certificates/BERGER_RECOIL_EXACT_MODE_KERNEL_PAYLOAD.json","diagonal":PACKAGE/"certificates/BERGER_RECOIL_MASSIVE_DIAGONAL_PREPARATION.json","forms":PACKAGE/"certificates/BERGER_SPACETIME_FORM_BLOCK_SIGN_BRIDGE.json"}
SOURCE_FILES=[Path(__file__),PACKAGE/"berger_recoil_massive_diagonal_preparation.py",PACKAGE/"verify_berger_recoil_physical_massive_cauchy_preparation.py",PACKAGE/"tests/test_berger_recoil_physical_massive_cauchy_preparation.py",SCHEMA,REPORT]
def _sha(p):return hashlib.sha256(p.read_bytes()).hexdigest()
def _payload(v):return hashlib.sha256(json.dumps(v,sort_keys=True,separators=(",",":")).encode()).hexdigest()
def _call(values,detector,two_j,column):return evaluate_physical_massive_advanced_cauchy_pair_at_support_left(detector_image_certificate=values["detector_image"],detector_profile_certificate=values["profiles"],switch_certificate=values["switches"],moment_certificate=values["moments"],exact_kernel_certificate=values["kernels"],detector=detector,two_j=two_j,column=column,mass_squared_interval=RationalInterval(Fraction(1),Fraction(2)))
def build():
 values={n:json.loads(p.read_text()) for n,p in DEPENDENCIES.items()}; required={"detector_image":"FINITE_MODE_ADVANCED_MAXWELL_IMAGE_TWO_J0_TO_4_EVALUATED","detector_form":"EXACT_SPACETIME_DHAT1_APPLIED_TO_DETECTOR_IMAGE","profiles":"DETECTOR_PROFILE_CLOCK_AND_ROD_NORMALIZATION_EXACT","switches":"SWITCHES_C_INFINITY_COMPACT_SUPPORTED","moments":"VALIDATED_STANDARD_FLAT_BUMP_MOMENTS_EXPORTED","kernels":"MAXWELL_AND_MASSIVE_BLOCKS_TWO_J0_TO_4_EXPORTED","diagonal":"DIAGONAL_MASSIVE_DEGREE_TWO_ADVANCED_IMAGE_AT_SUPPORT_LEFT_EXPORTED","forms":"EXACT_SPACETIME_CODERIVATIVE_BLOCKS_EXPORTED"}
 for n,f in required.items():
  if values[n].get("flags",{}).get(f) is not True:raise AssertionError(f"dependency dropped: {n}.{f}")
 d0=_call(values,"D0",0,0); d1=_call(values,"D1",4,4)
 if d0["cosine_nonzero_tau_powers"]!=[0,2,4,6,8,10] or len(d1["physical_two_form_value"])!=30:raise AssertionError("physical Cauchy fixture drifted")
 boundary="This exact LOCAL-ALGEBRAIC/LORENTZIAN-CAUSAL result derives cosine-kernel interval enclosures from the certified sine coefficients, evaluates the first time derivative of the switched diagonal massive advanced image, uses C-infinity switch flatness and F_tt=-A F, F_ttt=-A F_t at the support-left boundary, and applies the exact spacetime I+mu^-2 Dhat_1 Deltahat_2 correction. It exports the physical two-form value and physical-time derivative for every D0/D1 passive column through two_j=4 on any caller-declared strictly positive mass-squared interval. This is a finite full-form Cauchy pair, not yet the positive-energy dual tilde_u, an infinite spatial sum, I_abc, recoil, tangent-cone, Bridge 3 or quantum result."
 return {"schema":"closed-universe-berger-recoil-physical-massive-cauchy-preparation-v1","result_id":"BERGER_RECOIL_PHYSICAL_MASSIVE_CAUCHY_PREPARATION","setting_id":values["diagonal"]["setting_id"],"claim_status":"FINITE_PHYSICAL_MASSIVE_ADVANCED_CAUCHY_PAIR_CERTIFIED_POSITIVE_ENERGY_DUAL_OPEN","atlas_status":"CERTIFIED","dependency_tags":["LOCAL-ALGEBRAIC","LORENTZIAN-CAUSAL"],"dependency_refs":{n:{"path":str(p.relative_to(ROOT)),"result_id":values[n]["result_id"],"sha256":_sha(p)} for n,p in DEPENDENCIES.items()},"mode_scope":{"theory":"classical pure-Weyl gravity plus Berger clock, Maxwell detector and massive two-form emitters","background":"compact positive Berger clock at fixed coupling","boundaries":"support-left slice of h0 or h1; no spatial boundary","charge_sector":"fixed-coupling Berger sector","carrier":"physical massive two-form value and physical-time derivative interval vectors","degree":"spacetime two-form Cauchy pair","parity":"D0 axial and D1 transverse","ell":"two_j=0,...,4","m":"all component-major rows","k":"all passive columns","omega":"advanced sine/cosine finite series with uniform remainders"},"fixtures":{"D0_two_j0":_payload(d0),"D1_two_j4":_payload(d1)},"flags":{"COSINE_KERNEL_DERIVATIVE_ENCLOSURE_EXPORTED":True,"FLAT_ENDPOINT_SECOND_THIRD_DERIVATIVE_IDENTITIES_CERTIFIED":True,"PHYSICAL_PROCA_TWO_FORM_GREEN_CORRECTION_EXPORTED":True,"EMITTER_FULL_FORM_CAUCHY_PAIR_EXPORTED":True,"POSITIVE_ENERGY_DUAL_COEFFICIENTS_EXPORTED":False,"FOUR_RECOIL_SCALAR_INTERVALS_EXPORTED":False,"QUANTUM_CLAIM":False},"next_gate":"APPLY_POSITIVE_ENERGY_DUAL_AND_SERIALIZE_COUPLING_STRIPPED_EMITTER_PREPARATION_COEFFICIENTS","claim_boundary":boundary,"provenance":{"source_commit":"WORKTREE","source_manifest":[{"path":str(p.relative_to(ROOT)),"sha256":_sha(p)} for p in SOURCE_FILES]}}
def main():
 a=argparse.ArgumentParser();a.add_argument("--emit",action="store_true");a.add_argument("--check",action="store_true");x=a.parse_args();v=build();s=json.loads(SCHEMA.read_text());Draft202012Validator.check_schema(s);Draft202012Validator(s).validate(v);r=json.dumps(v,indent=2,sort_keys=True)+"\n"
 if x.emit:CERTIFICATE.write_text(r)
 if x.check and (not CERTIFICATE.exists() or CERTIFICATE.read_text()!=r):raise SystemExit("stale physical massive Cauchy certificate")
 print("BERGER_RECOIL_PHYSICAL_MASSIVE_CAUCHY_PREPARATION generation: PASS");return 0
if __name__=="__main__":raise SystemExit(main())
