#!/usr/bin/env python3
"""Verify the normalized algebraic bulk-endpoint to BFV suspension."""

from __future__ import annotations

import argparse
import json
from pathlib import Path
import sys

import sympy as sp

ROOT = Path(__file__).resolve().parents[2]
if str(ROOT) not in sys.path:
    sys.path.insert(0, str(ROOT))

from field_bv_identification.polarized_state import AlgebraicZeroModeTransgression


CERTIFICATE_PATH = (
    ROOT
    / "field_bv_identification"
    / "polarized_state"
    / "certificates"
    / "zero_mode_transgression.json"
)
LATEX_PATH = (
    ROOT
    / "field_bv_identification"
    / "generated_latex"
    / "zero_mode_transgression.tex"
)


def check(label: str, condition: object) -> None:
    if not bool(condition):
        raise AssertionError(label)
    print("[OK ] " + label)


def certificate_data() -> dict[str, object]:
    value = AlgebraicZeroModeTransgression.build()
    check(
        "FTBV-T1: the normalized endpoint quotient maps exactly once to BFV momentum",
        value.endpoint_to_bfv * value.normalized_endpoint_representatives
        == sp.eye(15),
    )
    check(
        "FTBV-T2: the D endpoint component is the certified Taub moment map",
        value.d_bulk_coefficient == 1,
    )
    check(
        "FTBV-T3: canonical Omega_gh and Omega_res give Q b_D=mu_D",
        value.d_bfv_coefficient == 1,
    )
    check(
        "FTBV-T4: cohomological-vector-field compatibility fixes lambda=+1",
        value.transgression_scalar == 1,
    )
    check(
        "FTBV-T5: equivariance extends the D normalization to all fifteen modes",
        value.bulk_quadratic_component
        == value.bfv_ghost_free_component
        == sp.eye(15),
    )
    check(
        "FTBV-T6: cotangent and homogeneous ghost orientations agree",
        value.cotangent_orientation
        == value.ghost_volume_orientation
        == value.centered_ghost_overlap
        == 1,
    )
    return {
        "schema": "pure-weyl-algebraic-zero-mode-transgression-v1",
        "category": "selected finite algebraic closed-cylinder BV-BFV zero modes",
        "endpoint_map": "Theta:coker(K^sharp)->Z^*",
        "suspension": "tau=suspension o Theta",
        "lambda_D": str(value.transgression_scalar),
        "lambda_all_generators": str(value.transgression_scalar),
        "bulk_D_coefficient": str(value.d_bulk_coefficient),
        "bfv_D_coefficient": str(value.d_bfv_coefficient),
        "generator_order": list(value.homogeneous_generator_order),
        "ghost_volume_orientation": str(value.ghost_volume_orientation),
        "cotangent_orientation": str(value.cotangent_orientation),
        "centered_ghost_overlap": str(value.centered_ghost_overlap),
        "conventions": {
            "ghost_symplectic_form": "Omega_gh=delta b_a wedge delta c^a",
            "residual_charge": "Omega_res=c^a mu_a-f^a_bc c^b c^c b_a/2",
            "ghost_free_vector_field": "Q_BFV b_a=mu_a",
        },
        "proved": [
            "the only equivariant magnitude is lambda=1 in the selected convention",
            "the D-component fixes all fifteen coadjoint components",
            "the bulk endpoint is suspended rather than copied",
            "the remaining orientation sign is fixed by the unit centered overlap",
        ],
        "not_proved": [
            "continuity on an analytic field-space completion",
            "uniqueness of the selected boundary polarization among other boundary problems",
            "nonlinear or quantum BV-BFV compatibility",
        ],
    }


def latex(data: dict[str, object]) -> str:
    return "\n".join(
        [
            "% Generated by verify_zero_mode_transgression.py",
            r"\begin{equation}",
            r" \tau=\Theta,\qquad \lambda_D=\lambda_{\rm all}=+1,",
            r" \qquad (v_-,v_-)_{\rm gh}=1.",
            r"\end{equation}",
            "",
        ]
    )


def main() -> None:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--emit", action="store_true")
    parser.add_argument("--claim-arbitrary-lambda", action="store_true")
    parser.add_argument("--claim-analytic-boundary-theorem", action="store_true")
    args = parser.parse_args()
    if args.claim_arbitrary_lambda:
        raise SystemExit(
            "REFUSED: endpoint, Taub, and canonical BFV normalizations force "
            "lambda=+1; no continuous magnitude remains"
        )
    if args.claim_analytic_boundary_theorem:
        raise SystemExit(
            "REFUSED: this is the selected algebraic zero-mode suspension, "
            "not a continuity theorem on a completed temporal boundary field space"
        )
    data = certificate_data()
    if args.emit:
        CERTIFICATE_PATH.parent.mkdir(parents=True, exist_ok=True)
        LATEX_PATH.parent.mkdir(parents=True, exist_ok=True)
        CERTIFICATE_PATH.write_text(
            json.dumps(data, indent=2, sort_keys=True) + "\n", encoding="utf-8"
        )
        LATEX_PATH.write_text(latex(data), encoding="utf-8")
        print("wrote", CERTIFICATE_PATH.relative_to(ROOT))
        print("wrote", LATEX_PATH.relative_to(ROOT))
    print("CONFORMAL ALGEBRAIC ZERO-MODE TRANSGRESSION: ALL PASS")


if __name__ == "__main__":
    main()
