#!/usr/bin/env python3
"""Verify the selected matter-times-ghost polarized pairing transfer."""

from __future__ import annotations

import argparse
import json
from pathlib import Path
import sys

import sympy as sp

ROOT = Path(__file__).resolve().parents[2]
if str(ROOT) not in sys.path:
    sys.path.insert(0, str(ROOT))

from field_bv_identification.polarized_state import PolarizedPairingTransfer


CERTIFICATE_PATH = (
    ROOT
    / "field_bv_identification"
    / "polarized_state"
    / "certificates"
    / "pairing_transfer.json"
)
LATEX_PATH = (
    ROOT
    / "field_bv_identification"
    / "generated_latex"
    / "polarized_pairing_transfer.tex"
)


def check(label: str, condition: object) -> None:
    if not bool(condition):
        raise AssertionError(label)
    print("[OK ] " + label)


def certificate_data(maximum_energy: int) -> dict[str, object]:
    value = PolarizedPairingTransfer.build(maximum_energy)
    check(
        "FTBV-J1: the action-normalized energy-two E primary has unit field norm",
        value.direct_primary_norm == 1,
    )
    check(
        "FTBV-J2: one exact energy-two isometry fixes the field/raw matter scalar",
        value.energy_two_field_to_raw.T
        * value.state.form.forms[2]
        * value.energy_two_field_to_raw
        == sp.eye(10),
    )
    check(
        "FTBV-J3: conformal recursion transports that scalar through the full buffer",
        value.state.induced_positive_form
        == value.state.form.block_diagonal_form(),
    )
    check(
        "FTBV-J4: canonical BFV orientation gives unit complementary ghost norm",
        value.ghost_norm
        == value.state.transgression.centered_ghost_overlap
        == 1,
    )
    check(
        "FTBV-J5: normalized Weyl-square and Pontryagin representatives have Gram I2",
        value.normalized_field_gram == sp.eye(2),
    )
    return {
        "schema": "pure-weyl-polarized-pairing-transfer-v1",
        "category": "selected algebraic closed-cylinder BV-BFV polarization",
        "matter_pipeline": "Omega_BV -> Omega_BFV -> Omega_Sigma -> J_positive",
        "positive_form_convention": "J(u,v)=-i Omega_Sigma(ubar,v)",
        "direct_energy_two_primary_norm": str(value.direct_primary_norm),
        "field_to_raw_isometry_shape": list(value.energy_two_field_to_raw.shape),
        "raw_two_class_gram": [
            [str(entry) for entry in row] for row in value.raw_kernel_gram.tolist()
        ],
        "ghost_norm": str(value.ghost_norm),
        "ghost_orientation": str(value.state.transgression.ghost_volume_orientation),
        "normalized_field_gram": [[1, 0], [0, 1]],
        "proved": [
            "one action-normalized primary fixes the matter scalar",
            "the exact conformal recursion fixes every subsequent energy",
            "the normalized BFV cotangent orientation induces the CE pairing",
            "the two residual representatives have field Gram I2",
        ],
        "not_proved": [
            "positivity of a propagating-particle Hilbert space",
            "boundedness on an analytic completion",
            "quantum BRST nilpotency or anomaly cancellation",
        ],
    }


def latex(data: dict[str, object]) -> str:
    return "\n".join(
        [
            "% Generated by verify_pairing_transfer.py",
            r"\begin{equation}",
            r" \langle W_r^2v_-,W_s^2v_-\rangle_{\rm field}=\delta_{rs},",
            r" \qquad G_{\rm field}=I_2.",
            r"\end{equation}",
            "",
        ]
    )


def main() -> None:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--max-energy", type=int, default=4)
    parser.add_argument("--emit", action="store_true")
    parser.add_argument("--claim-particle-hilbert", action="store_true")
    parser.add_argument("--claim-analytic-pairing", action="store_true")
    args = parser.parse_args()
    if args.claim_particle_hilbert:
        raise SystemExit(
            "REFUSED: I2 is the pairing on two polarized residual vertex "
            "classes, not a positive conformal-graviton Fock metric"
        )
    if args.claim_analytic_pairing:
        raise SystemExit(
            "REFUSED: the pairing is exact in the algebraic D-finite category; "
            "bounded analytic completion is not established"
        )
    data = certificate_data(args.max_energy)
    if args.emit:
        CERTIFICATE_PATH.parent.mkdir(parents=True, exist_ok=True)
        LATEX_PATH.parent.mkdir(parents=True, exist_ok=True)
        CERTIFICATE_PATH.write_text(
            json.dumps(data, indent=2, sort_keys=True) + "\n", encoding="utf-8"
        )
        LATEX_PATH.write_text(latex(data), encoding="utf-8")
        print("wrote", CERTIFICATE_PATH.relative_to(ROOT))
        print("wrote", LATEX_PATH.relative_to(ROOT))
    print("CONFORMAL POLARIZED PAIRING TRANSFER: ALL PASS")


if __name__ == "__main__":
    main()
