"""Exact thirty-row endpoint of the curvature-prolonged BV complex.

The hybrid algebraic projector proves that the 386-component mapping
cylinder retracts onto a thirty-component graph.  This module identifies
that graph *coefficientwise*.  It is important that this is not obtained by
relabeling the old 66-by-66 Fourier regression: the endpoint differential is
rebuilt from the actual curved metric gauge generator, the complete
action-normalized linearized Bach operator, and the companion forced by the
curved fibre pairings.

The retained order is

``G_met[5] -> h[10] -> Ebar_met[10] -> I_met[5]``

in degrees ``-1,0,1,2``.  The inclusion into the prolonged carrier is the
local graph

``(i_aux, T_core h, A_core Ebar_met, B_core I_met)``

and the projection is ``p_aux`` after the three forced cotangent corrections
of the mapping cylinder.  No inverse curvature map, Green operator, harmonic
projector, or Fourier-mode splitting occurs.

The module emits every parallel coefficient of ``Q_end`` and every primal
coefficient needed by the graph maps.  Cotangent coefficients are not fitted
again: they are generated by the formal-adjoint rule already certified by
the odd canonical mapping-cylinder kernel.
"""

from __future__ import annotations

from dataclasses import dataclass
import hashlib
import json
from pathlib import Path
from typing import Mapping

import sympy as sp

from covariant_completion.curved_operator.conventions import (
    SYMMETRIC_COORDINATES,
    _ordinary_system,
)
from covariant_completion.curved_operator.covariant_jets import CovariantJetBasis
from covariant_completion.curved_retract.curvature_auxiliary_chain_map import (
    _digest_tables,
    _state_coefficient_chunk,
)
from covariant_completion.curved_retract.curved_core_curvature_chain_map import (
    CoefficientTable,
    CurvedCoreCurvatureChainMap,
)
from covariant_completion.minimal_witness.linearized_bach import LinearizedBach


Multiindex = tuple[int, int, int, int]
ZERO: Multiindex = (0, 0, 0, 0)


def _digest_matrix(matrix: sp.MatrixBase) -> str:
    return hashlib.sha256(
        sp.srepr(sp.ImmutableSparseMatrix(matrix)).encode("utf-8")
    ).hexdigest()


def _certificate_digest(certificate: Mapping[str, object]) -> str:
    return hashlib.sha256(
        json.dumps(
            certificate, sort_keys=True, separators=(",", ":")
        ).encode("utf-8")
    ).hexdigest()


def _nonzero_count(table: CoefficientTable) -> int:
    return sum(int(value != 0) for _, matrix in table for value in matrix)


def _table_formal_adjoint(table: CoefficientTable) -> CoefficientTable:
    return tuple(
        (
            multiindex,
            (((-1) ** sum(multiindex)) * coefficient.T).applyfunc(sp.expand),
        )
        for multiindex, coefficient in table
    )


def _sparse_table(
    table: CoefficientTable,
    *,
    source: str,
    target: str,
) -> dict[str, object]:
    rows, columns = table[0][1].shape
    return {
        "source": source,
        "target": target,
        "shape": [rows, columns],
        "maximum_order": max(sum(multiindex) for multiindex, _ in table),
        "coefficient_multiindices": len(table),
        "nonzero_coefficients": _nonzero_count(table),
        "sha256": _digest_tables(table),
        "coefficients": [
            {
                "multiindex": list(multiindex),
                "entries": [
                    [row, column, str(matrix[row, column])]
                    for row in range(rows)
                    for column in range(columns)
                    if matrix[row, column] != 0
                ],
            }
            for multiindex, matrix in table
        ],
    }


def _metric_gauge_table() -> CoefficientTable:
    """Return the complete curved ``K_met:(xi,sigma)->h`` table."""

    source = _ordinary_system()
    tables: list[tuple[Multiindex, sp.Matrix]] = []
    zeroth = sp.zeros(10, 5)
    zeroth[:, 4] = sp.Matrix(
        [source.metric[a, b] for a, b in SYMMETRIC_COORDINATES]
    )
    tables.append((ZERO, zeroth))
    for axis in range(4):
        coefficient = sp.zeros(10, 5)
        for ghost in range(4):
            for row, (a, b) in enumerate(SYMMETRIC_COORDINATES):
                coefficient[row, ghost] = int(axis == a and ghost == b) + int(
                    axis == b and ghost == a
                )
        multiindex = tuple(int(index == axis) for index in range(4))
        tables.append((multiindex, coefficient))
    return tuple(sorted(tables))


def _metric_bach_table(
    basis: CovariantJetBasis,
    bach: LinearizedBach,
    field_pairing: sp.Matrix,
) -> CoefficientTable:
    """Reconstruct ``J_met^-1 E_Bach`` on every covariant four-jet."""

    source = _ordinary_system()
    output: list[tuple[Multiindex, sp.Matrix]] = []
    for multiindex in basis.geometry.exhaustive_multiindices(4):
        raw = sp.zeros(10)
        for column in range(10):
            metric = basis.covariant_monomial_symmetric(
                column, multiindex, 4
            )
            image = bach.action_normalized_bach(metric)
            coordinates = sp.Matrix(
                [image[a][b].value for a, b in SYMMETRIC_COORDINATES]
            )
            raw[:, column] = source.tensor_pairing * coordinates
        output.append(
            (
                multiindex,
                (field_pairing.inv() * raw).applyfunc(sp.expand),
            )
        )
    return tuple(sorted(output))


def _metric_companion_table(
    gauge: CoefficientTable,
    field_pairing: sp.Matrix,
    ghost_pairing: sp.Matrix,
) -> CoefficientTable:
    """Define ``C_met=Y_met^-1 K_met^sharp J_met`` coefficientwise."""

    return tuple(
        (
            multiindex,
            (
                ghost_pairing.inv()
                * ((-1) ** sum(multiindex) * coefficient.T)
                * field_pairing
            ).applyfunc(sp.expand),
        )
        for multiindex, coefficient in gauge
    )


def _shift_metric_from_projection(
    projection: CoefficientTable, field_pairing: sp.Matrix
) -> CoefficientTable:
    """Recover ``S_h`` from ``p_E=(J^-1 S_h^sharp J,1,0)``."""

    inverse = field_pairing.inv()
    return tuple(
        (
            multiindex,
            (
                (-1) ** sum(multiindex)
                * inverse
                * coefficient[:, :10].T
                * field_pairing
            ).applyfunc(sp.expand),
        )
        for multiindex, coefficient in projection
    )


@dataclass(frozen=True)
class ProlongedMetricEndpointComplex:
    """Coefficient-complete local presentation of the retained endpoint."""

    covector: tuple[sp.Symbol, ...]
    field_pairing: sp.Matrix
    ghost_pairing: sp.Matrix
    gauge_coefficients: CoefficientTable
    bach_coefficients: CoefficientTable
    companion_coefficients: CoefficientTable
    shift_metric_coefficients: CoefficientTable
    state_graph_coefficients: CoefficientTable
    equation_graph_coefficients: CoefficientTable
    identity_graph_coefficients: CoefficientTable
    equation_projection_coefficients: CoefficientTable
    identity_projection_coefficients: CoefficientTable

    @staticmethod
    def build() -> "ProlongedMetricEndpointComplex":
        basis = CovariantJetBasis.build()
        source = _ordinary_system()
        core = CurvedCoreCurvatureChainMap.build()
        field_pairing = source.field_fibre_pairing[:10, 10:20]
        ghost_pairing = source.gauge_fixing_pairing.extract(
            [0, 1, 2, 3, 8], [4, 5, 6, 7, 8]
        )

        gauge = _metric_gauge_table()
        bach = _metric_bach_table(
            basis, LinearizedBach.build(), field_pairing
        )
        companion = _metric_companion_table(
            gauge, field_pairing, ghost_pairing
        )
        shift_metric = _shift_metric_from_projection(
            core.equation_projection_coefficients, field_pairing
        )

        # This is the exhaustive curved state map (C1 h, div C1 h), not the
        # later principal-only rank-14 symbol audit.
        state_full = _state_coefficient_chunk(
            tuple(basis.geometry.exhaustive_multiindices(3))
        )
        state = tuple(
            (multiindex, coefficient[:, :10])
            for multiindex, coefficient in state_full
        )
        equation = ((ZERO, core.core_equation_attachment),)
        identity = ((ZERO, core.core_identity_attachment),)

        result = ProlongedMetricEndpointComplex(
            covector=basis.covector,
            field_pairing=field_pairing,
            ghost_pairing=ghost_pairing,
            gauge_coefficients=gauge,
            bach_coefficients=bach,
            companion_coefficients=companion,
            shift_metric_coefficients=shift_metric,
            state_graph_coefficients=state,
            equation_graph_coefficients=equation,
            identity_graph_coefficients=identity,
            equation_projection_coefficients=(
                core.equation_projection_coefficients
            ),
            identity_projection_coefficients=(
                core.identity_projection_coefficients
            ),
        )
        result.verify()
        return result

    @staticmethod
    def from_coefficient_payload(
        payload: Mapping[str, object],
    ) -> "ProlongedMetricEndpointComplex":
        """Load the content-addressed fast rail without rerunning 1,050 jets.

        The exhaustive :meth:`build` rail is the authority which emits the
        payload.  This loader reconstructs every rational matrix from that
        payload and reruns the algebraic coverage, adjoint, and cyclicity
        checks.  It deliberately does not claim to be a second derivation of
        the curved coefficients.
        """

        if payload.get("schema") != (
            "pure-weyl-prolonged-metric-endpoint-coefficients-v1"
        ):
            raise AssertionError("wrong endpoint coefficient payload schema")

        def table(section: Mapping[str, object], name: str) -> CoefficientTable:
            value = section.get(name)
            if not isinstance(value, Mapping):
                raise AssertionError(f"missing coefficient table {name}")
            shape = value.get("shape")
            coefficients = value.get("coefficients")
            if not (
                isinstance(shape, list)
                and len(shape) == 2
                and all(isinstance(entry, int) for entry in shape)
                and isinstance(coefficients, list)
            ):
                raise AssertionError(f"malformed coefficient table {name}")
            output: list[tuple[Multiindex, sp.Matrix]] = []
            for item in coefficients:
                if not isinstance(item, Mapping):
                    raise AssertionError(f"malformed coefficient item in {name}")
                multiindex_value = item.get("multiindex")
                entries = item.get("entries")
                if not (
                    isinstance(multiindex_value, list)
                    and len(multiindex_value) == 4
                    and all(isinstance(entry, int) for entry in multiindex_value)
                    and isinstance(entries, list)
                ):
                    raise AssertionError(f"malformed coefficient item in {name}")
                matrix = sp.zeros(shape[0], shape[1])
                for entry in entries:
                    if not isinstance(entry, list) or len(entry) != 3:
                        raise AssertionError(f"malformed sparse entry in {name}")
                    row, column, coefficient = entry
                    matrix[row, column] = sp.Rational(coefficient)
                output.append((tuple(multiindex_value), matrix))
            result = tuple(output)
            if _digest_tables(result) != value.get("sha256"):
                raise AssertionError(f"coefficient digest mismatch in {name}")
            return result

        endpoint = payload.get("endpoint_Q")
        graph = payload.get("graph_inclusion_primal")
        projection = payload.get("base_projection")
        pairings = payload.get("pairings")
        if not all(
            isinstance(value, Mapping)
            for value in (endpoint, graph, projection, pairings)
        ):
            raise AssertionError("endpoint coefficient payload is incomplete")
        assert isinstance(endpoint, Mapping)
        assert isinstance(graph, Mapping)
        assert isinstance(projection, Mapping)
        assert isinstance(pairings, Mapping)
        field_pairing = sp.Matrix(
            10, 10, [sp.Rational(value) for value in pairings["J_met"]]
        )
        ghost_pairing = sp.Matrix(
            5, 5, [sp.Rational(value) for value in pairings["Y_met"]]
        )
        if _digest_matrix(field_pairing) != pairings.get("J_met_sha256"):
            raise AssertionError("endpoint field-pairing digest mismatch")
        if _digest_matrix(ghost_pairing) != pairings.get("Y_met_sha256"):
            raise AssertionError("endpoint ghost-pairing digest mismatch")

        result = ProlongedMetricEndpointComplex(
            covector=tuple(sp.symbols("endpoint_cache_zeta_0:4", real=True)),
            field_pairing=field_pairing,
            ghost_pairing=ghost_pairing,
            gauge_coefficients=table(endpoint, "K_met"),
            bach_coefficients=table(endpoint, "Bach_bar"),
            companion_coefficients=table(endpoint, "C_met"),
            shift_metric_coefficients=table(graph, "S_h"),
            state_graph_coefficients=table(graph, "T_core"),
            equation_graph_coefficients=table(graph, "A_core"),
            identity_graph_coefficients=table(graph, "B_core"),
            equation_projection_coefficients=table(projection, "p_E"),
            identity_projection_coefficients=table(projection, "p_I"),
        )
        result.verify()
        return result

    def verify(self) -> None:
        expected = {
            "K_met": (self.gauge_coefficients, (10, 5), 5, 1),
            "Bach_bar": (self.bach_coefficients, (10, 10), 70, 4),
            "C_met": (self.companion_coefficients, (5, 10), 5, 1),
            "S_h": (self.shift_metric_coefficients, (10, 10), 15, 2),
            "T_core": (self.state_graph_coefficients, (26, 10), 35, 3),
            "A_core": (self.equation_graph_coefficients, (40, 10), 1, 0),
            "B_core": (self.identity_graph_coefficients, (14, 5), 1, 0),
            "p_E": (
                self.equation_projection_coefficients,
                (10, 24),
                15,
                2,
            ),
            "p_I": (
                self.identity_projection_coefficients,
                (5, 9),
                5,
                1,
            ),
        }
        for name, (table, shape, count, maximum_order) in expected.items():
            if len(table) != count or any(
                matrix.shape != shape for _, matrix in table
            ):
                raise AssertionError(f"{name} coefficient coverage drifted")
            if max(sum(multiindex) for multiindex, _ in table) != maximum_order:
                raise AssertionError(f"{name} differential order drifted")

        if self.field_pairing.shape != (10, 10) or self.field_pairing.rank() != 10:
            raise AssertionError("endpoint field pairing is degenerate")
        if self.ghost_pairing.shape != (5, 5) or self.ghost_pairing.rank() != 5:
            raise AssertionError("endpoint ghost pairing is degenerate")

        # Every coefficient of C=Y^-1 K^sharp J is checked, including the
        # algebraic Weyl row.  This is the endpoint odd-cyclicity condition.
        for (multiindex, gauge), (other, companion) in zip(
            self.gauge_coefficients,
            self.companion_coefficients,
            strict=True,
        ):
            if multiindex != other:
                raise AssertionError("K/C multiindex orders drifted")
            defect = (
                self.ghost_pairing * companion
                - ((-1) ** sum(multiindex))
                * gauge.T
                * self.field_pairing
            ).applyfunc(sp.expand)
            if defect != sp.zeros(5, 10):
                raise AssertionError("endpoint K/C adjoint defect")

        # The Bach Hessian is action-derived.  In paired coordinates its
        # formal self-adjoint identity is J B=B^sharp J.
        for multiindex, coefficient in self.bach_coefficients:
            defect = (
                self.field_pairing * coefficient
                - ((-1) ** sum(multiindex))
                * coefficient.T
                * self.field_pairing
            ).applyfunc(sp.expand)
            if defect != sp.zeros(10):
                raise AssertionError(
                    f"endpoint Bach adjoint defect at {multiindex}"
                )

        # p_E contains the exact formal adjoint of this S_h.  Reconstructing
        # one from the other guards the inclusion/projection convention.
        reconstructed = _shift_metric_from_projection(
            self.equation_projection_coefficients, self.field_pairing
        )
        if reconstructed != self.shift_metric_coefficients:
            raise AssertionError("endpoint tangent/cotangent graph drifted")

    def coefficient_payload(self) -> dict[str, object]:
        self.verify()
        return {
            "schema": "pure-weyl-prolonged-metric-endpoint-coefficients-v1",
            "normal_form": (
                "parallel coefficients multiplying symmetrized covariant "
                "derivatives; all cylinder curvature commutators included"
            ),
            "endpoint_Q": {
                "K_met": _sparse_table(
                    self.gauge_coefficients,
                    source="G_met[5]",
                    target="h[10]",
                ),
                "Bach_bar": _sparse_table(
                    self.bach_coefficients,
                    source="h[10]",
                    target="Ebar_met[10]",
                ),
                "C_met": _sparse_table(
                    self.companion_coefficients,
                    source="Ebar_met[10]",
                    target="I_met[5]",
                ),
            },
            "graph_inclusion_primal": {
                "S_h": _sparse_table(
                    self.shift_metric_coefficients,
                    source="h[10]",
                    target="f_aux[10]",
                ),
                "T_core": _sparse_table(
                    self.state_graph_coefficients,
                    source="h[10]",
                    target="X_U[26]",
                ),
                "A_core": _sparse_table(
                    self.equation_graph_coefficients,
                    source="Ebar_met[10]",
                    target="X_Eq[40]",
                ),
                "B_core": _sparse_table(
                    self.identity_graph_coefficients,
                    source="I_met[5]",
                    target="X_Id[14]",
                ),
            },
            "base_projection": {
                "p_E": _sparse_table(
                    self.equation_projection_coefficients,
                    source="Ebar_aux[24]",
                    target="Ebar_met[10]",
                ),
                "p_I": _sparse_table(
                    self.identity_projection_coefficients,
                    source="I_aux[9]",
                    target="I_met[5]",
                ),
            },
            "forced_cotangent_tables": {
                "rule": (
                    "A_I^sharp=(-1)^|I| A_I^T conjugated by the displayed "
                    "source/target fibre pairings; mapping-cylinder incidence "
                    "signs are fixed by the 16-block odd canonical kernel"
                ),
                "T_core_formal_transpose_sha256": _digest_tables(
                    _table_formal_adjoint(self.state_graph_coefficients)
                ),
                "A_core_formal_transpose_sha256": _digest_tables(
                    _table_formal_adjoint(self.equation_graph_coefficients)
                ),
                "B_core_formal_transpose_sha256": _digest_tables(
                    _table_formal_adjoint(self.identity_graph_coefficients)
                ),
                "not_an_independent_fit": True,
            },
            "pairings": {
                "J_met": [str(value) for value in self.field_pairing],
                "Y_met": [str(value) for value in self.ghost_pairing],
                "J_met_sha256": _digest_matrix(self.field_pairing),
                "Y_met_sha256": _digest_matrix(self.ghost_pairing),
            },
        }

    def certificate(
        self,
        *,
        dependencies: Mapping[str, Mapping[str, object]],
        coefficient_payload_sha256: str,
    ) -> dict[str, object]:
        self.verify()
        required_schemas = {
            "linearized_bach": "pure-weyl-linearized-bach-cylinder-v1",
            "curved_retract": "pure-weyl-curved-deformation-retract-status-v1",
            "curved_core_chain": "pure-weyl-curved-core-curvature-chain-map-v1",
            "mapping_substitution": (
                "pure-weyl-curvature-mapping-cylinder-substitution-v1"
            ),
            "hybrid_projector": (
                "pure-weyl-prolonged-hybrid-algebraic-projector-v1"
            ),
            "curvature_equation": (
                "pure-weyl-curvature-auxiliary-equation-chain-map-v1"
            ),
        }
        for name, schema in required_schemas.items():
            dependency = dependencies.get(name)
            if not isinstance(dependency, Mapping) or dependency.get("schema") != schema:
                raise AssertionError(f"missing endpoint dependency {name}")

        bach = dependencies["linearized_bach"]
        gauge_test = bach.get("gauge_jet_test")
        if not isinstance(gauge_test, Mapping) or not (
            bach.get("factorization_input") == "B_lin=C_1^sharp C_1"
            and bach.get("gauge_identity") == "C_1 K=0 and hence B_lin K=0"
            and gauge_test.get("exhaustive") is True
        ):
            raise AssertionError("endpoint Bach nilpotency input is incomplete")

        retract = dependencies["curved_retract"]
        promotion = retract.get("promotion_criteria")
        factorized = retract.get("factorized_actual_curved_Q")
        if not isinstance(promotion, Mapping) or not all(
            promotion.get(key) is True
            for key in (
                "curved_i_is_chain_map",
                "curved_p_is_chain_map",
                "actual_curved_Q_conjugation_verified",
                "all_full_BV_rows_included",
            )
        ):
            raise AssertionError("actual curved auxiliary SDR is incomplete")
        if not isinstance(factorized, Mapping) or factorized.get(
            "actual_curved_Q_conjugation_verified"
        ) is not True:
            raise AssertionError("factorized curved endpoint Q is unavailable")

        core = dependencies["curved_core_chain"]
        lifted = core.get("lifted_chain_squares")
        if not isinstance(lifted, Mapping) or lifted.get("exact") is not True:
            raise AssertionError("curved core graph squares are incomplete")

        substitution = dependencies["mapping_substitution"]
        kernel = substitution.get("kernel")
        if not (
            substitution.get("coefficientwise_complete_prolonged_Q") is True
            and isinstance(kernel, Mapping)
            and kernel.get("Q_squared") == "zero"
            and kernel.get("P_I") == "identity"
            and kernel.get("I_P_minus_identity") == "QH+HQ"
            and kernel.get("odd_BV_cyclicity_defect") == 0
        ):
            raise AssertionError("coefficient-complete mapping cylinder drifted")

        hybrid = dependencies["hybrid_projector"]
        ledger = hybrid.get("minimal_dimension_ledger")
        composite = hybrid.get("composite_SDR")
        if not isinstance(ledger, Mapping) or ledger.get(
            "retained_metric_curvature_graph"
        ) != 30:
            raise AssertionError("hybrid endpoint rank drifted")
        if not isinstance(composite, Mapping) or not all(
            composite.get(key) is True
            for key in (
                "P_end_idempotent",
                "D_P_end_equals_P_end_D",
                "cyclic_and_formally_self_adjoint",
                "support_local",
            )
        ):
            raise AssertionError("hybrid endpoint projector is incomplete")

        curvature_equation = dependencies["curvature_equation"]
        state_certificate = curvature_equation.get("T_state")
        if not isinstance(state_certificate, Mapping) or state_certificate.get(
            "sha256"
        ) != _digest_tables(
            tuple(
                (
                    multiindex,
                    coefficient.row_join(sp.zeros(26, 14)),
                )
                for multiindex, coefficient in self.state_graph_coefficients
            )
        ):
            # T_state in the source certificate is 26x24 with fourteen zero
            # auxiliary columns.  Rebuild that exact shape before comparing.
            raise AssertionError("curved T_core coefficient table drifted")

        return {
            "schema": "pure-weyl-prolonged-metric-endpoint-complex-v1",
            "dependency_sha256": {
                name: _certificate_digest(value)
                for name, value in dependencies.items()
            },
            "coefficient_payload_sha256": coefficient_payload_sha256,
            "ordered_endpoint_ledger": [
                {
                    "index": 0,
                    "block": "G_met[xi_minus_2[4],sigma[1]]",
                    "degree": -1,
                    "dimension": 5,
                    "prolonged_role": "retained auxiliary ghost base",
                },
                {
                    "index": 1,
                    "block": "h[10]",
                    "degree": 0,
                    "dimension": 10,
                    "prolonged_role": "metric plus local curvature-state graph",
                },
                {
                    "index": 2,
                    "block": "Ebar_met[10]",
                    "degree": 1,
                    "dimension": 10,
                    "prolonged_role": "paired Bach equation plus curvature-equation graph",
                },
                {
                    "index": 3,
                    "block": "I_met[4+1]",
                    "degree": 2,
                    "dimension": 5,
                    "prolonged_role": "diffeomorphism/Weyl identities plus curvature-identity graph",
                },
            ],
            "dimension": 30,
            "Q_end": {
                "formula": "p_end Q_prol j_end=Q_met",
                "nonzero_arrows": [
                    "G_met --K_met--> h",
                    "h --J_met^-1 E_Bach--> Ebar_met",
                    "Ebar_met --Y_met^-1 K_met^sharp J_met--> I_met",
                ],
                "maximum_orders": [1, 4, 1],
                "all_curved_lower_order_coefficients_emitted": True,
                "Q_end_squared": "zero",
                "lower_square": "Bach K_met=0 by exhaustive curved gauge jets",
                "upper_square": (
                    "C_met Bach=0 by formal adjunction of Bach K_met=0"
                ),
                "formal_adjoint_defects": 0,
                "odd_cyclicity_defect": 0,
                "coefficient_sha256": {
                    "K_met": _digest_tables(self.gauge_coefficients),
                    "Bach_bar": _digest_tables(self.bach_coefficients),
                    "C_met": _digest_tables(self.companion_coefficients),
                },
            },
            "local_graph_maps": {
                "j_end": {
                    "formula": "I_cyl I_aux",
                    "base": [
                        "xi_minus_2 -> G_aux.xi_minus_2",
                        "sigma -> (G_aux.xi_0=nabla sigma,G_aux.sigma=sigma)",
                        "h -> (M_aux.h=h,M_aux.f=S_h h,M_aux.v=0)",
                        "Ebar_met -> Ebar_aux.f-slot",
                        "I_met -> I_aux.(xi_0-star,sigma-star)-slot",
                    ],
                    "curvature_graph": [
                        "X_U=T_core h=(C1 h,div C1 h)",
                        "X_Eq=A_core Ebar_met",
                        "X_Id=B_core I_met",
                    ],
                    "all_Y_and_dual_X/Y_blocks": "zero",
                    "maximum_order": 3,
                },
                "p_end": {
                    "formula": "P_aux P_cyl",
                    "mapping_cylinder_corrections": [
                        "G_aux <- G_aux+Bsharp X_Id_sharp",
                        "M_aux <- M_aux+Asharp X_Eq_sharp",
                        "Ebar_aux <- Ebar_aux+Tsharp X_U_sharp",
                        "I_aux <- I_aux",
                    ],
                    "then": [
                        "p_G=(xi_minus_2,sigma)",
                        "p_M=(h)",
                        "p_E=(J_met^-1 S_h^sharp J_met,1,0)",
                        "p_I=the emitted order-one cotangent ghost projection",
                    ],
                    "maximum_order_before_composition": 3,
                    "cotangent_coefficients_forced_by_BV_canonical_adjoint": True,
                },
                "identities": {
                    "p_end_j_end": "identity_30",
                    "Q_prol_j_end": "j_end_Q_end",
                    "p_end_Q_prol": "Q_end_p_end",
                    "j_end_p_end": "P_end",
                    "P_end_squared": "P_end",
                    "Q_prol_P_end": "P_end_Q_prol",
                },
                "support": {
                    "finite_order_differential": True,
                    "pointwise_inverses_only": True,
                    "inverse_Weyl_Laplacian_or_curl": False,
                    "Fourier_or_harmonic_projector": False,
                    "compact": True,
                    "spacelike_compact": True,
                    "smooth_global": True,
                },
            },
            "cyclicity": {
                "endpoint_pairing": (
                    "Omega(G,I)=Y_met, Omega(h,Ebar)=J_met with odd reverse signs"
                ),
                "K_C_identity": "Y_met C_met=K_met^sharp J_met",
                "Bach_identity": "J_met Bach_bar=Bach_bar^sharp J_met",
                "coefficientwise_adjoint_reason": (
                    "the canonical normal form uses fully symmetrized covariant "
                    "derivatives; reversal permutes the same symmetrized words, "
                    "and every coefficient and fibre pairing is parallel, so "
                    "formal adjunction is exactly (-1)^|I| transpose with no "
                    "derivative-of-coefficient remainder"
                ),
                "graph_projector_formally_self_adjoint": True,
                "endpoint_Q_odd_cyclicity_defect": 0,
            },
            "curved_vs_regression_boundary": {
                "actual_curved_sources": [
                    "70-table covariant-jet LinearizedBach reconstruction",
                    "factorized actual-curved-Q split",
                    "35-table curved T_state reconstruction",
                    "curved p_E/p_I and A_core/B_core coefficient tables",
                    "coefficient-complete canonical mapping-cylinder substitution",
                ],
                "Fourier_66x66_matrices_used_as_curved_coefficients": False,
                "Fourier_regression_role": (
                    "dimension/order/sign regression only; its hashes are not emitted as curved tables"
                ),
            },
            "prolonged_green_witness": False,
            "curvature_causal_green_operators": False,
            "causal_green_homotopy": False,
            "warranted_atomic_flags": [
                "prolonged_metric_endpoint_complex_exact"
            ],
            "status_flags_promoted": [],
            "next_required_theorem": (
                "construct a Green witness/homotopy on this exact thirty-row endpoint"
            ),
            "fail_closed": True,
        }


def write_coefficient_payload(path: Path, payload: Mapping[str, object]) -> str:
    text = json.dumps(payload, indent=2, sort_keys=True) + "\n"
    path.write_text(text, encoding="utf-8")
    return hashlib.sha256(text.encode("utf-8")).hexdigest()
