"""Exact spin-two Weyl-anomaly reconstruction and one-generator D descent.

This module reconstructs the standard Euclidean background anomaly of the
four-dimensional conformal spin-two field from the factorized determinant
and second-order heat-kernel formulae in arXiv:1309.0785v4.  It deliberately
does not identify that background anomaly with the repository's still-open
BV master-equation breaking.

The D calculation is a restriction of the local ghost-number-one anomaly
cocycle to the one-dimensional subalgebra generated by D.  It is not the
degree-zero quantum Cartan defect ``[Q_hbar, iota_D,hbar] - L_D,hbar``.
"""

from __future__ import annotations

from dataclasses import dataclass
from fractions import Fraction
from math import factorial
from typing import Mapping


Q = Fraction


def _fraction(value: Fraction) -> str:
    return str(value.numerator) if value.denominator == 1 else f"{value.numerator}/{value.denominator}"


def unconstrained_rank_s_a(spin: int, mass_squared: int | Fraction) -> Fraction:
    """Return ``a[Delta_s(M^2)]`` from source equation (aa2).

    ``mass_squared`` is the dimensionless number called ``M^2`` in the
    source.  Consequently the ``M^4`` term is its square.
    """

    if spin < 0:
        raise ValueError("spin must be nonnegative")
    m2 = Q(mass_squared)
    components = Q((spin + 1) ** 2)
    return components * (
        components - 3 * m2**2 + 12 * m2 - Q(63, 5)
    ) / 144


def transverse_rank_s_a(spin: int, mass_squared: int | Fraction) -> Fraction:
    """Return the transverse determinant contribution from equation (aa22)."""

    if spin < 0:
        raise ValueError("spin must be nonnegative")
    m2 = Q(mass_squared)
    if spin == 0:
        return unconstrained_rank_s_a(0, m2)
    return unconstrained_rank_s_a(spin, m2) - unconstrained_rank_s_a(
        spin - 1, m2 - 2 * spin - 1
    )


def ricci_flat_operator_beta1(spin: int) -> Fraction:
    """Return ``beta_1[Delta_s]`` from source equation (211)."""

    if spin < 0:
        raise ValueError("spin must be nonnegative")
    components = Q((spin + 1) ** 2)
    return components * (21 - 20 * components + 3 * components**2) / 720


def chs_beta1(spin: int) -> Fraction:
    """Return the Ricci-flat CHS coefficient ``beta_1=c-a``.

    This is the determinant combination in source equations (12b) and (ww).
    """

    if spin < 1:
        raise ValueError("conformal higher spin must be positive")
    return spin * ricci_flat_operator_beta1(spin) - (spin + 1) * ricci_flat_operator_beta1(spin - 1)


def chs_a_closed_form(spin: int) -> Fraction:
    """Return the constant-curvature CHS coefficient from equation (nen)."""

    if spin < 1:
        raise ValueError("conformal higher spin must be positive")
    degrees_of_freedom = Q(spin * (spin + 1))
    return degrees_of_freedom**2 * (3 + 14 * degrees_of_freedom) / 720


def chs_a_factorized(spin: int) -> Fraction:
    """Evaluate the factorized transverse determinant sum before simplification."""

    if spin < 1:
        raise ValueError("conformal higher spin must be positive")
    total = Q(0)
    for depth in range(spin):
        physical_mass = 2 + spin - depth - depth**2
        ghost_mass = 2 + depth - spin - spin**2
        total += transverse_rank_s_a(spin, physical_mass)
        total -= transverse_rank_s_a(depth, ghost_mass)
    return total


def chs_c_conical_sphere(spin: int) -> Fraction:
    """Return the independent conical-sphere ``c_s`` formula.

    This is equation (1.6) of arXiv:1707.02456v2.  At spin two it is an
    independent spectral reconstruction of the same ``c`` coordinate.
    """

    if spin < 1:
        raise ValueError("conformal higher spin must be positive")
    degrees_of_freedom = Q(spin * (spin + 1))
    return degrees_of_freedom * (
        14 * degrees_of_freedom**2 - 17 * degrees_of_freedom - 4
    ) / 360


@dataclass(frozen=True)
class SpinTwoAnomaly:
    """The source-normalized conformal spin-two background anomaly."""

    a: Fraction
    c: Fraction
    beta1: Fraction
    beta2: Fraction

    @property
    def b4_basis(self) -> Mapping[str, Fraction]:
        """Coordinates in ``b4=-a E4+c C2`` convention."""

        return {"E4": -self.a, "C2": self.c}


def spin_two_anomaly() -> SpinTwoAnomaly:
    """Compute and cross-check the two standard spin-two coefficients."""

    a_from_factors = chs_a_factorized(2)
    a_from_closed_form = chs_a_closed_form(2)
    if a_from_factors != a_from_closed_form:
        raise AssertionError("constant-curvature determinant sum disagrees with its closed form")
    beta1 = chs_beta1(2)
    c = a_from_factors + beta1
    result = SpinTwoAnomaly(a_from_factors, c, beta1, 2 * c)
    if result != SpinTwoAnomaly(Q(87, 20), Q(199, 30), Q(137, 60), Q(199, 15)):
        raise AssertionError("spin-two anomaly normalization drifted")
    if result.c != chs_c_conical_sphere(2):
        raise AssertionError("Ricci-flat and conical-sphere c reconstructions disagree")
    return result


def spin_two_factor_ledger() -> tuple[dict[str, object], ...]:
    """Return the four transverse determinant contributions on (A)dS/S4."""

    rows = (
        ("physical_depth_0", 2, 4, 1),
        ("ghost_depth_0", 0, -4, -1),
        ("physical_depth_1", 2, 2, 1),
        ("ghost_depth_1", 1, -3, -1),
    )
    return tuple(
        {
            "factor_id": factor_id,
            "spin": spin,
            "M_squared": mass_squared,
            "determinant_sign": sign,
            "a_contribution_before_sign": _fraction(transverse_rank_s_a(spin, mass_squared)),
            "signed_a_contribution": _fraction(sign * transverse_rank_s_a(spin, mass_squared)),
        }
        for factor_id, spin, mass_squared, sign in rows
    )


@dataclass(frozen=True)
class DReducibility:
    """One exact Diff x Weyl reducibility pair for a constant metric."""

    frame: str
    vector_jacobian: tuple[tuple[Fraction, ...], ...]
    metric: tuple[tuple[Fraction, ...], ...]
    sigma: Fraction

    @property
    def divergence(self) -> Fraction:
        return sum(self.vector_jacobian[index][index] for index in range(4))

    @property
    def lie_metric(self) -> tuple[tuple[Fraction, ...], ...]:
        # For a constant diagonal metric, (L_X g)_mn = g_kn d_m X^k +
        # g_mk d_n X^k.  The explicit matrix form also tests off-diagonal
        # entries instead of assuming the result is proportional to g.
        return tuple(
            tuple(
                sum(
                    self.metric[k][nu] * self.vector_jacobian[k][mu]
                    + self.metric[mu][k] * self.vector_jacobian[k][nu]
                    for k in range(4)
                )
                for nu in range(4)
            )
            for mu in range(4)
        )

    @property
    def reducibility_residual(self) -> tuple[tuple[Fraction, ...], ...]:
        return tuple(
            tuple(
                self.lie_metric[mu][nu] + 2 * self.sigma * self.metric[mu][nu]
                for nu in range(4)
            )
            for mu in range(4)
        )

    def verify(self) -> None:
        if self.sigma != -self.divergence / 4:
            raise AssertionError(f"{self.frame}: sigma != -div(X_D)/4")
        if any(value for row in self.reducibility_residual for value in row):
            raise AssertionError(f"{self.frame}: L_X g+2 sigma g != 0")


MINKOWSKI_METRIC = tuple(
    tuple(Q(-1 if mu == nu == 0 else 1 if mu == nu else 0) for nu in range(4))
    for mu in range(4)
)


def cylinder_d_reducibility() -> DReducibility:
    """Cylinder time translation ``X_D=partial_t, sigma_D=0``.

    The product cylinder metric is time independent.  Its spatial connection
    does not enter because X_D has constant components and no spatial part.
    """

    zero = tuple(tuple(Q(0) for _ in range(4)) for _ in range(4))
    result = DReducibility("R_times_S3_cylinder", zero, MINKOWSKI_METRIC, Q(0))
    result.verify()
    return result


def minkowski_d_reducibility() -> DReducibility:
    """Minkowski dilation ``X_D=x^mu partial_mu, sigma_D=-1``."""

    identity = tuple(
        tuple(Q(1 if mu == nu else 0) for nu in range(4)) for mu in range(4)
    )
    result = DReducibility("Minkowski_dilation", identity, MINKOWSKI_METRIC, Q(-1))
    result.verify()
    return result


def d_pullback(reducibility: DReducibility, anomaly: SpinTwoAnomaly | None = None) -> dict[str, object]:
    """Restrict the local Weyl-anomaly cocycle to the D subalgebra.

    The top cocycle is ``c_D sigma_D (c C2-a E4)``.  Intrinsic lower
    descendants vanish for both declared D pairs because sigma_D is constant.
    Universal Diff descendants vanish after one-generator restriction: the
    top term already contains ``c_D``, and each contraction contributes a
    second copy, so ``c_D^2=0``.
    """

    reducibility.verify()
    anomaly = anomaly or spin_two_anomaly()
    top = {
        invariant: reducibility.sigma * coefficient
        for invariant, coefficient in anomaly.b4_basis.items()
    }
    universal = []
    for contraction_degree in range(1, 5):
        universal.append(
            {
                "form_degree": 4 - contraction_degree,
                "ghost_number": 1 + contraction_degree,
                "coefficient": _fraction(Q((-1) ** contraction_degree, factorial(contraction_degree))),
                "D_restricted_status": "ZERO_BY_cD_SQUARED",
            }
        )
    return {
        "frame": reducibility.frame,
        "D_vector_divergence": _fraction(reducibility.divergence),
        "weyl_compensator_sigma_D": _fraction(reducibility.sigma),
        "top_anomaly_coordinates": {
            key: _fraction(value) for key, value in top.items()
        },
        "top_anomaly_status": "ZERO" if all(value == 0 for value in top.values()) else "NONZERO_LOCAL_COCYCLE_PULLBACK",
        "intrinsic_type_B_lower_descent": "TRIVIAL",
        "intrinsic_type_A_lower_descent": "ZERO_FOR_CONSTANT_SIGMA_D",
        "universal_diff_lower_descent": universal,
        "one_generator_exterior_relation": "c_D^2=0",
    }


def exact_payload() -> dict[str, object]:
    """Return the exact calculation payload used by the certificate."""

    anomaly = spin_two_anomaly()
    cylinder = cylinder_d_reducibility()
    minkowski = minkowski_d_reducibility()
    beta1_factors = {
        "2_times_beta1_Delta2": _fraction(2 * ricci_flat_operator_beta1(2)),
        "minus_3_times_beta1_Delta1": _fraction(-3 * ricci_flat_operator_beta1(1)),
    }
    return {
        "coefficient_calculation": {
            "spin": 2,
            "effective_degrees_of_freedom_nu": 6,
            "constant_curvature_factor_ledger": list(spin_two_factor_ledger()),
            "constant_curvature_sum_a": _fraction(anomaly.a),
            "closed_form_a": _fraction(chs_a_closed_form(2)),
            "ricci_flat_factor_ledger": beta1_factors,
            "ricci_flat_sum_beta1_equals_c_minus_a": _fraction(anomaly.beta1),
            "derived_c_equals_a_plus_beta1": _fraction(anomaly.c),
            "independent_conical_sphere_c": _fraction(chs_c_conical_sphere(2)),
            "derived_beta2_equals_2c": _fraction(anomaly.beta2),
            "background_anomaly_convention": "(4 pi)^(-2) [c C2-a E4] modulo BoxR",
            "anomaly_coordinates": {
                key: _fraction(value) for key, value in anomaly.b4_basis.items()
            },
            "cross_checks": {
                "factorized_a_equals_closed_form": chs_a_factorized(2) == chs_a_closed_form(2),
                "beta1_equals_c_minus_a": anomaly.beta1 == anomaly.c - anomaly.a,
                "beta2_equals_2c": anomaly.beta2 == 2 * anomaly.c,
                "ricci_flat_c_equals_conical_sphere_c": anomaly.c == chs_c_conical_sphere(2),
            },
        },
        "D_descent": {
            "result_kind": "ONE_GENERATOR_PULLBACK_OF_LOCAL_GHOST_NUMBER_ONE_ANOMALY_COCYCLE",
            "cylinder": d_pullback(cylinder, anomaly),
            "minkowski": d_pullback(minkowski, anomaly),
            "cartan_defect_map_status": "NOT_CONSTRUCTED",
            "cartan_defect_status": "UNDEFINED_ANALYTICALLY",
        },
    }
