#!/usr/bin/env python3
import argparse,hashlib,json
from pathlib import Path
ROOT=Path(__file__).resolve().parents[2]; GEN=Path(__file__).resolve(); CERT=ROOT/"closed_universe_observers/certificates/CHARGED_TIME_FINITE_RESOLUTION_SAMPLING_THEOREM_V1.json"; OUT=ROOT/"residual_atlas/charged-time-finite-resolution-sampling-theorem-fragment-v1.json"
def sha(p):return hashlib.sha256(p.read_bytes()).hexdigest()
def cl(s,t):return {"status":s,"statement":t}
def build():
 v=json.loads(CERT.read_text()); ev=[{"path":str(CERT.relative_to(ROOT)),"result_id":v["result_id"],"sha256":sha(CERT)}]
 return {"schema":"pure-weyl-residual-atlas-fragment-v1","schema_version":"1.0.0","team":"observer","generated_by":str(GEN.relative_to(ROOT)),"generated_by_sha256":sha(GEN),"status_vocabulary":["CERTIFIED","OBSTRUCTED","OPEN","NOT_APPLICABLE","NO_CERTIFIED_MAP"],"description_axes":["causal","symplectic","nonlinear","observational","quantum"],"entries":[{"id":"observer.general.charged_time_finite_resolution_sampling","scope":{"theory":"Hamiltonian/BV theories with one surviving physical action-angle clock pair","background":"any oriented spacetime satisfying the imported event-map and declared compact-support hypotheses","boundaries":"compact receiver support; epsilon profile band in a regular lifted clock chart, or declared periodicized S1 profile","charge_sector":"unrestricted physical Q; charged R and D with K=D-H'(Q)R","carrier":"conditional compact receiver bicomplex class [A], action-angle pair (psi,Q), and normalized even compact profile kappa","degree":0,"parity":"profile even; receiver cooriented under primitive clock reversal","ell":"all receiver modes satisfying the contract","m":"all","k":"all/NOT_APPLICABLE according to background","omega":"finite sampled band with H'(Q) fixed nonzero sign on the lifted chart"},"descriptions":{"causal":"CERTIFIED","symplectic":"CERTIFIED","nonlinear":"OPEN","observational":"CERTIFIED","quantum":"NO_CERTIFIED_MAP"},"mode_data":{"dispersion":cl("CERTIFIED","Exact profile scaling, moment addition and charged action-angle covariance are certified; no wave dispersion is inferred."),"lee_wald":cl("CERTIFIED","The imported Darboux pair is nondegenerate; receiver nontriviality and any theory-specific descended pairing remain conditional."),"taub_maps":cl("NO_CERTIFIED_MAP","No theory-specific second-order source or nonlinear receiver is part of this theorem."),"resonance":cl("OPEN","Finite-resolution sampling does not decide a background-specific resonance."),"second_order":{"equation":"L_barPhi v = -(1/2) D^2 E_barPhi[u,u]","bounded_or_finite_quasiperiodic":cl("OPEN","Requires a theory-specific receiver and correction class."),"smooth_secular":cl("OPEN","Sampling and phase-map composition bounds do not supply a nonlinear secular correction."),"causal_retarded":cl("OPEN","Support inheritance is certified conditionally, but no theory-specific Green image or receiver class is supplied.")}},"evidence":ev,"claim_boundary":v["claim_boundary"]}],"verification_commands":["python3 closed_universe_observers/generate_charged_time_finite_resolution_sampling_theorem.py --check","python3 closed_universe_observers/verify_charged_time_finite_resolution_sampling_theorem.py","python3 -m pytest -q closed_universe_observers/tests/test_charged_time_finite_resolution_sampling_theorem.py","python3 residual_atlas/validate_fragment.py residual_atlas/charged-time-finite-resolution-sampling-theorem-fragment-v1.json"]}
def render(v):return json.dumps(v,indent=2,sort_keys=True)+"\n"
if __name__=="__main__":
 p=argparse.ArgumentParser();p.add_argument("--emit",action="store_true");p.add_argument("--check",action="store_true");a=p.parse_args();v=build()
 if a.emit:OUT.write_text(render(v))
 if a.check and OUT.read_text()!=render(v):raise AssertionError("atlas drift")
 print("CHARGED_TIME_FINITE_RESOLUTION_SAMPLING_THEOREM_ATLAS: PASS")
