#!/usr/bin/env python3
import argparse,hashlib,json
from pathlib import Path
ROOT=Path(__file__).resolve().parents[2];GEN=Path(__file__).resolve();CERT=ROOT/"closed_universe_observers/certificates/CHARGED_TIME_EMITTER_RECEIVER_COMPOSITION_THEOREM_V1.json";OUT=ROOT/"residual_atlas/charged-time-emitter-receiver-composition-theorem-fragment-v1.json"
def sha(p):return hashlib.sha256(p.read_bytes()).hexdigest()
def cl(s,t):return {"status":s,"statement":t}
def build():
 v=json.loads(CERT.read_text());ev=[{"path":str(CERT.relative_to(ROOT)),"result_id":v["result_id"],"sha256":sha(CERT)}]
 return {"schema":"pure-weyl-residual-atlas-fragment-v1","schema_version":"1.0.0","team":"observer","generated_by":str(GEN.relative_to(ROOT)),"generated_by_sha256":sha(GEN),"status_vocabulary":["CERTIFIED","OBSTRUCTED","OPEN","NOT_APPLICABLE","NO_CERTIFIED_MAP"],"description_axes":["causal","symplectic","nonlinear","observational","quantum"],"entries":[{"id":"observer.general.charged_time_emitter_receiver_composition","scope":{"theory":"Hamiltonian/BV theories with two or three surviving physical action-angle clocks","background":"declared causal path groupoid satisfying the conditional event-current contract","boundaries":"compact receiver supports and retarded edges; algebraic reverse is not a physical advanced edge","charge_sector":"separately labelled unrestricted Q_i fibres with explicit edge and vertex crosswalks","carrier":"conditional nonzero sampled event-current periods and transported phase records","degree":0,"parity":"primitive orientation lines eta_i; edge factor eta_i/eta_j","ell":"all receiver modes satisfying the contract","m":"all","k":"all/NOT_APPLICABLE according to background","omega":"sampled nonzero clock slopes on each declared edge"},"descriptions":{"causal":"CERTIFIED","symplectic":"CERTIFIED","nonlinear":"OPEN","observational":"CERTIFIED","quantum":"NO_CERTIFIED_MAP"},"mode_data":{"dispersion":cl("CERTIFIED","Exact comparison, orientation, charge and path-composition algebra is certified; no wave dispersion is inferred."),"lee_wald":cl("NO_CERTIFIED_MAP","A theory-specific nonradical receiver pairing is required before physical instantiation."),"taub_maps":cl("NO_CERTIFIED_MAP","No second-order source or nonlinear receiver is part of the theorem."),"resonance":cl("OPEN","The comparison algebra does not decide background-specific resonance."),"second_order":{"equation":"L_barPhi v = -(1/2) D^2 E_barPhi[u,u]","bounded_or_finite_quasiperiodic":cl("OPEN","Requires a theory-specific correction class."),"smooth_secular":cl("OPEN","No nonlinear secular source is supplied."),"causal_retarded":cl("OPEN","Path algebra is scoped to declared retarded edges; no background-specific Green image is supplied.")}},"evidence":ev,"claim_boundary":v["claim_boundary"]}],"verification_commands":["python3 closed_universe_observers/generate_charged_time_emitter_receiver_composition_theorem.py --check","python3 closed_universe_observers/verify_charged_time_emitter_receiver_composition_theorem.py","python3 -m pytest -q closed_universe_observers/tests/test_charged_time_emitter_receiver_composition_theorem.py","python3 residual_atlas/validate_fragment.py residual_atlas/charged-time-emitter-receiver-composition-theorem-fragment-v1.json"]}
def render(v):return json.dumps(v,indent=2,sort_keys=True)+"\n"
if __name__=="__main__":
 p=argparse.ArgumentParser();p.add_argument("--emit",action="store_true");p.add_argument("--check",action="store_true");a=p.parse_args();v=build()
 if a.emit:OUT.write_text(render(v))
 if a.check and OUT.read_text()!=render(v):raise AssertionError("atlas drift")
 print("CHARGED_TIME_EMITTER_RECEIVER_COMPOSITION_THEOREM_ATLAS: PASS")
