#!/usr/bin/env python3
import argparse,hashlib,json
from pathlib import Path
ROOT=Path(__file__).resolve().parents[2];GEN=Path(__file__).resolve();CERT=ROOT/"closed_universe_observers/certificates/CHARGED_TIME_RECEIVER_ADMISSIBILITY_CROSSWALK_V1.json";OUT=ROOT/"residual_atlas/charged-time-receiver-admissibility-crosswalk-fragment-v1.json"
def sha(p):return hashlib.sha256(p.read_bytes()).hexdigest()
def cl(s,t):return {"status":s,"statement":t}
def build():
 v=json.loads(CERT.read_text());ev=[{"path":str(CERT.relative_to(ROOT)),"result_id":v["result_id"],"sha256":sha(CERT)}]
 return {"schema":"pure-weyl-residual-atlas-fragment-v1","schema_version":"1.0.0","team":"observer","generated_by":str(GEN.relative_to(ROOT)),"generated_by_sha256":sha(GEN),"status_vocabulary":["CERTIFIED","OBSTRUCTED","OPEN","NOT_APPLICABLE","NO_CERTIFIED_MAP"],"description_axes":["causal","symplectic","nonlinear","observational","quantum"],"entries":[{"id":"observer.general.charged_time_receiver_admissibility_crosswalk","scope":{"theory":"Hamiltonian/BV theories with action-derived physical receiver candidates","background":"any explicitly scoped same-background carrier; no name-based cross-background identification","boundaries":"compact receiver support, retarded path maps and regular monotone clock bands","charge_sector":"explicit unrestricted charge fibres with separately typed D, R and K actions","carrier":"machine-readable receiver object and charge-fibre crosswalk interface","degree":0,"parity":"primitive orientation eta and receiver coorientation explicitly mapped","ell":"all modes individually populated through the interface","m":"all","k":"all/NOT_APPLICABLE according to background","omega":"nonzero sampled denominator margin on each populated clock band"},"descriptions":{"causal":"CERTIFIED","symplectic":"CERTIFIED","nonlinear":"OPEN","observational":"CERTIFIED","quantum":"NO_CERTIFIED_MAP"},"mode_data":{"dispersion":cl("NOT_APPLICABLE","The interface classifies receiver admissibility and does not infer dispersion."),"lee_wald":cl("NO_CERTIFIED_MAP","Each populated receiver must export a descended nonradical pairing and nonzero period."),"taub_maps":cl("NO_CERTIFIED_MAP","No second-order source is supplied."),"resonance":cl("OPEN","No background-specific resonance is decided."),"second_order":{"equation":"L_barPhi v = -(1/2) D^2 E_barPhi[u,u]","bounded_or_finite_quasiperiodic":cl("OPEN","Requires a populated theory-specific correction class."),"smooth_secular":cl("OPEN","No nonlinear secular source is supplied."),"causal_retarded":cl("OPEN","The interface requires a retarded support map but does not populate one for a background.")}},"evidence":ev,"claim_boundary":v["claim_boundary"]}],"verification_commands":["python3 closed_universe_observers/generate_charged_time_receiver_admissibility_crosswalk.py --check","python3 closed_universe_observers/verify_charged_time_receiver_admissibility_crosswalk.py","python3 -m pytest -q closed_universe_observers/tests/test_charged_time_receiver_admissibility_crosswalk.py","python3 residual_atlas/validate_fragment.py residual_atlas/charged-time-receiver-admissibility-crosswalk-fragment-v1.json"]}
def render(v):return json.dumps(v,indent=2,sort_keys=True)+"\n"
if __name__=="__main__":
 p=argparse.ArgumentParser();p.add_argument("--emit",action="store_true");p.add_argument("--check",action="store_true");a=p.parse_args();v=build()
 if a.emit:OUT.write_text(render(v))
 if a.check and OUT.read_text()!=render(v):raise AssertionError("atlas drift")
 print("CHARGED_TIME_RECEIVER_ADMISSIBILITY_CROSSWALK_ATLAS: PASS")
