#!/usr/bin/env python3
import argparse,hashlib,json
from pathlib import Path
ROOT=Path(__file__).resolve().parents[2]; GEN=Path(__file__).resolve(); CERT=ROOT/"closed_universe_observers/certificates/CHARGED_PHYSICAL_TIME_RELATIONAL_EVENT_MAP_THEOREM_V1.json"; OUT=ROOT/"residual_atlas/charged-physical-time-relational-event-map-theorem-fragment-v1.json"
def sha(p):return hashlib.sha256(p.read_bytes()).hexdigest()
def cl(s,t):return {"status":s,"statement":t}
def build():
 v=json.loads(CERT.read_text()); ev=[{"path":str(CERT.relative_to(ROOT)),"result_id":v["result_id"],"sha256":sha(CERT)}]
 return {"schema":"pure-weyl-residual-atlas-fragment-v1","schema_version":"1.0.0","team":"observer","generated_by":str(GEN.relative_to(ROOT)),"generated_by_sha256":sha(GEN),"status_vocabulary":["CERTIFIED","OBSTRUCTED","OPEN","NOT_APPLICABLE","NO_CERTIFIED_MAP"],"description_axes":["causal","symplectic","nonlinear","observational","quantum"],"entries":[{"id":"observer.general.charged_physical_time_relational_event_map","scope":{"theory":"Hamiltonian/BV theories with one surviving physical action-angle clock pair","background":"any oriented spacetime satisfying the declared local BV and compact-support hypotheses","boundaries":"closed or compact receiver support; regular clock level","charge_sector":"unrestricted physical Q; R and D charged, K=D-H'(Q)R separate","carrier":"conditional compact receiver bicomplex class [A] and action-angle pair (psi,Q)","degree":0,"parity":"NOT_APPLICABLE","ell":"all receiver modes satisfying the contract","m":"all","k":"all/NOT_APPLICABLE according to background","omega":"H'(Q) on a fixed-sign monotonicity interval"},"descriptions":{"causal":"OPEN","symplectic":"CERTIFIED","nonlinear":"OPEN","observational":"CERTIFIED","quantum":"NO_CERTIFIED_MAP"},"mode_data":{"dispersion":cl("CERTIFIED","Exact action-angle flow and primitive clock-basis composition are certified; no background-specific wave dispersion is inferred."),"lee_wald":cl("CERTIFIED","The theorem assumes and uses the nondegenerate clock Darboux pair; receiver nontriviality is conditional on pairing descent."),"taub_maps":cl("NO_CERTIFIED_MAP","No theory-specific second-order source is part of the general theorem."),"resonance":cl("OPEN","Lifted, orbital and modulated stability are separated without asserting a model-specific resonance theorem."),"second_order":{"equation":"L_barPhi v = -(1/2) D^2 E_barPhi[u,u]","bounded_or_finite_quasiperiodic":cl("OPEN","Requires a theory-specific receiver and correction class."),"smooth_secular":cl("OPEN","The theorem permits modulated/secular clock descriptions but supplies no model source."),"causal_retarded":cl("OPEN","Requires a theory-specific causal receiver class and Green image.")}},"evidence":ev,"claim_boundary":v["claim_boundary"]}],"verification_commands":["python3 closed_universe_observers/generate_charged_physical_time_event_map_theorem.py --check","python3 closed_universe_observers/verify_charged_physical_time_event_map_theorem.py","python3 -m pytest -q closed_universe_observers/tests/test_charged_physical_time_event_map_theorem.py","python3 residual_atlas/validate_fragment.py residual_atlas/charged-physical-time-relational-event-map-theorem-fragment-v1.json"]}
def render(v):return json.dumps(v,indent=2,sort_keys=True)+"\n"
if __name__=="__main__":
 p=argparse.ArgumentParser();p.add_argument("--emit",action="store_true");p.add_argument("--check",action="store_true");a=p.parse_args();v=build()
 if a.emit:OUT.write_text(render(v))
 if a.check and OUT.read_text()!=render(v):raise AssertionError("atlas drift")
 print("CHARGED_PHYSICAL_TIME_RELATIONAL_EVENT_MAP_THEOREM_ATLAS: PASS")
