from __future__ import annotations

import copy
import json
from pathlib import Path
import unittest

from foundations.build_matrix_site_v2 import build_dataset, generated
from foundations.check_matrix_site_v2 import check
from foundations.verify_matrix_site_v2 import RESULT, REPORT, load, verify

ROOT = Path(__file__).resolve().parents[2]


class MatrixSiteTests(unittest.TestCase):
    def test_dataset_separates_coverage_and_migration(self):
        data = build_dataset()
        self.assertEqual(len(data["cells"]), 576)
        self.assertEqual(data["counts"]["coverage_classified"], 576)
        self.assertEqual(data["counts"]["migration_reviewed"], 576)
        self.assertEqual(data["counts"]["migration_pending"], 0)
        self.assertEqual(data["counts"]["reviewed_no_transfer"], 88)

    def test_plain_language_guide_covers_every_axis_option(self):
        data = build_dataset()
        self.assertEqual([len(axis["keys"]) for axis in data["axes"]], [6, 6, 16])
        self.assertTrue(all(axis["plain_name"] and axis["guide_question"] for axis in data["axes"]))
        self.assertTrue(all(key["plain_meaning"] for axis in data["axes"] for key in axis["keys"]))

    def test_reviewed_gap_partition_is_fail_closed(self):
        data = build_dataset()
        reviewed = [x for x in data["cells"] if x["migration_status"] == "REVIEWED_NO_TRANSFER"]
        synthetic = [x for x in data["cells"] if not x["emitted"]]
        self.assertEqual((len(reviewed), len(synthetic)), (88, 0))
        self.assertEqual(sum(x["status"] == "REVIEWED_GAP" for x in data["cells"]), 169)
        self.assertEqual(sum(x["status"] == "NOT_MAPPED" for x in data["cells"]), 0)
        self.assertTrue(all(x["evidence"] and x["migration_evidence"] for x in reviewed))
        self.assertEqual(sum(x["migration_status"] == "DIRECT_COORDINATE_REVIEW" for x in data["cells"]), 124)

    def test_generated_outputs_are_current(self):
        for path, content in generated().items():
            self.assertTrue(path.is_file(), path)
            self.assertEqual(path.read_bytes(), content, path)

    def test_public_title_names_the_reverse_physics_programme(self):
        html = (ROOT / "foundations/matrix_site_assets/index.html").read_text()
        self.assertIn("<title>Reverse Physics Atlas — Mathematics, Theories, and Evidence</title>", html)
        self.assertIn("<h1>Reverse Physics <span>Atlas</span></h1>", html)
        self.assertEqual(build_dataset()["title"], "Reverse Physics Atlas")

    def test_independent_checker(self):
        errors, summary = check()
        self.assertEqual(errors, [])
        self.assertEqual(summary["total_not_mapped"], 0)

    def test_verifier(self):
        self.assertEqual(verify()[0], [])

    def test_absence_promotion_fails(self):
        result = copy.deepcopy(load(RESULT))
        result["claim_flags"]["reviewed_gap_means_absent"] = True
        self.assertTrue(verify(result=result)[0])

    def test_report_boundary_fails(self):
        report = REPORT.read_text().replace("it is not a result", "it is a result")
        self.assertTrue(verify(report=report)[0])

    def test_static_shell_exposes_migration_review(self):
        html = (ROOT / "foundations/site/index.html").read_text()
        base_app = (ROOT / "foundations/site/app.js").read_text()
        assembly_data = (ROOT / "foundations/site/assemblies.js").read_text()
        app = (ROOT / "foundations/site/migration-review.js").read_text()
        css = (ROOT / "foundations/site/styles.css").read_text()
        self.assertNotIn("https://", html)
        self.assertIn('<script src="migration-review.js"></script>', html)
        self.assertIn('data-view="guide"', html)
        self.assertIn('data-view="viability"', html)
        self.assertIn('data-view="assemblies"', html)
        self.assertIn('data-view="completion"', html)
        self.assertIn('id="completionView"', html)
        self.assertIn('id="completionExplorer"', html)
        self.assertIn("Represented Green action certified", app)
        self.assertIn("Scoped common snapshot accepted", app)
        self.assertIn("Full cylinder flow certified", app)
        self.assertIn("Algebraic q2 lift certified", app)
        self.assertIn("Valid construction, unproven identity", app)
        self.assertIn("First nonlinear causal response certified", app)
        self.assertIn("One response is not an interacting theory", app)
        self.assertIn("Finite polarized recursion certified", app)
        self.assertIn("Two four-leaf terms expose the boundary", app)
        self.assertIn("Formal coefficients certified; stronger name withheld", app)
        self.assertIn("The first BV promotion gap is at λ²", app)
        self.assertIn("Field-equation type gate corrected and closed", app)
        self.assertIn("The stronger inverse is impossible", app)
        self.assertIn("Read the audited V32 report", app)
        self.assertIn("Minimal cubic L∞ package completed", app)
        site_data = json.loads((ROOT / "foundations/site/data.json").read_text())
        self.assertEqual(site_data["completion_atlas"]["strict_minimal_q3_completion"]["arity_three_channels"], 72)
        self.assertIn("The quadratic-only λ² source is not closed", app)
        self.assertIn("The target has now been met at minimal scope", app)
        self.assertIn("Read Gate V14 reconciliation", app)
        self.assertIn("First nonlinear correction constructed", app)
        self.assertIn("Cubic family census and vv lift", app)
        self.assertIn("Inspect exact component tables", app)
        self.assertIn("Curved quadratic canonical lift completed", app)
        self.assertIn("Number(hhHvLift.hh_field_coefficients).toLocaleString()", app)
        self.assertIn("Number(hhHvLift.combined_cotangent_coefficients).toLocaleString()", app)
        self.assertEqual(site_data["completion_atlas"]["strict_hh_hv_auxiliary_cotangent_lift"]["combined_cotangent_coefficients"], 3907)
        self.assertTrue(site_data["completion_atlas"]["strict_hh_hv_auxiliary_cotangent_lift"]["full_quadratic_BV_cotangent_lift_serialized"])
        self.assertTrue(site_data["completion_atlas"]["strict_gate_v14_reconciliation"]["full_source_q2_assembled"])
        self.assertFalse(site_data["completion_atlas"]["strict_gate_v14_reconciliation"]["full_source_q3_assembled"])
        self.assertTrue(site_data["completion_atlas"]["claim_flags"]["strict_386_diff_bv_representation_component_complete"])
        self.assertTrue(site_data["completion_atlas"]["claim_flags"]["strict_386_exhaustive_full_nonlinear_bv_family_census"])
        self.assertTrue(site_data["completion_atlas"]["claim_flags"]["strict_386_full_source_q2_assembled"])
        self.assertEqual(site_data["completion_atlas"]["strict_gate_v14_reconciliation"]["accepted_top_level_hashes"], 1)
        self.assertEqual(site_data["completion_atlas"]["strict_source_q2_common_assembly"]["q1_q2_defects"], 0)
        self.assertIn("Common source q2 accepted", app)
        self.assertIn("The missing nonlinear ghost manifest adds no new families", app)
        self.assertIn('id="viabilityView"', html)
        self.assertIn('<script src="viability.js"></script>', html)
        self.assertIn('id="dimensionGuide"', html)
        self.assertIn("Regime × carrier × obligation", base_app)
        self.assertIn("Every result answers three different questions", base_app)
        self.assertIn("Why “general relativity works” is too compressed", base_app)
        self.assertIn('["viability", "assemblies", "guide", "graph", "ladder", "completion"]', base_app)
        self.assertIn("The question changes even when the equation does not", base_app)
        self.assertIn("Small glossary", base_app)
        self.assertIn("For reviewers: how the evidence letters and migration audit work", base_app)
        self.assertIn("Coverage readiness map", base_app)
        self.assertIn("Coverage envelope, not a composed theory", base_app)
        self.assertIn("No complete observationally validated theory is certified", base_app)
        self.assertIn("paretoProfiles", base_app)
        self.assertIn("Seven independent maturity rails", base_app)
        self.assertIn("Numerical reproduction is not empirical validation", base_app)
        self.assertIn("Euclidean/Krein carrier boundary", base_app)
        self.assertIn("Bounded assembly complete", base_app)
        self.assertIn("Field equations to Cassini", base_app)
        self.assertIn("Bounded model tests", base_app)
        self.assertIn("Research programmes", base_app)
        self.assertIn("Interfaces & calibration", base_app)
        self.assertIn('params.set("panel", state.assemblyPanel)', base_app)
        self.assertIn("Weyl action to NGC 3198", base_app)
        self.assertIn("random-error gate failed", base_app)
        self.assertIn("No parameter is refitted", base_app)
        self.assertIn("mannheimResidualSvg", base_app)
        self.assertIn("Residual audit against SPARC random errors", base_app)
        self.assertIn("±2 pointwise reference band—not the aggregate gate", base_app)
        self.assertIn("FOUNDATIONAL_MANNHEIM_NGC3198_MODEL_ASSEMBLY_V1", assembly_data)
        self.assertIn("commonFitCurveSvg", base_app)
        self.assertIn("NGC 3198 head-to-head control", base_app)
        self.assertIn("Scoped winner: GR + NFW", base_app)
        self.assertIn("FOUNDATIONAL_NGC3198_COMMON_FIT_COMPARISON_V1", assembly_data)
        self.assertIn("Meet the research programmes", base_app)
        self.assertIn("Bateman–Turok", assembly_data)
        self.assertIn("Mannheim conformal gravity", assembly_data)
        self.assertIn("Pure-Weyl BV–BFV", assembly_data)
        self.assertIn("camp-profile", base_app)
        self.assertIn("Applicability mask", base_app)
        self.assertIn("External positive control", base_app)
        self.assertIn("red is reserved for an explicit incompatibility", base_app.lower())
        self.assertIn("CERTIFIED ·", base_app)
        self.assertIn("GRAPH_PATHWAYS", base_app)
        self.assertIn("Relation ledger", base_app)
        self.assertIn("graph-edge-hit", base_app)
        self.assertIn("No direct certificate yet", base_app)
        self.assertNotIn("No stronger interpretation is licensed", base_app)
        self.assertNotIn("Open but seeded", html)
        self.assertIn("Open cells with a starting point", html)
        self.assertIn("Pieces only and Priority gap cells", html)
        self.assertIn("migration_evidence", app)
        self.assertIn("175-coordinate surface audit", app)
        self.assertIn("77 separately typed cells", app)
        self.assertIn("Where effort has the highest expected value", app)
        self.assertIn("Classical sign repair certified", app)
        self.assertIn("eight cyclicity defects", app)
        self.assertIn("Exact split local SDR", app)
        self.assertIn("190-entry H_alg", app)
        self.assertIn("graph coordinates", app)
        self.assertIn("RANK_ONLY_FEASIBLE", (ROOT / "foundations/site/data.json").read_text())
        self.assertIn("general non-cone 104-row no-go", app)
        self.assertIn('!["Migration unresolved", "Not mapped"].includes(label) || count > 0', base_app)
        self.assertIn("Reviewed gap versus priority gap", base_app)
        self.assertIn("repeat(auto-fit, minmax(9rem, 1fr))", css)
        self.assertIn("writing-mode: vertical-rl", css)
        self.assertIn("grid-template-columns: 12rem minmax(0, 1fr)", css)
        self.assertIn(".camp-gallery", css)
        self.assertIn(".curve-prediction", css)
        self.assertIn(".assembly-subtabs", css)
        self.assertIn(".assembly-panel.active", css)
        self.assertIn(".guide-equation", css)
        manifest = json.loads((ROOT / "foundations/site/manifest.json").read_text())
        self.assertGreaterEqual(len(manifest["outputs"]), 38)
        self.assertTrue((ROOT / "foundations/site/sources/foundations/results/FOUNDATIONAL_INTERSECTION_CUBE_V4.json").is_file())
        self.assertTrue((ROOT / "foundations/site/sources/foundations/results/FOUNDATIONAL_INTERSECTION_CUBE_V5.json").is_file())
        self.assertTrue((ROOT / "foundations/site/sources/foundations/results/FOUNDATIONAL_INTERSECTION_CUBE_V6.json").is_file())
        self.assertTrue((ROOT / "foundations/site/sources/foundations/results/FOUNDATIONAL_INTERSECTION_CUBE_V7.json").is_file())
        self.assertTrue((ROOT / "foundations/site/sources/foundations/results/FOUNDATIONAL_FINITE_OPERATOR_TEN_CELL_CLOSURE_V1.json").is_file())
        self.assertTrue((ROOT / "foundations/site/sources/foundations/results/FOUNDATIONAL_INTERSECTION_CUBE_V8.json").is_file())
        self.assertTrue((ROOT / "foundations/site/sources/foundations/results/FOUNDATIONAL_INTERSECTION_CUBE_V9.json").is_file())
        self.assertTrue((ROOT / "foundations/site/sources/foundations/results/FOUNDATIONAL_INTERSECTION_CUBE_V11.json").is_file())
        self.assertTrue((ROOT / "foundations/site/sources/foundations/results/FOUNDATIONAL_INTERSECTION_CUBE_V14.json").is_file())
        self.assertTrue((ROOT / "foundations/site/sources/foundations/results/FOUNDATIONAL_INTERSECTION_CUBE_V15.json").is_file())
        self.assertTrue((ROOT / "foundations/site/sources/foundations/results/FOUNDATIONAL_SCALAR_MINKOWSKI_BIWAVE_GREEN_V1.json").is_file())
        self.assertTrue((ROOT / "foundations/site/sources/foundations/results/FOUNDATIONAL_SCALAR_BIWAVE_TO_WEYL_BV_DEPENDENCY_DELTA_V1.json").is_file())
        self.assertIn("FOUNDATIONAL_CODED_WAVE_OBSERVABLE_RECONSTRUCTION_V1", assembly_data + base_app + (ROOT / "foundations/site/data.json").read_text())
        self.assertIn("FOUNDATIONAL_CODED_LOCAL_WEAK_WAVE_TEST_CLASS_V1", assembly_data + base_app + (ROOT / "foundations/site/data.json").read_text())
        self.assertTrue((ROOT / "foundations/site/sources/foundations/results/FOUNDATIONAL_BT_EUCLIDEAN_LATTICE_IMPORT_V1.json").is_file())
        self.assertTrue((ROOT / "foundations/site/sources/foundations/results/FOUNDATIONAL_FULL_SURFACE_GAP_AUDIT_V1.json").is_file())
        self.assertTrue((ROOT / "foundations/site/sources/foundations/results/FOUNDATIONAL_FINITE_BRST_TWENTY_CELL_CLOSURE_V1.json").is_file())
        self.assertTrue((ROOT / "foundations/site/sources/foundations/results/FOUNDATIONAL_BT_CORNER_BORN_INTERFACE_V1.json").is_file())
        self.assertTrue((ROOT / "foundations/site/sources/foundations/results/FOUNDATIONAL_KREIN_FOCK_GROUND_STATE_DYNAMICS_INTERFACE_V1.json").is_file())
        self.assertTrue((ROOT / "foundations/site/sources/foundations/results/FOUNDATIONAL_GR_CASSINI_MODEL_ASSEMBLY_V1.json").is_file())
        self.assertTrue((ROOT / "foundations/site/sources/foundations/results/FOUNDATIONAL_CYLINDER_WAVE_STRENGTH_LADDER_V2.json").is_file())
        self.assertTrue((ROOT / "foundations/site/sources/foundations/results/FOUNDATIONAL_LORENTZIAN_WEYL_BV_COMPLETION_ATLAS_V3.json").is_file())
        self.assertTrue((ROOT / "foundations/site/sources/foundations/results/FOUNDATIONAL_LORENTZIAN_WEYL_BV_COMPLETION_ATLAS_V10.json").is_file())
        self.assertTrue((ROOT / "foundations/site/sources/foundations/results/FOUNDATIONAL_LORENTZIAN_WEYL_BV_COMPLETION_ATLAS_V13.json").is_file())
        self.assertTrue((ROOT / "foundations/site/sources/foundations/results/FOUNDATIONAL_LORENTZIAN_WEYL_BV_COMPLETION_ATLAS_V14.json").is_file())
        self.assertTrue((ROOT / "foundations/site/sources/foundations/results/FOUNDATIONAL_LORENTZIAN_WEYL_BV_COMPLETION_ATLAS_V15.json").is_file())
        self.assertTrue((ROOT / "foundations/site/sources/foundations/results/FOUNDATIONAL_LORENTZIAN_WEYL_BV_COMPLETION_ATLAS_V16.json").is_file())
        self.assertTrue((ROOT / "foundations/site/sources/foundations/results/FOUNDATIONAL_LORENTZIAN_WEYL_BV_COMPLETION_ATLAS_V17.json").is_file())
        self.assertTrue((ROOT / "foundations/site/sources/foundations/results/FOUNDATIONAL_LORENTZIAN_WEYL_BV_COMPLETION_ATLAS_V18.json").is_file())
        self.assertTrue((ROOT / "foundations/site/sources/foundations/results/FOUNDATIONAL_LORENTZIAN_WEYL_BV_COMPLETION_ATLAS_V19.json").is_file())
        self.assertTrue((ROOT / "foundations/site/sources/foundations/results/FOUNDATIONAL_LORENTZIAN_WEYL_BV_COMPLETION_ATLAS_V20.json").is_file())
        self.assertTrue((ROOT / "foundations/site/sources/foundations/results/FOUNDATIONAL_LORENTZIAN_WEYL_BV_COMPLETION_ATLAS_V21.json").is_file())
        self.assertTrue((ROOT / "foundations/site/sources/quantum-weyl/classical_import/certificates/STRICT_386_CANONICAL_SHEAR_COMPONENT_JETS_V1.json").is_file())
        self.assertTrue((ROOT / "foundations/site/sources/quantum-weyl/classical_import/certificates/STRICT_386_GRAPH_Q1_SDR_COMPONENT_JETS_V1.json").is_file())
        self.assertTrue((ROOT / "foundations/site/sources/quantum-weyl/classical_import/certificates/STRICT_386_GRAPH_GREEN_ACTION_NAME_V1.json").is_file())
        self.assertTrue((ROOT / "foundations/site/sources/quantum-weyl/classical_import/certificates/STRICT_386_UNARY_CAUSAL_COMMON_SNAPSHOT_V1.json").is_file())
        self.assertTrue((ROOT / "foundations/site/sources/quantum-weyl/classical_import/certificates/STRICT_386_FULL_D_ACTION_V1.json").is_file())
        self.assertTrue((ROOT / "foundations/site/sources/quantum-weyl/classical_import/certificates/STRICT_386_STABILIZED_Q2_GREEN_COMPOSITION_PREFLIGHT_V1.json").is_file())
        self.assertTrue((ROOT / "foundations/site/sources/quantum-weyl/classical_import/certificates/STRICT_386_POLARIZED_FORMAL_MOLLER_COEFFICIENTS_V1.json").is_file())
        self.assertTrue((ROOT / "foundations/site/sources/quantum-weyl/classical_import/certificates/STRICT_386_FIELD_EQUATION_GREEN_QUOTIENT_INVERSE_V1.json").is_file())
        self.assertTrue((ROOT / "foundations/site/sources/quantum-weyl/classical_import/certificates/STRICT_386_RECURSIVE_CAUSAL_TREE_DOMAINS_V1.json").is_file())
        self.assertTrue((ROOT / "foundations/site/sources/quantum-weyl/classical_import/certificates/STRICT_386_STABILIZED_Q2_LIFT_PREFLIGHT_V1.json").is_file())
        self.assertTrue((ROOT / "foundations/site/sources/quantum-weyl/classical_import/certificates/CLASSICAL_IMPORT_GATE_V7_RECONCILIATION.json").is_file())
        self.assertTrue((ROOT / "foundations/site/sources/quantum-weyl/classical_import/REPORT_STRICT_386_FULL_D_ACTION_V1.md").is_file())
        self.assertTrue((ROOT / "foundations/site/sources/quantum-weyl/classical_import/REPORT_STRICT_386_STABILIZED_Q2_LIFT_PREFLIGHT_V1.md").is_file())
        self.assertTrue((ROOT / "foundations/site/sources/quantum-weyl/classical_import/REPORT_GATE_V7.md").is_file())
        self.assertTrue((ROOT / "foundations/site/sources/quantum-weyl/classical_import/certificates/STRICT_386_LOCAL_SDR_COMPONENT_MAPS_V1.json").is_file())
        self.assertTrue((ROOT / "foundations/site/sources/quantum-weyl/classical_import/certificates/STRICT_386_FULL_Q1_SPLIT_SIGN_GATE_V1.json").is_file())
        self.assertTrue((ROOT / "foundations/site/sources/quantum-weyl/classical_import/certificates/CLASSICAL_IMPORT_GATE_V3_RECONCILIATION.json").is_file())
        self.assertTrue((ROOT / "foundations/site/sources/quantum-weyl/classical_import/certificates/STRICT_DFINITE_RESIDUAL_SDR_V1.json").is_file())
        self.assertTrue((ROOT / "foundations/site/sources/foundations/results/FOUNDATIONAL_INTERSECTION_CUBE_MIGRATION_AUDIT_V2.json").is_file())


if __name__ == "__main__":
    unittest.main()
