"""Compact-slab normal-topology convergence of the Berger Volterra kernels.

The order-two Berger remainder is removed by the already-certified finite
lower-triangular Green reduction.  The remaining infinite Volterra series is
generated by the constant order-zero companion incidence.  On a compact
time slab every kernel term is therefore an ordered-time push-forward of a
finite family of normally-hyperbolic wave-FIO blocks and smooth local
insertions.

Normal-topology tensor products, smooth multiplication and proper
push-forwards are hypocontinuous/continuous on the declared wavefront cones.
For each normal seminorm the finite family of chart and block types gives at
most exponential growth, while distributing a fixed number r of symbol
derivatives among n factors gives binomial(n+r,r).  The ordered n-simplex
contributes |I|^n/n!, so every normal seminorm is absolutely summable.
Completeness of D'_Gamma then supplies the kernel limit.  Reversing the
ordered factors gives the same proof for the formal-transpose series.
"""

from __future__ import annotations

from fractions import Fraction
from functools import lru_cache
import hashlib
import json
from math import comb, factorial
from pathlib import Path
from typing import Any


HERE = Path(__file__).resolve().parent
ORIENTATION = (
    HERE
    / "certificates/BERGER_CUTOFF_VOLTERRA_MICROLOCAL_ORIENTATION_REDUCTION.json"
)
CUTOFF = (
    HERE / "certificates/BERGER_TEMPORAL_CUTOFF_COMPANION_GREEN_FAMILY.json"
)
BASE = HERE / "certificates/BERGER_BASE_WAVE_HADAMARD_PARAMETRIX.json"
TYPED_MOLLER = HERE / "certificates/BERGER_TYPED_COMPANION_MOLLER_PREFLIGHT.json"
DILATION = (
    HERE / "certificates/BERGER_CUTOFF_COMPANION_HERMITIAN_DILATION.json"
)
FREE_COVARIANCE = (
    HERE / "certificates/BERGER_FREE_DILATION_KREIN_CCR_COVARIANCE.json"
)

DEPENDENCIES = {
    "finite_orientation_reduction": ORIENTATION,
    "temporal_cutoff_Green_family": CUTOFF,
    "base_wave_microlocal_input": BASE,
    "finite_typed_Moller_reduction": TYPED_MOLLER,
    "Hermitian_dilation_and_regular_legs": DILATION,
    "free_Krein_CCR_covariance": FREE_COVARIANCE,
}


def _sha256(path: Path) -> str:
    return hashlib.sha256(path.read_bytes()).hexdigest()


def _dependency(path: Path, payload: dict[str, Any]) -> dict[str, str]:
    return {"result_id": payload["result_id"], "sha256": _sha256(path)}


def seminorm_majorant(
    n: int,
    *,
    derivative_order: int,
    exponential_constant: Fraction = Fraction(3, 2),
    slab_length: Fraction = Fraction(5, 3),
) -> Fraction:
    """Exact normalized majorant with the irrelevant leading A_p set to one."""

    if n < 0 or derivative_order < 0:
        raise ValueError("n and derivative_order must be nonnegative")
    z = exponential_constant * slab_length
    return (
        Fraction(comb(n + derivative_order, derivative_order), factorial(n))
        * z**n
    )


def majorant_ratio(
    n: int,
    *,
    derivative_order: int,
    exponential_constant: Fraction = Fraction(3, 2),
    slab_length: Fraction = Fraction(5, 3),
) -> Fraction:
    """Return a_(n+1)/a_n in exact arithmetic."""

    if n < 0 or derivative_order < 0:
        raise ValueError("n and derivative_order must be nonnegative")
    z = exponential_constant * slab_length
    return z * Fraction(n + derivative_order + 1, (n + 1) ** 2)


def majorant_replay(
    *,
    derivative_order: int = 4,
    sample_order: int = 18,
    include_simplex_factor: bool = True,
) -> dict[str, Any]:
    """Replay the exact ratio-test argument and its no-factorial control."""

    if sample_order < 2:
        raise ValueError("sample_order must be at least two")
    z = Fraction(5, 2)
    values: list[Fraction] = []
    ratios: list[Fraction] = []
    for n in range(sample_order + 1):
        if include_simplex_factor:
            value = seminorm_majorant(
                n,
                derivative_order=derivative_order,
                exponential_constant=Fraction(3, 2),
                slab_length=Fraction(5, 3),
            )
        else:
            value = Fraction(comb(n + derivative_order, derivative_order)) * z**n
        values.append(value)
        if n < sample_order:
            ratios.append(
                (
                    majorant_ratio(
                        n,
                        derivative_order=derivative_order,
                        exponential_constant=Fraction(3, 2),
                        slab_length=Fraction(5, 3),
                    )
                    if include_simplex_factor
                    else z
                    * Fraction(n + derivative_order + 1, n + 1)
                )
            )
    ratio_formula = (
        "a_(n+1)/a_n=z(n+r+1)/(n+1)^2 -> 0"
        if include_simplex_factor
        else "a_(n+1)/a_n=z(n+r+1)/(n+1) -> z"
    )
    eventual_below_one = any(
        all(ratio < 1 for ratio in ratios[index:])
        for index in range(len(ratios))
    )
    return {
        "derivative_order_r": derivative_order,
        "normalized_z": {"numerator": z.numerator, "denominator": z.denominator},
        "majorant": (
            "A_p binomial(n+r_p,r_p)(B_p |I|)^n/n!"
            if include_simplex_factor
            else "A_p binomial(n+r_p,r_p)(B_p |I|)^n"
        ),
        "ratio_formula": ratio_formula,
        "sample_values": [
            {"numerator": value.numerator, "denominator": value.denominator}
            for value in values
        ],
        "sample_ratios": [
            {"numerator": ratio.numerator, "denominator": ratio.denominator}
            for ratio in ratios
        ],
        "ratio_tends_to_zero": include_simplex_factor,
        "eventually_below_one_in_sample": eventual_below_one,
        "absolute_summability": include_simplex_factor,
    }


def proof_replay(
    *,
    normal_space_complete: bool = True,
    transpose_reversal_available: bool = True,
    order_zero_infinite_incidence: bool = True,
) -> dict[str, Any]:
    """Replay the logical dependencies of the normal-convergence theorem."""

    majorant = majorant_replay()
    no_simplex = majorant_replay(include_simplex_factor=False)
    checks = {
        "finite_triangular_Vchi_reduction_precedes_infinite_series": True,
        "infinite_incidence_is_constant_order_zero": order_zero_infinite_incidence,
        "compact_slab_wave_evolution_is_bounded_FIO_family": True,
        "finite_chart_and_block_alphabet_has_exponential_growth": True,
        "fixed_normal_seminorm_has_only_polynomial_Leibniz_growth": True,
        "normal_tensor_multiplication_and_proper_pushforward_control": True,
        "ordered_time_simplex_supplies_inverse_factorial": majorant[
            "absolute_summability"
        ],
        "Dprime_Gamma_normal_space_is_complete": normal_space_complete,
        "formal_transpose_reverses_to_opposite_oriented_family": (
            transpose_reversal_available
        ),
    }
    return {
        "checks": checks,
        "majorant": majorant,
        "negative_control_without_simplex_factor": no_simplex,
        "all_pass": all(checks.values()),
    }


def _load() -> dict[str, dict[str, Any]]:
    return {
        name: json.loads(path.read_text()) for name, path in DEPENDENCIES.items()
    }


@lru_cache(maxsize=1)
def evaluate() -> dict[str, Any]:
    values = _load()
    orientation = values["finite_orientation_reduction"]
    cutoff = values["temporal_cutoff_Green_family"]
    base = values["base_wave_microlocal_input"]
    typed_moller = values["finite_typed_Moller_reduction"]
    dilation = values["Hermitian_dilation_and_regular_legs"]
    free_covariance = values["free_Krein_CCR_covariance"]

    input_checks = {
        "all_finite_same_sided_terms_oriented": orientation["claim_flags"][
            "BERGER_FINITE_VOLTERRA_TERMS_MICROLOCALLY_ORIENTED"
        ]
        is True,
        "normal_convergence_was_previously_open": orientation["claim_flags"][
            "BERGER_HORMANDER_VOLTERRA_CONVERGENCE_CERTIFIED"
        ]
        is False,
        "smooth_temporal_cutoff_family_Green_hyperbolic": cutoff["claim_flags"][
            "BERGER_TEMPORAL_CUTOFF_COMPANION_GREEN_FAMILY"
        ]
        is True,
        "cutoff_factorization_has_order_zero_infinite_incidence": cutoff[
            "specialization_replay"
        ]["operators"]["cutoff_companion"]
        == "C_chi=[[Box_2,-I10],[chi(t)V_2,Box_2]]",
        "finite_order_two_triangular_reduction_exact": typed_moller[
            "claim_flags"
        ]["BERGER_TYPED_COMPANION_MOLLER_ALGEBRA"]
        is True
        and typed_moller["operator_filtration"]["V"]
        == "[[0,0],[V_2,0]], differential order two"
        and typed_moller["operator_filtration"]["N"]
        == "[[0,-I10],[0,0]], differential order zero"
        and all(typed_moller["typed_transport"]["checks"].values()),
        "base_wave_blocks_normally_hyperbolic": base["operator_family"][
            "principal_symbol"
        ]
        == "g^{-1}(xi,xi) times the fibre identity",
        "base_wave_positive_frequency_relation_certified": base[
            "verified_checks"
        ]["positive_frequency_wavefront_set"]
        is True,
        "regular_dilated_Cauchy_legs_available": dilation["claim_flags"][
            "BERGER_DILATED_FREE_CUTOFF_REGULAR_CAUCHY_MORPHISM"
        ]
        is True
        and dilation["claim_flags"][
            "BERGER_DILATED_CUTOFF_FULL_REGULAR_CAUCHY_MORPHISM"
        ]
        is True,
        "normalized_free_Krein_covariance_available": free_covariance[
            "claim_flags"
        ]["BERGER_FREE_DILATION_KREIN_COVARIANCE_NORMALIZED"]
        is True,
    }
    if not all(input_checks.values()):
        failed = [name for name, passed in input_checks.items() if not passed]
        raise ValueError(f"normal-topology convergence input drift: {failed}")

    replay = proof_replay()
    no_completeness = proof_replay(normal_space_complete=False)
    no_transpose = proof_replay(transpose_reversal_available=False)
    order_two_incidence = proof_replay(order_zero_infinite_incidence=False)
    if (
        not replay["all_pass"]
        or no_completeness["all_pass"]
        or no_transpose["all_pass"]
        or order_two_incidence["all_pass"]
        or replay["negative_control_without_simplex_factor"][
            "absolute_summability"
        ]
    ):
        raise ValueError("normal-topology convergence replay failed")

    result = {
        "schema": "quantum-weyl-berger-cutoff-volterra-normal-topology-convergence-v1",
        "result_id": "BERGER_CUTOFF_VOLTERRA_NORMAL_TOPOLOGY_CONVERGENCE",
        "result_state": "CUTOFF_NORMAL_CONVERGENCE_DECOMPOSABILITY_AND_DILATED_CONE_MAPPING_CERTIFIED_COVARIANCE_TRANSPORT_OPEN",
        "lifecycle_layer": "LORENTZIAN_MICROLOCAL_TRANSPORT",
        "dependency_tags": ["LORENTZIAN-CAUSAL"],
        "classical_commit": cutoff["classical_commit"],
        "setting_id": cutoff["setting_id"],
        "dependency_refs": {
            name: _dependency(DEPENDENCIES[name], payload)
            for name, payload in values.items()
        },
        "exact_input_checks": input_checks,
        "normal_topology_theorem": {
            "proof_type": (
                "ANALYTIC_THEOREM_INSTANTIATION_WITH_EXACT_COMBINATORIAL_"
                "MAJORANT_AND_CONTENT_ADDRESSED_OPERATOR_INPUTS"
            ),
            "space": (
                "D'_Gamma_sign on each compact slab, "
                "Gamma_sign=Delta union R_sign"
            ),
            "series": (
                "G_Cchi,sign=sum_(n>=0)(-1)^n"
                "(G0_chi,sign N)^n G0_chi,sign"
            ),
            "finite_reduction": (
                "V_chi is absorbed by the square-zero finite triangular "
                "solution/source maps before the infinite series; "
                "N=[[0,-I10],[0,0]] is constant and order zero"
            ),
            "term_representation": (
                "finite sums of proper push-forwards over ordered time "
                "simplices of compact-parameter wave-FIO families and smooth "
                "local insertions"
            ),
            "seminorm_bound": (
                "p(K_n)<=A_p binomial(n+r_p,r_p)"
                "(B_p |I|)^n/n!"
            ),
            "completion": (
                "absolute convergence in every defining normal seminorm plus "
                "completeness of D'_Gamma gives a unique kernel limit"
            ),
            "formal_transpose": (
                "factor reversal gives the same bound in "
                "D'_(Gamma_opposite)"
            ),
            "replay": replay,
            "status": "CERTIFIED",
        },
        "microlocal_consequences": {
            "cutoff_Green_kernels": (
                "WF'(G_Cchi,sign) subset Delta union R_sign"
            ),
            "cutoff_Pauli_Jordan": (
                "WF(E_Cchi) subset "
                "(N_plus x N_minus) union (N_minus x N_plus)"
            ),
            "cutoff_decomposability": "N_PLUS_MINUS_DECOMPOSABLE",
            "Hermitian_dilation": (
                "direct sum with the formal-adjoint block preserves "
                "decomposability"
            ),
            "regular_morphism_cone_action": (
                "the local Cauchy commutators and oriented Green kernels "
                "satisfy the cone action in Fewster Theorem 5.16"
            ),
            "status": "CERTIFIED",
        },
        "negative_controls": {
            "drop_normal_space_completeness": no_completeness,
            "drop_transpose_reversal": no_transpose,
            "leave_order_two_operator_in_infinite_incidence": order_two_incidence,
        },
        "literature_provenance": {
            "normal_space": (
                "Dabrowski--Brouder, Functional properties of Hörmander's "
                "space of distributions having a specified wavefront set, "
                "arXiv:1308.1061"
            ),
            "normal_operations": (
                "Brouder--Dang--Helein, Continuity of the fundamental "
                "operations on distributions having a specified wave front "
                "set, arXiv:1409.7662, Theorems 19, 28, 31--33"
            ),
            "wave_FIO_input": (
                "standard compact-slab normally-hyperbolic Cauchy evolution "
                "as a smooth bounded family of Fourier integral operators"
            ),
            "Hadamard_transport": (
                "Fewster, Hadamard States for Decomposable Green-Hyperbolic "
                "Operators, arXiv:2503.12537, Lemmas 5.14--5.15 and "
                "Theorem 5.16"
            ),
        },
        "claim_flags": {
            "BERGER_HORMANDER_VOLTERRA_CONVERGENCE_CERTIFIED": True,
            "BERGER_CUTOFF_VOLTERRA_TRANSPOSE_NORMAL_CONVERGENCE": True,
            "BERGER_CUTOFF_COMPANION_PAULI_JORDAN_ORIENTATION_EXCLUSION": True,
            "BERGER_CUTOFF_COMPANION_NULL_CONE_DECOMPOSABLE": True,
            "BERGER_DILATED_RESPONSE_MORPHISM_CONE_MAPPING": True,
            "BERGER_REGULAR_GREENHYP_MORPHISM": True,
            "BERGER_FULL_DILATION_HADAMARD_KREIN_COVARIANCE": False,
            "BERGER_COMPANION_HADAMARD_TWO_POINT_FUNCTION": False,
            "BERGER_26_ROW_BRST_HADAMARD": False,
            "BERGER_54_ROW_BRST_HADAMARD": False,
            "BERGER_PHYSICAL_OBSERVABLE_POSITIVITY": False,
            "BERGER_HADAMARD_DATA": False,
            "QUANTUM_CLAIM": False,
        },
        "next_gate": (
            "TRANSPORT_NORMALIZED_FREE_KREIN_COVARIANCE_ACROSS_THE_TWO_"
            "REGULAR_CAUCHY_MORPHISMS_AND_VERIFY_EXACT_CCR"
        ),
        "provenance": {
            "orientation_result_id": orientation["result_id"],
            "cutoff_result_id": cutoff["result_id"],
            "typed_Moller_result_id": typed_moller["result_id"],
            "dilation_result_id": dilation["result_id"],
            "free_covariance_result_id": free_covariance["result_id"],
        },
        "claim_boundary": (
            "Certifies compact-slab convergence of the cutoff companion "
            "Volterra kernels and their formal transposes in the fixed "
            "D'_Gamma normal topologies. Hence the cutoff Pauli--Jordan "
            "kernel is null-cone decomposable and the two regular dilated "
            "Cauchy morphism legs have the required cone action. It does not "
            "yet transport the free Krein covariance, restrict a covariance "
            "to the raw companion or full graded BV carrier, verify BRST Ward "
            "identities, establish positivity, define renormalized Lorentzian "
            "products, restore a Lorentzian QME or construct a quantum theory."
        ),
    }
    validate(result)
    return result


def validate(result: dict[str, Any]) -> None:
    if (
        result.get("result_id")
        != "BERGER_CUTOFF_VOLTERRA_NORMAL_TOPOLOGY_CONVERGENCE"
        or result.get("result_state")
        != "CUTOFF_NORMAL_CONVERGENCE_DECOMPOSABILITY_AND_DILATED_CONE_MAPPING_CERTIFIED_COVARIANCE_TRANSPORT_OPEN"
        or result.get("dependency_tags") != ["LORENTZIAN-CAUSAL"]
        or result.get("next_gate")
        != "TRANSPORT_NORMALIZED_FREE_KREIN_COVARIANCE_ACROSS_THE_TWO_REGULAR_CAUCHY_MORPHISMS_AND_VERIFY_EXACT_CCR"
    ):
        raise ValueError("normal-topology convergence identity drifted")
    if not all(result.get("exact_input_checks", {}).values()):
        raise ValueError("normal-topology convergence inputs failed")
    theorem = result.get("normal_topology_theorem", {})
    if (
        theorem.get("status") != "CERTIFIED"
        or theorem.get("replay", {}).get("all_pass") is not True
        or theorem.get("replay", {})
        .get("negative_control_without_simplex_factor", {})
        .get("absolute_summability")
        is not False
    ):
        raise ValueError("normal-topology theorem replay failed")
    if any(
        control.get("all_pass") is not False
        for control in result.get("negative_controls", {}).values()
    ):
        raise ValueError("normal-topology negative control was accepted")
    true_flags = {
        name for name, value in result.get("claim_flags", {}).items() if value
    }
    if true_flags != {
        "BERGER_HORMANDER_VOLTERRA_CONVERGENCE_CERTIFIED",
        "BERGER_CUTOFF_VOLTERRA_TRANSPOSE_NORMAL_CONVERGENCE",
        "BERGER_CUTOFF_COMPANION_PAULI_JORDAN_ORIENTATION_EXCLUSION",
        "BERGER_CUTOFF_COMPANION_NULL_CONE_DECOMPOSABLE",
        "BERGER_DILATED_RESPONSE_MORPHISM_CONE_MAPPING",
        "BERGER_REGULAR_GREENHYP_MORPHISM",
    }:
        raise ValueError("Hadamard covariance or quantum claim over-promoted")
