#!/usr/bin/env python3
"""Generate the exact inclusion-column appendix for Paper 11."""

from __future__ import annotations

import argparse
import json
from pathlib import Path


ROOT = Path(__file__).resolve().parents[1]
CARRIER = (
    ROOT
    / "d_quotient_classical/certificates/"
    "BERGER_PORTABLE_COUPLED_64_UNARY_PAIRING_36_SDR.json"
)
OUTPUT = ROOT / "paper/11-gravity-light-ell3-witness-inclusion-columns.tex"
TARGET_RETAINED_ROWS = (9, 4, 6, 13, 3)


def _tex_text(value: str) -> str:
    return (
        value.replace("\\", r"\textbackslash{}")
        .replace("_", r"\_")
        .replace("%", r"\%")
        .replace("&", r"\&")
        .replace("#", r"\#")
    )


def build() -> str:
    payload = json.loads(CARRIER.read_text(encoding="utf-8"))
    full_ids = {
        row["index"]: row["row_id"]
        for row in payload["full_complex"]["component_rows"]
    }
    retained_ids = {
        row["index"]: row["row_id"]
        for row in payload["retained_complex"]["component_rows"]
    }
    columns: dict[int, list[tuple[int, list[int], str]]] = {
        row: [] for row in TARGET_RETAINED_ROWS
    }
    for full_row, retained_row, operator in payload["contraction"][
        "iota_36_to_64"
    ]["entries"]:
        if retained_row not in columns:
            continue
        for derivative_word, coefficient in operator:
            columns[retained_row].append(
                (full_row, derivative_word, coefficient)
            )

    if any(not columns[row] for row in TARGET_RETAINED_ROWS):
        raise AssertionError("a requested witness inclusion column is empty")
    if sum(len(columns[row]) for row in TARGET_RETAINED_ROWS) != 106:
        raise AssertionError("witness inclusion-column coefficient count drifted")

    lines = [
        "% Generated by paper/generate_11_witness_inclusion_columns.py.",
        "% Do not edit this table by hand.",
        r"\begingroup",
        r"\scriptsize",
        r"\setlength{\tabcolsep}{4pt}",
        r"\begin{longtable}{@{}p{0.15\textwidth}r p{0.21\textwidth}c p{0.23\textwidth}@{}}",
        r"\caption{Exact full-carrier inclusion columns for every dressed gravity coordinate used by the two headline witnesses or their pairing partners.  Each row denotes the term $c\,\partial^\alpha e_{\rm full}$ in $\iota(e_{\rm retained})$.}",
        r"\label{tab:witness-inclusions}\\",
        r"\toprule",
        r"Retained ID & Row & Full-carrier ID & $\alpha$ & Exact $c$\\",
        r"\midrule",
        r"\endfirsthead",
        r"\multicolumn{5}{c}{\tablename\ \thetable\ (continued)}\\",
        r"\toprule",
        r"Retained ID & Row & Full-carrier ID & $\alpha$ & Exact $c$\\",
        r"\midrule",
        r"\endhead",
        r"\midrule",
        r"\multicolumn{5}{r}{Continued on next page}\\",
        r"\endfoot",
        r"\bottomrule",
        r"\endlastfoot",
    ]
    for retained_row in TARGET_RETAINED_ROWS:
        retained_id = _tex_text(retained_ids[retained_row])
        for position, (full_row, alpha, coefficient) in enumerate(
            columns[retained_row]
        ):
            shown_id = (
                rf"\texttt{{{retained_id}}}" if position == 0 else ""
            )
            shown_row = str(retained_row) if position == 0 else ""
            alpha_text = ",".join(str(entry) for entry in alpha)
            lines.append(
                f"{shown_id} & {shown_row} & "
                rf"\texttt{{{_tex_text(full_ids[full_row])}}} & "
                rf"$({alpha_text})$ & "
                rf"\texttt{{{_tex_text(coefficient)}}}\\"
            )
        lines.append(r"\addlinespace")
    lines.extend([r"\end{longtable}", r"\endgroup", ""])
    return "\n".join(lines)


def main() -> None:
    parser = argparse.ArgumentParser()
    parser.add_argument("--check", action="store_true")
    args = parser.parse_args()
    generated = build()
    if args.check:
        if not OUTPUT.is_file() or OUTPUT.read_text(encoding="utf-8") != generated:
            raise SystemExit("Paper 11 witness inclusion appendix is stale")
        print("PAPER_11_WITNESS_INCLUSION_COLUMNS: PASS")
        return
    OUTPUT.write_text(generated, encoding="utf-8")
    print(OUTPUT.relative_to(ROOT))


if __name__ == "__main__":
    main()
