#!/usr/bin/env python3
"""Generate the static atlas appendices for paper 21 from the website dataset."""

from __future__ import annotations

import argparse
import collections
import hashlib
import json
from pathlib import Path


ROOT = Path(__file__).resolve().parents[1]
SOURCE = ROOT / "foundations/site/data.json"
OUTPUT = ROOT / "paper/21-reverse-foundations-of-physics-appendices.tex"

STATUS_ORDER = [
    "LOCAL_RESULT",
    "LITERATURE_RESULT",
    "PIECES_ONLY",
    "PRIORITY_GAP",
    "NOT_MAPPED",
]
STATUS_SHORT = {
    "LOCAL_RESULT": "Local",
    "LITERATURE_RESULT": "Literature",
    "PIECES_ONLY": "Pieces",
    "PRIORITY_GAP": "Priority gap",
    "NOT_MAPPED": "Not mapped",
}
RELATION_LABEL = {
    "SUFFICIENT": "Enough for this step",
    "CONDITIONAL_SUFFICIENT": "Enough with conditions",
    "REPRESENTATION_DEPENDENT": "Depends on the coding",
    "COUNTEREXAMPLE_TO_METHOD": "This method fails",
    "LITERATURE_CONTRAST": "Literature contrast",
    "OPEN_IMPLICATION": "Unproved bridge",
    "NOT_SUFFICIENT": "Not enough by itself",
}


def sha256(path: Path) -> str:
    return hashlib.sha256(path.read_bytes()).hexdigest()


def tex(value: object) -> str:
    text = str(value)
    replacements = [
        ("\\", r"\textbackslash{}"),
        ("&", r"\&"),
        ("%", r"\%"),
        ("$", r"\$"),
        ("#", r"\#"),
        ("_", r"\_"),
        ("{", r"\{"),
        ("}", r"\}"),
        ("~", r"\textasciitilde{}"),
        ("^", r"\textasciicircum{}"),
        ("×", r"\(\times\)"),
        ("→", r"\(\rightarrow\)"),
        ("—", "---"),
        ("–", "--"),
    ]
    for old, new in replacements:
        text = text.replace(old, new)
    return text


def joined(values: list[str] | None) -> str:
    return tex("; ".join(values or []) if values else "---")


def cert(value: str) -> str:
    return rf"\cert{{{value}}}"


def axis_lookup(data: dict) -> dict[str, dict]:
    return {entry["id"]: entry for axis in data["axes"] for entry in axis["keys"]}


def emit_axis_table(lines: list[str], axis: dict) -> None:
    lines.extend(
        [
            rf"\subsubsection{{{tex(axis['question'])}}}",
            r"\begingroup",
            r"\small",
            r"\begin{longtable}{@{}p{0.29\textwidth}p{0.65\textwidth}@{}}",
            r"\toprule",
            r"Option & Plain-language purpose \\",
            r"\midrule",
            r"\endfirsthead",
            r"\toprule",
            r"Option & Plain-language purpose \\",
            r"\midrule",
            r"\endhead",
        ]
    )
    for option in axis["keys"]:
        lines.append(rf"{tex(option['label'])} & {tex(option.get('plain_meaning', option['meaning']))} \\")
    lines.extend([r"\bottomrule", r"\end{longtable}", r"\endgroup", ""])


def coverage_counts(cells: list[dict], field: str, value: str) -> collections.Counter:
    return collections.Counter(cell["status"] for cell in cells if cell[field] == value)


def build(data: dict) -> str:
    axes = {axis["id"]: axis for axis in data["axes"]}
    labels = axis_lookup(data)
    cells = data["cells"]
    evidence = data["evidence"]
    nodes = {node["id"]: node for node in data["graph"]["nodes"]}
    direct_evidence_ids: list[str] = []
    for edge in data["graph"]["edges"]:
        direct_evidence_ids.extend(edge.get("evidence", []))
    for step in data["ladder"]:
        if step.get("source"):
            direct_evidence_ids.append(step["source"])
    direct_evidence_ids = list(dict.fromkeys(direct_evidence_ids))

    lines = [
        "% Generated by paper/generate_21_reverse_foundations_appendices.py.",
        f"% Source SHA256: {sha256(SOURCE)}",
        r"\section{Static companion to the evidence atlas}",
        r"\label{app:atlas-companion}",
        "",
        "The interactive atlas exposes five views of the same normalized evidence: matrix, dimensions guide, typed implications, strength ladder, and evidence catalogue.  This appendix preserves their key research content in a citable static form.  It is a snapshot, not a replacement for cell inspection, filtering, neighboring-cell comparison, or the complete downloadable dataset.",
        "",
        r"\begin{center}",
        r"\small",
        r"\begin{tabularx}{\textwidth}{@{}p{0.20\textwidth}Y@{}}",
        r"\toprule",
        r"Website view & Static counterpart \\",
        r"\midrule",
        r"Matrix & Overall counts, a \(6\times6\) three-way coverage roll-up, and status counts for every obligation. \\",
        r"Dimensions guide & All 28 axis options with their non-specialist descriptions. \\",
        r"Implications & The complete typed relation ledger: ten directed edges with their exact assertion and evidence. \\",
        r"Strength ladder & All six cylinder-wave gates, including what each adds, establishes, and leaves open. \\",
        r"Evidence & Catalogue composition and the records directly used by the implication and ladder views. \\",
        r"\bottomrule",
        r"\end{tabularx}",
        r"\end{center}",
        "",
        r"\subsection{Dimensions guide}",
        r"\label{app:dimensions-guide}",
        "Every coordinate combines one foundational regime, one carrier, and one theorem-level obligation.  The tables below reproduce the website's plain-language guide rather than assuming the reader already knows the programme vocabulary.",
        "",
    ]
    for axis_id in ["FOUNDATION", "CARRIER", "REFINED_OBLIGATION"]:
        emit_axis_table(lines, axes[axis_id])

    lines.extend(
        [
            r"\subsection{Matrix overview}",
            r"\label{app:matrix-overview}",
            r"The full atlas has 576 coordinates.  The website exposes sixteen \(6\times6\) slices, one for each obligation.  For print, Table~\ref{tab:aggregate-matrix} aggregates those slices without implying that the statuses are truth values.  Each entry is \emph{direct / seeded / unmapped}: direct combines local and reviewed literature results; seeded combines pieces-only and priority-gap cells; unmapped means that no coverage classification is made.",
            "",
            r"\begin{table}[htbp]",
            r"\centering",
            r"\scriptsize",
            r"\setlength{\tabcolsep}{2pt}",
            r"\begin{tabular}{@{}p{0.20\textwidth}rrrrrr@{}}",
            r"\toprule",
            r"Regime \(\downarrow\) / carrier \(\rightarrow\) & Finite exact & Hilbert & Krein & Algebraic & PDE & Localic \\",
            r"\midrule",
        ]
    )
    carriers = axes["CARRIER"]["keys"]
    obligations = axes["REFINED_OBLIGATION"]["keys"]
    for foundation in axes["FOUNDATION"]["keys"]:
        row = [tex(foundation["label"])]
        for carrier in carriers:
            subset = [
                c for c in cells
                if c["foundation"] == foundation["id"] and c["carrier"] == carrier["id"]
            ]
            counts = collections.Counter(c["status"] for c in subset)
            direct = counts["LOCAL_RESULT"] + counts["LITERATURE_RESULT"]
            seeded = counts["PIECES_ONLY"] + counts["PRIORITY_GAP"]
            row.append(f"{direct}/{seeded}/{counts['NOT_MAPPED']}")
        lines.append(" & ".join(row) + r" \\")
    lines.extend(
        [
            r"\bottomrule",
            r"\end{tabular}",
            r"\caption{Aggregate coverage matrix.  Each cell reports direct results / open cells with a starting point / not mapped, across all sixteen obligations.}",
            r"\label{tab:aggregate-matrix}",
            r"\end{table}",
            "",
            r"\begin{longtable}{@{}p{0.29\textwidth}rrrrrr@{}}",
            r"\caption{Coverage status by physical obligation.  Every row sums to 36.}\label{tab:obligation-coverage}\\",
            r"\toprule",
            r"Obligation & Local & Literature & Pieces & Priority gap & Not mapped & Total \\",
            r"\midrule",
            r"\endfirsthead",
            r"\toprule",
            r"Obligation & Local & Literature & Pieces & Priority gap & Not mapped & Total \\",
            r"\midrule",
            r"\endhead",
        ]
    )
    for obligation in obligations:
        counts = coverage_counts(cells, "obligation", obligation["id"])
        values = [counts[s] for s in STATUS_ORDER]
        lines.append(
            f"{tex(obligation['label'])} & " + " & ".join(str(v) for v in values) + f" & {sum(values)}" + r" \\"
        )
    total = collections.Counter(c["status"] for c in cells)
    values = [total[s] for s in STATUS_ORDER]
    lines.extend(
        [
            r"\midrule",
            "All obligations & " + " & ".join(str(v) for v in values) + f" & {sum(values)}" + r" \\",
            r"\bottomrule",
            r"\end{longtable}",
            "",
            "A local or literature result remains bounded by its attached claim boundary.  Pieces-only means relevant ingredients do not yet compose the target.  Priority gap marks a coherent current-programme gap.  Not mapped is not an absence theorem.  Of the 205 not-mapped coordinates, 81 are emitted coordinates reviewed without a substantive transfer and 124 are synthetic complements used to expose the full surface.",
            "",
            r"\subsection{Typed implication ledger}",
            r"\label{app:implication-ledger}",
            r"The implication view is directional.  Table~\ref{tab:implication-ledger} is the authoritative print reading of its arrows: the relation column says how the edge may be used, and the assertion column says exactly what has and has not crossed that edge.",
            "",
            r"\begingroup",
            r"\scriptsize",
            r"\setlength{\tabcolsep}{3pt}",
            r"\begin{longtable}{@{}p{0.15\textwidth}p{0.16\textwidth}p{0.15\textwidth}p{0.36\textwidth}p{0.12\textwidth}@{}}",
            r"\caption{Complete typed relation ledger from the implications tab.}\label{tab:implication-ledger}\\",
            r"\toprule",
            r"From & Relation & To & Exact assertion & Evidence \\",
            r"\midrule",
            r"\endfirsthead",
            r"\toprule",
            r"From & Relation & To & Exact assertion & Evidence \\",
            r"\midrule",
            r"\endhead",
        ]
    )
    for edge in data["graph"]["edges"]:
        evidence_text = "; ".join(cert(item) for item in edge.get("evidence", [])) or "Open bridge---no direct certificate"
        lines.append(
            f"{tex(nodes[edge['from']]['label'])} & {tex(RELATION_LABEL[edge['relation']])} & "
            f"{tex(nodes[edge['to']]['label'])} & {tex(edge['meaning'])} & {evidence_text}" + r" \\"
        )
    lines.extend(
        [
            r"\bottomrule",
            r"\end{longtable}",
            r"\endgroup",
            "",
            r"\subsection{Cylinder-wave strength ladder}",
            r"\label{app:strength-ladder}",
            "The ladder prevents a certified lower level from being read as a theorem at a stronger level.  ``Adds'' names the new mathematical data at the gate; ``establishes'' records the result available there; and ``still open or excluded'' blocks silent promotion.",
            "",
            r"\begingroup",
            r"\footnotesize",
            r"\setlength{\tabcolsep}{3pt}",
            r"\begin{longtable}{@{}p{0.29\textwidth}p{0.20\textwidth}p{0.20\textwidth}p{0.23\textwidth}@{}}",
            r"\caption{All six gates in the cylinder-wave strength ladder.}\label{tab:strength-ladder}\\",
            r"\toprule",
            r"Gate, object, and sufficient base & Adds & Establishes & Still open or excluded \\",
            r"\midrule",
            r"\endfirsthead",
            r"\toprule",
            r"Gate, object, and sufficient base & Adds & Establishes & Still open or excluded \\",
            r"\midrule",
            r"\endhead",
        ]
    )
    for step in data["ladder"]:
        base = step.get("sufficient_base", step.get("candidate_upper_bound", "Not classified"))
        established = step.get("establishes", step.get("establishes_if_formalized", []))
        open_items = step.get("open", step.get("does_not_establish", []))
        if not open_items and step.get("boundary"):
            open_items = [step["boundary"]]
        if step.get("source_boundary"):
            open_items = list(open_items) + [step["source_boundary"]]
        object_and_base = f"{step['object']}. Base: {base}."
        if step.get("separation"):
            object_and_base += " " + step["separation"]
        lines.append(
            f"{cert(step['level'])} / {cert(step['status'])}. {tex(object_and_base)} & "
            f"{joined(step.get('adds'))} & {joined(established)} & {joined(open_items)}" + r" \\"
        )
    lines.extend(
        [
            r"\bottomrule",
            r"\end{longtable}",
            r"\endgroup",
            "",
            r"\subsection{Evidence catalogue snapshot}",
            r"\label{app:evidence-catalogue}",
        ]
    )
    kind_counts = collections.Counter(entry["kind"] for entry in evidence.values())
    quality_counts = collections.Counter(
        entry.get("artifact_status", entry.get("lifecycle", "UNCLASSIFIED"))
        for entry in evidence.values()
    )
    lines.extend(
        [
            f"The normalized catalogue contains {len(evidence)} evidence records: {kind_counts['LOCAL_RESULT']} local result records and {kind_counts['LITERATURE']} literature records.  Literature entries preserve their artifact status: metadata-only records are leads with resolved bibliographic metadata, not content-pinned evidence.",
            "",
            r"\begin{center}",
            r"\small",
            r"\begin{tabular}{@{}lr@{}}",
            r"\toprule",
            r"Catalogue lifecycle or artifact status & Records \\",
            r"\midrule",
        ]
    )
    for status, count in sorted(quality_counts.items(), key=lambda item: (-item[1], item[0])):
        lines.append(f"{cert(status)} & {count}" + r" \\")
    lines.extend(
        [
            r"\bottomrule",
            r"\end{tabular}",
            r"\end{center}",
            "",
            r"\begingroup",
            r"\scriptsize",
            r"\setlength{\tabcolsep}{3pt}",
            r"\begin{longtable}{@{}p{0.29\textwidth}p{0.18\textwidth}p{0.45\textwidth}@{}}",
            r"\caption{Evidence records directly used by the implications and strength-ladder tabs.}\label{tab:key-evidence}\\",
            r"\toprule",
            r"Record & Type/status & Boundary \\",
            r"\midrule",
            r"\endfirsthead",
            r"\toprule",
            r"Record & Type/status & Boundary \\",
            r"\midrule",
            r"\endhead",
        ]
    )
    for evidence_id in direct_evidence_ids:
        entry = evidence[evidence_id]
        status = entry.get("artifact_status", entry.get("lifecycle", "UNCLASSIFIED"))
        boundary = entry.get("boundary")
        if not boundary:
            exclusions = entry.get("does_not_establish", [])
            boundary = "Does not establish: " + "; ".join(exclusions[:3])
            if len(exclusions) > 3:
                boundary += "; see the certificate for the complete boundary."
        lines.append(
            f"{cert(evidence_id)} & {cert(entry['kind'])} / {cert(status)} & {tex(boundary)}" + r" \\"
        )
    lines.extend(
        [
            r"\bottomrule",
            r"\end{longtable}",
            r"\endgroup",
            "",
            rf"The complete normalized dataset is \cert{{foundations/site/data.json}} (SHA-256 \cert{{{sha256(SOURCE)}}}; canonical digest \cert{{{data['canonical_digest']}}}).  These tables are generated from that file and contain no hand-copied coverage counts or relation edges.",
            "",
        ]
    )
    return "\n".join(lines)


def main() -> int:
    parser = argparse.ArgumentParser()
    parser.add_argument("--check", action="store_true")
    args = parser.parse_args()
    data = json.loads(SOURCE.read_text())
    expected = build(data)
    if args.check:
        if not OUTPUT.exists() or OUTPUT.read_text() != expected:
            raise SystemExit(f"stale generated appendix: {OUTPUT.relative_to(ROOT)}")
        print(f"PASS {OUTPUT.relative_to(ROOT)} is current")
        return 0
    OUTPUT.write_text(expected)
    print(f"wrote {OUTPUT.relative_to(ROOT)}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
