#!/usr/bin/env python3
"""Generate the static atlas appendices for paper 21 from the website dataset."""

from __future__ import annotations

import argparse
import collections
import hashlib
import json
from pathlib import Path


ROOT = Path(__file__).resolve().parents[1]
SOURCE = ROOT / "foundations/site/data.json"
OUTPUT = ROOT / "paper/21-reverse-foundations-of-physics-appendices.tex"

STATUS_ORDER = [
    "LOCAL_RESULT",
    "LITERATURE_RESULT",
    "PIECES_ONLY",
    "PRIORITY_GAP",
    "REVIEWED_GAP",
    "NOT_MAPPED",
]
STATUS_SHORT = {
    "LOCAL_RESULT": "Local",
    "LITERATURE_RESULT": "Literature",
    "PIECES_ONLY": "Pieces",
    "PRIORITY_GAP": "Priority gap",
    "REVIEWED_GAP": "Reviewed gap",
    "NOT_MAPPED": "Not mapped",
}
RELATION_LABEL = {
    "SUFFICIENT": "Enough for this step",
    "CONDITIONAL_SUFFICIENT": "Enough with conditions",
    "REPRESENTATION_DEPENDENT": "Depends on the coding",
    "COUNTEREXAMPLE_TO_METHOD": "This method fails",
    "LITERATURE_CONTRAST": "Literature contrast",
    "OPEN_IMPLICATION": "Unproved bridge",
    "NOT_SUFFICIENT": "Not enough by itself",
}


def sha256(path: Path) -> str:
    return hashlib.sha256(path.read_bytes()).hexdigest()


def tex(value: object) -> str:
    text = str(value)
    replacements = [
        ("\\", r"\textbackslash{}"),
        ("&", r"\&"),
        ("%", r"\%"),
        ("$", r"\$"),
        ("#", r"\#"),
        ("_", r"\_"),
        ("{", r"\{"),
        ("}", r"\}"),
        ("~", r"\textasciitilde{}"),
        ("^", r"\textasciicircum{}"),
        ("×", r"\(\times\)"),
        ("→", r"\(\rightarrow\)"),
        ("—", "---"),
        ("–", "--"),
    ]
    for old, new in replacements:
        text = text.replace(old, new)
    return text


def joined(values: list[str] | None) -> str:
    return tex("; ".join(values or []) if values else "---")


def cert(value: str) -> str:
    return rf"\cert{{{value}}}"


def evidence_boundary(entry: dict) -> str:
    if entry.get("boundary"):
        return entry["boundary"]
    return "Does not establish: " + "; ".join(entry.get("does_not_establish", [])) + "."


def evidence_support(entry: dict) -> str:
    if entry["kind"] == "LITERATURE":
        return "; ".join(entry["supported_statements"])
    positive_flags = [name for name, enabled in entry.get("claim_flags", {}).items() if enabled]
    return "Certified positive flags: " + "; ".join(
        name.replace("_", " ") for name in positive_flags
    ) + "."


def axis_lookup(data: dict) -> dict[str, dict]:
    return {entry["id"]: entry for axis in data["axes"] for entry in axis["keys"]}


def emit_axis_table(lines: list[str], axis: dict) -> None:
    lines.extend(
        [
            rf"\subsubsection{{{tex(axis['question'])}}}",
            r"\begingroup",
            r"\small",
            r"\begin{longtable}{@{}p{0.29\textwidth}p{0.65\textwidth}@{}}",
            r"\toprule",
            r"Option & Plain-language purpose \\",
            r"\midrule",
            r"\endfirsthead",
            r"\toprule",
            r"Option & Plain-language purpose \\",
            r"\midrule",
            r"\endhead",
        ]
    )
    for option in axis["keys"]:
        lines.append(rf"{tex(option['label'])} & {tex(option.get('plain_meaning', option['meaning']))} \\")
    lines.extend([r"\bottomrule", r"\end{longtable}", r"\endgroup", ""])


def coverage_counts(cells: list[dict], field: str, value: str) -> collections.Counter:
    return collections.Counter(cell["status"] for cell in cells if cell[field] == value)


def build(data: dict) -> str:
    axes = {axis["id"]: axis for axis in data["axes"]}
    labels = axis_lookup(data)
    cells = data["cells"]
    evidence = data["evidence"]
    nodes = {node["id"]: node for node in data["graph"]["nodes"]}
    direct_evidence_ids: list[str] = []
    for edge in data["graph"]["edges"]:
        direct_evidence_ids.extend(edge.get("evidence", []))
    for step in data["ladder"]:
        if step.get("source"):
            direct_evidence_ids.append(step["source"])
    direct_evidence_ids = list(dict.fromkeys(direct_evidence_ids))
    evidence_usage = {
        evidence_id: {"cells": [], "graph": [], "ladder": []}
        for evidence_id in evidence
    }
    for cell in cells:
        for evidence_id in cell.get("evidence", []):
            evidence_usage[evidence_id]["cells"].append(cell)
    for edge_number, edge in enumerate(data["graph"]["edges"], start=1):
        for evidence_id in edge.get("evidence", []):
            evidence_usage[evidence_id]["graph"].append(edge_number)
    for step in data["ladder"]:
        if step.get("source"):
            evidence_usage[step["source"]]["ladder"].append(step["level"])
    evidence_anchor = {
        evidence_id: f"atlas-evidence-{number}"
        for number, evidence_id in enumerate(sorted(evidence), start=1)
    }

    lines = [
        "% Generated by paper/generate_21_reverse_foundations_appendices.py.",
        f"% Source SHA256: {sha256(SOURCE)}",
        r"\section{Static companion to the evidence atlas}",
        r"\label{app:atlas-companion}",
        "",
        "The interactive atlas exposes five views of the same normalized evidence: matrix, dimensions guide, typed implications, strength ladder, and evidence catalogue.  This appendix preserves their key research content in a citable static form.  It is a snapshot, not a replacement for cell inspection, filtering, neighboring-cell comparison, or the complete downloadable dataset.",
        "",
        r"\begin{center}",
        r"\small",
        r"\begin{tabularx}{\textwidth}{@{}p{0.20\textwidth}Y@{}}",
        r"\toprule",
        r"Website view & Static counterpart \\",
        r"\midrule",
        r"Matrix & Overall counts, a \(6\times6\) three-way coverage roll-up, and status counts for every obligation. \\",
        r"Dimensions guide & All 28 axis options with their non-specialist descriptions. \\",
        r"Implications & The complete typed relation ledger: ten directed edges with their exact assertion and evidence. \\",
        r"Strength ladder & All six cylinder-wave gates, including what each adds, establishes, and leaves open. \\",
        rf"Evidence & The complete literature register, local-certificate register, and usage crosswalk for all {len(evidence)} records. \\",
        r"\bottomrule",
        r"\end{tabularx}",
        r"\end{center}",
        "",
        r"\subsection{Dimensions guide}",
        r"\label{app:dimensions-guide}",
        "Every coordinate combines one foundational regime, one carrier, and one theorem-level obligation.  The tables below reproduce the website's plain-language guide rather than assuming the reader already knows the programme vocabulary.",
        "",
    ]
    for axis_id in ["FOUNDATION", "CARRIER", "REFINED_OBLIGATION"]:
        emit_axis_table(lines, axes[axis_id])

    lines.extend(
        [
            r"\subsection{Matrix overview}",
            r"\label{app:matrix-overview}",
            r"The full atlas has 576 coordinates.  The website exposes sixteen \(6\times6\) slices, one for each obligation.  For print, Table~\ref{tab:aggregate-matrix} aggregates those slices without implying that the statuses are truth values.  Each entry is \emph{direct / seeded / reviewed / unmapped}: direct combines local and reviewed literature results; seeded combines pieces-only and priority-gap cells; reviewed means a formulated open question with a typed missing certificate but no direct result; unmapped means that no coverage classification is made.",
            "",
            r"\begin{table}[htbp]",
            r"\centering",
            r"\scriptsize",
            r"\setlength{\tabcolsep}{2pt}",
            r"\begin{tabular}{@{}p{0.20\textwidth}rrrrrr@{}}",
            r"\toprule",
            r"Regime \(\downarrow\) / carrier \(\rightarrow\) & Finite exact & Hilbert & Krein & Algebraic & PDE & Localic \\",
            r"\midrule",
        ]
    )
    carriers = axes["CARRIER"]["keys"]
    obligations = axes["REFINED_OBLIGATION"]["keys"]
    for foundation in axes["FOUNDATION"]["keys"]:
        row = [tex(foundation["label"])]
        for carrier in carriers:
            subset = [
                c for c in cells
                if c["foundation"] == foundation["id"] and c["carrier"] == carrier["id"]
            ]
            counts = collections.Counter(c["status"] for c in subset)
            direct = counts["LOCAL_RESULT"] + counts["LITERATURE_RESULT"]
            seeded = counts["PIECES_ONLY"] + counts["PRIORITY_GAP"]
            row.append(f"{direct}/{seeded}/{counts['REVIEWED_GAP']}/{counts['NOT_MAPPED']}")
        lines.append(" & ".join(row) + r" \\")
    lines.extend(
        [
            r"\bottomrule",
            r"\end{tabular}",
            r"\caption{Aggregate coverage matrix.  Each cell reports direct results / open cells with a starting point / reviewed open gaps / not mapped, across all sixteen obligations.}",
            r"\label{tab:aggregate-matrix}",
            r"\end{table}",
            "",
            r"\begingroup",
            r"\scriptsize",
            r"\setlength{\tabcolsep}{3pt}",
            r"\begin{longtable}{@{}p{0.27\textwidth}rrrrrrr@{}}",
            r"\caption{Coverage status by physical obligation.  Every row sums to 36.}\label{tab:obligation-coverage}\\",
            r"\toprule",
            r"Obligation & Local & Literature & Pieces & \shortstack{Priority\\gap} & \shortstack{Reviewed\\gap} & \shortstack{Not\\mapped} & Total \\",
            r"\midrule",
            r"\endfirsthead",
            r"\toprule",
            r"Obligation & Local & Literature & Pieces & \shortstack{Priority\\gap} & \shortstack{Reviewed\\gap} & \shortstack{Not\\mapped} & Total \\",
            r"\midrule",
            r"\endhead",
        ]
    )
    for obligation in obligations:
        counts = coverage_counts(cells, "obligation", obligation["id"])
        values = [counts[s] for s in STATUS_ORDER]
        lines.append(
            f"{tex(obligation['label'])} & " + " & ".join(str(v) for v in values) + f" & {sum(values)}" + r" \\"
        )
    total = collections.Counter(c["status"] for c in cells)
    values = [total[s] for s in STATUS_ORDER]
    lines.extend(
        [
            r"\midrule",
            "All obligations & " + " & ".join(str(v) for v in values) + f" & {sum(values)}" + r" \\",
            r"\bottomrule",
            r"\end{longtable}",
            r"\endgroup",
            "",
            f"A local or literature result remains bounded by its attached claim boundary.  Pieces-only means relevant ingredients do not yet compose the target.  Priority gap marks a selected current-programme gap.  Reviewed gap marks an explicitly formulated open question with a typed missing certificate, not a result or literature-absence claim.  The atlas has {total['REVIEWED_GAP']} reviewed gaps and {total['NOT_MAPPED']} not-mapped coordinates; all {len(cells)} coordinates are emitted by the authoritative cube.",
            "",
            r"\subsection{Typed implication ledger}",
            r"\label{app:implication-ledger}",
            r"The implication view is directional.  Table~\ref{tab:implication-ledger} is the authoritative print reading of its arrows: the relation column says how the edge may be used, and the assertion column says exactly what has and has not crossed that edge.",
            "",
            r"\begingroup",
            r"\scriptsize",
            r"\setlength{\tabcolsep}{3pt}",
            r"\begin{longtable}{@{}p{0.15\textwidth}p{0.16\textwidth}p{0.15\textwidth}p{0.36\textwidth}p{0.12\textwidth}@{}}",
            r"\caption{Complete typed relation ledger from the implications tab.}\label{tab:implication-ledger}\\",
            r"\toprule",
            r"From & Relation & To & Exact assertion & Evidence \\",
            r"\midrule",
            r"\endfirsthead",
            r"\toprule",
            r"From & Relation & To & Exact assertion & Evidence \\",
            r"\midrule",
            r"\endhead",
        ]
    )
    for edge in data["graph"]["edges"]:
        evidence_text = "; ".join(cert(item) for item in edge.get("evidence", [])) or "Open bridge---no direct certificate"
        lines.append(
            f"{tex(nodes[edge['from']]['label'])} & {tex(RELATION_LABEL[edge['relation']])} & "
            f"{tex(nodes[edge['to']]['label'])} & {tex(edge['meaning'])} & {evidence_text}" + r" \\"
        )
    lines.extend(
        [
            r"\bottomrule",
            r"\end{longtable}",
            r"\endgroup",
            "",
            r"\subsection{Cylinder-wave strength ladder}",
            r"\label{app:strength-ladder}",
            "The ladder prevents a certified lower level from being read as a theorem at a stronger level.  ``Adds'' names the new mathematical data at the gate; ``establishes'' records the result available there; and ``still open or excluded'' blocks silent promotion.",
            "",
            r"\begingroup",
            r"\footnotesize",
            r"\setlength{\tabcolsep}{3pt}",
            r"\begin{longtable}{@{}p{0.29\textwidth}p{0.20\textwidth}p{0.20\textwidth}p{0.23\textwidth}@{}}",
            r"\caption{All six gates in the cylinder-wave strength ladder.}\label{tab:strength-ladder}\\",
            r"\toprule",
            r"Gate, object, and sufficient base & Adds & Establishes & Still open or excluded \\",
            r"\midrule",
            r"\endfirsthead",
            r"\toprule",
            r"Gate, object, and sufficient base & Adds & Establishes & Still open or excluded \\",
            r"\midrule",
            r"\endhead",
        ]
    )
    for step in data["ladder"]:
        base = step.get("sufficient_base", step.get("candidate_upper_bound", "Not classified"))
        established = step.get("establishes", step.get("establishes_if_formalized", []))
        open_items = step.get("open", step.get("does_not_establish", []))
        if not open_items and step.get("boundary"):
            open_items = [step["boundary"]]
        if step.get("source_boundary"):
            open_items = list(open_items) + [step["source_boundary"]]
        object_and_base = f"{step['object']}. Base: {base}."
        if step.get("separation"):
            object_and_base += " " + step["separation"]
        lines.append(
            f"{cert(step['level'])} / {cert(step['status'])}. {tex(object_and_base)} & "
            f"{joined(step.get('adds'))} & {joined(established)} & {joined(open_items)}" + r" \\"
        )
    lines.extend(
        [
            r"\bottomrule",
            r"\end{longtable}",
            r"\endgroup",
            "",
            r"\subsection{Complete evidence and literature registers}",
            r"\label{app:evidence-catalogue}",
        ]
    )
    kind_counts = collections.Counter(entry["kind"] for entry in evidence.values())
    quality_counts = collections.Counter(
        entry.get("artifact_status", entry.get("lifecycle", "UNCLASSIFIED"))
        for entry in evidence.values()
    )
    lines.extend(
        [
            rf"The normalized catalogue contains {len(evidence)} evidence records: {kind_counts['LOCAL_RESULT']} local result records and {kind_counts['LITERATURE']} literature records.  Tables~\ref{{tab:complete-literature-register}}--\ref{{tab:evidence-usage-crosswalk}} print the complete catalogue rather than only the records highlighted by the graph and ladder.  Literature entries preserve their artifact status: metadata-only records are bibliographic leads, not content-pinned evidence.  A catalogue entry supports only its stated role and never silently crosses its recorded boundary.",
            "",
            r"\begin{center}",
            r"\small",
            r"\begin{tabular}{@{}lr@{}}",
            r"\toprule",
            r"Catalogue lifecycle or artifact status & Records \\",
            r"\midrule",
        ]
    )
    for status, count in sorted(quality_counts.items(), key=lambda item: (-item[1], item[0])):
        lines.append(f"{cert(status)} & {count}" + r" \\")
    lines.extend(
        [
            r"\bottomrule",
            r"\end{tabular}",
            r"\end{center}",
            "",
            r"\subsubsection{Complete literature reference list}",
            r"The stable link is the catalogue's preferred public locator.  \cert{CONTENT_PINNED} means that the reviewed artifact is content-addressed in the evidence ledger; \cert{METADATA_ONLY} means that the bibliographic identity is resolved but the source content is not pinned.  The latter is a research lead, not equivalent evidential weight.",
            "",
            r"\begingroup",
            r"\scriptsize",
            r"\setlength{\tabcolsep}{3pt}",
            r"\begin{longtable}{@{}p{0.36\textwidth}p{0.58\textwidth}@{}}",
            rf"\caption{{Complete literature reference and evidence register ({kind_counts['LITERATURE']} records).}}\label{{tab:complete-literature-register}}\\",
            r"\toprule",
            r"Reference and provenance & Recorded evidential role and boundary \\",
            r"\midrule",
            r"\endfirsthead",
            r"\toprule",
            r"Reference and provenance & Recorded evidential role and boundary \\",
            r"\midrule",
            r"\endhead",
        ]
    )
    for evidence_id, entry in sorted(evidence.items()):
        if entry["kind"] != "LITERATURE":
            continue
        provenance = (
            rf"\hypertarget{{{evidence_anchor[evidence_id]}}}{{{cert(evidence_id)}}}. "
            f"{tex(entry['citation'])} "
            f"{cert(entry['source_kind'])} / {cert(entry['artifact_status'])}. "
            rf"\url{{{entry['stable_url']}}}"
        )
        role = (
            r"\emph{Supports:} " + tex(evidence_support(entry))
            + r" \emph{Boundary:} " + tex(evidence_boundary(entry))
        )
        lines.append(f"{provenance} & {role}" + r" \\")
    lines.extend(
        [
            r"\bottomrule",
            r"\end{longtable}",
            r"\endgroup",
            "",
            r"\subsubsection{Complete local result and certificate list}",
            "Local records are repository results, not external publications.  Their positive flags state what the registered certificate establishes; the complete negative list prevents a bounded result from being promoted to a stronger mathematical or physical claim.",
            "",
            r"\begingroup",
            r"\scriptsize",
            r"\setlength{\tabcolsep}{3pt}",
            r"\begin{longtable}{@{}p{0.36\textwidth}p{0.58\textwidth}@{}}",
            rf"\caption{{Complete local result and certificate register ({kind_counts['LOCAL_RESULT']} records).}}\label{{tab:complete-local-register}}\\",
            r"\toprule",
            r"Record and repository locator & Certified scope and complete boundary \\",
            r"\midrule",
            r"\endfirsthead",
            r"\toprule",
            r"Record and repository locator & Certified scope and complete boundary \\",
            r"\midrule",
            r"\endhead",
        ]
    )
    for evidence_id, entry in sorted(evidence.items()):
        if entry["kind"] != "LOCAL_RESULT":
            continue
        tags = ", ".join(entry.get("dependency_tags", [])) or "none recorded"
        provenance = (
            rf"\hypertarget{{{evidence_anchor[evidence_id]}}}{{{cert(evidence_id)}}}. "
            f"{cert(entry['result_kind'])} / {cert(entry['lifecycle'])}. "
            f"Dependency tags: {tex(tags)}. "
            f"Result: {cert(entry['result_path'])}. Report: {cert(entry['report_path'])}."
        )
        scope = (
            r"\emph{Establishes:} " + tex(evidence_support(entry))
            + r" \emph{Does not establish:} "
            + tex("; ".join(entry.get("does_not_establish", [])))
            + "."
        )
        lines.append(f"{provenance} & {scope}" + r" \\")
    lines.extend(
        [
            r"\bottomrule",
            r"\end{longtable}",
            r"\endgroup",
            "",
            r"\subsubsection{Evidence usage crosswalk}",
            r"Every evidence record is used by at least one matrix coordinate.  The matrix column reports the number of coordinates carrying the record and their coverage-status composition.  Graph entries use edge numbers from Table~\ref{tab:implication-ledger}; ladder entries use the gate identifiers from Table~\ref{tab:strength-ladder}.  Clicking a record identifier returns to its full literature or local-certificate entry above.",
            "",
            r"\begingroup",
            r"\scriptsize",
            r"\setlength{\tabcolsep}{3pt}",
            r"\begin{longtable}{@{}p{0.36\textwidth}p{0.29\textwidth}p{0.29\textwidth}@{}}",
            rf"\caption{{Complete crosswalk from the atlas views to all {len(evidence)} evidence records.}}\label{{tab:evidence-usage-crosswalk}}\\",
            r"\toprule",
            r"Evidence record & Matrix use & Graph and ladder use \\",
            r"\midrule",
            r"\endfirsthead",
            r"\toprule",
            r"Evidence record & Matrix use & Graph and ladder use \\",
            r"\midrule",
            r"\endhead",
        ]
    )
    for evidence_id, entry in sorted(evidence.items()):
        usage = evidence_usage[evidence_id]
        status_counts = collections.Counter(cell["status"] for cell in usage["cells"])
        status_summary = ", ".join(
            f"{STATUS_SHORT[status]} {status_counts[status]}"
            for status in STATUS_ORDER
            if status_counts[status]
        )
        matrix_use = f"{len(usage['cells'])} coordinates ({status_summary})."
        view_uses: list[str] = []
        if usage["graph"]:
            view_uses.append("graph edges " + ", ".join(str(n) for n in usage["graph"]))
        if usage["ladder"]:
            view_uses.append("ladder " + ", ".join(usage["ladder"]))
        graph_ladder_use = "; ".join(view_uses) + "." if view_uses else "No graph or ladder use."
        target = rf"\hyperlink{{{evidence_anchor[evidence_id]}}}{{{cert(evidence_id)}}}"
        target += " (literature)" if entry["kind"] == "LITERATURE" else " (local)"
        lines.append(f"{target} & {tex(matrix_use)} & {tex(graph_ladder_use)}" + r" \\")
    lines.extend(
        [
            r"\bottomrule",
            r"\end{longtable}",
            r"\endgroup",
            "",
            rf"The complete normalized dataset is \cert{{foundations/site/data.json}} (SHA-256 \cert{{{sha256(SOURCE)}}}; canonical digest \cert{{{data['canonical_digest']}}}).  These tables are generated from that file and contain no hand-copied coverage counts, relation edges, evidence roles, boundaries, or citations.",
            "",
        ]
    )
    return "\n".join(lines)


def main() -> int:
    parser = argparse.ArgumentParser()
    parser.add_argument("--check", action="store_true")
    args = parser.parse_args()
    data = json.loads(SOURCE.read_text())
    expected = build(data)
    if args.check:
        if not OUTPUT.exists() or OUTPUT.read_text() != expected:
            raise SystemExit(f"stale generated appendix: {OUTPUT.relative_to(ROOT)}")
        print(f"PASS {OUTPUT.relative_to(ROOT)} is current")
        return 0
    OUTPUT.write_text(expected)
    print(f"wrote {OUTPUT.relative_to(ROOT)}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
